### ISSUE TITLE
Multi-database access in triggers and SP [CORE644]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#1009]
Submitted by: @pcisar

Depends on [CORE776](https://github.com/FirebirdSQL/firebird/issues?q=CORE776+in%3Atitle)

Votes: 11

SFID: 807913#&#x2060;
Submitted By: pcisar

Allow for other databases to be accessed from within 
triggers and SPs\.
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
User: danielrail
Logged In: YES 
user\_id=238419

It would also be nice that multi\-databases access would be 
implemented and accessible from practically
anywhere\(i\.e\. in 
a SELECT, INSERT, UPDATE\), not just triggers and SPs\.
I think the use of the aliases are useful in this case\.

**Comment by dyemanov** [comment]
I believe #1158 covers this ticket too, so we don't need to have both.
