### ISSUE TITLE
DEFAULT Keyword [CORE665]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#1031]
Submitted by: Pierre Yager (pierrey)

Duplicates [CORE5449](https://github.com/FirebirdSQL/firebird/issues?q=CORE5449+in%3Atitle)

Votes: 4

SFID: 1153278#&#x2060;
Submitted By: pierrey

I would like to know I you can consider adding 
a "DEFAULT" keyword to force the engine to set the 
default value for a field if this field is present in a query 
\(insert or update\) but user don't want to give it a value :

CREATE TABLE MY\_TABLE \(
  TABLE\_KEY INTEGER NOT NULL,
  TABLE\_VALUE INTEGER NOT NULL DEFAULT 0,  
CONSTRAINT MY\_TABLE\_PK PRIMARY KEY 
\(TABLE\_KEY\)\);
 
INSERT INTO MY\_TABLE \(TABLE\_KEY, 
TABLE\_VALUE\) VALUES 
\(GEN\_ID\(MY\_GEN\_KEY\), DEFAULT\);

or

UPDATE MY\_TABLE SET
  TABLE\_VALUE=DEFAULT
WHERE TABLE\_KEY=:THE\_ID;

Vlad Horsun also said this keyword is in SQL 2002 :

"We talk about INSERT\\UPDATE syntax with explicit 
defaults\.

This is feauture F221 according SQL 2002 \(which i has\)

SQL 2002 say:

6\.5 <contextually typed value specification\>

Function
Specify a value whose data type is to be inferred from 
its context\.

Format
<contextually typed value specification\> ::= <implicitly 
typed value specification\>
\| <default specification\>
\.\.\.
<default specification\> ::=
DEFAULT

Both INSERT and UPDATE can specify <contextually 
typed value specification\>"

**Comment by hvlad** [comment]
Replaced by #5720 [CORE5449 ]
