### ISSUE TITLE
Server Hangs on   I/O error during "open" operation for file "/tmp/firebird/fb_trace_ksVDoc"   [CORE2917]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#1210]
Submitted by: Derryck welas (welas)

Jira\_subtask\_outward [CORE6009](https://github.com/FirebirdSQL/firebird/issues?q=CORE6009+in%3Atitle)

Attachments:
[error_sequence_of_events.PNG](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-2917/11608_error_sequence_of_events.PNG)

The server has been online for \~ 2 weeks then,

 hangs while nobody is using the system  \(4 AM\) \( i had to kill all fb\_inet\_server instances, then connection was possible again\)

this is written in the firebird\.log \(every second\)

eusdlsdbb024\.logistics\.corp	Mon Mar  8 04:05:04 2010
	Error in isc\_attach\_database\(\) API call when working with security database
	I/O error during "open" operation for file "/tmp/firebird/fb\_trace\_ksVDoc"
	Error while trying to open file
	No such file or directory

/tmp   seems to have  enough space \.

Client application jdbc stack error \(no connection possible\):

Caused by: org\.firebirdsql\.jdbc\.FBSQLException: GDS Exception\. 335544344\. I/O error for file open "/tmp/firebird/fb\_trace\_ksVDoc"
Error while trying to open file
null, error code: HY000
Reason: I/O error for file open "/tmp/firebird/fb\_trace\_ksVDoc"
Error while trying to open file
null

i have ODS Version 11\.2 and 11\.1 databases running on this instance\.

Commits: FirebirdSQL/firebird@0979b7c9288bd7e5b78e1b1f1e696932316d18ee FirebirdSQL/firebird@e8d1eeae2ff5a3390a0e4fc11fe29b553d521ffb FirebirdSQL/firebird@6ea33a52550e6e6ff23be9da55a085987992f4ae FirebirdSQL/firebird@f7f1defb488f6fafd2a994e101ae674e00ced0e6

**Comment by AlexPeshkoff** [comment]
Fix from 2.5 got broken in 3.0 due to bug (integer overflow) in ITimer code.
