### ISSUE TITLE
Can't create table with Chinese table name which is not quoted by double quotation marks [CORE892]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#1289]
Submitted by: liuwangxia (liuwangxia)

1\) Create a database encoding with UTF8;

2\) Use Hibernate to generate DDL and run the DDL script \(table name, field name, index name and constraint name are all Chinese\); 
the JDBC URL is:
jdbc:firebirdsql:embedded:c:/POS\.FDB?lc\_ctype=UTF8;sql\_dialect=3
\(When I use Firebird in superserver mode, it report the same error\)

3\) Firebird report the following error message:
GDS Exception\. 335544569\. Dynamic SQL Error
SQL error code = \-104
Token unknown

4\)Run the script that Hibernate generated in FlameRobin, Firebird report the same error;

5\) Quote the identifier name with double quotation marks, and run the script in FlameRobin, Firebird works quite well\.

When we use English word as identifier, we need no double quotation marks, and I create a database encoding with UTF8, so I think this is a bug\.

When I create a database encoding  with GB\_2312, Firebird report the same error;

BTW, I'm also use MS SQL Server and PostgreSQL, they don't have this problem, I think this bug can be easily solved\.

**Comment by mrotteveel** [comment]
Non-quoted identifiers are only for identifiers starting with A-Z, and the rest consisting of A-Z, 0-9, _, $ (this is defined in the SQL standard, except for $, which is a non-standard extension). Everything else must use quoted identifiers.
