### ISSUE TITLE
Disabling foreign constraint [CORE1084]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#1505]
Submitted by: lexas (lexas)

Votes: 5

i want the following feature in DDL:

alter constraint FK\_xxx\_yyyy disable;

This command doesn't drop description \(\) of foreign constraint, but disable referencial integrity\.

alter constraint FK\_xxx\_yyyy enable;

This command restores referential integrity\.

**Comment by aafemt** [comment]
I think this issue should be closed as a duplication of #2358
