### ISSUE TITLE
JayBird throws DataTruncation or produces empty results when using Hibernate and the search text reachs the column length [CORE1217]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#1641]
Submitted by: Jose M. Rus (josemrus)

Attachments:
[testcase-jdbc90.zip](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-1217/10126_testcase-jdbc90.zip)

Votes: 2

'Like' queries throw DataTruncation exceptions or produce empty results when the search text reachs the column length or the column length \-1\.

Consider a VARCHAR field and a simple Hibernate Criteria query like:
    Restrictions\.like\("fieldName", "%" \+ filter \+ "%"\) 
or
    Restrictions\.like\("fieldName", filter, MatchMode\.ANYWHERE\)

When the parameter value has the column length or the column length \-1 the query breaks\.

With JayBird 2\.1\.0 it produces an empty result when there should be matches, and with JayBird 2\.0\.1 it just throws a DataTruncation
exception\.

**Comment by mrotteveel** [comment]
Duplicate (which IMHO describes the problem better): https://github.com/FirebirdSQL/firebird/issues/1361
