### ISSUE TITLE
TempDirectories parameter in firebird.conf ignored by global temporary tables [CORE1241]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#1665]
Submitted by: John Franck (bozzy)

Is duplicated by [CORE1809](https://github.com/FirebirdSQL/firebird/issues?q=CORE1809+in%3Atitle)

Votes: 3

Files created for Global Temporary Tables are located on linux default temporary directory \(/tmp\), ignoring the setting imposed by TempDirectories parameter in firebird\.conf\.

**Comment by pavel-zotov** [comment]
::: test details :::
Test checks ability to use TempTableIDrectory parameter and also verifies that firebird.log contains error message when this parameter points to inaccessible directory or has invalid value (see https://github.com/FirebirdSQL/firebird/commit/fd0fa8a3a58fbfe7fdc0641b4e48258643d72127 ; "Let include file name into error message when creation of temp file failed.")
See details in .fbt

**Comment by dyemanov** [comment]
`TempTableDirectory` configuration setting is available since FB 4.0, so I'm closing this ticket as resolved.
