### ISSUE TITLE
Default values for procedure [CORE1976]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#2414]
Submitted by: Alexander Tyutik (tut)

I have many procedures with many parameters with default values\. It would be nice to have ability to omit any default parameter, not only last\.
I have 2 solutions:

CREATE PROCEDURE PROC \(
  PARAM\_A INTEGER,
  PARAM\_B INTEGER = 2,
  PARAM\_C INTEGER = 3
\) \.\.\.

1\) Use empty parameters or DEFAULT keyword:

SELECT  \* FROM PROC\(1, , 5\)     or      SELECT  \* FROM PROC\(1, DEFAULT, 5\)

2\) Use named parameters \(always in the end of list\):

SELECT  \* FROM PROC\(1, ?PARAM\_C = 5\)     or     SELECT  \* FROM PROC\(?PARAM\_A = 1, ?PARAM\_C = 5\)

**Comment by dyemanov** [comment]
AFAIU, this is now superseded by #7566 and #7586 and thus can be closed.
