### ISSUE TITLE
Extend INSERT to support inserting multiple rows in single command (ala PostgreSQL/MySQL) [CORE1978]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#2416]
Submitted by: Gustavo Torres (gusta1308)

Votes: 20

I suggest include INSERT for multi\-values

INSERT INTO Table \(a, b, c\)
 values\(1, 2, 3\), \(4, 5, 6\);

for improvement performance insert

**Comment by MarvinKlein1508** [comment]
Are there any plans to support this?

**Comment by mrotteveel** [comment]
Related/duplicate of #4217

**Comment by piervalli** [comment]
Hello,

If we use Firebird as client on Android is very important in bulk insert to synchronized with back and, there is no way to add?

Thanks

**Comment by aafemt** [comment]
If you can use API, IBatch and IReplicator does it in more effective way. If you are limited to script, ISQL already has this functionality as written above.

**Comment by piervalli** [comment]
Yes can use api, what is the api of fbclient that can I use ? Thanks

**Comment by AlexPeshkoff** [comment]
On 11/19/24 19:39, piervalli wrote:
>
> Yes can use api, what is the api of fbclient that can I use ? Thanks
>

Use Batch API.

**Comment by dyemanov** [comment]
Closing as a duplicate for #4217 which offers the standard solution.
