### ISSUE TITLE
FB super server allocate DefaultDbCachePages for all databases, even for security2.fdb [CORE2013]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#2450]
Submitted by: Sergey Mereutsa (green_dq)

When DefaultDbCachePages is set to any number \(for example, 65536\) and we connect to one database, server tried to allocate DefaultDbCachePages\*2 \- it threat security2\.fdb as usual database\. When this parameter represent great values \(1GB, for example\) a lot of RAM allocated, but did not used\.

Vlad Khorsun confirmed the problem\.

**Comment by mrotteveel** [comment]
This is available since Firebird 3.0, with the default configuration for `security.db` in `databases.conf` (`DefaultDbCachePages = 50` in Firebird 3.0, `DefaultDbCachePages = 256` in Firebird 4.0/5.0).
