### ISSUE TITLE
New additional functions similar LIST [CORE2134]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#2565]
Submitted by: Igor Lobov (ivl)

Votes: 2

Create additional functions that are similar LIST, but returns only FIRST,  LAST or ANY value from the list\.

**Comment by dyemanov** [comment]
We have `FIRST_VALUE` and `LAST_VALUE` (as well as `NTH_VALUE`) as window functions (since FB3, IIRC), and we have `ANY_VALUE` added as an aggregate function to FB6. Is it enough to have this ticket closed?

**Comment by mrotteveel** [comment]
@dyemanov I think it can.
