### ISSUE TITLE
How to see cause why FireBird does not see UDF? [CORE2193]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#2621]
Submitted by: Eugenk Konkov (kes)

Votes: 1

1\. Test how firebird recognize libxxx and xxx and <http://xxx.so> libraries
\(because of C variant of UDF works I will try gcc\)

a\) source file:
extern int c\_test\(\);

int c\_test\(\)

return 8;

b\) home#&#x2060; gcc \-c testudf\.c
c\) home#&#x2060; gcc testudf\.o \-o <http://testudf.so> \-shared
d\) home#&#x2060; nm <http://testudf.so>
00001630 A \_DYNAMIC
00001704 A \_GLOBAL\_OFFSET\_TABLE\_
         w \_Jv\_RegisterClasses
000016f4 d \_\_CTOR\_END\_\_
000016f0 d \_\_CTOR\_LIST\_\_
000016fc d \_\_DTOR\_END\_\_
000016f8 d \_\_DTOR\_LIST\_\_
0000162c r \_\_FRAME\_END\_\_
00001700 d \_\_JCR\_END\_\_
00001700 d \_\_JCR\_LIST\_\_
0000171c A \_\_bss\_start
         w \_\_cxa\_finalize@@FBSD\_1\.0
00000550 t \_\_do\_global\_ctors\_aux
000004a0 t \_\_do\_global\_dtors\_aux
00001624 d \_\_dso\_handle
00000537 t \_\_i686\.get\_pc\_thunk\.bx
0000171c A \_edata
00001720 A \_end
00000584 T \_fini
0000046c T \_init
00000540 T c\_test
0000171c b completed\.4685
00000500 t frame\_dummy
00001628 d p\.4683

e\) ls \-l
\-rwxr\-xr\-x  1 root  wheel      4520 15 ноя 21:29 <http://testudf.so>
f\) cp <http://testudf.so> /usr/local/libexec/firebird/udf
g\) Because of FireBird is started from inetd:
home#&#x2060; /etc/rc\.d/inetd restart
Stopping inetd\.
Starting inetd\.
h\)
DECLARE EXTERNAL FUNCTION FNTEST
  RETURNS INTEGER BY VALUE 
  ENTRY\_POINT 'c\_test'
  MODULE\_NAME 'testudf'
i\) select fntest\(\) from rdb$database
result 8

2\. Now I test different names for UDF
a\) home#&#x2060; cd /usr/local/libexec/firebird/udf
b\) home#&#x2060; mv <http://testudf.so> <http://libtestudf.so>
c\) home#&#x2060; /etc/rc\.d/inetd restart
Stopping inetd\.
Starting inetd\.

d\) select fntest\(\) from rdb$database
result 8

e\) home#&#x2060; mv <http://libtestudf.so> testudf
f\) home#&#x2060; /etc/rc\.d/inetd restart
Stopping inetd\.
Starting inetd\.

g\) select fntest\(\) from rdb$database
result 8

h\) home#&#x2060; mv testudf libtestudf
i\) home#&#x2060; /etc/rc\.d/inetd restart
Stopping inetd\.
Starting inetd\.

j\) select fntest\(\) from rdb$database
k\) invalid requiest BLR at offset 60
function FNTEST is not defined
module name or entrypoint could not be found

So when I write:
\.\.\. MODULE\_NAME 'testudf'
firebird will see <http://testudf.so/libtestudf.so/testudf> and do not see libtestudf

PS\.
#&#x2060;rm libtestudf
#&#x2060;cd to my directory with sources

3\. Now I try to compile by FPC:
a\) home#&#x2060; cat testudf\.pp
library testudf;

function pp\_test\(\): integer; cdecl; export;
begin
 pp\_test:= 7;
end;

exports
 pp\_test name 'pp\_test2';
begin
end\.

b\) home#&#x2060; fpc testudf\.pp
Target OS: FreeBSD/ELF for i386
Compiling testudf\.pp
Linking <http://libtestudf.so>
11 lines compiled, 0\.1 sec

c\) nm <http://libtestudf.so> \> libtestudf\.txt see in attached file
libtestudf\.txt
d\) home#&#x2060; cp <http://libtestudf.so> /usr/local/libexec/firebird/udf
e\) home#&#x2060; /etc/rc\.d/inetd restart
Stopping inetd\.
Starting inetd\.
f\) Change definition in SQL\. So now it looks like:
DECLARE EXTERNAL FUNCTION FNTEST
  RETURNS INTEGER BY VALUE 
  ENTRY\_POINT 'pp\_test'
  MODULE\_NAME 'testudf'
g\) select fntest\(\) from rdb$database
h\) invalid requiest BLR at offset 60
function FNTEST is not defined
module name or entrypoint could not be found

i\) change definition in SQL\. So now it looks like:
DECLARE EXTERNAL FUNCTION FNTEST
  RETURNS INTEGER BY VALUE 
  ENTRY\_POINT 'pp\_test2'
  MODULE\_NAME 'testudf'
j\) select fntest\(\) from rdb$database
k\) invalid requiest BLR at offset 60
function FNTEST is not defined
module name or entrypoint could not be found

4\. Compiling with fpc \-Xc
a\) nm testudf\.o
home#&#x2060; nm testudf\.o
         U FPC\_INITIALIZEUNITS
00000020 D FPC\_RESOURCESTRINGTABLES
00000014 D FPC\_THREADVARTABLES
         U INIT$\_SYSTEM
00000004 D INITFINAL
00000000 T P$TESTUDF\_PP\_TEST$$SMALLINT
00000014 T P$TESTUDF\_main
00000014 T PASCALMAIN
00000000 D THREADVARLIST\_P$TESTUDF
         U THREADVARLIST\_SYSTEM
0000002c D \_\_fpc\_valgrind
00000028 D \_\_heapsize
00000024 D \_\_stklen
00000000 T pp\_test
00000020 T pp\_test2

b\) home#&#x2060; cp <http://libtestudf.so> /usr/local/libexec/firebird/udf
c\) home#&#x2060; /etc/rc\.d/inetd restart
Stopping inetd\.
Starting inetd\.
d\) DECLARE EXTERNAL FUNCTION FNTEST
  RETURNS INTEGER BY VALUE 
  ENTRY\_POINT 'pp\_test2'
  MODULE\_NAME 'testudf'
e\) select fntest\(\) from rdb$database
f\) invalid requiest BLR at offset 60
function FNTEST is not defined
module name or entrypoint could not be found

g\) DECLARE EXTERNAL FUNCTION FNTEST
  RETURNS INTEGER BY VALUE 
  ENTRY\_POINT 'pp\_test'
  MODULE\_NAME 'testudf'
h\) select fntest\(\) from rdb$database
i\) invalid requiest BLR at offset 60
function FNTEST is not defined
module name or entrypoint could not be found

CONCLUSION: FPC generate wrong object file???

**Comment by dyemanov** [comment]
This ticket is old and UDFs are deprecated now, thus closed.
