### ISSUE TITLE
DB created with FB 1.5.x and used with FB 2.x leads to "index page error" [CORE2325]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#2749]
Submitted by: Attila Molnár (e_pluribus_unum)

Votes: 1

The engine does not throw error, just the queries become very slow \(because the index corruption\) \.The index page error is reported by gfix with \-m parameter\.

I can reproduce this bug\. Unforunetly this means thousands of DDL, DML and DQL sql statements\. How can I log all the sql statement?

**Comment by EPluribusUnum** [comment]
You can close this issue. Thank you.
