### ISSUE TITLE
another performance degradation in v2.1.2 (at least twice slower than v1.5.5) [CORE2334]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#2758]
Submitted by: Paulius Pazera (ppazera)

Attachments:
[amdtests.pdf](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-2334/11382_amdtests.pdf)

Votes: 1

test case below shows \~2\+ times slowdown comparing 2\.1\.2rc1 with 1\.5\.5\. To reproduce \-\- create database, re\-connect isql using localhost and execute the script provided below\. Note how long 'select \* from sp;' takes to insert initial records, and how long 'insert  \.\. select \.\.\.' takes to insert additional records\. For example, on our dual xeon server classic firebird v1\.5\.5 takes \~9 seconds to insert initial and \~5\.5 seconds to insert additional records while classic v2\.1\.2rc1 takes \~22 seconds to insert initial and \~13\.5 seconds to insert additional records on the same hardware

set stats on;
set plan on;
create table tbl\(i1 integer\);
create index idx\_tbl\_i1 on tbl\(i1\); 
commit;

set term ^;
create procedure sp
returns \(i integer\)
as begin
  i=0;
  while\(i<1000000\) do begin
    i=i\+1;
    insert into tbl values \(:i/5\);
  end
  suspend;
end
^
set term ;^

select \* from sp; /\* \~9 sec v1\.5\.5 vs \~22 sec v2\.1\.2 \-\- more than twice slower \*/
commit;

insert into tbl \(i1\)
 select i1\+100000 from tbl where i1<100000; /\* \~5 sec v1\.5\.5 vs \~14 sec v2\.1\.2 \-\- more than twice slower \*/
rollback;

insert into tbl \(i1\)
 select i1\+100000 from tbl where i1<100000; /\* \~6 sec v1\.5\.5 vs \~13 sec v2\.1\.2 \-\- more than twice slower \*/
commit;

drop procedure sp;
drop table tbl;
commit;

**Comment by dyemanov** [comment]
This ticket is very old and covers unsupported versions, thus closed. If performance is still an issue with recent versions, some updated information would be appreciated.
