### ISSUE TITLE
Same select give different resultset on 1.5.5 and 2.0.5 [CORE2649]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#3056]
Submitted by: Attila Molnár (e_pluribus_unum)

Attachments:
[testcase2.zip](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-2649/11503_testcase2.zip)

The database is created on FB1\.5\.5 \(ODS 10\.1\)

CREATE TABLE TESTTABLE \(
    ID     XIDN /\* XIDN = INTEGER NOT NULL \*/,
    FLAG   XVAR1N /\* XVAR1N = VARCHAR\(1\) NOT NULL \*/,
    CODE   XVAR30N /\* XVAR30N = VARCHAR\(30\) NOT NULL \*/,
    NAME   XVAR100N /\* XVAR100N = VARCHAR\(100\) NOT NULL \*/,
    NAME2  XVAR100 /\* XVAR100 = VARCHAR\(100\)  \*/
\);
ALTER TABLE TESTTABLE ADD CONSTRAINT TESTTABLE\_PK PRIMARY KEY \(ID\);
ALTER TABLE TESTTABLE ADD CONSTRAINT TESTTABLE\_UK1 UNIQUE \(FLAG, NAME\);
ALTER TABLE TESTTABLE ADD CONSTRAINT TESTTABLE\_UK2 UNIQUE \(ID, NAME2\);

CREATE TABLE TESTTABLE\_CHILD \(
    ID            XIDN /\* XIDN = INTEGER NOT NULL \*/,
    TESTTABLE\_ID  XIDN /\* XIDN = INTEGER NOT NULL \*/,
    TEXT          XVAR30N /\* XVAR30N = VARCHAR\(30\) NOT NULL \*/,
    NAME2         XVAR100 /\* XVAR100 = VARCHAR\(100\)  \*/
\);
ALTER TABLE TESTTABLE\_CHILD ADD CONSTRAINT TESTTABLE\_CHILD\_PK PRIMARY KEY \(ID\);
ALTER TABLE TESTTABLE\_CHILD ADD CONSTRAINT TESTTABLE\_CHILD\_FK1 FOREIGN KEY \(TESTTABLE\_ID, NAME2\) REFERENCES TESTTABLE \(ID, NAME2\);

INSERT INTO testtable\(id,flag,code,name,name2\) VALUES\(0,'A','001','Name1','Name1\-alternative'\);
INSERT INTO testtable\(id,flag,code,name,name2\) VALUES\(1,'A','002','Name2','Name2\-alternative'\);
INSERT INTO testtable\(id,flag,code,name,name2\) VALUES\(2,'A','003','Name3',NULL\);
INSERT INTO testtable\(id,flag,code,name,name2\) VALUES\(3,'B','004','Name4',NULL\);
INSERT INTO testtable\(id,flag,code,name,name2\) VALUES\(4,'B','005','Name5',NULL\);
INSERT INTO testtable\_child\(id,testtable\_id,text,NAME2\) values\(5,0,'a text','Name1\-alternative'\);
INSERT INTO testtable\_child\(id,testtable\_id,text,NAME2\) values\(6,1,'a text','Name2\-alternative'\);

SELECT \* FROM testtable ORDER BY id

On FB 1\.5\.5 all 5 records are in the list \(runs on TESTTABLE\_UK2 index\)
On FB 2\.0\.5 only the first 2 records are \(where the name2 value is not null\) in the list \(runs on TESTTABLE\_UK2 index\)

I know TESTTABLE\_UK2 is a strange unique, becaue it's first field is the PK, but we need it, because the child table foreign key\. The TESTTABLE\_CHILD\_FK1 protects the name2 field value form updates\.

We've got workarounds for the problem \(use a different way for protection\)\. BUT because the "data loss" \(phisically the data is exists in the DB, and can be reached if do not use the ORDER BY on id\) I set it Mayor instead of Minor\. Or it sholud be Critical?

**Comment by EPluribusUnum** [comment]
You can close this issue. Thank you.
