### ISSUE TITLE
Many indexed reads in a compound index with NULLs [CORE2709]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#3106]
Submitted by: Alex Bekhtin (afgm)

Is related to [CORE3449](https://github.com/FirebirdSQL/firebird/issues?q=CORE3449+in%3Atitle)
Relate to [CORE3675](https://github.com/FirebirdSQL/firebird/issues?q=CORE3675+in%3Atitle)

CREATE TABLE TEST\_TABLE \(
    ID1  INTEGER,
    ID2  INTEGER,
    ID3  INTEGER
\);
COMMIT;

INSERT INTO TEST\_TABLE \(ID1, ID2, ID3\) VALUES \(1, 1, NULL\);
INSERT INTO TEST\_TABLE \(ID1, ID2, ID3\) VALUES \(1, 2, NULL\);
INSERT INTO TEST\_TABLE \(ID1, ID2, ID3\) VALUES \(1, 3, NULL\);
INSERT INTO TEST\_TABLE \(ID1, ID2, ID3\) VALUES \(2, 1, NULL\);
INSERT INTO TEST\_TABLE \(ID1, ID2, ID3\) VALUES \(2, 2, NULL\);
INSERT INTO TEST\_TABLE \(ID1, ID2, ID3\) VALUES \(2, 3, NULL\);
COMMIT;

CREATE INDEX TEST\_TABLE\_IDX1 ON TEST\_TABLE \(ID1, ID2\);
COMMIT;

select \* from test\_table where ID1 = 1 and ID2 = 2
\-\- one indexed read
select \* from test\_table where ID1 = 1 and ID2 IS NULL
\-\- zero indexed read

DROP INDEX TEST\_TABLE\_IDX1;
CREATE INDEX TEST\_TABLE\_IDX1 ON TEST\_TABLE \(ID1,ID2,ID3\);

select \* from test\_table where ID1 = 1 and ID2 = 2
\-\- one indexed read again
select \* from test\_table where ID1 = 1 and ID2 IS NULL
\-\-   3\(\!\!\!\) indexed reads 

Commits: FirebirdSQL/firebird@c1c5d2b0dbaa4118652e27c588f0144e0595a4e4 FirebirdSQL/firebird@cf6e3d09690ab6384b7fa2d83bfe9c721a325976 FirebirdSQL/firebird@a021e4d1a12eded10800c3c380ae72f7d4429435 FirebirdSQL/firebird@ce9e812717e6a8b02654d1e7ec95b5f41bb91bbe FirebirdSQL/fbt-repository@a290acc6c6ea1beb2f7d397178ca8ed9d2cb5575

**Comment by hvlad** [comment]
I can't reproduce it with 3.0.0 and 3.0.11
