### ISSUE TITLE
Wrong parameter management in the engine / partial workaround in JayBird driver [CORE3099]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#3477]
Submitted by: Sylvain Dusart (sdusart)

Attachments:
[FBParametersTestCase.java](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-3099/11697_FBParametersTestCase.java)
[testcase_output.txt](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-3099/11698_testcase_output.txt)
[testcase_output_with_jaybird_workaround_removed.txt](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-3099/11699_testcase_output_with_jaybird_workaround_removed.txt)

Votes: 1

Hi,

there is, as explained in issues [JDBC58](https://github.com/FirebirdSQL/jaybird/issues?q=JDBC58+in%3Atitle) and [CORE1217](https://github.com/FirebirdSQL/firebird/issues?q=CORE1217+in%3Atitle), a bug in Firebird engine : string parameters get truncated and this may lead to a FB server crash\.

There is a workaround in JayBird \(class org\.firebirdsql\.jdbc\.field\.FBWorkaroundStringField, method setString\) to prevent server from crashing\.
This method throws a java\.sql\.DataTruncation as soon as possible \(before sending the sql request to the database server\)\.
Workaround is :

if \(data\.length \> field\.sqllen && \!isSystemTable\(field\.relname\)\) \{
                // special handling for the LIKE ? queries with CHAR\(1\) fields
                if \(\!\(value\.length\(\) <= field\.sqllen \+ 2 && value\.charAt\(0\) == '%' && value\.charAt\(value\.length\(\) \- 1\) == '%'\)\) \{
                    throw new DataTruncation\(\-1, true, false, data\.length, field\.sqllen\);
                \}
            \}

Requests like "SELECT \* FROM COMPANY WHERE NAME LIKE ?" with a parameter whose length is higher than the NAME column length should not fail but return an empty resultset\.

I'll attach a java class to reproduce the parameter problem using JDK6 \+ JayBird 2\.1\.6 \+ FB 2\.1\.3\.

If you run it with a patched JayBird driver \(commented workaround lines in org\.firebirdsql\.jdbc\.field\.FBWorkaroundStringField\), you'll see that insert or update queries do not fail if the new value length for the NAME column is 11 or 12 \(data gets silently truncated to maximum length of 10 in the engine\) but fail if new length is \>= 13\.

I'll try to reproduce the test case in Delphi\.

Regards,

Sylvain

**Comment by mrotteveel** [comment]
Duplicate (which IMHO describes the problem better): https://github.com/FirebirdSQL/firebird/issues/1361
