### ISSUE TITLE
the server crash very often: The Firebird Server - DefaultInstance service terminated unexpectedly.  [CORE3213]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#3587]
Submitted by: vander clock stephane (arkadia)

Is related to [CORE3206](https://github.com/FirebirdSQL/firebird/issues?q=CORE3206+in%3Atitle)

Attachments:
[fbserver.exe.15660.dmp](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-3213/12286_fbserver.exe.15660.dmp)

Votes: 1

hello,

now that i check the windows log i discover that our fb server crash very often \(1 times / 2 days in average\):
The Firebird Server \- DefaultInstance service terminated unexpectedly\.  It has done this 1 time\(s\)\.  The following corrective action will be taken in 0 milliseconds: Restart the service\.

hard to know why\.\.\. no firebird\.log file are even created \!

The server is very intensive, i remembered that the last time it's crash, it's was when i do myself an heavy update query \(using the ISQL\)\. but redoing the query just after the crash not make the server crash again \.\.\.

Actually i set up the cache memory to use 85% of all available memory \(so 28GB of 32GB are used in the task manager\)\.

any idea how to debug it more deeply ?

**Comment by dyemanov** [comment]
Closed as outdated (and possibly resolved).
