### ISSUE TITLE
database page errors and record level error when updating records with blobs several times [CORE3214]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#3588]
Submitted by: Alexandre Palmeira (palmeira)

Attachments:
[INDICEErr.7z](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-3214/11834_INDICEErr.7z)

I have a database with only one table:

CREATE TABLE IMP\_PESSOAL\_NDX 
\(
  PALAVRA              INTEGER         NOT NULL,
  N                    INTEGER,
  VERSAO              SMALLINT,
  INDICE                  BLOB SUB\_TYPE 0 SEGMENT SIZE 80,
 CONSTRAINT PK\_IMP\_PESSOAL\_NDX PRIMARY KEY \(PALAVRA\)
\);

INDICE is a list of integers\. My program reads a list of 300\.000 pairs \(P, N\), locates or inserts the record with PALAVRA=P, reads the sorted integer list in INDICE, adds N to the list and saves it back to INDICE\. \(I am not sure when the alterations are commited\.\)

At the end of the process, there are several page errors\. The database is several times larger than it should be, and I am unable to back it up\.

The issue was also present in version 2\.1\.

**Comment by dyemanov** [comment]
Outdated / not reproducible.
