### ISSUE TITLE
Partial Indexes [CORE3384]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#3750]
Submitted by: Vladimir Arkhipov (arkinform)

Votes: 4

Example:

CREATE UNIQUE INDEX orders\_number\_idx ON orders \(number\)
    WHERE number is not null

Description from <http://www.postgresql.org/docs/8.0/static/indexes-partial.html>

"A partial index is an index built over a subset of a table; the subset is defined by a conditional expression \(called the predicate of the partial index\)\. The index contains entries for only those table rows that satisfy the predicate\."

"A major motivation for partial indexes is to avoid indexing common values\. Since a query searching for a common value \(one that accounts for more than a few percent of all the table rows\) will not use the index anyway, there is no point in keeping those rows in the index at all\. This reduces the size of the index, which will speed up queries that do use the index\. It will also speed up many table update operations because the index does not need to be updated in all cases\."

Very very useful \!\!\!

**Comment by justin-fyfe** [comment]
+1 if this feature can be done. Not for performance but for unique enforcement. For example, consider the table:

```
CREATE TABLE FOO_TBL (
     ID    UUID NOT NULL,
     USER_ID UUID NOT NULL,
     UNIQUE_VALUE VARCHAR(256) NOT NULL, -- THE UNIQUE VALUE
     START_TS TIMESTAMP NOT NULL, -- THE TIME THE VALUE BECAME ACTIVE
     STOP_TS TIMESTAMP, -- THE TIME THAT THE VALUE WAS NO LONGER ACTIVE
     CONSTRAINT PK_FOO PRIMARY KEY (ID),
     CONSTRAINT FK_FOO_USER FOREIGN KEY (USER_ID) REFERENCES USER_TBL(USER_ID)
);
```

Basically a table which needs to track changes over time of a value (can be anything like an medical record number, etc.) but basically the business requirement is: **value must be unique if it is active**.

In PostgreSQL, Oracle, and even SQLite this is done via:

```
CREATE UNIQUE INDEX FOO_UQ_IDX ON FOO_TBL(UNIQUE_VALUE) WHERE (STOP_TS IS NULL);
```

i.e. Enforce the unique constraint on `UNIQUE_VALUE` if it has not been indicated as no longer valid.

If there is a way to do this other than indexes in Firebird I'd love an example - currently we've just removed unique checking on this value when users use Firebird, it would be nice if our Firebird provider could behave the same way as our Postgres, SQLite and Oracle providers :)

**Comment by hvlad** [comment]
You may use expression index right now:

```
CREATE UNIQUE INDEX FOO_UQ_IDX ON FOO_TBL COMPUTED BY (CASE WHEN STOP_TS IS NULL THEN UNIQUE_VALUE END) 
```

**Comment by pavel-zotov** [comment]
@@@ QA issue @@@
Currently this test contains only trivial cases for check.
More complex examples, including test of backup/restore, validation, using of misc datatypes (non-ascii, decfloat and int128), will be added later.

**Comment by pavel-zotov** [comment]
QA: see tests for #7257
