### ISSUE TITLE
RDB$INDICES information stored inconsistently after a CREATE INDEX [CORE3741]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#4085]
Submitted by: @mrotteveel

The information in RDB$INDICES is stored inconsistently for the true/false values of 1 and 0 when an index is created using CREATE INDEX\.

RDB$UNIQUE\_FLAG is 1 for a unique index, but NULL for non\-unique \(I would expect 0\)
RDB$INDEX\_INACTIVE is NULL for newly created indices \(I would expect 0\), issuing an ALTER INDEX <name\> INACTIVE makes it 1 and 0 if it has been again altered to ACTIVE
RDB$INDEX\_TYPE is 1 for DESCENDING indices, but NULL for ASCENDING \(I would expect 0\)

After a backup and restore, these fields do get the expected values\.

Small DDL script that will demonstrate most of this:
CREATE TABLE TEST\_COLUMN\_DEFAULTS
\(
  COL\_INTEGER\_DEFAULT\_NULL Integer DEFAULT NULL,
  COL\_INTEGER\_DEFAULT\_999 Integer DEFAULT 999,
  COL\_VARCHAR\_DEFAULT\_NULL Varchar\(100\) DEFAULT NULL,
  COL\_VARCHAR\_DEFAULT\_USER Varchar\(100\) DEFAULT USER,
  COL\_VARCHAR\_DEFAULT\_LITERAL Varchar\(100\) DEFAULT 'literal'
\);
CREATE INDEX IDX\_COMPUTED ON TEST\_COLUMN\_DEFAULTS COMPUTED BY \('\!'\|\|COL\_VARCHAR\_DEFAULT\_USER\|\|'\!'\);
CREATE DESCENDING INDEX IDX\_COMPUTED2 ON TEST\_COLUMN\_DEFAULTS COMPUTED BY \('\!'\|\|COL\_VARCHAR\_DEFAULT\_USER\|\|'\!'\);
CREATE DESCENDING INDEX IDX\_TEST\_COLUMN\_DEFAULTS1 ON TEST\_COLUMN\_DEFAULTS \(COL\_INTEGER\_DEFAULT\_NULL\);
CREATE UNIQUE INDEX IDX\_TEST\_COLUMN\_DEFAULTS2 ON TEST\_COLUMN\_DEFAULTS \(COL\_INTEGER\_DEFAULT\_999\);

**Comment by dyemanov** [comment]
RDB$UNIQUE_FLAG and RDB$INDEX_TYPE are filled correctly (as you expect) starting with FB3, however RDB$INDEX_INACTIVE is still NULL. I'm going to commit a remaining fix.
