### ISSUE TITLE
DROP [IF EXISTS] ...  [CORE3863]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#4203]
Submitted by: eXandr (i.reg)

Votes: 4

It should be possible to determine not cause an error when deleting an object that does not exist
Something like that:
 
  execute statement 'ALTER TABLE SOME\_TABLE DROP \[IF EXISTS\] SOME\_FIELD'; \-\- no raise error if field  SOME\_FIELD is not exist 
  or
  execute statement 'DROP INDEX IDX1 \[IF EXISTS\]';  \-\- no raise error if index IDX1 is not exist 

Workaround for now is:

  begin 
    execute statement 'ALTER TABLE SOME\_TABLE DROP SOME\_FIELD'; 
  when any do 
    begin 
    end 
  end

But this solution hides any error that is very bad\. Another solution is to access the system tables, but it requires more code and can add even more errors\.

**Comment by ertankucukoglu** [comment]
Even if it is not in standard such use case is supported by several database systems and readability is far more easy compared to existing method (execute statement). I would also ask CREATE / ADD statements and allowing NOT usage as well.

CREATE TABLE IF NOT EXISTS <table name>
ALTER TABLE ADD COLUMN IF NOT EXISTS <column name>
CREATE INDEX IF NOT EXISTS <index name>

**Comment by asfernandes** [comment]
I think this is like RECREATE or CREATE OR ALTER. It's not standard, but if it helps users, why not?
But I would go only for the top level objects, not for columns like in your above example.

**Comment by dyemanov** [comment]
> I think this is like RECREATE or CREATE OR ALTER. It's not standard, but if it helps users, why not? But I would go only for the top level objects, not for columns like in your above example.

Agreed.

**Comment by ertankucukoglu** [comment]
I do not think it is like RECREATE. I do not want to create it again or
modify existing table data.
I work on database update scripts quite a lot. Tables are already there
99% of the time. Adding columns is one of the main tasks I frequently do
and so I gave an example of it.

Dmitry Yemanov ***@***.***>, 10 Haz 2023 Cmt, 22:02 tarihinde
şunu yazdı:

**Comment by aafemt** [comment]
In your own database, it is much easier and more predictable to know exactly which tables exist and which aren't. If the database structure is fixed, documented and changed only on new release - there is no need to check existence of database objects. So it is just a matter of developer's discipline.

**Comment by ertankucukoglu** [comment]
It is not my database, I am a freelancer mostly fixing other's mess.

Dimitry Sibiryakov ***@***.***>, 10 Haz 2023 Cmt, 22:38
tarihinde şunu yazdı:

**Comment by mrotteveel** [comment]
> I do not think it is like RECREATE. I do not want to create it again or modify existing table data. 

That is not what Adriano said. He just said the RECREATE and CREATE OR ALTER are also non-standard, but we introduced them because they can be helpful. Similar reasoning can be applied for adding IF NOT EXISTS for CREATE.

**Comment by mrotteveel** [comment]
If this is going to get added, I'd also like its counter part `IF EXISTS` to `DROP <object-type>`, e.g `DROP TABLE IF EXISTS <table-name>`.

**Comment by dyemanov** [comment]
I'm somewhat worried about the `CREATE` part of this feature request. Imagine a case when the object exists but declared differently. No error is raised with `CREATE ... IF NOT EXISTS` but the object keeps its old definition which is maybe not what you'd expect. `CREATE OR ALTER` is IMHO superior in this regard. This problem does not exist for `DROP ... IF EXISTS`.

**Comment by mrotteveel** [comment]
> I'm somewhat worried about the `CREATE` part of this feature request. Imagine a case when the object exists but declared differently. No error is raised with `CREATE ... IF NOT EXISTS` but the object keeps its old definition which is maybe not what you'd expect. `CREATE OR ALTER` is IMHO superior in this regard. This problem does not exist for `DROP ... IF EXISTS`.

As far as I'm aware, all other DBMSes that implement `IF NOT EXISTS` are simply going by existence of an object with that name, they don't care about the actual content or structure of that object. It would be the responsibility of the one writing the script to make "the right choice".

**Comment by dyemanov** [comment]
But do those other DBMSes have some analogue of `CREATE OR ALTER`? For example, MSSQL has `CREATE OR ALTER` and `DROP ... IF EXISTS`, but AFAIK it does not have `CREATE ... IF NOT EXISTS`, supposedly because `CREATE OR ALTER` does it better in all cases.

**Comment by mrotteveel** [comment]
Well, Firebird doesn't have `CREATE OR ALTER TABLE` (nor for `INDEX`, or `DOMAIN`), so that point is a bit moot. 

Sure, if looked at in isolation, for the object types which do have `CREATE OR ALTER`, using that would usually be superior to a `CREATE .. IF NOT EXISTS`. However, I think that in itself is not a reason to not add `IF NOT EXISTS` (though it does reduce the need for it for object types which already have `CREATE OR ALTER`). 

Although I usually argue for not introducing non-standard features, I think that `IF [NOT] EXISTS` for DDL is common enough to be considered a community standard. For example, it is supported by PostgreSQL, MySQL, MariaDB, SQLite, HSQLDB, H2, BigQuery, and probably others.

**Comment by dyemanov** [comment]
Well, recent Oracle versions have both `CREATE OR REPLACE` and `CREATE ... IF NOT EXISTS`, so we can surely go the same route.

**Comment by ertankucukoglu** [comment]
Just comparing with an execute block script, I only check for object existence. I don't drop existing one. I don't check if it is of same data type. I didn't have the need to do that so far as I'm mostly adding new columns. Everyone's use case is different for sure.
