### ISSUE TITLE
Optimize disk space consumption for BLOB concatenation operations [CORE3948]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#4281]
Submitted by: Jörg Fröber (j_froeber)

Relate to [CORE1658](https://github.com/FirebirdSQL/firebird/issues?q=CORE1658+in%3Atitle)
Relate to [CORE3838](https://github.com/FirebirdSQL/firebird/issues?q=CORE3838+in%3Atitle)
Relate to [CORE1273](https://github.com/FirebirdSQL/firebird/issues?q=CORE1273+in%3Atitle)

Votes: 7

When a blob is being concatenated mulitple times, the disk space for the database file grows massively\. The only way to get the file size back to normal is a backup and restore of the database\.

The issue can be reproduced as described below: 

\- Create an empty database
\-  Create the following procedure:
SET TERM ^ ;
CREATE OR ALTER PROCEDURE P\_TEST \(
  TEST VARCHAR\(200\),
  ITERATIONS INTEGER\)
RETURNS \(
  BLOBTEXT BLOB SUB\_TYPE 0 SEGMENT SIZE 80\)
AS
DECLARE COUNTER INTEGER;
BEGIN
  COUNTER = 0;
  BLOBTEXT = '';

  WHILE \(COUNTER < ITERATIONS\)
  DO BEGIN
    BLOBTEXT = BLOBTEXT \|\| ' ' \|\| TEST;
    COUNTER = COUNTER \+ 1;
  END 

  SUSPEND;
END^
SET TERM ; ^

GRANT EXECUTE ON PROCEDURE P\_TEST TO "PUBLIC";
GRANT EXECUTE ON PROCEDURE P\_TEST TO SYSDBA;

\- run the procedure:
SELECT BLOBTEXT FROM P\_TEST\('This is a test sentence, which is going to be concatenated\.', 4000\);

After the procedure has been executed, the disk space used by the database file increases to over 1 GB\. It makes no difference, if the transaction is committed or not\.
When you run the procedure another time using the SQL\-command EXECUTE PROCEDURE P\_TEST\('This is a test sentence, which is going to be concatenated\.', 4000\); the file size increases again\.

**Comment by dyemanov** [comment]
AFAIU, with `BLOB_APPEND` and `RDB$BLOB_UTIL` this should not be an issue anymore and thus the ticket could be closed as resolved.

**Comment by hvlad** [comment]
Agree.
