### ISSUE TITLE
Allow connect to external databases, separate from execute statement [CORE4195]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#4521]
Submitted by: @sim1984

The idea is to declare a connection to an external database in PSQL block and use it to execute statement\.

execute block as
  declare stt varchar\(255\) = 'select count\(\*\) from rdb$relations';
  declare cnt int;
  declare i int = 10;
  declare external source my\_ext\_source  'localhost:D:\\TEST25\.fdb' as user 'sysdba' password 'masterke';
begin
  open my\_ext\_source;
  while \(i \> 0\) do
  begin
     execute statement \(:stt\)
       with autonomous transaction
       on external my\_ext\_source
       into :cnt;
     i = :i \- 1;
  end
  close my\_ext\_source;
end

This will connect to the database only once, instead of connections and disconnections for each execution execute statement\.

**Comment by dyemanov** [comment]
Closed in favour of the priorly created (and more general) #1158.
