### ISSUE TITLE
Add new clause to FOR UPDATE WITH LOCK:  SKIP LOCKED - for selecting 'free' record(s) from table or updatable view [CORE4385]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#4707]
Submitted by: @pavel-zotov

Currently one need to write cursor with trying to update record and catch lock conflicts in when\-block to skip rows which are locked by others\.
It will be useful if FB has the mechanism to obtain non\-locked record\(s\) directly in SELECT statement\.

**Comment by mrotteveel** [comment]
Duplicate of: https://github.com/FirebirdSQL/firebird/pull/7350 (implemented in Firebird 5.0)
