### ISSUE TITLE
Grant and Revoke update (field) [CORE4407]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#4729]
Submitted by: Tomas Beran (berant)

I have a problem with permissions\. I test this problem on new database\.
I have two users \(User1 and User2\), one table \(TEST\_TABLE \(PKID, NAME, AGE\)\)\. I set permission select and update\(AGE\) to both users\. Now everything is all right, but when I revoke permission to USER2 \(revoke select, update\(AGE\)\), then USER1 has not permission to update fields \(but he should have\)\.

Example:
create table TEST\_TABLE \(  PKID                  integer,  NAME                  varchar\(10\),  AGE                   integer,
constraint TEST\_PKID primary key \(PKID\)\);

commit;

insert into TEST\_TABLE values \(1, 'TEST', 99\);

grant select, update\(AGE\) on TEST\_TABLE to USER1, USER2;

\-\-USER1 or USER2:
update TEST\_TABLE set AGE = 1; \-\-both can update

revoke select, update\(AGE\) on TEST\_TABLE from USER2;
\-\-USER1:
update TEST\_TABLE set AGE = 1; \-\-no permission to update

  Now USER1 has no permission for update/write access to COLUMN TEST\_TABLE\.AGE
  but has permission to select\. If I grant update on whole TEST\_TABLE then everything all right, but if I set permission on one field,
  permissions are wrong\.

**Comment by hubeny** [comment]
Hi,

I tested this bug again and the problem is actual on last build of FB3 (3.0.10) and last build of FB4 (4.0.2).  Is there any time plan to fix it?

Thank you,

Jan Hubeny

**Comment by AlexPeshkoff** [comment]
Confirm an issue in all versions, suppose will fix till next fb4 release.

**Comment by hubeny** [comment]
Hi Alex,  

please add also  label:"affect-version: 3.0.10". I tested it again and it really affect also version 3.0.10.

Thank you,

H.
