### ISSUE TITLE
Introduce SORTLIST function [CORE4520]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#4838]
Submitted by: Tim Kelly (m00bh000)

It would be useful to have a built in function to sort a list, perhaps called SORTLIST\(aList, ASC \| DESC\)\. This would particularly useful when combined with the aggregate LIST function\.

SELECT SORTLIST\('A, C, B'\)  FROM RDB$DATABASE\.\.\.\. \-\> Should return CONSTANT:  "A, B, C"

Please note this would solve [CORE2332](https://github.com/FirebirdSQL/firebird/issues?q=CORE2332+in%3Atitle) as you could:

SELECT SORTLIST\(LIST\(MY\_COL\)\) FROM \.\.\. to get a sorted version of an aggregated list\.

It would also solve [CORE2106](https://github.com/FirebirdSQL/firebird/issues?q=CORE2106+in%3Atitle):

SELECT HASH\(SORTLIST\(LIST\(MY\_COL\)\)\) FROM\.\.\. to get a checksum based on an aggrageted query \(ie determine quickly if any of the value in MY\_COL have changed\. This currently is not possible since the order that LIST returns is undefined\.

Would also be useful if we implemented [CORE4335](https://github.com/FirebirdSQL/firebird/issues?q=CORE4335+in%3Atitle)\. \(non\-aggregate version of LIST \(LISTVALUE\(\)\)

**Comment by dyemanov** [comment]
As mentioned in #2756, there's a standard extension to the LIST function for this purpose, so we don't need an additional function. Given that it's already being developed, I'm closing this ticket as duplicated.
