### ISSUE TITLE
Select slowing down [CORE4628]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#4943]
Submitted by: Attila Molnár (e_pluribus_unum)

Attachments:
[test.gbk.zip](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-4628/12640_test.gbk.zip)
[test.sql](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-4628/12641_test.sql)

Hi\!

See attached files\.
Running the SQL you'll see that SELECT statement in the loop block slows down by every iteration \(dSelect\)\.
Updata \(dUpdate\) and fetch \(dFetch\) times are stable\.

Runtime statistic shows what you expect
IR : 87121 \(form the slowing down select \)
NIR : 87121 \(from the for select\)
UPD : 87121 \(from the update\)

So looks like index reading slows down\.

This is a bug and can be fixed, or this cames from inner desing and works as expected?

Thank you\!

**Comment by EPluribusUnum** [comment]
You can close this issue. Thank you.
