### ISSUE TITLE
Auto sweeper kills its own connection [CORE4745]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#5050]
Submitted by: Omacht András (aomacht)

On different databases at different time auto sweeper dies and restarts three or four times and finally complete the job\.

Log:
xxx    Thu Apr  9 15:51:31 2015
        Sweep is started by SWEEPER
        Database "/u1/firebird/db/yyy\.fdb"
        OIT 229037, OAT 229038, OST 229038, Next 263970

xxx    Thu Apr  9 15:51:53 2015
        Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

xxx    Thu Apr  9 15:51:54 2015
        Error during sweep:
        connection shutdown

xxx    Thu Apr  9 15:52:55 2015
        Sweep is started by SWEEPER
        Database "/u1/firebird/db/yyy\.fdb"
        OIT 232570, OAT 253894, OST 253894, Next 263979

xxx    Thu Apr  9 15:52:55 2015
        Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

xxx    Thu Apr  9 15:52:55 2015
        Error during sweep:
        connection shutdown

xxx    Thu Apr  9 15:53:16 2015
        Sweep is started by SWEEPER
        Database "/u1/firebird/db/yyy\.fdb"
        OIT 232570, OAT 253894, OST 253894, Next 263985

xxx    Thu Apr  9 15:53:16 2015
        Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

xxx    Thu Apr  9 15:53:16 2015
        Error during sweep:
        connection shutdown

xxx    Thu Apr  9 15:53:23 2015
        Sweep is started by SWEEPER
        Database "/u1/firebird/db/yyy\.fdb"
        OIT 232570, OAT 253894, OST 253894, Next 263989

xxx    Thu Apr  9 15:57:44 2015
        Sweep is finished
        Database "/u1/firebird/db/yyy\.fdb"
        OIT 253893, OAT 253894, OST 253894, Next 264042

After backup/restore randomly the same happen\. Backup without \-g works fine\.

**Comment by omachtandras** [comment]
We haven’t experienced this error in the last few years, so the issue can be closed.
