### ISSUE TITLE
Connect error : Database is probably already opened by another engine instance in another Windows session. [CORE4751]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#5055]
Submitted by: Attila Molnár (e_pluribus_unum)

Hi\!

I've started a long running process at 14 Apr 2015 07:34:38 \+0200, which maintains the database schema and data by running a lot of DDL, DQL, DML commands\. The process also does connect\-disconnect many times\.

Error in client side : "Database is probably already opened by another engine instance in another Windows session\." at 14 Apr 2015 07:37:53 \+0200
This error is raised when I try to connect to the database\.

No concurrency in client side, calls are made from apps main thread\.
Looks like sweep connection / concurrency handling is flawed\.

Logs in server side \(2\.5\.4 Classic Server\)

L3S\-4 Tue Apr 14 07:35:45 2015
Sweep is started by SWEEPER
Database "D:\\DATABASES\\AMOLNAR\_ELESKER\.GDB3S"
OIT 207896, OAT 227897, OST 227897, Next 227898

L3S\-4 Tue Apr 14 07:36:03 2015
Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

L3S\-4 Tue Apr 14 07:36:03 2015
Error during sweep:
connection shutdown

L3S\-4 Tue Apr 14 07:36:03 2015
Sweep is started by SWEEPER
Database "D:\\DATABASES\\AMOLNAR\_ELESKER\.GDB3S"
OIT 207896, OAT 228222, OST 228222, Next 228227

L3S\-4 Tue Apr 14 07:36:59 2015
Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

L3S\-4 Tue Apr 14 07:36:59 2015
Error during sweep:
connection shutdown

L3S\-4 Tue Apr 14 07:36:59 2015
Sweep is started by SWEEPER
Database "D:\\DATABASES\\AMOLNAR\_ELESKER\.GDB3S"
OIT 207896, OAT 228232, OST 228232, Next 229499

L3S\-4 Tue Apr 14 07:37:01 2015
Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

L3S\-4 Tue Apr 14 07:37:01 2015
Error during sweep:
connection shutdown

L3S\-4 Tue Apr 14 07:37:01 2015
Sweep is started by SWEEPER
Database "D:\\DATABASES\\AMOLNAR\_ELESKER\.GDB3S"
OIT 207896, OAT 229502, OST 229502, Next 229504

L3S\-4 Tue Apr 14 07:37:19 2015
Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

L3S\-4 Tue Apr 14 07:37:19 2015
Error during sweep:
connection shutdown

L3S\-4 Tue Apr 14 07:37:19 2015
Sweep is started by SWEEPER
Database "D:\\DATABASES\\AMOLNAR\_ELESKER\.GDB3S"
OIT 207896, OAT 229508, OST 229508, Next 229511

L3S\-4 Tue Apr 14 07:37:20 2015
Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

L3S\-4 Tue Apr 14 07:37:20 2015
Error during sweep:
connection shutdown

L3S\-4 Tue Apr 14 07:37:20 2015
Sweep is started by SWEEPER
Database "D:\\DATABASES\\AMOLNAR\_ELESKER\.GDB3S"
OIT 207896, OAT 229537, OST 229537, Next 229539

L3S\-4 Tue Apr 14 07:37:21 2015
Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

L3S\-4 Tue Apr 14 07:37:21 2015
Error during sweep:
connection shutdown

L3S\-4 Tue Apr 14 07:37:21 2015
Sweep is started by SWEEPER
Database "D:\\DATABASES\\AMOLNAR\_ELESKER\.GDB3S"
OIT 207896, OAT 229671, OST 229671, Next 229673

L3S\-4 Tue Apr 14 07:37:25 2015
Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

L3S\-4 Tue Apr 14 07:37:25 2015
Error during sweep:
connection shutdown

L3S\-4 Tue Apr 14 07:37:25 2015
Sweep is started by SWEEPER
Database "D:\\DATABASES\\AMOLNAR\_ELESKER\.GDB3S"
OIT 207896, OAT 229990, OST 229990, Next 229994

L3S\-4 Tue Apr 14 07:37:53 2015
Shutting down the server with 1 active connection\(s\) to 1 database\(s\), 0 active service\(s\)

L3S\-4 Tue Apr 14 07:37:53 2015
Error during sweep:
connection shutdown

**Comment by omachtandras** [comment]
We haven’t experienced this error in the last few years, so the issue can be closed.
