### ISSUE TITLE
String truncation exception on UPPER/LOWER functions, UTF8 database and some multibyte characters [CORE5255]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#5534]
Submitted by: Олег Короткий (олег короткий)

Votes: 2

select upper\('ɐ'\) from rdb$database
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
arithmetic exception, numeric overflow, or string truncation\.
string right truncation\.
expected length 2, actual 2\.

select lower\('ɐ'\) from rdb$database
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
LOWER
ɐ

select lower\('Ⱥ'\) from rdb$database
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
arithmetic exception, numeric overflow, or string truncation\.
string right truncation\.
expected length 2, actual 2\.

select upper\('Ⱥ'\) from rdb$database
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
UPPER
Ⱥ

**Comment by asfernandes** [comment]
> Commented by: Олег Короткий (олег короткий)
> 
> Also CONTAINING function bug:
> select iif('ɱ' containing 'а',1,0) from rdb$database
> ------------------
> arithmetic exception, numeric overflow, or string truncation.
> string right truncation.
> expected length 2, actual 2.

The problem with UPPER/LOWER is being fixed as part of this report.

Problem with CONTAINING is left for #6851.

**Comment by mrotteveel** [comment]
@asfernandes Will this also be fixed for 4.0.1?

**Comment by asfernandes** [comment]
> @asfernandes Will this also be fixed for 4.0.1?

Yes. I've put now the missing label.

**Comment by pavel-zotov** [comment]
::: test details :::
CONTAINING still does not work. 
Sent example to Adriano, waiting for reply.

**Comment by asfernandes** [comment]
> ::: test details :::
> CONTAINING still does not work.
> Sent example to Adriano, waiting for reply.

@pavel-zotov, as I've commented:

> The problem with UPPER/LOWER is being fixed as part of this report.
> 
> Problem with CONTAINING is left for #6851.

**Comment by pavel-zotov** [comment]
sorry for noise, I was inattentive. Test for this issue will check all except statements with `containing`.

**Comment by pavel-zotov** [comment]
::: test details :::

Test verifies work of predicates, functions for string handling and comparison.
This is performed for VARCHAR and BLOB datatypes, but currently BLOB datatype has a problem:
invocation of rsa_encrypt() leads to 'malformed string' error.
Because of this, such code for BLOBs temporary is commented out.
Sent letter to Alex et al, 14-jun-2021 20:03.
