### ISSUE TITLE
Non US-ASCII field names treated as unicode, although charset non-unicode, lowering max field length [CORE5258]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#5537]
Submitted by: Олег Короткий (олег короткий)

Charset: WIN1251

select 1 as "Поле в 25 символов" from rdb$database
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Поле в 25 символов
1

select 1 as "Поле в 26 символов\!" from rdb$database
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
arithmetic exception, numeric overflow, or string truncation\.
string right truncation\.
expected length 31, actual 19\.

2\.5 is not affected by this bug\.

**Comment by pavel-zotov** [comment]
QA note.
It seems that this ticket can be closed: error message in 3.x is "Name longer than database column size", all other FB versions work as expected (no errors).
