### ISSUE TITLE
When 32bit and 64bit FB 3 servers run on one Windows machine concurrently, Firebird services freeze several minutes after first disconnect. [CORE5515]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#5784]
Submitted by: michalk1 (michalk1)

Attachments:
[CORE-5515.7z](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-5515/13313_CORE-5515.7z)

Steps to reproduce:
1\) Install FB3\.0\.2 64bit with default settings \(port 3050, service name DefaultInstance\)
2\) Use FB3\.0\.2 32bit zip package to install another FB instance at the same machine, change its RemoteServicePort in firebird\.conf \(e\.g\. to 3051\), setup its security database and use instsvc to configure and start the service \(named say FB30\)
  instsvc i \-n FB30
  instsvc start \-n FB30
3\) Run isql from DefaultInstance server and make TCP connect to its employee database
  isql \-user sysdba \-password masterkey localhost/3050:employee
4\) Run isql from FB30 server instance and connect to its employee database as well
  isql \-user sysdba \-password masterkey localhost/3051:employee
5\) Close both connections and isql consoles \(ctrl\+z\)
6\) Wait at least two minutes
7\) Now, when trying to connect again to any database, isql console freezes\. Both FB services are stuck as well and must be killed from task manager\.
  
Clues:
The problem is not isql or database specific, you can use i\.e\. FlameRobin, and connect to any database to demonstrate the problem\.
What is weird is the time limit required in step 6, because when the new connection is established fast enough \(in less than about those two minutes\), everything continues to work\.
Two FB 3 64bit or two 32bit servers work together ok, it is only combination of 32bit and 64bit servers that cause hangs\.

Commits: FirebirdSQL/firebird@90270cd11a385e92355492b08ba63b1bca1e9169 FirebirdSQL/firebird@ffaf62b5ffcd5e17e26b4ce94a50813993b88c26

**Comment by marcosfba** [comment]
Tenho uma aplicação utilizando as seguintes versões do firebird de modo embarcado Firebird 2.5.9 e Firebird 3.0.7 de modo concomitante e varias conexões simultâneas funcionando perfeitamente. Ao adicionar a versão do Firebird 4.0.0 na aplicação sistema operacional entra em conflito conforme imagem abaixo:
![image](https://user-images.githubusercontent.com/12546259/130676224-d7b26801-0f66-4a91-9145-d7ce45eea2a8.png)
Gostaria de saber como resolver.

**Comment by mrotteveel** [comment]
@marcosfba Please post in English

**Comment by marcosfba** [comment]
I have an application using the following versions of firebird in embedded mode Firebird 2.5.9 and Firebird 3.0.7 concurrently and several simultaneous variants working perfectly. When adding the version of Firebird 4.0.0 in the operating system application, it conflicts as shown below: I would like to know how to solve it?
https://user-images.githubusercontent.com/12546259/130676224-d7b26801-0f66-4a91-9145-d7ce45eea2a8.png

**Comment by marcosfba** [comment]
I have an application using the following versions of firebird in embedded
mode Firebird 2.5.9 and Firebird 3.0.7 concurrently and several
simultaneous variants working perfectly. When adding the version of
Firebird 4.0.0 in the operating system application, it conflicts as shown
below: I would like to know how to solve it?
https://user-images.githubusercontent.com/12546259/130676224-d7b26801-0f66-4a91-9145-d7ce45eea2a8.png

Tanks

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em ter., 24 de ago. de 2021 às 16:30, Mark Rotteveel <
***@***.***> escreveu:

**Comment by mrotteveel** [comment]
@marcosfba I recommend you post a question to the [firebird-support Google Group](https://groups.google.com/g/firebird-support). If you're sure this is a bug in Firebird, then create a [new issue](https://github.com/FirebirdSQL/firebird/issues/new/choose) instead of trying to repurpose an existing issue. Make sure to include all the necessary information to reproduce the problem.
