### ISSUE TITLE
Allow to create BIGINT fields in the dialect 1 [CORE5669]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#5935]
Submitted by: Yurii Kucheriavyi (yurock)

Votes: 13

New features, types are available in the dialect 1\.
The system tables that contain the BYGINT fields works in the dialect 1\.
Please, allow create fields with BIGINT type same as in dialect 3 too\.
Thank you\.

**Comment by dyemanov** [comment]
Dialect 1 is deprecated, no new features are going to be added there.
