### ISSUE TITLE
Add support for QUARTER to EXTRACT, FIRST_DAY and LAST_DAY [CORE5693]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#5959]
Submitted by: @ibprovider

I'm surprised that Firebird \(v3\) still not support QUARTER in EXTRACT statement\.

It has a serious reason?

**Comment by omachtandras** [comment]
Oracle: select to_char(sysdate, 'Q') as qtr from  dual;
MSSQL: SELECT DATEPART(quarter, '2017/08/25') AS DatePartInt;
Mysql: SELECT QUARTER("2017-06-15");
Postre: SELECT EXTRACT (QUARTER FROM TIMESTAMP '2011-11-22 13:30:15')

**Extract would also be logical for Firebird:
select extract(quarter from cast('TODAY' as date)) from rdb$database**
