### ISSUE TITLE
Slow performance when executing SQL scripts as non-SYSDBA user [CORE5966]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6220]
Submitted by: @reevespaul

Attachments:
[prep.sh](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-5966/13363_prep.sh)

Votes: 2

When a set of approxiamtely 30\-50 SQL scripts containing updates of single records in various tables is executed as non\-SYSDBA user granted rights to all required objects it takes 3\-4 times more time compared with SYSDBA\.

Commits: FirebirdSQL/firebird@2bf61985922c591ce731b9a0c5a0fa3e6283a38f

**Comment by romansimakov** [comment]
Can we close this issue?

**Comment by AlexPeshkoff** [comment]
Suggest to close - no reply from author for a lo-o-o-ong time, and existing tests show that it's solved.

**Comment by romansimakov** [comment]
Agreed
