### ISSUE TITLE
nbackup unlock causes internal Firebird consistency check (next transaction older than oldest active transaction) [CORE6059]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6309]
Submitted by: Omacht András (aomacht)

Hi\!

Our backup script uses nbackup\.
1\. It locks the database with \-L
2\. Copy it \(with scp\) to an another box
3\. Unlock with \-N

We have running and newly starting transactions while the backup process running\.

Backup log:
2019\-04\-30 23:19:56 /u1/firebird/database\.fdb LOCKED \[ OK \]
2019\-04\-30 23:20:00 /u1/firebird/database\.fdb SCP\[ OK \]
2019\-04\-30 23:20:00 /u1/firebird/database\.fdb UnLOCKED \[ OK \]

Firebird log \(same time as unlock\):
server<\-\-\-\>Tue Apr 30 23:20:00 2019
<\-\-\-\-\-\-\>Database: /u1/firebird/database\.fdb
<\-\-\-\-\-\-\>internal Firebird consistency check \(next transaction older than oldest active transaction \(266\), file: cch\.cpp line: 6523\)

server<\-\-\-\>Tue Apr 30 23:22:01 2019                                     \(2 mins later\!\)
<\-\-\-\-\-\-\>Database: /u1/firebird/database\.fdb
<\-\-\-\-\-\-\>deadlock

We have 3 other databases following with the same error \(internal Firebird consistency check \(next transaction older than oldest active transaction \(266\), file: cch\.cpp line: 6523\)\)\.
But only 2 of 4 have deadlock entry\.

**Comment by omachtandras** [comment]
We cannot reproduce the issue since then, so Vlad, please close it. Thanks!
