### ISSUE TITLE
v2.5.9 Regression: MON$Attachments.MON$Remote_Address now includes the remote TCP port number [CORE6151]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6400]
Submitted by: Attila Molnár (e_pluribus_unum)

Before 2\.5\.9 mon$attachments\.mon$remote\_address returned just IP, e\.g\.: "192\.168\.0\.1"\.
With 2\.5\.9 it returns IP \+ port number, e\.g\.: "192\.168\.0\.1/55970"\.

It made broke some of our code\. \(We are comparing mon$remote\_address to outer source IP without port\)

It this intentional, a side effect or a bug? Changelog doesn't mentions this change\.

**Comment by EPluribusUnum** [comment]
FB4.0 returns IPv6 adress. + port number in MON$REMOTE_ADDRESS. Is there a way to get IPv4 address + port?

**Comment by mrotteveel** [comment]
I believe that depends on whether the connection is established using IPv6 or IPv4.

**Comment by EPluribusUnum** [comment]
@mrotteveel , yep. Using IPv4 in connection string instead of computername reported IPv4. Thank you.

**Comment by EPluribusUnum** [comment]
You can close this issue. Thank you.

**Comment by mrotteveel** [comment]
You can also explicitly enforce IPV4 by using the inet4 connection string: inet4://host:port/database
