### ISSUE TITLE
Windows Server 2016: "Operating system call CryptAcquireContext failed. Error code 127 Firebird 3.0.4.33054 [CORE6154]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#6403]
Submitted by: Jose Zaragoza (pepe_itd_hotmail.com)

Hello There, i have an isssue that i cannot connect with SYSDBA and i check the firebird\.log file and im getting this error:

SERVIDOR	Fri Oct 04 15:14:04 2019
	Operating system call CryptAcquireContext failed\. Error code 127

SERVIDOR	Fri Oct 04 15:14:04 2019
	Authentication, client plugin:
	operating system directive CryptAcquireContext failed
	No se encontró el proceso especificado\. 

Does someone know what is wrong?

Best Regards

Jose Zaragoza

**Comment by trldebrito** [comment]
E quando vc esta no windows 8.1? Como resolve. rsrsrs

**Comment by mrotteveel** [comment]
> E quando vc esta no windows 8.1? Como resolve. rsrsrs

Please post in English, and for support questions, please use https://groups.google.com/g/firebird-support
