### ISSUE TITLE
Cannot use select with collate on blob field created with domain [CORE6249]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6493]
Submitted by: Rudi Feijó (rudi.feijo_multidadosti.com.br)

CREATE DOMAIN DOMAINBLOB AS BLOB SUB\_TYPE 0 SEGMENT SIZE 80;
CREATE TABLE TEST \(    BLOBFIELD       DOMAINBLOB \);

select \* from test where blobfield collate win\_ptbr containing '123';

throws :
Dynamic SQL Error\.
SQL error code = \-204\.
Data type unknown\.
Invalid use of CHARACTER SET or COLLATE\.

**Comment by rudibr78** [comment]
Issue still persists with 3.0.10.
Also with varchar fields I get COLLATION WIN_PTBR for CHARACTER SET NONE is not defined, even if the connection is using WIN1252

**Comment by asfernandes** [comment]
The issue is opened, so it has not changed.

And accordingly to the comments, I think it should be closed as wontfix.
