### ISSUE TITLE
"Nested aggregate functions are not allowed" error on FB30 [CORE6256]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6498]
Submitted by: Attila Molnár (e_pluribus_unum)

Hi\!

This works for FB25 \(Dialect1\), but not for FB30 \(Dialect3\)\.

SELECT
    SUM\(
        kf\.keszlet\_db \+
        \(SELECT
            SUM\(\(
            CASE WHEN rt\.vdb IS NULL THEN rt\.db ELSE rt\.vdb END \- COALESCE\(rt\.ktdb, 0\)\) \*
            \(SELECT kv\.szorzo
            FROM ktfj\_valtoszam\(kf\.ktfj\_id, rt\.mert\_id, kf\.mert\_id\) kv\)\)
        FROM ktrt rt\)\) szabad\_db
FROM ktkf kf

Our workaround : extract the subselect into CTE and then FB30 accepts it\.

WITH
  sub AS
    \(SELECT
        \(CASE WHEN rt\.vdb IS NULL THEN rt\.db ELSE rt\.vdb END \- COALESCE\(rt\.ktdb, 0\)\) \*
        \(SELECT kv\.szorzo
        FROM ktfj\_valtoszam\(kf\.ktfj\_id, rt\.mert\_id, kf\.mert\_id\) kv\) db
    FROM ktrt rt\)
SELECT
    SUM\(
        kf\.keszlet\_db \+
        \(SELECT
            SUM\(db\)
        FROM sub\)\) szabad\_db
FROM ktkf kf

\(I can send the database on request\)

**Comment by EPluribusUnum** [comment]
This is still an issue with FB30 (works as expected in FB40)

**Comment by pavel-zotov** [comment]
Why this issue has been marked as 'fixed' for 4.0.0 ? It does not work on all FB 3.x+.
This is re-formatted SQL:
```
set bail on;
set list on;
shell if exist c:\temp\tmp4test.fdb del /q /f c:\temp\tmp4test.fdb;
create database 'localhost:c:\temp\tmp4test.fdb' user 'sysdba' password 'masterkey';

set term ^;
create or alter procedure ktfj_valtoszam(
    a_ktfj_id int
   ,a_rt_mert_id int
   ,a_kf_mert_id int
) returns (
    szorzo int
)
as begin
    szorzo = a_ktfj_id + a_rt_mert_id + a_kf_mert_id;
    suspend;
end
^
recreate table ktrt(
    vdb int
   ,db int
   ,ktdb int
   ,mert_id int
)
^

recreate table ktkf(
    keszlet_db int
   ,ktfj_id int
   ,mert_id int
)
^
set term ;^
commit;

set echo on;
select
sum (
    kf.keszlet_db +
    (
        select
        sum (
        (
            case when rt.vdb is null then rt.db else rt.vdb end - coalesce(rt.ktdb, 0)
        )
        *
        (
            select kv.szorzo
            from ktfj_valtoszam(kf.ktfj_id, rt.mert_id, kf.mert_id) kv)
        )
        from ktrt rt
    )
) szabad_db
from ktkf kf;
```

On FB 2.5.9.27156 in completes OK and displays ```SZABAD_DB                       <null>```
On FB 4.0.5.3086, 5.0.1.1383, 6.0.0.336 it fails with:
```
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Nested aggregate and window functions are not allowed
```

**Comment by asfernandes** [comment]
I've marked it as fixed because of the comment
> This is still an issue with FB30 (works as expected in FB40)

**Comment by pavel-zotov** [comment]
But i can't understand: what means phrase "works as *expected* in FB40" ? this query is not compiled in all FB >= 3.x

**Comment by EPluribusUnum** [comment]
4.0.0 was not yet release when I was testing on FB40, it was a snapshot/alpha/beta/rc (can't remember exactly).
I meant "works as expected" that FB25 and FB40 was behaving the same.

**Comment by pavel-zotov** [comment]
BTW, this works OK:
```
select
    sum(
            m.i
            *
            (
                select sum(i) s from (select 1 i from rdb$types rows 2)
            )
       )
from (
    select 4 i from rdb$types rows 3
) m;
```
