### ISSUE TITLE
ALTER SEQUENCE RESTART WITH <n> should not change the initial sequence START value [CORE6386]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6625]
Submitted by: @asfernandes

Replaces [CORE5133](https://github.com/FirebirdSQL/firebird/issues?q=CORE5133+in%3Atitle)

Standalone ALTER SEQUENCE RESTART WITH and IDENTITY COLUMN RESTART WITH has different behavior\.

If standalone sequence is created with initial value 10, then later
RESTARTed WITH value 20 and then RESTARTed, it's restarted to 20\.

With identity column RESTART WITH value is not saved and the last
restart goes to 10\.

Accordingly to the standard, the START value is part of the "descriptor", so it's stored in metadata\.

But in ALTER SEQUENCE RESTART WITH, that descriptor is not updated\.

It does only update the sequence's current value\.

We had this behavior but it was changed with [CORE5133](https://github.com/FirebirdSQL/firebird/issues?q=CORE5133+in%3Atitle)\.

Commits: FirebirdSQL/firebird@e94c66bcc66be364f5f1806c34ee8f03056ed9a2 FirebirdSQL/fbt-repository@95fb600f518f803c4aa1c25cbf7847188291db69

====== Test Details ======

See fbt\-repo\\tests\\functional\\generator\\alter\_01\.fbt

**Comment by romansimakov** [comment]
I'm looking in SQL Standard 2016 and here are what I see:
Chapter 9.31 Altering a sequence generator
Page 677
Syntax Rules 9b says:

> b) If <alter sequence generator restart option> is specified and contains a <sequence generator restart
value>, then let NEWVAL be that <sequence generator restart value>.

below this General Rules 2e says:

> e) The current base value is set to NEWVAL.

And it seems reasonable. Am I wrong?

**Comment by mrotteveel** [comment]
@romansimakov The rules you quote are about the current value (base value) of the sequence. The current behaviour complies with the SQL standard. What you're confused about is that the SQL standard describes it from the point of view that the next value to be generated is stored, while Firebird stores the last generated value. So, to be able to conform, we need to adjust.

The SQL standard rules do not say anything about modifying the start value, what this ticket is about (notice the total absence of an equivalent of rule 2c of _9.30 creation of a sequence generator_ (_"The start value, set to START."_)

**Comment by romansimakov** [comment]
I understabd "base value" as "initial value" in terms of Firebird. This means "current value" is not "base value". The rule 9c clearly says

> If <alter sequence generator restart option> is not specified, then let NEWVAL be the current base
value of SEQ.

I proofs my point because otherwise current value will not be changed.

So if restart option *specifies* NEWVAL than according to general rule current base must be set to NEWVAL.

**Comment by mrotteveel** [comment]
The Syntax Rules explain how the different values NEWIV, NEWMAX, NEWMIN, NEWCYCLE and NEWVAL are derived so they can be set in General Rules 2. What rule Syntax Rule 9a is: _"If \<alter sequence generator restart option> is not specified, then let NEWVAL be the current base value of SEQ."_, which - rephrased - means that if the restart option is not specified, then NEWVAL is the current base value, so the effect of applying General Rule 2e is that the current value **doesn't change**.

**Comment by mrotteveel** [comment]
Or in other words, Syntax Rule 9a specifies if you do `ALTER SEQUENCE SEQ INCREMENT BY 5` that the generator retains its current value.

**Comment by mrotteveel** [comment]
Or, to quote from section 4.27 Sequence generators:

> A sequence generator has a time-varying _current base value_, which is a value of its data type. A sequence generator has a cycle which consists of all the possible values between the minimum value and the maximum value which are expressible as (current base value + _N_ * increment), where _N_ is a non-negative number.
>
> When a sequence generator is created, its current base value is initialized to the start value. Subsequently, the current base value is set to the value of the lowest non-issued value in the cycle for an ascending sequence generator, or the highest non-issued value in the cycle for a descending sequence generator.

**Comment by mrotteveel** [comment]
and

> Any time after a sequence generator is created, its current base value can be set to an arbitrary value of its data type by an \<alter sequence generator statement>.

**Comment by romansimakov** [comment]
It seems you are right. 4.27 makes clear different between "current base value" and "start value". It looks SQL Standard does not provide a way to change start value other than recreation. Users ask for it. I suppose it's a good feature to have.
