### ISSUE TITLE
Support for WHEN NOT MATCHED BY SOURCE for MERGE statement [CORE6448]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6681]
Submitted by: Leonardt (lxo)

It would be very useful to have the option "WHEN NOT MATCHED BY <SOURCE\>/<TARGET\>" for "MERGE statements"\.
Like for example in MSSQL\.

Use case and example of how to use this in Firebird now without "WHEN NOT MATCHED BY <SOURCE\>/<TARGET":
<https://www.sql.ru/forum/1323218/merge-when-not-matched-by-source>

I currently need this for mass copying\.
When copying, I would like to take everything from the source, update matches, add new records and delete data not contained in the source from the target\.

Without the merge statement I would first have to delete everything from the target and then insert it\.
Or "Update or Insert "and then do a delete with "where not exists"\.

I see this new feature as very useful for such purposes\. Therefore I don't understand why the request in a ticket was rejected years ago \([CORE2515](https://github.com/FirebirdSQL/firebird/issues?q=CORE2515+in%3Atitle)\)

**Comment by nLeonardt95** [comment]
Hello, 

is this being considered for implementation in Firebird 4?

**Comment by hvlad** [comment]
It is too late to consider new features for Firebird 4, sorry.

**Comment by asfernandes** [comment]
> Hello,
> 
> is this being considered for implementation in Firebird 4?

Could you please test it in next Firebird 5 snapshot?

**Comment by nLeonardt95** [comment]
First tests look good so far. Seems to work.
