### ISSUE TITLE
Trace: provide ability to see STATEMENT RESTART events (or their count) [CORE6500]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6730]
Submitted by: @pavel-zotov

Ticket was created after discussion with Vlad\.

When engine can not fetch any record for lock it starts undo, restores Tx level to RC READ CONSISTENCY and makes restart of top\-level statement\.
It will be useful to see this event in the trace log: either like "<timestamp\> \(<trace\_uid\>\) EXECUTE\_STATEMENT\_RESTART"  or in statistics table\.

**Comment by pavel-zotov** [comment]
@@@ QA issue @@@
See test functional/transactions/test_read_consist_statement_delete_undone_01.py
(it was re-implemented to check presence in the launched trace log lines about restart statement and number of times when this occurred).
