### ISSUE TITLE
Wrong message when connecting to tiny trash database file [CORE6518]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#6747]
Submitted by: @AlexPeshkoff

Is related to [CORE2484](https://github.com/FirebirdSQL/firebird/issues?q=CORE2484+in%3Atitle)

When connecting to tiny DB file which is missing some pages in the end firebird produces various diags \(depending upon what garbage it'a using instead missing page\), for example:
Missing crypt plugin, but page appears encrypted

Commits: FirebirdSQL/firebird@f18063a6e7fa3866c18b4bc8ced67878281c7f5e FirebirdSQL/firebird@3dadc082847eec891a010827ff124f8df648ac06

====== Test Details ======

Sent letter to Alex et al, 06\.04\.2021 09:32\.
Test implemented but not yet committed to fbt\-repo\.
To be discussed further, after FB 4\.x release\.

**Comment by pavel-zotov** [comment]
::: QA note :::
Covered by tests for #2897 and  #8450
