### ISSUE TITLE
Add support for Package Body Constants (or even Variables) [CORE6538]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6765]
Submitted by: Anderson Farias (afarias)

Votes: 1

It would be nice to declare CONSTANTS in package body \(or even variables\) that could be used by all functions/procedues with in it\. Eg\.

RECREATE PACKAGE BODY MY\_PACKAGE
AS
  DECLARE MY\_CONSTANT VARCHAR\(10\) = 'SOME VALUE';
BEGIN

  FUNCTION MY\_FUNCTION\_A RETURNS VARCHAR\(10\)
  AS
  BEGIN
      RETURN  MY\_CONSTANT;
  END

  FUNCTION MY\_FUNCTION\_B RETURNS VARCHAR\(50\)
  AS
      DECLARE MY\_LOCAL\_VAR VARCHAR\(20\);
  BEGIN
      MY\_LOCAL\_VAR = 'OTHER VALUE';
      RETURN  MY\_CONSTANT \|\| MY\_LOCAL\_VAR;
  END

\(\.\.\.\)

**Comment by asfernandes** [comment]
Duplicates https://github.com/FirebirdSQL/firebird/issues/3411
