### ISSUE TITLE
firebird 2.5.8 install.sh doesnt create startup itens in ubuntu and dont start server [DOC137]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird#6779]
Submitted by: erick de oliveira leal (erickdeoliveiraleal)

im trying to install firebird 2\.5\.8 in ubuntu 18\.04 with no luck
manual says in number 6

    SuperServer only installs a /etc/rc.d/init.d/firebird server start script.

    Classic server installs a /etc/xinetd.d/firebird start script or, for older inetd systems, adds an entry to the /etc/inetd file

but it is not happening after I run install.sh, it only create opt/firebird files, also not starting service after install\.

<https://www.firebirdsql.org/file/documentation/release_notes/html/install210.html#rnfbtwo-install-psx>

**Comment by AlexPeshkoff** [comment]
FB 2.5 was born when initd was used instead systemd in all linux distro. That's why install does not work on systems with systemd like yours. 2.5 is not supported any more, please register it manually (utility systemctl will help) or use FB3.
