### ISSUE TITLE
Getting "records fetched" for functions/procedures in trace

### ISSUE THREAD

**Issue by cincuranet** [FirebirdSQL/firebird#6782]
I'm looking at this https://github.com/FirebirdSQL/firebird/blob/B3_0_Release/src/utilities/ntrace/TracePluginImpl.cpp#L1410 line and wondering how I can get that in trace's output, aka what to do in function's/procedure's code to get something in `pin_records_fetched`. For normal DSQL statements it works as expected.

**Comment by hvlad** [comment]
Affected tracing of selectable procedures only. Tracing of function and executable procedures is not affected.

**Comment by cincuranet** [comment]
Not sure I follow. Is function ever going to print the _records fetched_, i.e. [this](https://github.com/FirebirdSQL/firebird/blob/B3_0_Release/src/utilities/ntrace/TracePluginImpl.cpp#L1477)?

**Comment by hvlad** [comment]
First, it was you who mention functions :) 
Second, due to a bug all pieces of stats was missing at trace output, not only the number of records fetched.
