### ISSUE TITLE
Need ICU version to fix FirebirdSQL at Nixpkgs/NixOS

### ISSUE THREAD

**Issue by superherointj** [FirebirdSQL/firebird#6784]
Hello!

FirebirdSQL is [broken in NixOS](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/firebird/default.nix#L88) for quite some time. Which makes me sad to see. I've tried to get it running but I had a really hard time pinpointing exact ICU version to be used in each version.

I want to know the exact ICU versions for each Firebird release version:

Current Versions
https://github.com/FirebirdSQL/firebird/releases/tag/T4_0_0_RC1 # 01-Feb-2021
https://github.com/FirebirdSQL/firebird/releases/tag/R3_0_7 # 3.0.7    20-Oct-2020
https://github.com/FirebirdSQL/firebird/releases/tag/R2_5_9 # 2.5.9    24-Jun-2019

Legacy Versions
https://github.com/FirebirdSQL/firebird/releases/tag/R2_1_7   # 2.1.7    05-Dec-2014
https://github.com/FirebirdSQL/firebird/releases/tag/R2_0_7

Thanks.

**Comment by asfernandes** [comment]
For v4 ICU 63.1 is tested and distributed in Windows. More up to date versions should be ok too.

For v3 and v2.5, probably any version.

**Comment by superherointj** [comment]
I am using Linux NixOS.
Latest version did not work.
And 'any version' does not work for v3, v2.5.
You are closing the issue without any helpful answer.
Never mind.

**Comment by asfernandes** [comment]
We have the devel list to discuss things. Have you search there? We have already talked about ICU versions there.

You saying that a thing does not work pointing a link to a `broken = true;` line does not help I help you.

**Comment by AlexPeshkoff** [comment]
If you want to get useful answer please ask useful question. 
https://wwwusers.ts.infn.it/~mocchiut/bugs/bugs.html

**Comment by superherointj** [comment]
> We have the devel list to discuss things. Have you search there? We have already talked about ICU versions there.
I did search a lot on the internet, google groups, tried IRC [ask there]. But no luck [up to that point].
Thanks for pointing out the 'devel list'.
 
> You saying that a thing does not work pointing a link to a `broken = true;` line does not help I help you.
I only asked for the specific ICU version on each release. I was merely pointing out the reasoning on why I was asking this. 

Thanks anyway.

**Comment by AlexPeshkoff** [comment]
Since FB3 there is no need in SPECIFIC ICU version - any not too old (say >= 5.0) for FB3 must work. If it does not - than may be something goes wrong with ICU or FB build.

**Comment by superherointj** [comment]
I am trying to build from sources for Linux NixOS. Is this still the case?

**Comment by asfernandes** [comment]
Since FB 3, we do not have ICU in the FB sources. It should be built and installed before build/install Firebird.

**Comment by hvlad** [comment]
Firebird 2.x uses own build of ICU 3.0 (could use OS\system build also).
Firebird 3.0 is build and tested with ICU 52.
Firebird 4.0 is build and tested with ICU 63.
All Firebird versions should work with system-supplied ICU of corresponding versions or higher (not mention own MS builds at modern Win10).

@superherointj: until you show the real problem we can't help.

**Comment by aafemt** [comment]
Crazy CentOS developers made their ICU incompatible with any other on purpose. It is not our problem.

**Comment by AlexPeshkoff** [comment]
@aafemt Just curious - how? Non-standard entries like SUSE? Or invited something else?

**Comment by aafemt** [comment]
Oh, I mixed it up with SUSE indeed. I'm sorry.

**Comment by superherointj** [comment]
Using ICU63 with Firebird tag T4_0_0_RC1 the build went through until new error:
```
/build/source/gen/Release/firebird/bin/isql -q -i /build/source/src/dbs/metadata.sql
Error loading plugin Engine13
-Module /build/source/gen/Release/firebird/plugins/libEngine13.so exists but can not be loaded
-/build/source/gen/Release/firebird/plugins/libEngine13.so: undefined symbol: ltm_desc
```
For full log: https://termbin.com/bbkv 

Any idea?

**Comment by aafemt** [comment]
The error has nothing to do with ICU and caused by missing libtommatch library.

**Comment by superherointj** [comment]
libtommatch is present.

**Comment by superherointj** [comment]
Previous error was ICU related. By adding the proper ICU it worked until new error. Will search this library. But libtommath and libtomcrypt is present already.

**Comment by aafemt** [comment]
Error message clearly states otherwise. Most likely libtommatch version 1.X is present while Firebird is linked against 0.X.

**Comment by hvlad** [comment]
ltm_desc is libtomcrypt's symbol, not libtommath
I hope @AlexPeshkoff could make it clear.

**Comment by superherointj** [comment]
Tried building `libtomcrypt` with flags:

1) `CFLAGS="-DUSE_LTM -DLTM_DESC"` 

2) CPPFLAGS+=" -DLTM_DESC -DGMP_DESC -DUSE_LTM" EXTRALIBS="-ltommath -lgmp"

But got same error when building `firebird` package:

Error loading plugin Engine13
-Module /build/source/gen/Release/firebird/plugins/libEngine13.so exists but can not be loaded
-/build/source/gen/Release/firebird/plugins/libEngine13.so: **_undefined symbol: ltm_desc_**

Any idea on how to get around this `"undefined symbol: ltm_desc"` error?

**Comment by AlexPeshkoff** [comment]
On 4/28/21 9:36 PM, superherointj wrote:
>
> Tried building |libtomcrypt| with flags:
>
> 1.
>
>     |CFLAGS="-DUSE_LTM -DLTM_DESC"|
>

That should be enough - from ltm_desc POV. Also do not forget 
-DLTC_PTHREAD -pthread - or firebird can segfault randomly when using 
tomcrypt.

> 1.
>
>
> 2.
>
>     CPPFLAGS+=" -DLTM_DESC -DGMP_DESC -DUSE_LTM" EXTRALIBS="-ltommath
>     -lgmp"
>

Firebird is not using GMP support in tomcrypt.

> 1.
>
> But got same error when building |firebird| package:
>
> Error loading plugin Engine13
> -Module /build/source/gen/Release/firebird/plugins/libEngine13.so 
> exists but can not be loaded
> -/build/source/gen/Release/firebird/plugins/libEngine13.so: 
> */undefined symbol: ltm_desc/*
>
> Any idea on how to get around this |"undefined symbol: ltm_desc"| error?
>

Start with using switch
--with-builtin-tomcrypt
in firebird's configure and see does it help.

**Comment by superherointj** [comment]
I was able to build `tomcrypt` with flags properly. Firebird 4 build no longer stops at `tomcrypt` but goes back to complaining about ICU, but with different error: 
`Could not find acceptable ICU library`
I am providing `icu63`. So it finds ICU, just doesn't like it?

Full logs: https://termbin.com/5idg

**Comment by asfernandes** [comment]
Please run `ls -l` showing `lib*icu*` files.

**Comment by AlexPeshkoff** [comment]
On 4/29/21 5:39 PM, Adriano dos Santos Fernandes wrote:
>
> Please run |ls -l| showing |lib*icu*| files.
>

Also please
nm -C -D libicuuc.so | grep ucnv_open

**Comment by superherointj** [comment]
> Please run `ls -l` showing `lib*icu*` files.

```
$ ls -l
total 33M
lrwxrwxrwx 1 root root   18 dez 31  1969 libicudata.so -> libicudata.so.63.1
lrwxrwxrwx 1 root root   18 dez 31  1969 libicudata.so.63 -> libicudata.so.63.1
-r-xr-xr-x 1 root root  26M dez 31  1969 libicudata.so.63.1
lrwxrwxrwx 1 root root   18 dez 31  1969 libicui18n.so -> libicui18n.so.63.1
lrwxrwxrwx 1 root root   18 dez 31  1969 libicui18n.so.63 -> libicui18n.so.63.1
-r-xr-xr-x 1 root root 3,9M dez 31  1969 libicui18n.so.63.1
lrwxrwxrwx 1 root root   16 dez 31  1969 libicuio.so -> libicuio.so.63.1
lrwxrwxrwx 1 root root   16 dez 31  1969 libicuio.so.63 -> libicuio.so.63.1
-r-xr-xr-x 1 root root  76K dez 31  1969 libicuio.so.63.1
lrwxrwxrwx 1 root root   18 dez 31  1969 libicutest.so -> libicutest.so.63.1
lrwxrwxrwx 1 root root   18 dez 31  1969 libicutest.so.63 -> libicutest.so.63.1
-r-xr-xr-x 1 root root 100K dez 31  1969 libicutest.so.63.1
lrwxrwxrwx 1 root root   16 dez 31  1969 libicutu.so -> libicutu.so.63.1
lrwxrwxrwx 1 root root   16 dez 31  1969 libicutu.so.63 -> libicutu.so.63.1
-r-xr-xr-x 1 root root 246K dez 31  1969 libicutu.so.63.1
lrwxrwxrwx 1 root root   16 dez 31  1969 libicuuc.so -> libicuuc.so.63.1
lrwxrwxrwx 1 root root   16 dez 31  1969 libicuuc.so.63 -> libicuuc.so.63.1
-r-xr-xr-x 1 root root 2,2M dez 31  1969 libicuuc.so.63.1
```

>  Please run |ls -l| showing |lib*icu*| files.
```
$ nm -C -D libicuuc.so | grep ucnv_open
0000000000078990 T ucnv_open_63
000000000007f140 T ucnv_openAllNames_63
0000000000078a80 T ucnv_openCCSID_63
00000000000789c0 T ucnv_openPackage_63
000000000007e380 T ucnv_openStandardNames_63
00000000000789d0 T ucnv_openU_63
```

If remove icu63 dependency from path, it errors as:
> checking for unicode/ucnv.h... no
> configure: error: ICU support not found - please install development ICU package

If I add icu63 dependency to path, it errors as:
> Could not find acceptable ICU library

**Comment by AlexPeshkoff** [comment]
Please try wirh this patch (it's from current head, will get into 
release fb4).

**Comment by AlexPeshkoff** [comment]
On 4/30/21 10:55 AM, Alex Peshkoff wrote:
> Please try wirh this patch (it's from current head, will get into 
> release fb4).
>
>

Hops - github strips even tiny attachments, what a shame. Please get it 
here: http://web.firebirdsql.org/download/rabbits/alex/A.patch

A.

**Comment by superherointj** [comment]
Thanks for patch.

I just tried building [master](https://github.com/FirebirdSQL/firebird/commit/04ed073932a81b7d4b5a8fee379636bf318f6005). But I get same error.
> Could not find acceptable ICU library

**Comment by asfernandes** [comment]
Do you have some more information in firebird.log file in the source/build tree?

**Comment by AlexPeshkoff** [comment]
> I just tried building master 
> <https://github.com/FirebirdSQL/firebird/commit/04ed073932a81b7d4b5a8fee379636bf318f6005>. 
> But I get same error.
>
>     Could not find acceptable ICU library
>

Just to make sure - where are ICU libraries installed? Is that place in 
system so search path?

**Comment by superherointj** [comment]
I understand you want: (1) 'firebird.log' file. (2) make sure ICU library is in path.

NixOS works differently than most Linux distributions so I'm struggling to do both of these things the usual way on the Nix side.
 still trying to learn how to properly observe the package being built. I don't know at which folder it is being built and how to interact/observe it. Tried nix-shell/nix-develop but I still didn't make much progress.

By now, I guess this is beyond my current capabilities and likely would be wise to let go of trying this. I'm missing some fundamental knowledge (which is not obvious to me). It could be on either side (firebird or nix).

I appreciate all the effort you have made in helping me. And I'm sorry if this issue showed a bit of heat. I really appreciate you came forward despite this. Whenever I am more experienced I may try again. I hope you can understand.

Thank you.

**Comment by asfernandes** [comment]
I have never heard about NixOS.

You should check how programs using `dlopen` is handled in it.

Firebird loads ICU with `dlopen`.

**Comment by superherointj** [comment]
> I have never heard about NixOS.

It's quite nice. One day give it a try, I believe you won't regret, I don't consider going back to Arch any soon.
My struggle here is mostly my incompetence as a systems admin/programmer.

> You should check how programs using `dlopen` is handled in it.
> Firebird loads ICU with `dlopen`.

With this tip from you:
@jneto (J.Neto), from "NixOS Brasil" Telegram channel, figured out what was wrong. 
'icu' library should have been at LD_LIBRARY_PATH as well.
Which in Nix would be done this way:
`LD_LIBRARY_PATH = lib.makeLibraryPath [ icu ];`

``
He reported to be able to successfully build Firebird 3.0.7 doing so. [Which is nice because now we can upstream this. So others won't struggle on getting Firebird running.]

My attempt to build Firebird 4 master, now errors at a different place:

```
       > /build/source/src/qli/../qli/dtr.h: In function 'qli_syntax* PARQ_parse()':
       > /build/source/src/qli/../qli/dtr.h:271:8: note: at offset 8192 to object 'qli_symbol::sym_name' with size 2 declared here
       >   271 |  TEXT  sym_name[2]; // space for name, if necessary
       >       |        ^~~~~~~~
       > make[3]: Leaving directory '/build/source/gen'
       > make[2]: *** [Makefile:287: master_process] Error 2
       > make[2]: Leaving directory '/build/source/gen'
       > make[1]: *** [Makefile:86: firebird] Error 2
       > make[1]: Leaving directory '/build/source/gen'
       > make: *** [Makefile:6: firebird] Error 2
```
Full log: https://termbin.com/4x9g

**Comment by AlexPeshkoff** [comment]
On 5/2/21 8:13 PM, superherointj wrote:

> My attempt to build Firebird 4 master, now errors at a different place:
>
> |> /build/source/src/qli/../qli/dtr.h: In function 'qli_syntax* 
> PARQ_parse()': > /build/source/src/qli/../qli/dtr.h:271:8: note: at 
> offset 8192 to object 'qli_symbol::sym_name' with size 2 declared here 
> > 271 | TEXT sym_name[2]; // space for name, if necessary > | ^~~~~~~~ 
> > make[3]: Leaving directory '/build/source/gen' > make[2]: *** 
> [Makefile:287: master_process] Error 2 > make[2]: Leaving directory 
> '/build/source/gen' > make[1]: *** [Makefile:86: firebird] Error 2 > 
> make[1]: Leaving directory '/build/source/gen' > make: *** 
> [Makefile:6: firebird] Error 2 |
>
> Full log: https://termbin.com/4x9g <https://termbin.com/4x9g>
>

May be due to:

unzip -o /build/source/extern/icu/tzdata/le.zip -d 
/build/source/gen/Release/firebird/tzdata
/nix/store/68c5b0h2w2ab57sbas1b4m073ik8hlm5-bash-4.4-p23/bin/bash: 
unzip: command not found

This is not used in fb3.

**Comment by superherointj** [comment]
Hello Alex.

That message was old. I have already added unzip. (and other things)
I am able to build Firebird 2.5, 3, 4 for x64_64. And Firebird 4 for aarch64.

Now I only need to build Firebird 2.5 / 3 at aarch64 to cover all the platforms.
Is there some instruction on how to do this? Does it need some special flag?

**Comment by AlexPeshkoff** [comment]
On 5/3/21 9:07 PM, superherointj wrote:
>
> Hello Alex.
>
> That message was old. I have already added unzip. (and other things)
> I am able to build Firebird 2.5, 3, 4 for x64_64. And Firebird 4 for 
> aarch64.
>

Nice  :)

> Now I only need to build Firebird 2.5 / 3 at aarch64 to cover all the 
> platforms.
> Is there some instruction on how to do this? Does it need some special 
> flag?
>

I do not expect problems building FB3 on aarch64. What about 2.5... We 
already do not support that version, I see no reasons making ports.

**Comment by superherointj** [comment]
> I do not expect problems building FB3 on aarch64. What about 2.5... We already do not support that version, I see no reasons making ports.

I have disabled FB 2.5 and 3 for aarch64 [in Nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/121546).

Firebird 3.0.7 at aarch64, errors as:
```
error: builder for '/nix/store/vkwvb7m9vldnx0cm7banhxhxyqqwv1zj-firebird-3.0.7.drv' failed with exit code 2;
       last 10 log lines:
       > make[3]: Entering directory '/build/source/gen'
       > rm -f metadata.fdb
       > /build/source/gen/Release/firebird/bin/isql -q -i /build/source/src/dbs/metadata.sql
       > make[3]: *** [Makefile:362: metadata.fdb] Segmentation fault (core dumped)
       > make[3]: Leaving directory '/build/source/gen'
       > make[2]: *** [Makefile:192: master_process] Error 2
       > make[2]: Leaving directory '/build/source/gen'
       > make[1]: *** [Makefile:66: firebird] Error 2
       > make[1]: Leaving directory '/build/source/gen'
       > make: *** [Makefile:6: firebird] Error 2
```
Full log: https://termbin.com/g6dit

Anything rings a bell?

**Comment by AlexPeshkoff** [comment]
On 5/4/21 3:04 AM, superherointj wrote:
>
>     I do not expect problems building FB3 on aarch64. What about
>     2.5... We already do not support that version, I see no reasons
>     making ports.
>
> I have disabled FB 2.5 and 3 for aarch64 in Nixpkgs PR 
> <https://github.com/NixOS/nixpkgs/pull/121546>.
>
> Firebird 3.0.7 at aarch64, errors as:
>
> |error: builder for 
> '/nix/store/vkwvb7m9vldnx0cm7banhxhxyqqwv1zj-firebird-3.0.7.drv' 
> failed with exit code 2; last 10 log lines: > make[3]: Entering 
> directory '/build/source/gen' > rm -f metadata.fdb > 
> /build/source/gen/Release/firebird/bin/isql -q -i 
> /build/source/src/dbs/metadata.sql > make[3]: *** [Makefile:362: 
> metadata.fdb] Segmentation fault (core dumped) > make[3]: Leaving 
> directory '/build/source/gen' > make[2]: *** [Makefile:192: 
> master_process] Error 2 > make[2]: Leaving directory 
> '/build/source/gen' > make[1]: *** [Makefile:66: firebird] Error 2 > 
> make[1]: Leaving directory '/build/source/gen' > make: *** 
> [Makefile:6: firebird] Error 2 |
>
> Full log: https://termbin.com/g6dit <https://termbin.com/g6dit>
>
> Anything rings a bell?
>

First of all I see a warning

dynamic exception specifications are deprecated in C++11

FB3 should not be built in c+11 mode, it's c++03 (CXXFLAGS=-std=gnu++03)
