### ISSUE TITLE
problem when restoring the database firebird 4 rc1 4.0.0.2353

### ISSUE THREAD

**Issue by sszaytsev83** [FirebirdSQL/firebird#6785]
Hello.
 There was a problem with firebird 4 rc14.0.0.2353. When restoring metadata in several databases, the process hangs:
 gbak: activating and creating deferred index FK_SQL_CLASS_LINK_1
 gbak: adjusting views dbkey length
 gbak: updating ownership of packages, procedures and tables 

 in this state, it hangs for several days until you forcefully kill the process. I tried snaphot Firebird-4.0.0.2447-ReleaseCandidate1.amd64.tar.gz, but it didn't solve the problem. Tell me what can be done in this case?

**Comment by romansimakov** [comment]
Show the stacktrace of the hang process. If you use Linux it's:
gdb fbserver <pid>
thread apply all bt

and show the output

**Comment by hvlad** [comment]
Could you provide reproducible test case ? It could be backup with metadada only.

**Comment by andrewkip** [comment]
Hello! 
This one is the problem backup from 2.5 to 4.0

[fb25tofb40propblem.zip](https://github.com/FirebirdSQL/firebird/files/6415050/fb25tofb40propblem.zip)

**Comment by andrewkip** [comment]
and stactrace 
Thread 8 (Thread 0x7f997930f700 (LWP 78742)):
#0  0x00007f99825f1e12 in do_futex_wait () from /lib64/libpthread.so.0
#1  0x00007f99825f1f23 in __new_sem_wait_slow () from /lib64/libpthread.so.0
#2  0x00007f998080f520 in ?? () from /opt/firebird/plugins/libEngine13.so
#3  0x00007f99805368f4 in ?? () from /opt/firebird/plugins/libEngine13.so
#4  0x00007f9980537df3 in ?? () from /opt/firebird/plugins/libEngine13.so
#5  0x00007f99807ba230 in ?? () from /opt/firebird/plugins/libEngine13.so
#6  0x00007f99825e916a in start_thread () from /lib64/libpthread.so.0
#7  0x00007f998231af83 in clone () from /lib64/libc.so.6

Thread 7 (Thread 0x7f997a807700 (LWP 78741)):
#0  0x00007f99825f1e12 in do_futex_wait () from /lib64/libpthread.so.0
#1  0x00007f99825f1f23 in __new_sem_wait_slow () from /lib64/libpthread.so.0
#2  0x00007f998080f520 in ?? () from /opt/firebird/plugins/libEngine13.so
#3  0x00007f99804058c1 in ?? () from /opt/firebird/plugins/libEngine13.so
#4  0x00007f9980406103 in ?? () from /opt/firebird/plugins/libEngine13.so
#5  0x00007f99807ba230 in ?? () from /opt/firebird/plugins/libEngine13.so
#6  0x00007f99825e916a in start_thread () from /lib64/libpthread.so.0
#7  0x00007f998231af83 in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7f997a006700 (LWP 78740)):
#0  0x00007f9982a2595b in fesetenv () from /lib64/libm.so.6
#1  0x00007f99834bfdc9 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#2  0x00007f99834a92ac in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#3  0x00007f99834c33a6 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#4  0x00007f99807fd622 in ?? () from /opt/firebird/plugins/libEngine13.so
#5  0x00007f998075ed3d in ?? () from /opt/firebird/plugins/libEngine13.so
#6  0x00007f998076abe6 in ?? () from /opt/firebird/plugins/libEngine13.so
#7  0x00007f998076b78a in ?? () from /opt/firebird/plugins/libEngine13.so
#8  0x00007f998077c0c5 in ?? () from /opt/firebird/plugins/libEngine13.so
#9  0x00007f998074b50d in ?? () from /opt/firebird/plugins/libEngine13.so
#10 0x00007f998074e478 in ?? () from /opt/firebird/plugins/libEngine13.so
#11 0x00007f99804f82c7 in ?? () from /opt/firebird/plugins/libEngine13.so
#12 0x00007f99807ba230 in ?? () from /opt/firebird/plugins/libEngine13.so
#13 0x00007f99825e916a in start_thread () from /lib64/libpthread.so.0
#14 0x00007f998231af83 in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f997b108700 (LWP 78735)):
#0  0x00007f99825ef31c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f99807da833 in ?? () from /opt/firebird/plugins/libEngine13.so
#2  0x00007f998036350f in ?? () from /opt/firebird/plugins/libEngine13.so
#3  0x00007f998035c5b3 in ?? () from /opt/firebird/plugins/libEngine13.so
#4  0x00007f99807ba230 in ?? () from /opt/firebird/plugins/libEngine13.so
#5  0x00007f99825e916a in start_thread () from /lib64/libpthread.so.0
#6  0x00007f998231af83 in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f99778d0700 (LWP 78733)):
#0  0x00007f99825f1e12 in do_futex_wait () from /lib64/libpthread.so.0
#1  0x00007f99825f1f23 in __new_sem_wait_slow () from /lib64/libpthread.so.0
#2  0x00007f998080f520 in ?? () from /opt/firebird/plugins/libEngine13.so
#3  0x00007f99804f58ef in ?? () from /opt/firebird/plugins/libEngine13.so
#4  0x00007f99804fb4f7 in ?? () from /opt/firebird/plugins/libEngine13.so
#5  0x00007f998047b781 in ?? () from /opt/firebird/plugins/libEngine13.so
#6  0x00007f998049e085 in ?? () from /opt/firebird/plugins/libEngine13.so
#7  0x00007f99834a7911 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#8  0x00007f99834c5e85 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#9  0x000000000043f41a in ?? ()
#10 0x00000000004467a9 in ?? ()
#11 0x0000000000448dfb in ?? ()
#12 0x0000000000466e80 in ?? ()
#13 0x00007f99825e916a in start_thread () from /lib64/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x00007f998231af83 in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f99815ff700 (LWP 78700)):
#0  0x00007f99825f1e12 in do_futex_wait () from /lib64/libpthread.so.0
#1  0x00007f99825f1f23 in __new_sem_wait_slow () from /lib64/libpthread.so.0
#2  0x00007f9983586660 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#3  0x00007f99834646c9 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#4  0x00007f9983538440 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#5  0x00007f99825e916a in start_thread () from /lib64/libpthread.so.0
#6  0x00007f998231af83 in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f9981e00700 (LWP 78699)):
#0  0x00007f99825f1bf6 in do_futex_wait.constprop () from /lib64/libpthread.so.0
#1  0x00007f99825f1ce8 in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007f9983586582 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#3  0x00007f99834b4be5 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#4  0x00007f9983538440 in ?? () from /opt/firebird/bin/../lib/libfbclient.so.2
#5  0x00007f99825e916a in start_thread () from /lib64/libpthread.so.0
#6  0x00007f998231af83 in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f9983b46780 (LWP 78698)):
#0  0x00007f998230fd01 in poll () from /lib64/libc.so.6
#1  0x000000000040db52 in ?? ()
#2  0x00000000004398fb in ?? ()
#3  0x0000000000407cc8 in ?? ()
#4  0x00007f9982241803 in __libc_start_main () from /lib64/libc.so.6
#5  0x0000000000408fef in ?? ()
