### ISSUE TITLE
Problems in fields with the name LOCAL

### ISSUE THREAD

**Issue by JardelLemos** [FirebirdSQL/firebird#6792]
When migrating my database to version 4, all fields with the name LOCAL do not allow relation to other tables.

**Comment by dyemanov** [comment]
This is not a bug, LOCAL is a new reserved keyword and this is documented in the Chapter 5 of the release notes. You need to either rename such fields or enclose their name into double quotes, i.e. type "LOCAL" instead of LOCAL.

**Comment by JardelLemos** [comment]
in that case how would the selection be?
SELECT AP.local FROM SM_MV_EF_CTB_CO_DET_AP AP

**Comment by dyemanov** [comment]
`SELECT AP."LOCAL" FROM SM_MV_EF_CTB_CO_DET_AP AP`

**Comment by JardelLemos** [comment]
Thanks for your attention!
