### ISSUE TITLE
Replication gets stuck due to "Blob xxx.xx is not found for table xxx" error

### ISSUE THREAD

**Issue by albertas-akistechnologies** [FirebirdSQL/firebird#6795]
Hello,
replication stops working after empty blob is inserted/updated. New journal files are produced, but consumption stops. This issue is present in Firebird-4.0.0.2353-0-RC1 and master.

Empty blobs are stored in replication journal like this (from _src/jrd/replication/Replicator.cpp_):
```
txnData.putTag(opStoreBlob);
txnData.putInt32(blobId.gds_quad_high);
txnData.putInt32(blobId.gds_quad_low);
txnData.putInt16(0); // end-of-blob marker
```
And deserialization is done like this (from _src/jrd/replication/Applier.cpp_):
```
case opStoreBlob:
	{
		bid blob_id;
		blob_id.bid_quad.bid_quad_high = reader.getInt32();
		blob_id.bid_quad.bid_quad_low = reader.getInt32();
		do {
			const ULONG length = reader.getInt16();
			if (!length)
				break;
			const auto blob = reader.getBinary(length);
			storeBlob(tdbb, traNum, &blob_id, length, blob);
		} while (!reader.isEof());
	}
	break;
```
_storeBlob_ function is not called for empty blobs, and no blob is created. This causes the "Blob xxx.xx is not found for table xxx" error. This can be fixed by explicitly calling _storeBlob_ for empty blobs:
```
case opStoreBlob:
	{
		bid blob_id;
		blob_id.bid_quad.bid_quad_high = reader.getInt32();
		blob_id.bid_quad.bid_quad_low = reader.getInt32();
		bool blobStored = false;
		do {
			const ULONG length = reader.getInt16();
			if (!length)
				break;
			const auto blob = reader.getBinary(length);
			storeBlob(tdbb, traNum, &blob_id, length, blob);
			blobStored = true;
		} while (!reader.isEof());
		if (!blobStored) {
			storeBlob(tdbb, traNum, &blob_id, 0, nullptr);
		}
	}
	break;
```

**Comment by pavel-zotov** [comment]
::: test details :::
Test name: functional.replication.updating-blob-with-empty-string-stops-replication
(decided to put all replication-related tests in to separate subdir.)
