### ISSUE TITLE
Functions DECRYPT and RSA_DECRYPT return VARCHAR CHARACTER SET NONE instead of VARBINARY (VARCHAR CHARACTER SET OCTETS)

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/firebird#6797]
According to the Firebird 4.0 Release Notes, the return type of `DECRYPT` is (emphasis mine):

> Functions return BLOB when the first argument is blob and **varbinary for all text types.**

However, the actual return type is `VARCHAR CHARACTER SET NONE`. This needs to be changed to `VARBINARY` (`VARCHAR CHARACTER SET OCTETS`). The same applies to `RSA_DECRYPT`: it should return `VARBINARY` as well.

Note that the counterparts `ENCRYPT` and `RSA_ENCRYPT` correctly return `VARBINARY` for non-blob inputs.

**Comment by mrotteveel** [comment]
Assuming the decrypted content is binary and requiring an explicit cast makes more sense to me.

**Comment by AlexPeshkoff** [comment]
On 5/11/21 12:30 PM, Dimitry Sibiryakov wrote:
> 11.05.2021 11:17, Alexander Peshkov wrote:
> > The reasoning is clear - |ENCRYPT really returns binary data, what
> > returns decrypt we just do not know (up to ascii), that's why 
> charset none.
>
> IIRC charset NONE defines one invalid character - <NUL>. That's why it 
> is a wrong
> assumption for decrypt function: it will fail to decrypt binary data.
>

With following table:

SQL> show table var;
BI                              VARCHAR(10) Nullable Character set None
NAR                             VARBINARY(10) Nullable Character set Octets

SQL> insert into var(nar) values(ASCII_CHAR(65) || ASCII_CHAR(66) || 
ASCII_CHAR(0) || ASCII_CHAR(67));
SQL> update var set bi = nar;
SQL> select bi, nar from var;

BI         NAR
========== ====================
AB 41420043

It seems that <NUL> is really something bad for Octets, but that's just 
ISQL printing problem:

SQL> select cast(bi as varbinary(10)), nar from var;

CAST                 NAR
==================== ====================
41420043             41420043

And to make sure:
SQL> select cast(decrypt(encrypt(nar using rc4 key 'qqqqqq') using rc4 
key 'qqqqqq') as varbinary(10)) from var;

CAST
====================
41420043

**Comment by AlexPeshkoff** [comment]
accidentially given wrong number in commit

**Comment by mrotteveel** [comment]
> It seems that <NUL> is really something bad for Octets, but that's just ISQL printing problem:

Don't you mean "NONE" instead?

**Comment by asfernandes** [comment]
The only practical difference between NONE and OCTETS is that with OCTETS the padding is done with \0 and NONE with space. And also how client (ISQL for example) interprets and display it.

They both have different conversion routines, but they should not be called.

In this specific case, if the ENCRYPT routines are more commonly called with strings (not OCTETS), DECRYPT should return NONE. This requirement is ambiguous however. Who knows it?

**Comment by AlexPeshkoff** [comment]
I can agree that RSA_DECRYPT should always work with binary data, for DECRYPT it's unpredictable, i.e. no reason to change.

**Comment by mrotteveel** [comment]
My point is, encryption and decryption transform binary data to another form of binary data. That that binary data in some cases happens to be textual, doesn't mean that you should default to handling it as text. However, that is what the current solution does by applying character set `NONE` for the result of `DECRYPT`.

**Comment by mrotteveel** [comment]
@pavel-zotov Given nothing has been implemented for this issue, you probably applied to label to the wrong issue.

**Comment by pavel-zotov** [comment]
@Mark:
we already have test for core_5970 ("Built-in cryptographic functions"), and it checks lot of combinations related to encrypt() / decrypt() functions. 
Among other, it does check for content of SQLDA for decrypt() when its first argument is varbinary.
But it does not verify SQLDA for blobs.
I prefer to have separate (small) test exactly for this ticket rather than add more statements to existing one.

**Comment by mrotteveel** [comment]
@pavel-zotov My point is, nothing has yet changed for this issue, so applying "qa: done successfully" doesn't seem appropriate. Maybe you meant to test #6804 instead (Alex accidentally closed this issue with a commit for #6804).

**Comment by pavel-zotov** [comment]
@mark:
No, i did not yet make test for #6804. It will be implemented.
But in test for this issue (6797) i changed title: "DECRYPT() must return BLOB if its first argument is blob, otherwise returnted datatype must be VARCHAR with charset NONE" - and this was done intentionally.
Perhaps, such test must have another place and name (i.e. be in 'functional' subdirectory rather than here) - ?

**Comment by aafemt** [comment]
Generally speaking: can the type of returning value for a function to be dynamically deduced from left side of assignment?

**Comment by asfernandes** [comment]
> Generally speaking: can the type of returning value for a function to be dynamically deduced from left side of assignment?

It makes no sense to even think about that.

With both NONE and OCTETS it works identically in relation to what you are doing with the result of the call if where this result is going expects a fixed type.

The practical difference happens in two places:
- describe
- using that result in some system call that accepts multiple character sets and works different - for example TRIM

**Comment by asfernandes** [comment]
Another way of dealing with this function is to force special syntax on it:

```
DECRYPT( <value> AS { <character set> | VARBINARY })
```

**Comment by AlexPeshkoff** [comment]
On 5/12/21 4:32 PM, Adriano dos Santos Fernandes wrote:
>
> Another way of dealing with this function is to force special syntax 
> on it:
>
> |DECRYPT( <value> AS { <character set> | VARBINARY }) |

If go this way - may be better:|

DECRYPT( <value> AS { <character set> | OCTETS })

?

|

**Comment by mrotteveel** [comment]
> Another way of dealing with this function is to force special syntax on it:
> 
> ```
> DECRYPT( <value> AS { <character set> | VARBINARY })
> ```

That is what casts are for. And yes, I fully understand that argument can be applied in the other direction, and that I should just shut up and explicitly cast to varbinary. The problem however is one of correctly describing your data. Drivers, like for example Jaybird, will handle OCTETS as a binary type, while all other character sets including NONE are handled as string types. This will result in potentially lossy conversions and incorrect behaviour in applications, **even if the underlying data is textual** (due to differences in connection or platform default character set and the actual character set of the data.

Describing it as OCTETS is the right default as it will result in the most appropriate behaviour in all circumstances, preserving the actual data without loss, while still allowing conversion to string types if necessary.

**Comment by aafemt** [comment]
> Drivers, like for example Jaybird, will handle OCTETS as a binary type, while all other character sets including NONE are handled as string types.

That's a good point. Unicode APIs (such as ODBC or ADO.NET) can have a problem with delivering result of such query to application.

**Comment by mrotteveel** [comment]
> If go this way - may be better:| DECRYPT( <value> AS { <character set> | OCTETS }) ? |

That said, I can live with a solution like this, **if** `OCTETS` is the default, that is, syntax:

```
DECRYPT ( _encrypted_input_
  USING <algorithm> [MODE <mode>]
  KEY _key_
  [IV _iv_] [<ctr_type>] [CTR_LENGTH _ctr_length_]
  [COUNTER _initial_counter_] 
  [AS <char_set>])
```

With `<char_set>` defaulting to `OCTETS`

**Comment by asfernandes** [comment]
> Drivers, like for example Jaybird, will handle OCTETS as a binary type, while all other character sets including NONE are handled as string types.

I understand and do the same in the nodejs driver, but that may be incorrect as well. You can't know what NONE is.

**Comment by asfernandes** [comment]
> DECRYPT( <value> AS { <character set> | OCTETS })

OCTETS (as well BINARY) is already a <character set>., it does not need special syntax.

So we can eliminate VARBINARY as just use `AS <character set>`.

**Comment by mrotteveel** [comment]
> > Drivers, like for example Jaybird, will handle OCTETS as a binary type, while all other character sets including NONE are handled as string types.
> 
> I understand and do the same in the nodejs driver, but that may be incorrect as well. You can't know what NONE is.

It is not a perfect world, but in most cases `NONE` is textual data, and handling `NONE` as string is therefor a better compromise than handling it has binary. The same can not be said for decrypted data (I have used encryption far more on binary data than on textual data). However, I have the feeling I'm beginning to sounds like a broken record.

**Comment by aafemt** [comment]
>  in most cases NONE is textual data, and handling NONE as string is therefor a better compromise than handling it has binary

I just wonder how do you convert it to Unicode?

**Comment by asfernandes** [comment]
It's why I suggested to have explicit syntax, but not with CAST.

CAST is difficult/ugly, it requires one to put length again.

But note that explicit `AS <character set>` may be trick in relation to declared length of parameter and length of result byte in a given character set. Engine would also need to check well-formedness of result.

**Comment by mrotteveel** [comment]
> > in most cases NONE is textual data, and handling NONE as string is therefor a better compromise than handling it has binary
> 
> I just wonder how do you convert it to Unicode?

We're going really off-topic here... but for Jaybird, when you use connection character set `NONE`, it uses the JVM default character set to convert to a Java `String`, otherwise it uses the connection character set. Formally, Jaybird doesn't convert to Unicode at all (the fact that a Java String is technically UTF-16 is an not-so-relevant implementation detail, conversions between strings and bytes always happen using a character set (either explicitly, or implicitly using the JVM default).

**Comment by AlexPeshkoff** [comment]
Let me summarize. Use of none or octets character set in the result of decrypt function has advantages and disadvantages with any choice. This can be solved adding AS clause in the function, or even additional session control SET statement for that purpose. 
Taking into an account that such clause/statement (or even both) can be added in future versions not breaking compatibility (including adding it as an enhancement in a point release) I suggest to STOP with this issue right now cause it is not a showstopper for v4.0 release.

**Comment by mrotteveel** [comment]
> Taking into an account that such clause/statement (or even both) can be added in future versions not breaking compatibility (including adding it as an enhancement in a point release) I suggest to STOP with this issue right now cause it is not a showstopper for v4.0 release.

It is not a showstopper as such, no.

Also, when fixing this later, we should make it behave consistent between `BLOB` and non-`BLOB`, because right now it returns either `VARCHAR CHARACTER SET NONE` or `BLOB SUB_TYPE BINARY`. Either we explicitly choose that we really consider this text, and then the blob type must change to `BLOB SUB_TYPE TEXT CHARACTER SET NONE`, or we consider this binary and the non-blob type must change to `VARBINARY`/`VARCHAR CHARACTER SET OCTETS`.

**Comment by dyemanov** [comment]
Personally, I don't have any preference between NONE / OCTETS, but I agree that the charset should be the same for blobs and non-blobs and that it should be done now.
