### ISSUE TITLE
When the statement timeout is set, it causes the lock manager to delay reporting deadlocks until timeout is expired

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#6802]
Consider script:

```SQL
set list on;
recreate global temporary table gt(f01 int) on commit preserve rows;
commit;
insert into gt values(1);
commit;
set transaction read only read committed record_version; -- lock timeout 12;

set term ^; execute block returns(dts_beg timestamp) as begin dts_beg = 'now'; rdb$set_context('USER_SESSION','DTS_BEG', dts_beg); suspend; end^ set term ;^

delete from gt;
set term ^;
execute block as 
begin 
    in autonomous transaction 
    do update gt set f01=-1; 
end
^
set term ;^
commit;
select cast('now' as timestamp) as dts_end, datediff(second from cast( rdb$get_context('USER_SESSION', 'DTS_BEG') as timestamp) to cast('now' as timestamp)) as waited_for_sec from rdb$database;
```

In FB 2.5.x and 3.0.x this script will instantly raise:
SQLSTATE = 40001 /  deadlock / -update conflicts ... / -concurrent transaction number is NNN
(and this is expected because two transactions belong to the same attachment).

In FB 4.x result will be:
1) if config parameter 'StatementTimeout' is UNDEFINED (commented out) then this exception ("update conflicts...") will raise after DeadLockTimeout seconds (and if it is also commented out then its default value = 10 is used);
2) if config parameter 'StatementTimeout' has some value then max( coalesce(DeadLockTimeout,10), StatementTimeout) will be used.

PS
Regression was discovered by accident when firebird.conf for FB 4.x has StatementTimeout = 86400, during run test core_3924.fbt.
Ticket has been created after discussion with Vlad.

**Comment by hvlad** [comment]
There are actually two issues
a) no instant deadlock detection for read-only transactions - because fb4 keeps RO transaction lock while fb3 and fb2.5 released it on transaction start. It was changed when ReadConsistency mode was developed.
b) when Statement timeout is set, it makes LM not report deadlocks until timeout is expired

**Comment by dyemanov** [comment]
Created  #6811 and renamed title for this ticket after Vlad's suggestion to split the ticket.
