### ISSUE TITLE
RDB$TYPES has incorrect entries for RDB$TYPE 28 and 29 in RDB$TYPE_NAME column.

### ISSUE THREAD

**Issue by jasonwharton** [FirebirdSQL/firebird#6805]
These values are incorrect:
TIMESTAMP WITH TIMEZONE
TIME WITH TIMEZONE

They should be:
TIMESTAMP WITH TIME ZONE
TIME WITH TIME ZONE

Please take notice of the space between TIME and ZONE.

I believe it should match the syntax in the CREATE TABLE statement which wants TIME and ZONE separated by a space.

**Comment by jasonwharton** [comment]
All in all, my preference would be to have TIMEZONE remain a single token.  Makes the parsing easier.

**Comment by AlexPeshkoff** [comment]
Afraid that SQL standard requires TIME ZONE - with space.

**Comment by dyemanov** [comment]
RDB$TYPES entries are not required to strictly follow the standard, we already have a lot of inconsistencies there, like LONG instead of INT, INT64 instead of BIGINT, etc. That said, I agree that at least for new types the name inside RDB$TYPES should better match the real SQL type name.

**Comment by pavel-zotov** [comment]
::: test details :::
No need to make separate test, see functional\basic\db\db_30.fbt

**Comment by jasonwharton** [comment]
Hi Dmitry!
 
Perhaps all of these entries in that table should be corrected?  Seems like
it shouldn't be that much work and a major version is the perfect time to do
stuff like this.
 
I was really pleased that the way my DDL extract tool worked it did most of
the new columns correctly with no changes at all in the IB Objects code
base.  If this metadata had been done correctly, it would have been perfect.
 
Thanks for all the great work on Firebird!
 
Jason Wharton
 

  _____

**Comment by dyemanov** [comment]
@jasonwharton I feel that renaming the old types may break something. Maybe it's OK for a major version, or maybe not. But I don't want to see more and more things that delay v4, so I'd better defer this renaming (if agreed) to v5.

**Comment by jasonwharton** [comment]
I agree this is not worth holding up the release for.  I'm sure your team
will make the right decision on what is best.
 
Thanks,
Jason

  _____
