### ISSUE TITLE
Rename RSA_SIGN and RSA_VERIFY

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#6806]
The RSA_SIGN and RSA_VERIFY functions are potentially confusing, as they don't actually do what - I think - most users would expect: sign a message of arbitrary length.

Their actual use is to sign a hash of a message, with the additional constraint that the HASH parameter of the function needs to be supplied with the hash algorithm that was used to generate that hash.

Given this confusing use case, I suggest that we rename RSA_SIGN to RSA_SIGN_HASH, and RSA_VERIFY to RSA_VERIFY_HASH, and clarify the release notes further.

The advantage of this is that the name makes clear - I hope - it signs a hash, and that we could - at a later time - add a function that signs/verifies a message of arbitrary length (e.g. RSA_SIGN/RSA_VERIFY or - maybe better - RSA_SIGN_MESSAGE/RSA_VERIFY_MESSAGE).

I know this is very late, but I think this is better to do this before releasing Firebird 4 than the alternative of having to live with an unclear function for all eternity.

**Comment by mrotteveel** [comment]
@AlexPeshkoff The change was only committed to master, not to v4.0-release.

**Comment by AlexPeshkoff** [comment]
Done, checked build after cherry-pick.

**Comment by pavel-zotov** [comment]
::: test details :::
See functional\intfunc\encryption\rsa_family.fbt

**Comment by aafemt** [comment]
> Their actual use is to sign a hash of a message, with the additional constraint that the HASH parameter of the function needs to be supplied with the hash algorithm that was used to generate that hash.

No, it isn't. I'm sorry, I was wrong. In PSS the message's hash is hashed once again and this parameter is the name of this second hash function.

**Comment by mrotteveel** [comment]
> No, it isn't. I'm sorry, I was wrong. In PSS the message's hash is hashed once again and this parameter is the name of this second hash function.

True, but the TomCrypt documentation specifies that it should be the same hash as was used to generate the message-hash parameter.

**Comment by mrotteveel** [comment]
I updated the existing docs in the release notes (but did not add change documentation).

**Comment by dyemanov** [comment]
> I updated the existing docs in the release notes (but did not add change documentation).

Thanks, I will add the changes part soon.
