### ISSUE TITLE
Regression in FB 4.x : "Unexpected end of command" with incorrect line/column info

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#6807]
Consider following INCORRECT script (it contains wrong token in RETURNUNG clause: "AS" instead of "INTO"):

```SQL
recreate table test(id int);
insert into test(id) values(null);
set term ^;
execute block as
    declare v_id int;
begin
    update test set id = -id returning id as v_id; -- this is WRONG; "INTO" must be here
end
^
set term ;^
```

Its output will be:
1) in FB 2.5:

> Statement failed, SQLSTATE = 42000
> Dynamic SQL Error
> -SQL error code = -104
> -Token unknown - line 4, column 43
> -as

2) in FB 3.0.8.33465:

> Statement failed, SQLSTATE = 42000
> Dynamic SQL Error
> -SQL error code = -104
> -Unexpected end of command - line 4, column 40

(looks strange because all commands appear to have tokens of completion; but anyway, we can easy find problem place because of non-zero line/column values) 

3) in FB 4.0.0.2479:

> Statement failed, SQLSTATE = 42000
> Dynamic SQL Error
> -SQL error code = -104
> -Unexpected end of command - line 0, column 0

This output is much worse: we can not find problem place because of zeroes for line/column.

**Comment by asfernandes** [comment]
The `AS <name>` is supported now, so the error is correct.

The only problem seems `line 0, column 0`.

**Comment by mrotteveel** [comment]
@asfernandes Did you mean "as alias in RETURNING columns"?

**Comment by asfernandes** [comment]
> @asfernandes Did you mean "as alias in RETURNING columns"?

Yes. It may be useless in PSQL code, but is also supported there.
