### ISSUE TITLE
Integer hex-literal support for INT128

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/firebird#6809]
Currently, the integer hex-literal does not support `INT128`. Values with more than 8 hex pairs result in a `INTEGER` with value 0.

Expected behaviour:

- Literals of 1-4 hex-pairs -> `INTEGER`
- literals of 5-8 hex-pairs -> `BIGINT`
- literals of 9-16 hex-pairs -> `INT128`
- literals of length > 16 hex-pairs should produce an error

**Comment by AlexPeshkoff** [comment]
I wonder - should this improvement go to v4.0? On my mind this can wait first service release.

**Comment by dyemanov** [comment]
@AlexPeshkoff, I agree.

**Comment by mrotteveel** [comment]
I agree as well.

**Comment by dyemanov** [comment]
> Expected behaviour:
> 
>     literals of length > 16 hex-pairs should produce an error

Testing with current v5 snapshot:

```
SQL> select 0x8000000000000000000000000000000000000000 from RDB$DATABASE;

X8000000000000000000000000000000000000000 
========================================= 
                                        0 
```

I definitely agree that an error should be raised, but currently it's missing.

**Comment by mrotteveel** [comment]
@dyemanov That problem is tracked as #7594
