### ISSUE TITLE
BASE64_ENCODE and HEX_ENCODE return type has wrong length for VARCHAR/VARBINARY

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/firebird#6813]
The `BASE64_ENCODE` and `HEX_ENCODE` functions produce types with the wrong length for `VARCHAR`/`VARBINARY` input. It seems to include the two length bytes when determining the length.

Some examples:

| Type | Hex Expected | HexActual | Base64 Expected | Base64 Actual |
| -- | -- | -- | -- | -- |
| VARBINARY(1) | 2 | 6 | 4 | 4 |
| VARBINARY(2) | 4 | 8 | 4 | 8 |
| VARBINARY(3) | 6 | 10 | 4 | 8 |
| VARBINARY(4) | 8 | 12 | 8 | 8 |
| VARBINARY(5) | 10 | 14 | 8 | 12 |
| VARCHAR(5) | 10 | 14 | 8 | 12 |
|BINARY(5) | 10 | 10 | 8 | 8 |

(last row for contrast)

Example in _isql_:

```
set sqlda_display on;
select hex_encode(cast('' as varbinary(5))), base64_encode(cast('' as varbinary(5))) from rdb$database where 1 <> 1;
```
output:
```
INPUT message field count: 0

OUTPUT message field count: 2
01: sqltype: 448 VARYING scale: 0 subtype: 0 len: 14 charset: 2 ASCII
  :  name: HEX_ENCODE  alias: HEX_ENCODE
  : table:   owner:
02: sqltype: 448 VARYING scale: 0 subtype: 0 len: 12 charset: 2 ASCII
  :  name: BASE64_ENCODE  alias: BASE64_ENCODE
  : table:   owner:
```

**Comment by dyemanov** [comment]
Superseded by #6816.
