### ISSUE TITLE
BASE64_DECODE and HEX_DECODE wrong return type length for multi-byte character set input

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/firebird#6814]
The `BASE64_DECODE` and `HEX_DECODE` functions produce types with the wrong length for `VARCHAR` input types with a multi-byte character set, the calculation uses the number of bytes instead of the number of characters. The resulting type is 4 times too wide for UTF8.

| Type | Hex Expected | HexActual | Base64 Expected | Base64 Actual |
| -- | -- | -- | -- | -- |
|VARCHAR(4) UTF8 | 2 | 8 | 3 | 12 |
|VARCHAR(8) UTF8 | 4 | 16 | 6 | 24 |
|VARCHAR(8) ASCII | 4 | 4 | 6 | 6 |

(last row for contrast)

Example in _isql_:

```
set sqlda_display on;
select hex_decode(cast('00' as varchar(8) character set utf8)), base64_decode(cast('====' as varchar(8) character set utf8)) from rdb$database where 1 <> 1;
```
Output:
```
INPUT message field count: 0

OUTPUT message field count: 2
01: sqltype: 448 VARYING scale: 0 subtype: 0 len: 16 charset: 1 OCTETS
  :  name: HEX_DECODE  alias: HEX_DECODE
  : table:   owner:
02: sqltype: 448 VARYING scale: 0 subtype: 0 len: 24 charset: 1 OCTETS
  :  name: BASE64_DECODE  alias: BASE64_DECODE
  : table:   owner:
```

**Comment by aafemt** [comment]
> the number of bytes instead of the number of characters, the resulting type is 4 times too 
> wide.

And this is actually right because 2-bytes character will have 4 bytes hex representation 
(4-bytes character - 8 bytes representation) unless you insist that result must be hex 
representation of Unicode characters instead of bytes from actual encoding.

**Comment by mrotteveel** [comment]
> the number of bytes instead of the number of characters, the resulting type is 4 times too wide.
> And this is actually right because 2-bytes character will have 4 bytes hex representation (4-bytes character - 8 bytes representation) unless you insist that result must be hex representation of Unicode characters instead of bytes from actual encoding.

This is the **decode** function, in other words, 2 hex characters produce 1 byte)), and 4 base64 characters produces 1 - 3 bytes. Even if the input is `varchar(4) character set utf8`, it can only produce 2 bytes (hex) or 3 bytes (base64), it cannot produce 8 bytes or 24 bytes.

**Comment by aafemt** [comment]
Oops, I'm sorry.

**Comment by dyemanov** [comment]
Superseded by #6816.
