### ISSUE TITLE
-fetch_password passwordfile does not work with gfix

### ISSUE THREAD

**Issue by virgoparna** [FirebirdSQL/firebird#6817]
gfix -z 
gfix version WI-V3.0.7.33374 Firebird 3.0

gfix  -user sysdba -pass masterkey localhost:F:\dbpath\database.FDB -sweep
executes successfully

gfix -user sysdba -fetch_password F:\dbpath\pwd.txt localhost:F:\dbpath\database.FDB -sweep
reports:
incompatible switch combination
please retry, specifying an option
Same error is in 2.5.9 and 4.0 Release Candidate 1

**Comment by virgoparna** [comment]
It appears, that  -fetch_password F:\dbpath\pwd.txt needs to be at the end of command. Then it works.

**Comment by pavel-zotov** [comment]
::: warning :::
Intermediate build for FB 3.x was not created due to error.
Attribute `min_version` will be changed to 3.0.8 after fix for FB 3.x.
