### ISSUE TITLE
My IBExpert crashes on connecting to any DB now after upgrade to 4.0-RELEASE

### ISSUE THREAD

**Issue by gzip4** [FirebirdSQL/firebird#6837]
Windows 10 LTSB x64

Case 1
Firebird was installed from distrib: Firebird-4.0.0.1436-0-Beta1-x64.exe
IBExpert version: 2020.4.1.1
Connection string: 127.0.0.1:employee
Client Library File: C:\Program Files\Firebird\Firebird_4_0\WOW64\fbclient.dll
All fine.

Case 2
Firebird was upgraded from distrib: Firebird-4.0.0.2496-1-x64.exe
IBExpert settings not changed
IBExpert crashes on connecting to 127.0.0.1:employee

Case 3
Firebird is new
IBExpert Client Library File: D:\app\IBExpert\WOW64\fbclient.dll (This whole directory from Beta1 distrib)
All fine.

Switch back to C:\Program Files\Firebird\Firebird_4_0\WOW64\fbclient.dll - crash again

**Comment by aafemt** [comment]
Your Expert is too old. Upgrade.

  With questions about third-party software tools you'd better go to their support, not Firebird issue tracker.

**Comment by hvlad** [comment]
I can't reproduce it with IBE 2021.3.29.1 and Firebird-4.0.0.2496-1-Win32
Try to upgrade IBE, 
check if C:\Program Files\Firebird\Firebird_4_0\WOW64\fbclient.dll is really Win32 binaries (see file properties)

BTW, what is "crashes" ? What exact error message do you see ?

**Comment by gzip4** [comment]
"Crashes" means Windows kills IBExpert and shows the window about that

**Comment by aafemt** [comment]
Still it is IBExpert issue.

**Comment by gzip4** [comment]
Upgrade IBExpert to current 2021.5.14.1 solves the issue. Thanks to all.
