### ISSUE TITLE
The Firebird 4.0 process is wrongly named in Windows Task Manager

### ISSUE THREAD

**Issue by luronumen** [FirebirdSQL/firebird#6841]
ACTUAL RESULT
- The Firebird 4.0 process is wrongly named in _Windows Task Manager_:  **Firebird Server executable (64-bit)**

![FB40](https://user-images.githubusercontent.com/8019466/120480321-4758ca00-c385-11eb-865a-b4099f0f0035.png)

EXPECTED RESULT
- The Firebird 4.0 process should be named in _Windows Task Manager_ like it is named on Firebird 3.0: **Firebird SQL Server**

![FB30](https://user-images.githubusercontent.com/8019466/120480564-8f77ec80-c385-11eb-862d-fc83052781c4.png)

ENVIRONMENT SETUP
- Windows 10 Version 21H1 (x64)
- Firebird 4.0.0.2502 (x64)
- Firebird 3.0.733374 (x64)

**Comment by hvlad** [comment]
Why do you thnk it is a bug ?
See #245

**Comment by luronumen** [comment]
> Why do you thnk it is a bug ?
> See #245

Hi @hvlad 

In my opinion yes and I explain why:
All processes listed in the _Windows Task Manager_ are executable. So, why is Firebird 4.0 process called **Firebird Server executable (64-bit)**? Can you imagine if all the processes in the _Windows Task Manager_ had the executable suffix? What would be the relevance of this?
Also issue #5957 clearly says not to change with the firebird.exe description.
Why did you close CR without waiting for my reply?

**Comment by hvlad** [comment]
Task Manager is not the only way to see file description.
I see nothing wrong in usage word "executable" for executable files.
I see no contradiction with #5957.
I waited long enough before closing issue. It could be re-opened if needed. So far I see no such need.
And it is definitely not a bug.

**Comment by hvlad** [comment]
BTW, what actual problem do you see ?

**Comment by luronumen** [comment]
Hi @hvlad 

What do you mean when asked me what the actual problem is? Did you ask me if there is any problem with you wanting to rename the description as you wish or did you ask if renaming the service description caused some functionality break in Firebird 4.0?

The issue I reported was the unnecessary change to the Firebird 4.0 service description by adding the word **executable (64-bit)** misleading people to believe that Firebird 4.0 is running as an _application_ and not a _service_.

Now I return to you a question: Why not just use **Firebird Server** keeping consistency with the name of the service (_Firebird Server – DefaultInstance_) instead of keeping the current description as _Firebird Server executable (64-bit)_ which confuses the user about the way what Firebird is running on the machine (_Service_ or _Application_)?

But instead of listening to my arguments, you preferred to close the CR, right? 

![FB40_Service](https://user-images.githubusercontent.com/8019466/120532274-e72e4c00-c3b5-11eb-9f59-c8a23a429435.PNG)

**Comment by dyemanov** [comment]
The question was why the new/changed naming is a bug? What actually was broken and how? I might agree that word "executable" looks unnecessary but what real problem does it cause? It's just a visible name, not API or SQL or any other functional thing.

**Comment by hvlad** [comment]
> The issue I reported was the unnecessary change to the Firebird 4.0 service description

Service description was not changed. File description was. And this is two very different things.
Also, I don't see how file description is related with a way the executable is running by OS.

**Comment by dyemanov** [comment]
I'm not a native English speaker and could be missing something, but for me _executable_ is not a synonym for _application_, it just means a binary file that can be executed by OS. firebird.exe may be executed as either an application or as a service, and in both cases it's seen inside the Task Manager as firebird.exe which is _executable_ file.

**Comment by asfernandes** [comment]
Everything seen in the task manager is an executable, so it is superfluous.

It seems Vlad want to put a suffix like in others cases (tool, plugin, library), but for me "server" is sufficient in this case

**Comment by luronumen** [comment]
> The question was why the new/changed naming is a bug? What actually was broken and how? I might agree that word "executable" looks unnecessary but what real problem does it cause? It's just a visible name, not API or SQL or any other functional thing.

Hi @dyemanov 

Thanks for your reply!

The issue is that when it was decided to change the description of the firebird.exe file, it was not thought to improve the understanding for the end user. Why instead of using the description _Firebird Server executable (64-bit)_ didn't it think of something like that?

- Firebird Server
- Firebird Server 4.0
- Firebird Server 4.0 (64 bit)
- Firebird SQL Server
- Firebird SQL Server 4.0
- Firebird SQL Server 4.0 (64 bit)
- FirebirdSQL Server
- FirebirdSQL Server 4.0
- FirebirdSQL Server 4.0 (64 bit)

Anyway this issue has already been closed and this discussion is too long compared to the effort it would be to adjust a simple file description.

Best Regards,
Luciano
