### ISSUE TITLE
Add support for an UUID data type

### ISSUE THREAD

**Issue by afarias-br** [FirebirdSQL/firebird#6842]
The 'UUID' data type would store data as a 16 byte binary (just like CHAR(16) character set octets) but it would read and write field value as a hex formated 32/36 or 38 bytes (chars) "GUID" [VARCHAR(N>=32) ascii]  (like implicity applying uuid_to_char and char_to_uuid each time it reads from, compare or write to the 'UUID' field)

**Comment by asfernandes** [comment]
ISQL already does this with octets. Every application could do the same.
