### ISSUE TITLE
Database-level and DDL triggers are executed at the replica side

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#6850]
While record-level replication does cause regular triggers to run on the replica side, DDL statements are replicated "as is" and thus cause existing DDL triggers to run on the replica side. This should not happen. The same issue with ON CONNECT/DISCONNECT and other database-level triggers. While theoretically they may be harmless and do not modify the database, let's better be on the safe side and avoid execution of those triggers for replicator connections.

**Comment by pavel-zotov** [comment]
:::: test details :::
Two separate tests was implemented for this issue: one for check DB-level triggers, second for DDL-level.
Check for DB-level triggers passes OK: these triggers fire only on master, but result of their activity will be eventually "transferred" to replica. 
But this is not so for DDL triggers: replica will have only their DDL but not result of their actions (e.g., no data in the log table will be transferred to replica).

Sent letter to dimitr, 21.06.2021 09:00. Waiting for fix.
