### ISSUE TITLE
LEFT JOIN on UTF8 column is really slow 

### ISSUE THREAD

**Issue by MarvinKlein1508** [FirebirdSQL/firebird#6855]
Hey everyone,

we want to change our character set from ISO_8859_1 to UTF8. In order to do so we have recreated our old database with UTf8 charset and inserted all data from our old database via a custom script to the new database. This worked fine so far.  But with UTf8 we have significant performance drops in any JOIN statements.

E.G. This query finsihed under a few ms in our old database with ISO_8859_1. In our new UTF8 one it needs around 10 seconds to execute.

When I cut the join from the query it is as fast as in the old database, but we need the result from the extra join.
```
SELECT FIRST 30 SKIP 0 
KUND_A_NR, KUND_A_NAME1, KUND_A_NAME2, KUND_A_NAME3, KUND_A_STRASSE, KUND_A_LAND, KUND_A_PLZ, KUND_A_ORT, KUND_A_USTIDNR, KUND_L_SPERRE, KUND_A_TEL1,
(SELECT SUM(OP) AS OFFENEPOSTEN FROM
(
select
BELE_A_TYP, 
CASE WHEN BELE_A_TYP = 'GU' THEN
     -COALESCE(SUM(BELE_N_BRUTTO), 0) - coalesce(SUM(BezahltBetrag), 0)
ELSE
     COALESCE(SUM(BELE_N_BRUTTO), 0) - coalesce(SUM(BezahltBetrag), 0)
END AS OP
from
  KUNDENBELEGE
where
  (
    (
      BELE_A_TYP ='RE'
    and BELE_L_BEZAHLT = 'N'
    ) or
   (BELE_A_TYP ='GU' and BELE_L_VERRECHNET = 'N' )
  )
 and BELE_A_KUNDENNR = KUND_A_NR
 GROUP BY BELE_A_TYP)) AS OP 
FROM KUNDEN WHERE 1=1 ORDER BY KUND_WK5_N_WICHTIGKEIT DESC, KUND_A_NR DESC
```

This one is working fine for us:
```
SELECT FIRST 30 SKIP 0 
KUND_A_NR, KUND_A_NAME1, KUND_A_NAME2, KUND_A_NAME3, KUND_A_STRASSE, KUND_A_LAND, KUND_A_PLZ, KUND_A_ORT, KUND_A_USTIDNR, KUND_L_SPERRE, KUND_A_TEL1
FROM KUNDEN WHERE 1=1 ORDER BY KUND_WK5_N_WICHTIGKEIT DESC, KUND_A_NR DESC
```

I think the issue has something todo with the new character set. The column BELE_A_KUNDENNR is from a custom domain type `VARCHAR(30) UTF8` in the new database and `VARCHAR(30) ISO_8859_1` in the old one.

We need to change the charset in order to save the euro sign in the database. Unfortunately we cannot use the windows1252 charset because we also need all the characters from ISO_8859_1. In our case ISO_8859_15 would be perfect but Firebird does not seem to offer us this option.

What should we do to get this working?

**Comment by dyemanov** [comment]
Was `KUNDENBELEGE.KUND_A_NR` also changed from `ISO_8859_1` to `UTF8`?

**Comment by dyemanov** [comment]
Also, please show us query plans for both databases (ISO_8859_1 vs UTF8). So far it seems like an index is not used for the join.

**Comment by MarvinKlein1508** [comment]
Hi @dyemanov thanks for your input. My bad. I forgot to migrate the indexes. After importing them, it works like magic.
