### ISSUE TITLE
4.0 - Permission error with replication

### ISSUE THREAD

**Issue by gaborboros-bgss** [FirebirdSQL/firebird#6856]
Hi All,

The steps...

Create a new database with SYSDBA: create database 'C:\R\DB\ORIGINAL.FDB';
Create a new user with admin rights: CREATE USER USR1 PASSWORD 'pwd1' GRANT ADMIN ROLE;
Add admin rights to the new user in the new database: grant RDB$ADMIN to user USR1;
Create two copies (REPLICA_ASYNC.FDB and REPLICA_SYNC.FDB) of the new database and set as read only replica with gfix.
Enable the replication (ALTER DATABASE INCLUDE ALL TO PUBLICATION; and ALTER DATABASE ENABLE PUBLICATION;) on the ORIGINAL.FDB.
Then connect to the ORIGINAL.FDB as SYSDBA with ISQL and execute the next:
execute block
as
begin
  execute statement 'create or alter view v1 as select 1 x from rdb$database'
  with autonomous transaction
  as USER 'USR1'
  password 'pwd1'
  role 'rdb$admin';
end

The async conf

database = C:\R\DB\ORIGINAL.FDB
{
	journal_directory = C:\R\JD
	journal_archive_directory = C:\R\JAD
}

database = C:\R\DB\REPLICA_ASYNC.FDB
{
	journal_source_directory = C:\R\JAD
}

and the error

... (replica) ...
	Database: C:\R\DB\REPLICA_ASYNC.FDB
	ERROR: unsuccessful metadata update
	CREATE OR ALTER VIEW V1 failed
	No permission for CREATE VIEW operation

The sync conf

database = C:\R\DB\ORIGINAL.FDB
{
	sync_replica = SYSDBA:masterkey@localhost:C:\R\DB\REPLICA_SYNC.FDB
}

and the error

... (primary) ...
	Database: C:\R\DB\ORIGINAL.FDB
	ERROR: unsuccessful metadata update
	CREATE OR ALTER VIEW V1 failed
	No permission for CREATE VIEW operation

... (primary) ...
	Database: C:\R\DB\ORIGINAL.FDB
	ERROR: Replication is stopped due to critical error(s)

No error without replication. Tried with 4.0.1.2517 SuperServer Win64 .

Gabor

**Comment by pavel-zotov** [comment]
::: test details :::
See: functional.replication.permission-error-on-ddl-issued-by-non-sysdba.fbt
