### ISSUE TITLE
ASCII_CHAR(255.4)

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird#6857]
FB 3.0.8.36403

SQL: select ASCII_CHAR(255.4) from rdb$database

Server executes this query without any problems - returns symbol with code 255.

It is OK?

**Comment by aafemt** [comment]
Implicit cast from numeric to integer is not prohibited.

**Comment by mrotteveel** [comment]
If your unsure if something is a bug, please ask first on the [firebird-support Google Group](https://groups.google.com/g/firebird-support)

**Comment by mrotteveel** [comment]
As [documented](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html#fblangref30-functions-string):

> code An integer within the range from 0 to 255

The value 255.4 is automatically coerced to the integer 255, and although the function name contains ASCII, what it actually does is return a `CHAR(1) CHARACTER SET NONE`, and any value 0 - 255 is accepted (and basically converted to the equivalent byte value).
