### ISSUE TITLE
Significant performance regression of SIMILAR TO and SUBSTRING(SIMILAR) when pattern is taken from variable (rather than directly specified)

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#6875]
Ticked is based on example that was shown in russian DB forum by Evgeny Shavlyuk.
( https://www.sql.ru/forum/actualutils.aspx?action=gotomsg&tid=1336524&msg=22330618 )

Consider this script:
```
shell del c:\temp\tmp4test.fdb 2>nul;
create database 'localhost:c:\temp\tmp4test.fdb' user 'sysdba' password 'masterkey';

set term ^;
create or alter procedure TEST (
    N integer,
    V integer)
as
    declare nums varchar(16) = '[-+]?[0-9]{1,10}';
    declare b boolean;
begin
  while (n > 0) do
  begin
    if (v = 1) then
      b = '5' similar to nums; -------------------- [ 1 ]
    else if (v = 2) then
      b = '5' similar to '[-+]?[0-9]{1,10}'; ------ [ 2 ]
    n = n - 1;
  end
end
^
set term ;^
commit;

show version;
set stat on;
set echo on;

execute procedure test(1000000, 1);

execute procedure test(1000000, 2);
```

Its performance:
```
execute procedure test(1000000, 1);
...
Elapsed time = 35.336 sec
```
== vs ==
```
execute procedure test(1000000, 2);
...
Elapsed time = 1.312 sec
```

Regression was introduced between 4.0.0.1575 (snapshot timestamp: 06-sep-2019 06:17) and 4.0.0.1598 (09-sep-2019 03:25).

On build 4.0.0.1575 result was:
```
Elapsed time = 3.591 sec
Elapsed time = 1.737 sec
```
The same results (as on 4.0.0.1575) can be seen on FB 3.x

**Comment by asfernandes** [comment]
Looks like regexp compilation by RE2 is much slower than what we had before.

And invariant/computed internal mechanism does not work in this case.

Since RE2 objects are shareable (and even thread safe), I'd say it's better to create a cache mechanism for them, which may be internal per request for easy management.
