### ISSUE TITLE
DataTypeCompatibility not applied in concatenated timestamps

### ISSUE THREAD

**Issue by tonne1** [FirebirdSQL/firebird#6876]
testcase: 
Switch off time zones by setting DataTypeCompatibility = 3.0 in firebird.conf. Or set bind as indicated by the SQL comment. 
Then run

`-- set bind of time zone to legacy

select current_timestamp, '' || current_timestamp, '' || localtimestamp, '' || left(current_timestamp, 24)
from rdb$database`

Column 1, 3, 4 are as expected, 
Column 2 is not. A concatenated current_timestamp includes a TZ String. This is not consistent and ignores the compatibility setting. Affects Firebird 4.0.0

**Comment by asfernandes** [comment]
Both settings acts only when sending/receiving data in the client.

Computations (done in the server) are not affected.

There is no such thing as "disable time zones".

Just use the correct expressions (in your case `localtimestamp`.
