### ISSUE TITLE
4.0 - Different LIST result than with 2.5 and 3.0

### ISSUE THREAD

**Issue by gaborboros-bgss** [FirebirdSQL/firebird#6881]
Hi All,

CREATE TABLE TBL1 (F1 INTEGER, F2 VARCHAR(10), F3 VARCHAR(10), F4 VARCHAR(10));

INSERT INTO TBL1 (F1, F2, F3, F4) VALUES (1, '27', 'Y', 'X');

INSERT INTO TBL1 (F1, F2, F3, F4) VALUES (25, '12', 'Y', 'X');

with list1 as (select * from tbl1 order by 1, 2)
select cast(list(f1) as varchar(10)) f1, cast(list(f2) as varchar(10)) f2, f3, f4
from list1
group by 3, 4;

2.5

F1         F2         F3         F4
========== ========== ========== ==========
25,1       12,27      Y          X

3.0

F1         F2         F3         F4
========== ========== ========== ==========
25,1       12,27      Y          X

4.0

F1         F2         F3         F4
========== ========== ========== ==========
1,25       27,12      Y          X

with list1 as (select * from tbl1 order by 2, 1)
select cast(list(f1) as varchar(10)) f1, cast(list(f2) as varchar(10)) f2, f3, f4
from list1
group by 3, 4;

2.5

F1         F2         F3         F4
========== ========== ========== ==========
25,1       12,27      Y          X

3.0

F1         F2         F3         F4
========== ========== ========== ==========
25,1       12,27      Y          X

4.0

F1         F2         F3         F4
========== ========== ========== ==========
1,25       27,12      Y          X 

Gabor

**Comment by dyemanov** [comment]
This example clearly shows that neither 2.5 / 3.0 nor 4.0 respects the inner ORDER BY clause ;-) They just do it differently. GROUP BY is internally implemented via sorting, thus the original ordering is not guaranteed to be preserved during the grouping. SQL is a declarative language and tricks based on expected execution order are generally not reliable. The only proper solution is to support declarative ordering inside the LIST function.
