### ISSUE TITLE
Index violation with GTT and primary key

### ISSUE THREAD

**Issue by touchcut-markk** [FirebirdSQL/firebird#6882]
I've created a global temporary table like the following in Firebird 3.0.6

CREATE GLOBAL TEMPORARY TABLE tmpCacheChangeHelper 
  (
    cacheName varchar(63) NOT NULL primary key,
    changed boolean default false NOT NULL 
  )
  ON COMMIT PRESERVE ROWS;  

if in two separate transactions I run the following update statement the 2nd one will fail with a constraint violation 
update or insert into tmpCacheChangeHelper (cacheName, changed) values ('MATERIAL_INFO', true) matching (cacheName);

Engine Code    : 335544665
Engine Message :
violation of PRIMARY or UNIQUE KEY constraint "INTEG_168" on table "TMPCACHECHANGEHELPER"
Problematic key value is ("CACHENAME" = 'MATERIAL_INFO')

Is this a bug or one of the constraint limitations?  If this is constraint limitation with GTT then shouldn't sql fail at table create time?

**Comment by hvlad** [comment]
Both tx sees empty table and trying to insert the same record. 
Of course one of the inserts will fail with PK violation.
The same will be with permament tables.
Probably you need GTT ON COMMIT DELETE ROWS ?

**Comment by touchcut-markk** [comment]
Sorry, I wasn't clear enough, both transactions are different connections
' Global temporary tables have persistent metadata, but their contents are transaction-bound (the default) or connection-bound. Every transaction or connection has its own private instance of a GTT, isolated from all the others.'

**Comment by hvlad** [comment]
I can't reproduce it with both 3.0.6 and current build of 3.0.8
Check twice your case, make sure you really using GTT, not persistent table;

**Comment by mrotteveel** [comment]
Are you sure they are actually separate connections, and not the same connection through a connection pool?

**Comment by touchcut-markk** [comment]
I suspect you've just pointed out what I'm doing wrong, I thought FlameRobin opened a new connection for each window but when I do a "select current_connection from rdb$database"  I see both windows return the same value so need to open to a new Flamerobin to test properly.

I replaced the temp table with one with no index but some problems occurred in the process with trying to drop the temp table and Firebird got into a state where it thought index/key existed but couldn't drop because it didn't exist.  After a restart I could drop but the new temp table now isn't honoring 'on commit preserve rows' so I since its a test database I think I'll trash db and recreate.
