### ISSUE TITLE
Differerent interfaces behaviour depending upon source of interface

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#6886]
ResultSet::close function behaves differently depending upon provider of interface - in YValve it releases result set on success (according to docs), in Engine/Remote - does not release result set. Same difference in bahaviour is present in all functions, closing access to the object (Transaction::commit, Attachment::detach, etc.).

That causes memory leaks when attachments from engine are used directly (like in Mappong.cpp).

**Comment by aafemt** [comment]
Do you suggest YValve to stop release interface breaking every existing application or make plugins to release objects breaking every existing third-party plugin?

**Comment by aafemt** [comment]
IMHO, this behavior must be simply documented and every API user to be aware that they must release interfaces by hand if they were gotten from plugin itself rather than Y-Valve.

**Comment by AlexPeshkoff** [comment]
That's a question I was waiting for. To know - do some 3d-party 
providers exist.

What about your suggestion. Yes, documented bug becomes feature, but I 
prefer to fix it. There are ways to avoid failures with old providers.

**Comment by aafemt** [comment]
Yes, Magpie (provider for ODBC) exists and I raised thread in firebird-devel about exactly this issue during its development. But provider-type plugin is not the only one which have interfaces with terminating methods.

**Comment by aafemt** [comment]
Perhaps the best thing you can do is to introduce a new set of Y-interfaces without terminal methods and declare old set deprecated. Also it is a good occasion to divorce client API for and plugin API.

**Comment by AlexPeshkoff** [comment]
This fixed approx.80% of memory leaks in engine when running TCS. Number of leaks in yValve and network server also got smaller. But I reopen it in order to wait for full QA runs and after it backport to FB 4 and 3.
