### ISSUE TITLE
error no permision occurred while ALTER USER SET TAGS on snapshot build WI-V3.0.8.33482

### ISSUE THREAD

**Issue by virgonia** [FirebirdSQL/firebird#6889]
an error no permision occurred while ALTER USER SET TAGS on snapshot build WI-V3.0.8.33482 (attached picture).
work fine on WI-V3.0.8.33476  (attached picture).
![WI-V3 0 8 33476 Firebird 3 0_ok](https://user-images.githubusercontent.com/30924531/124585283-5567a200-de7f-11eb-9179-bffdbd2cb350.jpg)
![WI-V3 0 8 33482 Firebird 3 0_bug](https://user-images.githubusercontent.com/30924531/124585295-5698cf00-de7f-11eb-8a6a-debaed2bb43a.jpg)

**Comment by virgonia** [comment]
solved, thanks

**Comment by AlexPeshkoff** [comment]
that's great that bug was found so fast, and thanks for testing snapshots
