### ISSUE TITLE
Problem with replication of BLOB segments longer than 32KB

### ISSUE THREAD

**Issue by km4zm** [FirebirdSQL/firebird#6893]
FB4 replication works fine, except for the (small) problem I have. 

When I change Master db all the changes get replicated to Replica db, except BLOB graphics (image) column. Actually, BLOB graphic gets replicated if size of the image is small (let's say less than 16K). For bigger images BLOB column is not replicated. Change shows up correctly in Master db, but not in Replica db. Replication.log does not show any messages.

Replication is async and here is my replication.conf file

# (for the primary side)
database = D:\Delphi\Projects\Database\YU1SRS\YU1SRS.FDB
 {
  disable_on_error = false
  journal_segment_size = 524288000 # 500MB
  buffer_size = 524288000 # 500MB
  journal_directory = D:\Delphi\Projects\Database\FBReplication\Journal\YU1SRS
  journal_archive_directory = D:\Delphi\Projects\Database\FBReplication\Archive\YU1SRS
  journal_archive_command = "copy $(pathname) $(archivepathname)"
  journal_archive_timeout = 10
 }
# (for the replica side)
database = D:\Delphi\Projects\Database\FBReplication\Replica\YU1SRS\YU1SRS_Repl.FDB
 {
  journal_source_directory = D:\Delphi\Projects\Database\FBReplication\Archive\YU1SRS
 }

I was playing with values for journal_segment_size and buffer_size, but it makes no difference.
 
I am using Delphi 10.3.3, FireDAC, FB4 stable release (same happens with Daily Builds), Win 10 Ent.
Here is Delphi code for test:
 
  ms := TMemoryStream.Create;
  try
    ms.LoadFromFile(edtBLOBFile.Text);
    ms.Position := 0;
    FDConnection1.StartTransaction;    //connected as SYSDBA
    try
      qryBLOB.SQL.Text := 'update DOC_DOCUMENT_BLOB set Doc_BLOB=:blob, LC_User_Id=1 where Id=27';
      qryBLOB.Params[0].ParamType := ptInput;
//      qryBLOB.Params[0].FDDataType := dtBlob;   //makes no difference
      qryBLOB.Params[0].LoadFromStream(ms, ftBlob);
      qryBLOB.ExecSQL;
      FDConnection1.Commit;
    except
      FDConnection1.Rollback;
      raise;
    end;
  finally
    ms.Free;
  end;

Same problem happens if I do an insert.

Perhaps I'm doing something wrong. Is there some conf option in FB4 that I'm missing?

Regards
Zoran

**Comment by dyemanov** [comment]
Can you provide a test case with a compiled application?

**Comment by km4zm** [comment]
Hi Dmitry

Here is the test (databases, source for test program, exe of test program, replication.conf etc). Test inserts/updates 3 rows, one with small blob, one with mid size blob, and one with large blod. Small size blob replicates ok, the other two don't.

You might want to change ConnectionString.txt in Home folder to match your environment. Also, replication.conf should be changed for the same reason.

Regards
Zoran

ppofe.com/svetlo/FB4TestCase.zip

**Comment by dyemanov** [comment]
Please test the next snapshot build, it should be fixed.

**Comment by km4zm** [comment]
All is working fine now. Thank you.

Regards
Zoran

**Comment by pavel-zotov** [comment]
Test name: functional.replication.blob-segments-longer-32kb-are-not-replicated
