### ISSUE TITLE
Client forcing server to encryption

### ISSUE THREAD

**Issue by cincuranet** [FirebirdSQL/firebird#6896]
I have server with `WireCrypt = Disabled`, but I can "just" send `op_crypt` and server follows. I think server should return error in such case.

Seen on 3.0.7.

**Comment by AlexPeshkoff** [comment]
How far does server follow on op_crypt? As far as I can see from code it will send no keysInfo when WireCrypt = Disabled. Am I wrong with it?

**Comment by cincuranet** [comment]
I get a regular response to `op_crypt` and the encryption is started (the response needs to be decrypted). I then ask for `isc_info_firebird_version` and correct response is received with, in my case, _WI-V3.0.7.33374 Firebird 3.0/tcp (xxx)/P13:**C**_ (emphasis mine).

**Comment by AlexPeshkoff** [comment]
Got you, i.e. I should be more careful when emulating that case. Can you 
attach server's firebird.conf?

**Comment by cincuranet** [comment]
Here it is. 

[firebird.conf](https://github.com/FirebirdSQL/firebird/files/6847905/firebird.conf.txt)

**Comment by cincuranet** [comment]
I'm testing [this build](https://github.com/FirebirdSQL/firebird/actions/runs/1049596679) and when I send `op_crypt` now, server puts into log:

```text
	start_crypt:
	Client attempted to start wire encryption using unknown key Symmetric
```

And no response to `op_crypt` is sent back to client app.

**Comment by AlexPeshkoff** [comment]
Yes, exactly. And what is a problem? Breaking connection is correct reply on wrong operation, including op_crypt.
After op_crypt client expects (at least should expect) encrypted data, but server can not send them encrypted.

**Comment by cincuranet** [comment]
I would expect generic response with an error message. Because currently the client app has no idea what really happened.

**Comment by AlexPeshkoff** [comment]
Once more: if client sends op_crypt, that means next packet from server (including error response) should be encrypted. But  during start crypt error happened, i.e. server can not send something encrypted. Sending unencrypted error response makes no sense - client will try to decrypt it and get decryption error or invalid packet (depending upon can wire crypt plugin distinguish between wrong and correct encrypted packets or not). You may yourself treat broken connection as 'sooner of all start crypt error happened on server' and report it to the user.

Moreover, such behavior (op_crypt when encryption at server side is disabled) means client missed message from server that encryption should not be used. And the best solution is to not send op_crypt at all after receiving that information.

**Comment by cincuranet** [comment]
> Once more: if client sends op_crypt, that means next packet from server (including error response) should be encrypted. But during start_crypt error happened, i.e. server can not send something encrypted. Sending unencrypted error response makes no sense - client will try to decrypt it and get decryption error or invalid packet (depending upon can wire crypt plugin distinguish between wrong and correct encrypted packets or not). 

You're right. Weird situation. :\

> You may yourself treat broken connection as 'sooner of all start_crypt error happened on server' and report it to the user.

This is not a robust behavior. Broken connection might be unrelated to encryption, simple network issue.

> Moreover, such behavior (op_crypt when encryption at server side is disabled) means client missed message from server that encryption should not be used. Therefore the best solution is to not send op_crypt at all after receiving that information.

Yeah. I would like to to this. Where is the information about not starting the encryption?

**Comment by aafemt** [comment]
Weird design. The answer to op_crypt must not be encrypted and the real encryption should be starting from the next client packet.

**Comment by cincuranet** [comment]
> Weird design. The answer to op_crypt must not be encrypted and the real encryption should be starting from the next client packet.

Funny enough, when I was first implementing the encryption, I did it like this on a first try.

I would put it into same category as _zlib_ usage for compression, vs. "just" _deflate_.

**Comment by AlexPeshkoff** [comment]
@aafemt 
This will not help in many cases. The most typical one - when there is problem with encryption key. As long as we have not sent first encrypted packet and successfully decrypted it on the other side we can't say for sure 'encryption is OK'.

May be it's really worth to send at least something from the server in order to help client distinguish between network error and wire-crypt problems. I will think about it in next protocol version.

**Comment by aafemt** [comment]
At this stage "encryption is OK" is not needed, "I agree on encryption" is enough for proper diagnostics.

**Comment by AlexPeshkoff** [comment]
It's needed. Agreement on encryption was already discussed by them in op_connect / op_accept packets (very first exchange). Jiri ignored data from server and sent op_crypt anyway. Before my fix server started encrypted session successfully, which was certainly a bug.

@cincuranet 
The way how server returns is it going to use encryption or not is not too simple. There is data block, containing chain of special clumplets. It may contain _name of usable key_ (TAG_KEY_TYPE == 0), _list of appropriate for that key plugins_ (TAG_KEY_PLUGINS == 1) and some other data like list of usable authentication plugins. Format of that clumplets block is almost DPB1-like, but untagged. The next issue is that depending upon connection stage and chosen method that block may be sent in:
op_accept_data: p_acpt_keys
op_cond_accept: p_acpt_keys 
                (p_acpt_keys is last field in this packets)
op_cont_auth: p_keys
                (p_keys is last field in this packet)
op_response: p_resp_data
                (p_resp_data is also last field in this packet - but I believe you are familiar with it)

If server is not going to use encryption it does not send any key/plugins to the client. Client must choose from sent data key and plugin it can use and start encryption.

**Comment by aafemt** [comment]
> Before my fix server started encrypted session successfully

But which wire crypt plugin it used for that? If the list of available plugins had been empty then sever should react as if received opcode is unknown/disallowed...

**Comment by AlexPeshkoff** [comment]
> But which wire crypt plugin it used for that? If the list of available 
> plugins had been empty then sever should react as if received opcode 
> is unknown/disallowed...
>

That's not straightforward process. List of available plugins with 
acceptable for it types of keys is prebuilt in the beginning of server 
operation and saved in a cache. What about the keys - they are coming 
from auth plugins when connecting particular port. And that *auth* 
plugins have absolutely no idea, should wire be encrypted or not, they 
just create keys. Before the fix I did not send type of created keys to 
the client, but created keys themself were stored on server till the end 
of authentication. Now I do not drop keys at once but not let server use 
them in a case of disabled wirecrypt - that's just simpler programmatically.

**Comment by aafemt** [comment]
> List of available plugins with acceptable for it types of keys is prebuilt in the beginning of server operation and saved in a cache.

Isn't WireCryptPlugin setting per-connection? IIRC databases.conf can be reloaded on-the-fly so the cache should be rather useless in this case.

**Comment by AlexPeshkoff** [comment]
> Isn't WireCryptPlugin setting per-connection? IIRC databases.conf can 
> be reloaded on-the-fly so the cache should be rather useless in this case.
>

Yes, but don't mix with per-DB. Remember that: "Per-connection 
configuration is primarily client tool" (from firebird.conf). On server 
side setting of WireCryptPlugin is shared for all databases.

PS. Cache of _key types_ will be efficient in a case of per-database 
configuration too. But it will need rework in order to make it 
insertable during server operation.
