### ISSUE TITLE
Firebird 3 native identity column, and "RESTART WITH" DDL-SQL

### ISSUE THREAD

**Issue by devEric69** [FirebirdSQL/firebird#6906]
Hello,

The DDL-SQL statement ( "ALTER TABLE ... ALTER COLUMN ... (RESTART WITH {n});" ) does nothing on the native IDentity fields, without nor external SQL generator, neither external SQL sequence and associated before INSERT triggers. 

For example, if I only have 3 records left after having destroyed many records (say 1000), and I would like now to restart the next insert number at num# 4, the next number is 1003, even after running the DDL-SQL below:

ALTER TABLE MY_TABLE ALTER COLUMN MY_IDENTITY_COLUMN_ID (RESTART WITH 4);

Is this normal?

Regards.

**Comment by mrotteveel** [comment]
Please ask questions on [firebird-support](https://groups.google.com/g/firebird-support). If you think something is a bug, then please provide the necessary reproduction steps, including expected behaviour and actual behaviour. 

The DDL as shown does is not valid Firebird syntax and would result in a token unknown - ( error. The  actual syntax is without the parenthesis

```sql
ALTER TABLE MY_TABLE ALTER COLUMN MY_IDENTITY_COLUMN_ID RESTART WITH 4;
```

This works with one minor caveat (fixed in 3.0.8 iirc):
```
SQL> create table withid (id integer generated by default as identity);
SQL> insert into withid default values;
SQL> select id from withid;

          ID
============
           1

SQL> alter table withid alter column id restart with 5;
SQL> insert into withid default values;
SQL> select id from withid;

          ID
============
           1
           6

SQL>
```

**Comment by mrotteveel** [comment]
Or as an example more in line with your issue:
```
SQL> insert into withid default values;
SQL> insert into withid default values;
SQL> insert into withid default values;
SQL> select id from withid;

          ID
============
           1
           6
           7
           8
           9

SQL> delete from withid where id < 9;
SQL> alter table withid alter column id restart with 1;
SQL> insert into withid default values;
SQL> select id from withid;

          ID
============
           9
           2

SQL>
```

**Comment by devEric69** [comment]
Oops: it works fine without the brackets :-) . 

Sorry for the noise, and I'll ask my questions on the firebird-support first, in the future. Thanks a lot.

**Comment by mrotteveel** [comment]
No problem, and good to hear your issue is solved.

firebird-support probably gets more eyes than the GitHub issues, so chances are you get a quicker answer there. We also like to keep a bit of separation between 'support/questions' and 'bug reports/feature requests'.
