### ISSUE TITLE
Add way to retrieve statement BLR with Statement::getInfo and ISQL's SET EXEC_PATH_DISPLAY BLR

### ISSUE THREAD

**Issue by asfernandes** [FirebirdSQL/firebird#6910]
Info codes to be used with `Statement::getInfo`:

```
#define isc_info_sql_exec_path_blr_bytes	31
#define isc_info_sql_exec_path_blr_text		32
```

To make `isc_info_sql_exec_path_blr_*` work, session must be first execute `set debug option dsql_keep_blr = true`.

ISQL command:

In ISQL, `set debug option` must not be used directly, instead user should use `set exec_path_display blr`.

```
SET EXEC_PATH_DISPLAY BLR/OFF

Retrieves the execution path of a DML statement formatted as BLR text.

Warning: this feature is very tied to engine internals and its usage is discouraged
if you do not understand very well how these internals are subject to change between
versions.
```

**Comment by pavel-zotov** [comment]
Sent letter to Adriano, 28.07.2021 17:32, waiting for reply.

**Comment by asfernandes** [comment]
> Sent letter to Adriano, 28.07.2021 17:32, waiting for reply.

Unfortunately it was only working with embedded.

I've rolled back the feature and will think in another way to implement it.
