### ISSUE TITLE
UPDATE OR INSERT freezes Firebird 4 server

### ISSUE THREAD

**Issue by MarvinKlein1508** [FirebirdSQL/firebird#6916]
I have the follwing table:

```
CREATE TABLE WK5_AUFTRAGSFREIGABE 
(
  FREI_N_BELENR               TBELEGNR ,
  FREI_D_PACKENAB                 DATE         NOT NULL,
  FREI_N_LASTUSER                 TINT ,
 CONSTRAINT PK_WK5_AUFTRAGSFREIGABE PRIMARY KEY (FREI_N_BELENR)
);
```

It stores a value of type TBELEGNR which is defined as:
```
CREATE DOMAIN TBELEGNR AS 
 INTEGER
 DEFAULT 0
 NOT NULL
;
```

Now I have this statement:
`UPDATE OR INSERT INTO WK5_AUFTRAGSFREIGABE (FREI_N_BELENR, FREI_D_PACKENAB, FREI_N_LASTUSER) VALUES (42308, '06.08.2021', 30)`

The first run of this method freezes the Firebird 4 server. The server seems to hang in a kind of loop which allocates more and more memory. After a few minutes it took over 4GB already. The service can't be stopped with `services.msc`. To get it working again you'll need to kill the service via task manager.

**Comment by MarvinKlein1508** [comment]
I've just notice I even can't insert into this table using `INSERT INTO` not sure why. I have the only connection open to my local db.

**Comment by asfernandes** [comment]
Cannot reproduce. Please create a reproducible case.

**Comment by asfernandes** [comment]
> I've just notice I even can't insert into this table using `INSERT INTO` not sure why. I have the only connection open to my local db.

A corrupted database?

**Comment by MarvinKlein1508** [comment]
@asfernandes all other tables work just fine. It's just this one. I try to re-create the table now. Not sure what's going on.

Is there any way to check for a courrupted database?

**Comment by MarvinKlein1508** [comment]
@asfernandes nevermind. I figured out what went wrong.

The table at a trigger which raises another trigger from another table which then raises a trigger from my table over and over again.
