### ISSUE TITLE
FB 4 installer asks for SYSDBA password when doing client installation

### ISSUE THREAD

**Issue by WarmBooter** [FirebirdSQL/firebird#6917]
The Windows installer of Firebird 4 is asking for SYSDBA password when doing a Client install and Minimum Cliente Install. I see no reason for that.

**Comment by reevespaul** [comment]
On Sat, 07 Aug 2021 18:55:46 -0700
"Carlos H. Cantu" ***@***.***> wrote:

> The Windows installer of Firebird 4 is asking for SYSDBA password when
> doing a Client install and Minimum Cliente Install. I see no reason for
> that.
> 

Me neither.

I'll fix it.


Paul
-- 

Paul Reeves
http://www.ibphoenix.com
Supporting users of Firebird
