### ISSUE TITLE
Static compilation of fbclient.dll or fbclient.so

### ISSUE THREAD

**Issue by rfx77** [FirebirdSQL/firebird#6923]
Hi!

Is ist possible to do a static compilation of fbclient so that it can be embedded in a static rust or go binary. I would like to use it as an alternative to sqlite.

Greetings,
Franz

**Comment by aafemt** [comment]
In theory - yes. On practice current Firebird build procedure doesn't produce static library usable out-of-box.

**Comment by rfx77** [comment]
Would it be hard to do or is there some documentation which can help?

**Comment by aafemt** [comment]
Yes, it would be hard. Especially if the Rust (which I know nothing about) is unable to link against C/C++ object files.

**Comment by hvlad** [comment]
> Is ist possible to do a static compilation of fbclient so that it can be embedded in a static rust or go binary. I would like to use it as an alternative to sqlite.

AFAIU, sqlite is full engine, while fbclient is just a client. I.e. if you need statically linked alternative to sqlite - you need to link not only fbclient but also engine and probably few more plugins.

**Comment by rfx77** [comment]
Rust and go can use c object files without a problem. fbclient has the server embedded so it is like sqlite.

**Comment by AlexPeshkoff** [comment]
On 8/17/21 4:20 PM, Franz wrote:
>
> fbclient has the server embedded so it is like sqlite.
>

embedded server is one more dynamic library

**Comment by hvlad** [comment]
> 
> 
> fbclient has the server embedded so it is like sqlite.

No, it doesn't.
