### ISSUE TITLE
Slow query with a blob over the network (FB 2.x / fb3.x)

### ISSUE THREAD

**Issue by davidmullerz** [FirebirdSQL/firebird#6924]
Query are very slow with un small blob text over network

Create a Database in network.

Create this small Table
````sql
CREATE TABLE TESTBLOB (
ID integer PRIMARY key,
 Blob1 blob sub_type text,
VC varchar(32765));
````

Insert 5000 lines
````sql
EXECUTE block
AS
DECLARE i integer;
BEGIN
	i=1;
	WHILE (i <= 5000) do
	BEGIN
		INSERT INTO testblob (ID,Blob1, VC) 
		VALUES (:I,'TEST MESSAGE TEXT very Short','TEST MESSAGE TEXT very Short');
	i = I +1;
	end
END;
````

First query with blob
````sql
SELECT ID,Blob1 FROM testblob;
/* Result in 17 sec. on network*/
````

Second query with Varchar
````sql
SELECT ID,VC FROM testblob;
/* Result in 110 ms. on network*/
````

**Comment by mrotteveel** [comment]
This is basically the result of how the Firebird wire protocol works. Each blob needs to be fetched individually, which results in a lot of additional network roundtrips. Short of a redesign of the wire protocol, there is not a lot that can be done.

Duplicates #4916 (and others).
