### ISSUE TITLE
GTT's pages are not released while dropping it

### ISSUE THREAD

**Issue by ilya071294** [FirebirdSQL/firebird#6932]
The problem is related to GTTs ON COMMIT PRESERVE ROWS.
Steps to reproduce:
1. Create GTT. For example: `create global temporary table temp_table(id bigint, str varchar(100)) on commit preserve rows;`
2. Insert some data in it.
3. Drop it.

Repeat these steps many times, and the temp file will be constantly growing in size.

**Comment by pavel-zotov** [comment]
::: test details :::
Test implemented for Windows only: there is no ability to get name of GTT file on Linux (from Python code) without shell calls because all such files marked as deleted immediately after creation.
