### ISSUE TITLE
SQL SECURITY DEFINER does not affect the ownership of created DDL objects

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#6934]
When DDL is executed via EXECUTE STATEMENT inside a procedure/function created by a privileged user (e.g. SYSDBA) and declared as SQL SECURITY DEFINER, it's allowed to execute (effective user is SYSDBA), but the created object has the session user as an owner and all permissions are granted to the session user. I believe the created objects should belong to the effective user instead.

Test case:

```
create database test.fdb user sysdba;

set term ^;

create procedure test
sql security definer
as
begin
  execute statement 'create table t (id int)';
end
^

set term ;^

commit;

create user asd password 'asd';
grant execute on procedure test to asd;

connect test.fdb user asd;

execute procedure test;
commit;

select rdb$owner_name
from rdb$relations
where rdb$relation_name = 'T';

RDB$OWNER_NAME                                                  
=============================================================== 
ASD                                                             

set blobdisplay 3;

select rdb$acl
from rdb$relations join rdb$security_classes using (rdb$security_class)
where rdb$relation_name = 'T';

RDB$ACL:  
ACL version 1
person: ASD, privileges: (alter, control, drop, insert, update, delete, select, references)

```

**Comment by dyemanov** [comment]
So far I can think of three possible solutions:
1. Consider it a bug and fix, as suggested
2. Restore the original default behaviour of ES -- execute with invoker's permissions -- and add WITH DEFINER PRIVILEGES as an option
3. Keep the current behaviour of ES (defined by SQL SECURITY) as default and add two options -- WITH {INVOKER | DEFINER} PRIVILEGES -- to override the default in both ways
Comments / votes / other suggestions, please.

**Comment by dyemanov** [comment]
And obviously in all cases the effective user should become the owner of the created metadata objects.

**Comment by romansimakov** [comment]
Only the first solution seems consistant to me. Under SQL SECURITY DEFINER there is no any INVOKER. The same I see in the SQL Standard. There is only "autirization id" and only it does all actions. I tend to consider another user appearance as a bug that must be fixed. So I think the solution 1 and a way to go.

**Comment by dyemanov** [comment]
I've fixed this ticket by using effective user as an owner. If someone insists EXECUTE STATEMENT should have more flexibility, feel free to create a new ticket for that. Even if effective user is reset for ES to some other value, the ownership logic will still be correct now.

**Comment by pavel-zotov** [comment]
::: test details :::
have a question, sent to Alex and dimitr; waiting for reply.
