### ISSUE TITLE
Windows client install missing DLLs

### ISSUE THREAD

**Issue by WarmBooter** [FirebirdSQL/firebird#6943]
The currently Firebird 4 windows "Client" install (both minimal and client+tools) doesn't install the ICU DLLs (required for correct time zone support), nor the chacha.dll or zlib1.dll

**Comment by mrotteveel** [comment]
The fact it doesn't install the ICU DLLs is, as far as I know, intentional.

**Comment by WarmBooter** [comment]
> The fact it doesn't install the ICU DLLs is, as far as I know, intentional.

Intentional or not, it doesn't seem correct.
