### ISSUE TITLE
Give a shorter form for SET STATISTICS (e.g. 'SET STAT')

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#6951]
```
SQL> set statistics index qtyx;
SQL> commit;
SQL> set stat index qtyx;
Command error: set stat index qtyx
```

**Comment by aafemt** [comment]
"Set statistics" is not ISQL command, it is in the engine.

**Comment by dyemanov** [comment]
Given that we consider adding more powerful support to statistics calculation (which is likely to have even longer syntax), I tend to reject this request. And we usually don't add shortcuts to the parser grammar anyway.
