### ISSUE TITLE
grant references not working

### ISSUE THREAD

**Issue by roger-castaldo** [FirebirdSQL/firebird#6963]
Using Firebirdsql 4.0.0 server I have found an issue with the grant references on a table.  Even though grant references has been given to a given user for a specific table, that user is unable to create a foreign key relationship, though based on the documentation for references, thats the point of it.  To recreate:

CREATE TABLE TEST(
    ID INT NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE USER tester PASSWORD 'testing';
GRANT SELECT,REFERENCES ON TEST TO tester;

Login as user tester

CREATE TABLE TEST_EXT(
    ID INT NOT NULL,
    EXT_NAME VARCHAR(1024) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(ID) REFERENCES TEST(ID) ON UPDATE CASCADE ON DELETE CASCADE 
);

Expected behavior here is to create the table with the foreign key constraint, however, an error occurs:
**no permission for ALTER access to TABLE TEST**

Based on communication with another, this is due to the update/delete cascade component needing to alter the test table.

Additional Note:  If I login as the database admin after the test user creates the table without the foreign key, and create the foreign key, it works as expected.  However, as the test user I can drop that table afterwards without a security issue (even though technically it is altering the table that tester does not have access to alter).

**Comment by AlexPeshkoff** [comment]
Is TEST_EXT created if you remove ON UPDATE CASCADE ON DELETE CASCADE?
