### ISSUE TITLE
On Windows, engine may hung when works with corrupted database and read after the end of file

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#6968]
`GetOverlappedResult()` should not be called when read\write failed and was completed synchronously.
I.e. we must always check for ERROR_IO_PENDING error before call `GetOverlappedResult()`.

See also #6747 as a case when such hung could happen.

**Comment by pavel-zotov** [comment]
:::: test details ::::
It seems that "engine may hung" - not yet fixed (although "GetOverlappedResult() should not be called" - solved for sure).
Sent letter to Vlad, 20.09.2021 01:08, waiting for reply.
