### ISSUE TITLE
Crash or hang while shutting down the replica database if segments are being applied

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#6975]
If the replicator is connected to the replica database and applying the change sets, and that database is shut down in the meantime, gfix may hang, or the server process may crash (and bugcheck may be reported in firebird.log).

**Comment by pavel-zotov** [comment]
::: test details :::
See test in dedicated folder ( functional/replication/ ), its name: 
shutdown-during-applying-segments-leads-to-crash.fbt
