### ISSUE TITLE
FB 4.0 - Windows x64 server installer installs an incomplete x86 client

### ISSUE THREAD

**Issue by abzalov** [FirebirdSQL/firebird#6979]
After installing the x64 server and trying to use the x86 library (\Firebird_4_0\WOW64\fbclient.dll) an error occurs - "Error loading plugin ChaCha
Module C:\Program Files\Firebird\Firebird_4_0\plugins/ChaCha exists but can not be loaded
unknown Win32 error 193".

If you copy the firebird.conf file from root FB directory to the WOW64 directory, the connection is established, but the x86 client still turns out to be incomplete, because there are no libraries of the corresponding client bitness, for example:
  - plugins\chacha.dll
  - ICU libraries
  - zlib library
  - possibly something else as described in issue [6943](https://github.com/FirebirdSQL/firebird/issues/6943)

**Comment by reevespaul** [comment]
This has already been reported in #6943 and will be fixed for the next release

**Comment by asfernandes** [comment]
#6943 talks about client-only install, while this one seems (my understand of problem description, not looked in packages) happens even in full install of x64 packages.

**Comment by abzalov** [comment]
Yes, this issue about a full installation of x64 server.

**Comment by reevespaul** [comment]
Ah, I see - sort of. From my perspective I see this as fixing the client install will fix the server install, too.  
But I'll reopen this for now as a reminder to check the server side too.

**Comment by mrx23dot** [comment]
Still a problem in Firebird-4.0.1.2692-0-x64.exe
![fail](https://user-images.githubusercontent.com/4163396/149916911-d0f785c4-e616-449b-ade1-f98d1c3cdada.jpg)

**Comment by arvanus** [comment]
Hello, looks like this issue exists in the latest setup, wow64\fbclient.dll tries to load \plugins\chacha.dll instead of wow64\plugins\chacha.dll

**Comment by reevespaul** [comment]
I am wondering if this a different bug?
The initial bug report was that the installer was not deploying the 32-bit plugin. Now it definitely does.
So is this still an installer bug or is it something else?
If it is installer related then we should re-open the bug. If not we need a new bug report.

**Comment by TommiPrami** [comment]
Not sure,  but sounds like there is a  attempt to connect to db with embedded. 

And having 32bit fbclient.dll in the syswow64 should be enough, for "normal " connection, or is in my Limited experience.

**Comment by arvanus** [comment]
Hi, I was connecting via localhost to employee.fdb
From my POV, looks like somehow fbclient.dll looks for firebird.conf, and from there it looks for chacha.dll, and not directly looking for chacha.dll.
I imagine that this behavior where designed to determine if chacha needed to be loaded, is it? But if it where to be loaded, why don't try to load first from local plugin folder instead of firebird.conf plugin folder?
Thanks

**Comment by aafemt** [comment]
Because it is the way to find a "root directory". The directory with firebird.conf is taken as one.

**Comment by arvanus** [comment]
Right.

Tbh I think it's a strange way to determine the priority of which DLL should be loaded from client.dll but I respect it.

I'll change Flamerobin behavior and set this folder as the lowest priority possible for x86 builds

Thank you.

**Comment by hvlad** [comment]
> Because it is the way to find a "root directory". The directory with firebird.conf is taken as one.

And I tald this few years ago: fbclient should not look for a `root` in the upper folder. At least on Windows.
This behavior is from the old times when fbclient was located in the `root\bin` folder in the Windows layout.
Time to fix it ?

**Comment by AlexPeshkoff** [comment]
On 10/12/23 16:02, Vlad Khorsun wrote:
>
>     Because it is the way to find a "root directory". The directory
>     with firebird.conf is taken as one.
>
> And I tald this few years ago: fbclient should not look for a |root| 
> in the upper folder. At least on Windows.
>

Certainly. Such change should had been applied >10 years ago, when we 
reworked layout on windows.

> This behavior is from the old times when fbclient was located in the 
> |root\bin| folder in the Windows layout.
> Time to fix it ?
>

Certainly. Surprise that it still does.
