### ISSUE TITLE
Verification of time's parts

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird#6990]
Firebird do not check TIME's parts.

As result, it may return bad data.

See attached image.

![image](https://user-images.githubusercontent.com/4594554/135972400-ad2318a3-e292-4c3d-a72d-6335e595a930.png)

**Comment by dmitry-lipetsk** [comment]
![image](https://user-images.githubusercontent.com/4594554/141674650-35555c9d-f079-483f-bbd1-42f85a7bfc48.png)

Firebird/Interbase ? :)

**Comment by hvlad** [comment]
> Firebird do not check TIME's parts.

Have something better reproducible than pictures ?

**Comment by asfernandes** [comment]
> Firebird do not check TIME's parts.
> 
> As result, it may return bad data.
> 
> See attached image.
> 

You are doing a CAST to VARCHAR. From what type?

**Comment by asfernandes** [comment]
What Firebird version?

**Comment by dmitry-lipetsk** [comment]
Hello.

First screenshot.

It was (customer) database with corrupted or wrong data - don't known.

ACTUAL_DATE_UP is TIMESTAMP.

---------------
See attached database with example of corruption - IBP_TEST_FB30_D3--issue6990.7z (FB3.0.8) 

[IBP_TEST_FB30_D3--issue6990.zip](https://github.com/FirebirdSQL/firebird/files/7534261/IBP_TEST_FB30_D3--issue6990.zip)

`select CAST(COL AS VARCHAR(32)) from TTT6`

returns 25:05:01.0000

![image](https://user-images.githubusercontent.com/4594554/141691419-5b0e392b-e87c-4b7c-8e37-e7f1ff7bc4ac.png)

`select COL||'' from TTT6`

returns 25:05:01.0000

`select COL-1 from TTT6`

returns 01:05:00.0000

`select COL-0 from TTT6`

returns 01:05:01

`select COL from TTT6`

returns error: "value exceeds the range for a valid time"

---------------
You are may reproduce this problem with (debug) FB3.0.8 and debugger.

1. CREATE TABLE TTT6 (COL TIME)

2. INSERT INTO TTT6 (COL) VALUES(CAST('23:00:00' as TIME))

- set breakpoint at
ISC_TIME NoThrowTimeStamp::encode_time(int hours, int minutes, int seconds, int fractions) throw()
- change arguments: hours to 24, minuntes to 5, secconds to 1.
- step next and **skip two checks of data for allow write wrong data into database**

3. select CAST(COL AS VARCHAR(32)) from TTT6

get string "25:05:01.0000"

![image](https://user-images.githubusercontent.com/4594554/141691117-c84abeb8-befa-49c3-91b4-64d312cad2c3.png)

**Comment by asfernandes** [comment]
Many things could happen with a corrupted database, and purposely corrupting things in the debugger does not make an issue valid.

**Comment by dyemanov** [comment]
Date/time is properly validated when the value is stored/assigned. It's not validated every time it's read. So if the invalid value appeared inside the database with some magic (corruption, UFO, whatever), it's not our problem any more.
