### ISSUE TITLE
Gbak removes database and backup files.

### ISSUE THREAD

**Issue by silvafabio** [FirebirdSQL/firebird#6999]
Hi Guys.

We are using the "gbak version LI-V2.5.9.27139 Firebird 2.5" on "CentOS Linux release 7.9.2009 (Core)".

After run a successful backup with the command: 
```
[fabio@fedora teste]$ /opt/firebird/bin/gbak -g -b -v -z 127.0.0.1:/storage/dados/teste/MYDB.FDB MYDB.fbk -user sysdba -password masterkey
```
We ends with two files as expected:
```
[fabio@fedora teste]$ ls
MYDB.fbk  MYDB.FDB
```
Then, for a mistake, instead of type and execute the command:
```
mv MYDB.FDB MYDB2.FDB 
```
We appended the desired command to the last successful backup command:
```
[fabio@fedora teste]$ /opt/firebird/bin/gbak -g -b -v -z 127.0.0.1:/storage/dados/teste/MYDB.FDB MYDB.fbk -user sysdba -password masterkeymv MYDB.FDB MYDB2.FDB
```
And the output was:
```
gbak:gbak version LI-V2.5.9.27139 Firebird 2.5
gbak:    Version(s) for database "127.0.0.1:/storage/dados/teste/MYDB.FDB"
	Firebird/linux AMD64 (access method), version "LI-V2.5.9.27139 Firebird 2.5"
	Firebird/linux AMD64 (remote server), version "LI-V2.5.9.27139 Firebird 2.5/tcp (fedora)/P12"
	Firebird/linux AMD64 (remote interface), version "LI-V2.5.9.27139 Firebird 2.5/tcp (fedora)/P12"
	on disk structure version 11.2
gbak:readied database 127.0.0.1:/storage/dados/teste/MYDB.FDB for backup
gbak: ERROR:size specification either missing or incorrect for file MYDB.fbk
gbak:Exiting before completion due to errors
```
After that, we listed the directory content and both files "MYDB.FDB" and "MYDB.fbk" were deleted.

We know the "db set" and "backup set" work with multiple files and that file extensions are merely formalities, but it could be helpfully and secure maybe to have some files header analises before run the effectively execute of command and if anything goes wrong, do not remove the already existing files. 

I don't know if you guys find that it is a bug and it could be ported to the 2.5 version. If it's a bug, but can't be back ported, please, investigate that in the master branch, as i found indices that this could be present in the current version.

https://github.com/FirebirdSQL/firebird/blob/799bca3ca5f9eb604433addc0f2b7cb3b6c07275/src/burp/burp.cpp

Thanks

**Comment by AlexPeshkoff** [comment]
Duplicates https://github.com/FirebirdSQL/firebird/pull/43, fix for it backported to B3_0_Release & B2_5_Release. Pay attention - I've changed a code in B2_5_Release too but it is unsupported and no new binaries builds are expected.
