### ISSUE TITLE
ISQL showing publication status

### ISSUE THREAD

**Issue by aafemt** [FirebirdSQL/firebird#7001]
It would be nice if ISQL command SHOW DATABASE displayed publication status for database and SHOW TABLE command - for particular table.

**Comment by dyemanov** [comment]
Added publication status into `SHOW DATABASE` and `SHOW TABLE` output. Also added support for `SHOW PUB[LICATIONS]` and `SHOW PUB[LICATION] <publication name>` command.

**Comment by pavel-zotov** [comment]
::: test issue :::
Test name: functional/basic/isql/test_08.py

NOTE: command 'show pub;' currently displays "There is no publications in this database".
This is expected. Detailed output of this command will be implemented later (discussed with dimitr).
