### ISSUE TITLE
Improve performance of STARTING WITH of fixed-byte charsets with insensitive collations

### ISSUE THREAD

**Issue by asfernandes** [FirebirdSQL/firebird#7038]
To process `STARTING WITH` with insensitive collations, it's first necessary to generate canonical bytes of the matching strings.

If the matching string is much greater than the pattern string, a time is wasted generating unneeded canonical bytes.

It's necessary to only generate canonical bytes for the initial substring with the same length of the pattern string.

Since INTL subsystem is not ready to accept truncated multi-byte strings, this improvement is being made only for fixed-byte character sets in this issue.

In my tests with matching strings of length 60 and pattern string with length 1, I see performance improvement of ~30%.

Test:

```
execute block
as
    declare p varchar(1) character set win1252 collate win_ptbr = 'x';
    declare s varchar(60) character set win1252 collate win_ptbr = 'x12345678901234567890123456789012345678901234567890123456789';
    declare n integer = 0;
    declare b boolean;
begin
    while (n < 1000000)
    do
    begin
        b = s starting with p;
        n = n + 1;
    end
end!
```

**Comment by asfernandes** [comment]
Updated performance improvement verified in test after changes in the implementation.

**Comment by asfernandes** [comment]
After small changes in INTL API description for `canonical` function and small changes in engine I verified more than 50% improvement with UTF8 and UNICODE_CI in the same test, so I'm changing this issue to also optimize multi-byte character sets.

**Comment by pavel-zotov** [comment]
Currently implemented only for WINDOWS: package 'psutil' can not be installed on Python 2.7 when it is running on Linux (Debian).
