### ISSUE TITLE
Make ability to add comment to mapping ('COMMENT ON MAPPING ... IS ...')

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7046]
Ticket was created after discussion with Alex.
Currently following script:
```
create or alter mapping lmap using plugin srp from user foo to user ltost;
comment on mapping lmap is 'test mapping,  do not delete';
```
-- issues:
```
Invalid token.
Dynamic SQL Error.
SQL error code = -104.
Token unknown - line 1, column 12.
mapping.
```

**Comment by AlexPeshkoff** [comment]
No backporting supposed for this issue - it requires new ODS, at least minor (i.e. 13.1 in FB5).

**Comment by mrotteveel** [comment]
@AlexPeshkoff I assume you meant Firebird 4 instead of Firebird 5 there

**Comment by pavel-zotov** [comment]
QA: test will be adjusted after issue about visibility of comments to mapping in 'isql -x' result will be fixed.

**Comment by mrotteveel** [comment]
Shouldn't this be reopened while this finding is pending?

**Comment by pavel-zotov** [comment]
QA: added check to see comments on mapping in extracted metadata. Text of comment intentionally was replaced to non-ascii.
