### ISSUE TITLE
Races between transactions on the primary side may cause update conflicts while applying journals to the replica

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#7052]
Currently there may be a gap between marking the transaction as committed in TIP and inside the journal. In the meanwhile, other transactions may already see the first transaction as committed and write something to the journal that may later conflict with the first transaction. The more reliable order would be to write the journal first (write-ahead-logging).

**Comment by pavel-zotov** [comment]
Issue can be reproduced under heavy workload in OLTP-EMUL but not in usual way. Discussed with dimitr, letter 09.12.2021 17:46.
