### ISSUE TITLE
Fetching from a scrollable cursor may overwrite user-specified buffer and corrupt memory

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#7056]
Every fetch from a scrollable cursor returns 2-8 bytes longer message than the client expects. Sometimes this may be harmless, but sometimes it may corrupt application memory and thus cause various crashes.

**Comment by pavel-zotov** [comment]
Test will be added after migration to pytest/firebird-driver framework.

**Comment by ilya071294** [comment]
Will FB3 be fixed?

**Comment by dyemanov** [comment]
It requires more changes for backporting, thus was postponed. But if there's a demand to have this fix in v3, I will do it during this weekend.
