### ISSUE TITLE
B2_5_Release on debian 11.1

### ISSUE THREAD

**Issue by denbip** [FirebirdSQL/firebird#7058]
Hello! I've built B2_5_Release tree on debian 11.1, classic server, all seems to be working except when I try write (reading is working) something with user SYSDBA I get an error SQLCode: -902, SQLState: 08006, GDSCode: 335544726, and there are no any messages in logs

**Comment by denbip** [comment]
I've also test it on debian 9 - the same problem

**Comment by hvlad** [comment]
335544726 is error code `isc_net_read_err`
I.e. there was network error when reading. 
Check if Firebird process was not crashed. If yes, provide us with stack trace obtained from coredump.
Note, Firebird 2.5 is relatively old release and more current versions is recommended to use.

**Comment by denbip** [comment]
I've found a reason, the problem was on my UDF library, I've forgot link it with rt library, through gdb I've got an exit error 0177 which probably means exit code 127 'command not found' that give me a clue. Now it works! @hvlad Thank you for reply! And why I should use older version, because of difficulty of transporting into newer versions. First of all I use many UDF functions, which are "almost deprecated", then fields with required timezone - I use my own mechanism, so don't want to change it...and others details...wish the newest FB works compatibility 2.5

**Comment by mrotteveel** [comment]
> wish the newest FB works compatibility 2.5

You can use `DataTypeCompatibility = 2.5` in Firebird 4.0 to ensure only types are returned that are available in Firebird 2.5. Also, if you run into problems with newer versions, please ask about it on [firebird-support](https://groups.google.com/g/firebird-support)

**Comment by denbip** [comment]
@mrotteveel Hi! In this case CURRENT_TIMESTAMP for example will return the old format?

**Comment by AlexPeshkoff** [comment]
On 12/3/21 11:25, denbip wrote:
>
> @mrotteveel <https://github.com/mrotteveel> Hi! In this case 
> CURRENT_TIMESTAMP for example will return the old format?
>

yes

**Comment by denbip** [comment]
Thanks! Then I will try to work with the newest version
