### ISSUE TITLE
Return dotted field names

### ISSUE THREAD

**Issue by zedalaye** [FirebirdSQL/firebird#7059]
Is there something in the SQL specs or a Firebird functional limitation that forbids returned field names to embed "." ?

Would be super handy to map returned values into "objects".

In the following case, if returned fields names were 'OLD.CODE', 'NEW.CODE', instead of 'CODE' and 'CONSTANT' (all "NEW" fields are returned as "CONSTANT" by the way), it would be easier to map fields into a "NEW" and "OLD" hashmaps (for instance, to compare and log what changed or what was inserted if OLD fields are NULL)

```sql
update or insert into STORES (UID, CODE, NAME, ADDRESS, POSTCODE, CITY, COUNTRY, ...)
values (?,?,?,?,?,?,?,...)
matching (UID)
returning UID,
  OLD.CODE, NEW.CODE,
  OLD.NAME, NEW.NAME,
  OLD.ADDRESS, NEW.ADDRESS,
  OLD.POSTCODE, NEW.POSTCODE,
  OLD.CITY, NEW.CITY,
  OLD.COUNTRY, NEW.COUNTRY,
  ...
``` 

Instead, I have to do that:

```sql
update or insert into STORES (UID, CODE, NAME, ADDRESS, POSTCODE, CITY, COUNTRY, ...)
values (?,?,?,?,?,?,?,...)
matching (UID)
returning UID,
  OLD.CODE as OLD_CODE, NEW.CODE as NEW_CODE,
  OLD.NAME as OLD_NAME, NEW.NAME as NEW_NAME,
  OLD.ADDRESS as OLD_ADDRESS, NEW.ADDRESS as NEW_ADDRESS,
  OLD.POSTCODE as OLD_POSTCODE, NEW.POSTCODE as NEW_POSTCODE,
  OLD.CITY as OLD_CITY, NEW.CITY as NEW_CITY,
  OLD.COUNTRY as OLD_COUNTRY, NEW.COUNTRY as NEW_COUNTRY,
  ...
``` 

This is hard to read and error-prone in Delphi as there is no syntax highlighting within (constant) strings.

**Comment by aafemt** [comment]
Dot is a reserved symbol so it can be used in an identifier only if the identifier is delimited:
`OLD.CODE as "OLD.CODE"`

**Comment by zedalaye** [comment]
It works exactly as expected. Thank you.
