### ISSUE TITLE
Deadlock when execute test for CORE-4337

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7060]
Ticked created after discussion with Alex.
Detected on LI-5.0.0.328, server mode = Super.
Server process does not keep opened any .fdb file but execution hangs.

FB dump, stack trace and snapshot were stored in:

https://drive.google.com/drive/folders/1ygATSATHs64Aw9CenXvEIV_5tGBrla4u?usp=sharing

Stack trace is also in attached zip here.
[gdb-firebird-hanged-on-core_4337.fbt.txt.zip](https://github.com/FirebirdSQL/firebird/files/7649401/gdb-firebird-hanged-on-core_4337.fbt.txt.zip)

**Comment by AlexPeshkoff** [comment]
@pavel-zotov no test needed - races might happen for any service invocation with running thread, but with very low possibility
