### ISSUE TITLE
Improvement of IProvider methods exception handling

### ISSUE THREAD

**Issue by aafemt** [FirebirdSQL/firebird#7063]
attachDatabase(), createDatabase() and attachServiceManager() CLOOP envelopes would better return isc_unavailable as a primary error code if an unhandled exception is caught in provider implementation object.

**Comment by AlexPeshkoff** [comment]
In order to let yvalve proceed to next provider?

**Comment by aafemt** [comment]
Yes.

**Comment by AlexPeshkoff** [comment]
May be better change rules of provider selection by yvalve?

**Comment by aafemt** [comment]
After a good thinking the issue should be closed as pointless.
