### ISSUE TITLE
Linear regression functions aren't implemented correctly

### ISSUE THREAD

**Issue by lukaseder** [FirebirdSQL/firebird#7064]
Many of our integration tests seem to fail when we upgrade our own emulation of linear regression functions to Firebird 4.0.0's native support.

Try this, for example:

```sql
select regr_avgx(a, b)
from (
  select 1, 1 from RDB$DATABASE union all
  select 2, 1 from RDB$DATABASE union all
  select 3, 2 from RDB$DATABASE union all
  select 4, 2 from RDB$DATABASE
) t (a, b);
```

Firebird 4.0 produces the value `4`, when it should produce `1.5` like these database products:

- [Db2: 1.5](https://dbfiddle.uk/?rdbms=db2_11.1&fiddle=9d1c94ab18b1f6f5e4f4a604592d8efd)
- [Oracle: 1.5](https://dbfiddle.uk/?rdbms=oracle_21&fiddle=a3f274f2940e23ae9fd04ce87f09a420)
- [PostgreSQL: 1.5](https://dbfiddle.uk/?rdbms=postgres_14&fiddle=9d1c94ab18b1f6f5e4f4a604592d8efd)

Maybe, this gives you a hint about the bug?

```sql
select regr_avgx(a, b), regr_avgx(cast(a as bigint), cast(b as bigint))
from (
  select 1, 1 from RDB$DATABASE union all
  select 2, 1 from RDB$DATABASE union all
  select 3, 2 from RDB$DATABASE union all
  select 4, 2 from RDB$DATABASE
) t (a, b);

select regr_avgx(cast(a as bigint), cast(b as bigint)), regr_avgx(a, b)
from (
  select 1, 1 from RDB$DATABASE union all
  select 2, 1 from RDB$DATABASE union all
  select 3, 2 from RDB$DATABASE union all
  select 4, 2 from RDB$DATABASE
) t (a, b);
```

In both cases, I'm getting this, now:

```
|REGR_AVGX|REGR_AVGX|
|---------|---------|
|4.0      |0        |
```

**Comment by AlexPeshkoff** [comment]
On 12/10/21 17:29, Lukas Eder wrote:
>
> Many of our integration tests seem to fail when we upgrade our own 
> emulation of linear regression functions to Firebird 4.0.0's native 
> support.
>
> Try this, for example:
>
> select  regr_avgx(a, b)
> from  (
>    select  1,1  from  RDB$DATABASEunion all
>    select  2,1  from  RDB$DATABASEunion all
>    select  3,2  from  RDB$DATABASEunion all
>    select  4,2  from  RDB$DATABASE
> ) t (a, b);
>
> Firebird 4.0 produces the value |4|, when it should produce |1.5| like 
> these database products:
>
>   * Db2: 1.5
>     <https://dbfiddle.uk/?rdbms=db2_11.1&fiddle=9d1c94ab18b1f6f5e4f4a604592d8efd>
>   * Oracle: 1.5
>     <https://dbfiddle.uk/?rdbms=oracle_21&fiddle=a3f274f2940e23ae9fd04ce87f09a420>
>   * PostgreSQL: 1.5
>     <https://dbfiddle.uk/?rdbms=postgres_14&fiddle=9d1c94ab18b1f6f5e4f4a604592d8efd>
>

Not rperoduced with current v4.
Please try latest snapshot.

# ./isql -z employee
ISQL Version: LI-V4.0.1.2673-dev Firebird 4.0
Server version:
LI-V4.0.1.2673-dev Firebird 4.0
Database: employee, User: SYSDBA
SQL> select regr_avgx(a, b)
from (
   select 1, 1 from RDB$DATABASE union all
   select 2, 1 from RDB$DATABASE union all
   select 3, 2 from RDB$DATABASE union all
   select 4, 2 from RDB$DATABASE
) t (a, b);

               REGR_AVGX
=======================
       1.500000000000000

SQL>

**Comment by asfernandes** [comment]
What platform (hardware and OS)?

**Comment by lukaseder** [comment]
That's great to know, thanks for the hint. I'm using this docker image here: https://hub.docker.com/r/jacobalberty/firebird. It's using version 4.0. I'm afraid, I can't really allocate the time to try upgrading until 4.0.1 is released to that docker hub, but if it's already fixed, all the better.

**Comment by asfernandes** [comment]
I've tested all latest point releases and found no problem.

But I don't found a fix after these functions were introduced.

**Comment by mrotteveel** [comment]
I just tried Firebird-4.0.0.2496-1-x64 and Firebird-4.0.1.2680-0_x64 on Windows 11, and the query returns 6.776288196345199e-318, so definitely something fishy is going on.

**Comment by lukaseder** [comment]
Yeah, sorry, should have mentioned, I'm using docker on windows too, Microsoft Windows [Version 10.0.22000.318]

**Comment by mrotteveel** [comment]
To be clear, I tried with the Windows builds.

**Comment by asfernandes** [comment]
Reproduced in release build.

**Comment by asfernandes** [comment]
v3 is not affected.

**Comment by mrotteveel** [comment]
Tested in Firebird-4.0.1.2682-0_x64 on Windows 10, and I can confirm it's fixed.
