### ISSUE TITLE
Connection hangs after delivery of 256GB of data

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7065]
ChaCha wire encryption, used by default since FB4, is using 32-bit counter. When counter overflows secure packets delivery becomes impossible without reconnect.

**Comment by AlexPeshkoff** [comment]
Added configuration parameter CounterSize (in ChaCha.conf). Setting it to 32 restores legacy behavior, by default 64-bit counter is used making it possible to exchange with very big volume of data, practically unlimited.

**Comment by mrotteveel** [comment]
This is not an appropriate fix. The client has no way to know to know the counter size the server expects. In addition, this is no longer ChaCha20 as defined in [RFC-7539](https://datatracker.ietf.org/doc/html/rfc7539#section-2.4), which makes it harder to support. If a bigger counter is needed, then a **new** variant of ChaCha needs to be added with a separate name, to distinguish it from the standard 32-bit counter variant.

**Comment by AlexPeshkoff** [comment]
The client has a way to know the counter size the server expects. IV (nonce) is sent to client, and depending on it's size client does know what counter size should be used. 

What about use of .conf for choosing chacha variant: we are not the only one who met this problem, see for example https://libsodium.gitbook.io/doc/advanced/stream_ciphers/chacha20. Pay attention - And I disagree with you about "harder to support" - having single plugin with reasonable parameter much simpler to support compared with duplicated copies of same code.

**Comment by AlexPeshkoff** [comment]
> Java only supports ... ChaCha20 with 32-bit counter

That's what you could say at once instead of loosing so many words...  Will rework - never new that original for one people variant is not supported by others :-)

**Comment by aafemt** [comment]
May I suggest to leave ChaCha as is and just move it deeper in configuration so rc4 is used by default with added warning that ChaCha while is "more secure" cannot be used for long lasting connections?

**Comment by asfernandes** [comment]
Then ChaCha must be deprecated. I see no point in have this limitation.

**Comment by AlexPeshkoff** [comment]
@asfernandes - chacha with 32-bit counter is IETF recommended solution and looks like the only one supported by java.
I know that RC4 is quite enough for us (with our use of secure key it has no security problems), but I can't explain it to some users. I.e. chacha is 'must be' to avoid loosing such users. What's cool is that now (with Mark's suggestion implemented) our default configuration has no 256Gb limitation.

@mrotteveel I've checked current default configuration for compatibility with FB4.0.0 client but additional check with jaybird is also welcome.

**Comment by mrotteveel** [comment]
On 2021-12-13 12:18, Adriano dos Santos Fernandes wrote:
> Then ChaCha must be deprecated. I see no point in have this
> limitation.

The counter limitation could also be "solved" by extending the protocol 
to allow the wire protocol encryption to be re-keyed (either by changing 
key + nonce, or maybe just changing nonce), but this brings additional 
challenges and complexity.

Mark

**Comment by einar-hjortdal** [comment]
Is there any update on this matter? 
I'm developing a driver for the V language [here](https://github.com/einar-hjortdal/firebird), the current solution to this issue requires time investment to develop and maintain a custom implementation of chacha20 with a 64bit counter in order to please the firebird server.
I understand that rc4 is a viable option, but the custom chacha20 solution feels almost malicious: the standard introduces connections hanging, the "default" requires a custom implementation.

**Comment by mrotteveel** [comment]
Or more specifically, ChaCha with 64-bit counter is the ["original" ChaCha cipher](https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant), while the one with 32-bit counter is the ChaCha variant standardized by IETF in [RFC 7539](https://datatracker.ietf.org/doc/html/rfc7539).

**Comment by einar-hjortdal** [comment]
The main issue is that this chacha64 cipher is somewhat of a custom implementation as it is not standardized by IETF, and its implementation may or may not be available as a third party library in languages.
Unfortunately, it is not available in the language I am using. The only options I have are rc4 and IETF RFC 7539 chacha20, and this leaves me the following options.
- Implement chacha64 in the language I am using (best option but requires effort)
- use chacha20 (and introduce hanging connections)
- use rc4 (alright)
- no crypto (not a real option)

> if Firebird would simply switch to using TLS.

That would be great.

**Comment by mrotteveel** [comment]
The ChaCha64 cipher is not really a "custom" implementation, it is the original ChaCha cipher *before* IETF adopted (and adapted) it for RFC 7539, but yes, the RFC 7539 is more likely to be easily available (I had a similar problem in Java).
