### ISSUE TITLE
No archlinux support 

### ISSUE THREAD

**Issue by devlulcas** [FirebirdSQL/firebird#7079]
I'm using Manjaro, an Arch distro and the AUR package for firebird is deprecated: https://aur.archlinux.org/packages/firebird-superserver/ (firebird-superserver 2.5.9.27139-1)

Do you plan to support archlinux or create a PKGBUILD for version 3.0?

**Comment by AlexPeshkoff** [comment]
We (firebird project) do not support distro-specific package managers, this should be done by distro makers. We have rather universal sh installer, which runs on many various linuxes. It may be downloaded here: http://firebirdsql.org/en/server-packages/. If you have problems with it on archlinux feel free to re-open an issue.
