### ISSUE TITLE
Creating unique constraints on MacOS fails on larger tables

### ISSUE THREAD

**Issue by haanerg** [FirebirdSQL/firebird#7084]
I've discovered something strange, seemingly isolated to MacOS, but independent of CPU architecture.

Creating unique constraints on medium sized tables (>2^17 records) fails and the connection is terminated. This applies to both Intel and AppleM1 chips, FireBird versions 3.0.7 and 3.0.8 tested on both platforms. It, of course, applies to indices (unique), primary keys and the works. I discovered it by trying to restore a database (gbak) which failed while activating indices.

Test script attached.
[unique_test.sql.zip](https://github.com/FirebirdSQL/firebird/files/7762792/unique_test.sql.zip)

power(2, 18) fails
power(2, 17) succeeds

There is nothing in firebird.log. isql doesn't give any error message. IBExpert shows: 
SQLCODE: -902
SQLSTATE: 08006
GDSCODE: 335544726
Connection will be closed immediately 

So not very many useful hints, I'm afraid.

**Comment by asfernandes** [comment]
Does the server crashes?

Can you build Firebird with `--enable-developer` and run the server with gdb and give us the stack trace?

**Comment by haanerg** [comment]
> Does the server crashes?
Server does indeed crash. But nothing else is available in firebird.log.
> Can you build Firebird with `--enable-developer` and run the server with gdb and give us the stack trace?
I'll do that

**Comment by haanerg** [comment]
gdb isn't available on M1, but I've attached the crash output from Console and lldb
[firebird_crash.log](https://github.com/FirebirdSQL/firebird/files/7762968/firebird_crash.log)
[lldb.log](https://github.com/FirebirdSQL/firebird/files/7762969/lldb.log)

**Comment by asfernandes** [comment]
Reproduced and verifying.
