### ISSUE TITLE
Database downgrade via gbak may be broken

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#7087]
The common downgrade path is to make a backup using older (e.g. v3.0) _gbak_ connected to a newer (e.g. v4.0) FB server. However, it was also possible to make a backup using newer _gbak_ and restore it using older _gbak_. It may not always work, but usually it does. In this case, _gbak_ ignores any unknown attributes (they correspond to the system tables / columns added in newer versions) like as they would not exist. For that purpose, every backup attribute has its length which allows it to be skipped safely. However, new functions `put_boolean() / get_boolean()` in backup.epp / restore.epp break this rule and do not store the length byte. If such a v4 backup is being restored by v3 _gbak_, it cannot parse the backup file and fails during restore.

The good thing is that booleans inside backups are currently used only for SQL SECURITY columns which is commonly NULL for newly created and migrated databases. Only those already using SQL SECURITY options explicitly may be affected, but they're unlikely to be able to downgrade easily due to different security logic implied by SQL SECURITY DEFINER, for example.

But we may have other booleans added to _gbak_ in v5 or later versions, thus making this issue more visible. Therefore I suggest to fix the issue now:

- deprecate existing boolean attributes (currently all `att_*_sql_security`, there are six of them), and perhaps rename them to avoid their usage intentionally
- add support for them into Firebird 3, which will simply ignore them with `get_skip(tdgbl, 1)`
- introduce new properly encoded (with length byte) attributes for the SQL SECURITY columns
- fix Firebird 4 to decode both deprecated and new attributes, but store only new attributes

**Comment by aafemt** [comment]
> However, it was also possible to make a backup using newer /gbak/ and restore it 
> using older /gbak/. It may not always work, but usually it does.

AFAIK it never worked because older gbak refused backup file of higher (unknown) 
version.

**Comment by dyemanov** [comment]
Can we be sure the backup format is always increased when new tags are introduced? Similarly to DPB, this is not really necessary.

**Comment by dyemanov** [comment]
Given that FB4 has backup version 11, such a downgrade should be impossible. Sorry for a false alarm. So in fact this issue only affects migration between official FB builds and forks that use the same backup format version. Not sure whether it's critical to solve. And we need to decide whether following the original backup format is important (and thus whether it deserves fixing regardless of the migration question).

**Comment by AlexPeshkoff** [comment]
On 12/24/21 13:41, Dmitry Yemanov wrote:
>
> Given that FB4 has backup version 11, such a downgrade should be 
> impossible. Sorry for a false alarm. So in fact this issue only 
> affects migration between official FB builds and forks that use the 
> same backup format version. Not sure whether it's critical to solve. 
> And we need to decide whether following the original backup format is 
> important (and thus whether it deserves fixing regardless of the 
> migration question).
>

Format should be fixed. Or we finally get one more SPB-like mess.

**Comment by aafemt** [comment]
Firebird 4.0.1 and 4.0 has the same ODS. There is no need in gbak to migrate between them.

**Comment by romansimakov** [comment]
Be more accurate please) I asked "Is it OK?". Your answer is yes, isnt' it?

**Comment by aafemt** [comment]
My answer is "increasing version of backup and making such restore impossible is the better solution" so my answer for the question "is it OK?" the answer is "No".

**Comment by dyemanov** [comment]
I think this should be OK.

**Comment by AlexPeshkoff** [comment]
On 1/12/22 19:08, Dmitry Yemanov wrote:
>
> I think this should be OK.
>
+1

**Comment by romansimakov** [comment]
> I think this should be OK.

Increase version of backup?

**Comment by dyemanov** [comment]
Nope, for me OK is to leave v4.0.0/4.0.1 without ability to restore booleans from v4.0.2 (they will be skipped), but preserve the ability to restore v4.0.2 backups in general (due to the same backup version).

**Comment by AlexPeshkoff** [comment]
On 1/12/22 19:57, Roman Simakov wrote:
>
>     I think this should be OK.
>
> Increase version of backup?
>

I've meant suggested trick with new attribute skippable by old backup 
version.
