### ISSUE TITLE
Firebird 4.0.1 Sequence Increment Failed

### ISSUE THREAD

**Issue by diegoverdan** [FirebirdSQL/firebird#7089]
Firebird 4.0.1 Sequence Increment Failed:
[Sequence.zip](https://github.com/FirebirdSQL/firebird/files/7794091/Sequence.zip)

After testing migrating from Firebird 2.5 to Firebird 4.0.1 I noticed that sequences/generators are not incrementing as determined as increment in sequence creation. Attached are prints of attempted increment (at 1) which actually only works at -1 the increment value.
Example:
ALTER SEQUENCE GEN_ID_VENDA RESTART WITH 32915 INCREMENT BY 1;
Instead of setting the value to 32915 the value goes to 32914.

In Firebird 2.5 and 3.0.8 it works perfectly.

**Comment by asfernandes** [comment]
It's correct because the next increment will return 32915.

There is also changes to RESTART WITH here https://github.com/FirebirdSQL/firebird/issues/6625

**Comment by diegoverdan** [comment]
@asfernandes Adriano, eu já havia verificado a questão #6625 mas como disse, apesar de mandar incrementar para um valor via código, o valor que realmente fica é o VALOR-1.

**Comment by asfernandes** [comment]
> @asfernandes Adriano, eu já havia verificado a questão #6625 mas como disse, apesar de mandar incrementar para um valor via código, o valor que realmente fica é o VALOR-1.

Mande um teste com script mostrando o que está errado ou diferente.

**Comment by mrotteveel** [comment]
@diegoverdan @asfernandes Please use English in the tracker.

**Comment by mrotteveel** [comment]
This change of behaviour is explicitly documented in the release notes, chapter _Compatibility Issues_, section [Starting Value of Sequences](https://www.firebirdsql.org/file/documentation/release_notes/html/en/4_0/rlsnotes40.html#rnfb40-compat-sql-sequence-start-value). See also #6334, #6615 and #4671

**Comment by mlzampier** [comment]
Example:

	CREATE SEQUENCE GEN_ACOES START WITH 0 INCREMENT BY 1; 

	Setting value with ALTER SEQUENCE:
		ALTER SEQUENCE GEN_ACOES RESTART WITH 100
	
	Checking:
		select gen_id(GEN_ACOES,0) from RDB$DATABASE
		> Retorno: 99
		
	Setting value with SET GENERATOR:
		SET GENERATOR GEN_ACOES TO 100

	Checking:
		select gen_id(GEN_ACOES,0) from RDB$DATABASE
		> Retorno: 100

Not contradictory? It seems to be a bug

**Comment by dyemanov** [comment]
Behaviour of `ALTER SEQUENCE` was changed to being standard-compliant. `RESTART WITH X` means that the next value (retrieved using `NEXT VALUE FOR` function) must be `X`. `SET GENERATOR` is a non-standard extension and thus it preserves its historical behaviour. It's not recommended to mix both old-style and new-style sequence SQL together to avoid inconsistencies.
