### ISSUE TITLE
Firebird 3.0 Database Corruption

### ISSUE THREAD

**Issue by Anoop-Ajayan95** [FirebirdSQL/firebird#7095]
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/97387455/148680208-0fbb2942-0218-485b-842c-d67d05a90628.png">
Database is corrupted and we are able to work with the database. And it was realized after a long time. Now we are not able to perform the database restore process with Entire data and Metadata also. We tried all the normal mechanism of Database recovery and Tried with IB Surgeon tool also. But Still the problem is unresolved

**Comment by mrotteveel** [comment]
This issue tracker is for requesting new features or reporting reproducible bugs.

For support questions, please ask on [firebird-support](https://groups.google.com/g/firebird-support), or contact one of the companies offering professional [support](https://firebirdsql.org/en/support/).
