### ISSUE TITLE
FB 4.0 - Client install is missing files

### ISSUE THREAD

**Issue by lwennekers** [FirebirdSQL/firebird#7096]
The installation of a client is missing the fbclient.dll and possibly gds32.dll in the Windows\System32 directory. During the x64 installation those files are missing also in Windows\SysWOW64 directory.

**Comment by mrotteveel** [comment]
I am able to reproduce this. 

The workaround is - from a command prompt run as administrator - to run `instclient i f` (from the 64-bit install root for 64-bit, from WOW64 directory for the 32-bit client). Use `instclient i g` if you also need `gds32.dll`.

However, note that the 64-bit installer should install the files into %WINDIR%\System32, and the 32-bit installer on a 64-bit system installs it into %WINDIR%\SysWOW64.

**Comment by mrotteveel** [comment]
Interestingly enough, when the 64-bit installer is used to install a minimal client (which didn't actually install it in System32), when you subsequently install it manually, and then uninstall Firebird again, it will remove `fbclient.dll` from the System32 directory.

**Comment by lwennekers** [comment]
Thanks for your response and solution. It works :). I'm however hoping that the client setup is going to be modified where the copying of those files is going to be asked like in the server setup.

**Comment by mrotteveel** [comment]
@lwennekers I understand, and it will be looked at by the maintainer of the Windows installer. My comments were to provide confirmation and a workaround.

**Comment by reevespaul** [comment]
Can you confirm this problem exists in 4.0.1 ?

**Comment by lwennekers** [comment]
I can confirm that it exists in 4.0.1

**Comment by mrx23dot** [comment]
Just finished Firebird-4.0.1.2692-0-x64.exe installation, there isn't anymore an option to copy CLIENT to system dir.
![2022-01-18 12_19_11-Setup - Firebird 4 0 1 2692 (x64)](https://user-images.githubusercontent.com/4163396/149936539-7557a3ca-e7ab-4395-9606-7784ef09c52c.jpg)

fbclient.dll is not copied to:
- C:\Windows\System32
- C:\Windows\SysWOW64

Also location of DLLs is misleading:
- C:\Program Files\Firebird\Firebird_4_0\fbclient.dll is 64bit
- C:\Program Files\Firebird\Firebird_4_0\**WOW64**\fbclient.dll is **32bit**

Python lib FBD has a hard time finding the correct library, thus doesn't work out of the box.
64bit dll should be automatically copied to C:\Windows\SysWOW64

**Comment by aafemt** [comment]
Nothing is misleading here "WOW64" is an abbreviation for "Windows on Windows 64" i.e. emulation of 32 bits environment on 64 bits system.

**Comment by mrx23dot** [comment]
Ok, but it should still install the correct file to the correct location.

**Comment by aafemt** [comment]
SysWOW64 *is* the correct location for 32 bits client library and system32 is *incorrect* location for it.

**Comment by mrx23dot** [comment]
Correct.
https://www.connx.com/products/connx/CONNX%2013.5%20UserGuide/location_of_dlls_on_64bit_windows.htm#:~:text=Under%2032bit%20windows%2C%20this%20location,is%20C%3A%5CWINDOWS%5CSYSTEM32.

So  C:\Program Files\Firebird\Firebird_4_0\fbclient.dll should be automatically copied to C:\Windows\System32

**Comment by aafemt** [comment]
IMHO - yes, but core developers prefer not to blow up system directories.

**Comment by mrx23dot** [comment]
There was an option for that in older versions. If something doesn't work out of the box users will just move to MySQL.

**Comment by asfernandes** [comment]
Some files are located based on the fbclient.dll path.

I don't think everything (like firebird.msg, firebird.conf, plugins directory) should be in system directory.

**Comment by asfernandes** [comment]
`C:\Windows\System32\plugins`?

What if another software also want to put its `plugins` directory in system32? This does not make sense for me.

I do not know how good is symbolic links today in Windows, but if they are good it would make much more sense to create a symbolic link.

Or, just use what many others software do. Add they path to PATH environment variable.

**Comment by aafemt** [comment]
PATH on windows is the same for 32 and 64 bit applications so it won't work.
And yes, just "plugins" may seem weird so, perhaps, an attempt to use "firebird_plugins" should be added to plugins module loader.

**Comment by lwennekers** [comment]
Also the following command-line is failing to install the dll's:
Firebird-4.0.1.2692-0-x64.exe /SP /VERYSILENT /COMPONENTS="ServerComponent\ClassicServerComponent,ServerComponent,DevAdminComponent,ClientComponent" /MERGETASKS="SuperClassicTask,UseServiceTask,CopyFbClientAsGds32Task

The command-line with the installation of Firebird-4.0.0.xxxx was working correctly, both dll's were installed in the correct location
