### ISSUE TITLE
DatabaseAccess None fails

### ISSUE THREAD

**Issue by mrx23dot** [FirebirdSQL/firebird#7104]
Installed Firebird-4.0.1.2692-0.amd64.tar.gz on Debian10

Restricted access only via aliases:
```
sudo nano /opt/firebird/firebird.conf        
DatabaseAccess = None  #  If you choose 'None', then only databases listed in databases.conf can be attached.
```
rebooted service
prepared database:
`./registerDatabase.sh ethereum.fdb /DB/ethereum.fdb`

it shows up in /opt/firebird/databases.conf
```
# Live Databases:
ethereum = /DB/ethereum.fdb
```

trying to create DB fails:
```
SQL> create database 'localhost:ethereum.fdb';
Statement failed, SQLSTATE = 28000
Use of database at location /tmp/ethereum.fdb is not allowed by server configuration
```

Not sure where /tmp/ comes from, I requested ethereum.fdb which should resolve to /DB/ethereum.fdb
Same happens if I prepare database before restricting DatabaseAccess, but then it happens on connection.

**Comment by aafemt** [comment]
"ethereum" is not the same as "ethereum.fdb" you know...

**Comment by hvlad** [comment]
Could you, please, ask such questions in support list first ?
Note, registered name is "ethereum" while you attempt to create "ethereum.fdb".
