### ISSUE TITLE
Wrong detection of must-be-delimited user names

### ISSUE THREAD

**Issue by aafemt** [FirebirdSQL/firebird#7106]
The routine which uppercase user name during attachDatabase etc doesn't strictly follow rules for SQL identifiers when detect user names that should be delimited. As the result user with names like `test-user` cannot connect without proper delimiting them.
Also it silently ignores delimiting errors trimming the rest of string. For example `"abc"def` is transformed to `abc`.

**Comment by aafemt** [comment]
I think we should follow SQL standard and abandon dialect 1.

**Comment by AlexPeshkoff** [comment]
Will get into fb3 after 3.0.9 release.
