### ISSUE TITLE
Content of DB file can be overwritten with zero characters in some (rare) cases.

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7109]
This ticket was created after discussion with Vlad.
Database file can be "nullified", i.e. its content can become filled with chr(0)  chars.
Only Windows FB 3.0.6 / 3.0.7 (both - in SS mode) are affected, and only when some attachment is established exactly at the moment with DB file is increased.
No such problem on Linux.
No such problem on Windows if we use special builds of FB 3.x with async IO with FILE_FLAG_OVERLAPPED.
Also, no such problem when work in SC/CS, or if FB major version is 4.x

**Comment by omachtandras** [comment]
Pavel, is it 100% sure that 3.0.8 is not affected?

**Comment by hvlad** [comment]
Bug was introduced at 3.0.6 and affected Windows SS only.
