### ISSUE TITLE
error "expression evaluation not supported - Arguments for BIN_AND must be integral types or NUMERIC/DECIMAL without scale"

### ISSUE THREAD

**Issue by VerbovenBerg** [FirebirdSQL/firebird#7111]
Test case:

select BIN_and(4,power(2,2)) from RDB$DATABASE; 

FB 4.0 V4.0.1.2692 (Client SQL dialect is set to: 3 and database SQL dialect is: 3): 
error "expression evaluation not supported 
- Arguments for BIN_AND must be integral types or NUMERIC/DECIMAL without scale" 

In FB 2.5.9 it works correctly

**Comment by asfernandes** [comment]
I have tested this in 2.5 and it gives the same error.

Maybe you have an UDF on this database?

**Comment by VerbovenBerg** [comment]
@asfernandes 
In the 2.5 database there is indeed a UDF :
_DECLARE EXTERNAL FUNCTION "BIN_AND"
integer, integer
RETURNS integer BY VALUE 
ENTRY_POINT 'IB_UDF_bin_and'
MODULE_NAME 'ib_udf';_

**Comment by asfernandes** [comment]
So you were using an UDF, not the builtin function.

The builtin function didn't changed the behavior.

**Comment by mrotteveel** [comment]
I don't think this limitation should exist. I agree it is not a regression, but I think it should be fixed.

**Comment by aafemt** [comment]
By documentation return type of POWER() function is DOUBLE PRECISION and implicit data conversions is not possible in dialect 3.

**Comment by asfernandes** [comment]
> I don't think this limitation should exist. I agree it is not a regression, but I think it should be fixed.

A double is imprecise and bits logic are the last thing would benefit from that.
