### ISSUE TITLE
Wrong path in object pascal readme.md

### ISSUE THREAD

**Issue by vejrous** [FirebirdSQL/firebird#7113]
File path "/opt/firebird/include/Firebird common" specified in file "firebird/examples/object_pascal/readme.md" does not exists.
_Firebird.pas_ file mentioned in readme is located at "firebird/src/include/gen/Firebird.pas".

**Comment by AlexPeshkoff** [comment]
Suggested by you path is correct only for src tree - with binary package installed it's wrong. The problems were that: one suggested

**Comment by vejrous** [comment]
Sorry, I didn't know that.
May be it would be beter with:
Go into Project options and add the following paths **based in the Firebird installation directory**
I was searching for path in Lazarus, in Delphi and then in GitHub.

**Comment by vejrous** [comment]
Also there are pascal examples in other directories (dbcrypt, interfaces,...) and 01.create.pas is located in both object_pascal and interfaces. So shouldn't the other examples be in interfaces also?
