### ISSUE TITLE
fbclient.dll 32/64bits

### ISSUE THREAD

**Issue by AdySouza** [FirebirdSQL/firebird#7114]
Boa noite! A todos
Notei um problema que inclusive eu tive dificuldade para entender, o que eu fazia de errado na hora de criar ou conectar em um banco firebird, o fbclient.dll não possui uma indicação de qual versão de banco firebird ele pertence, logo não adianta somente saber se a DLL é de 32bits ou 64bits, pois uma dll 32bits do firebird 4.0 não conecta na versão 3.0 apresenta erro de versão não suportada devido
ao ODS ser diferente entre a versão 3 e 4, ate aqui entendo ser normal, o banco adicionou novos recursos em sua estrutura, mas eu ainda desconheço a forma de identificar dll a qual versão de banco pertence, sugestão para uma futura versão seria de que nas propriedade da dll também tivesse a versão do banco ou da ODS. Eu utilizo o Ibexpert 2021.12.6.1 gratuito em sua ultima versão e só existe a opção 32bits a DLL que vem é do firebird 3.0 32bits

**Comment by asfernandes** [comment]
@AdySouza aqui deve ser relatado problemas e em inglês.

Não existe esse problema que você disse, você não entendeu exatamente como funciona a relação da fbclient com o servidor.

Procure um grupo de suporte (por exemplo, em português tem a lista da firebase).
