### ISSUE TITLE
Invalid state of mapping cache after replacement of database

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7122]
Mapping cache for particular DB is stored on a server (SS/SC) as long as mappings are not modified for that database (or server restarted). But there are some more cases when it should be invalidated. I plan to add the following:
- database is created (it may be overwrite operation or old database file removed using OS tools);
- database shutdown status changes (when database is shutdown file might be replaced by another with same name);
- nbackup restore is complete;

I can not detect a case when file is replaced by OS tools w/o prior DB or server shutdown because it requires opening file on each cache access which is avoided by normal check operation. Want to mentions that such trick was never recommended to do i.e. no new restrictions added here.

**Comment by AlexPeshkoff** [comment]
There is big desire to keep cache after DBB death for performance reason

**Comment by aafemt** [comment]
Was performance gain by this cache ever measured?

**Comment by AlexPeshkoff** [comment]
It highly depends on usage patterns. In brief it makes attach to database twice faster.

**Comment by AlexPeshkoff** [comment]
BTW - as soon as we have shared metadata cache (i.e. efficiently controlled by linger) I believe I will return to your suggestion.

**Comment by aafemt** [comment]
Since implementation of database linger DBB is not unloaded immediately and under low load cache miss is very probable.

**Comment by livius2** [comment]
Why caching something which is not locked (e.g. lock of file) and can dissapear or change content?

**Comment by AlexPeshkoff** [comment]
May be I did not understand your question, caching is done (as almost all caching) for performance reasons. And in some cases it's very important to keep in cache closed (i.e. not attached) database.

**Comment by livius2** [comment]
Yes, you understand correctly. But to have database still "available" after all user attachemnt are gone, we have "linger". When the file handle is closed, all cache should be invalid, if not that is a bug.

**Comment by AlexPeshkoff** [comment]
On 2/6/22 12:45, Karol Bieniaszewski wrote:
>
> Yes, you understand correctly. But to have database still "available" 
> after all user attachemnt are gone, we have "linger". When the file 
> handle is closed, all cache should be invalid, if not that is a bug.
>

Long term I agree with you. The problem is that as far as I know people 
use linger quire rare, and changing this pre-fb5 is therefore bad idea.

**Comment by asfernandes** [comment]
@AlexPeshkoff TCS tests GF_SHUT_* is having error "Some database(s) were shutdown when trying to read mapping data".

**Comment by AlexPeshkoff** [comment]
> @AlexPeshkoff TCS tests GF_SHUT_* is having error "Some database(s) were shutdown when trying to read mapping data".

@asfernandes Yep, there was ugly dup of shutdown-related error codes. Fixed now.

**Comment by mariuz** [comment]
@AlexPeshkoff 

LibreOffice has a building issue , might be related to this fix

https://ci.libreoffice.org/job/gerrit_windows/161172/consoleFull#1408899889d893063f-7f3d-4b7e-b56f-4e0f225817cd
https://bugs.documentfoundation.org/show_bug.cgi?id=134526#c18
