### ISSUE TITLE
Execute Block with more than 128 statements - "Too many Contexts of Relation/Procedure/Views. Maximum allowed is 256."

### ISSUE THREAD

**Issue by nLeonardt95** [FirebirdSQL/firebird#7126]
Why does this message ("Too many Contexts of Relation/Procedure/Views. Maximum allowed is 256.") appear if you make an execute block with more than 128 entries? 
Is it possible to modify this limit?

**Comment by nLeonardt95** [comment]
I have just noticed that the error 
"Too many Contexts of Relation/Procedure/Views. Maximum allowed is 256'"

occurs for executeblock with more than 128 UPDATE-statements, but for executeblocks with insert statements only at over 256.

Why does it behave like that?

**Comment by dyemanov** [comment]
Because UPDATE has two "contexts", one for reading and one for writing (internally it's a SELECT loop with single-row update inside).

**Comment by dyemanov** [comment]
Support question has been answered. As a bug reference, this duplicates #1195. Thus closed.
