### ISSUE TITLE
Optimizer regression: bad plan (HASH instead of JOIN) is chosen for some inner joins

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#7137]
Initial test case from user:

```sql
SELECT A.JEDIN
  FROM ARDACO_EDESK_INFO A
  JOIN ADRESAR B ON B.ICO = A.ICO
  JOIN ARDACO_EDESK_ADDRESS C ON C.ARDACO_EDESK_INFO = A.JEDIN
  WHERE B.JEDIN = 0 AND A.CORPORATE_NAME = B.NAZOV_DLHY

-- 3.0.8 PLAN SORT (JOIN (B INDEX (RDB$PRIMARY3), A INDEX (IDX_ARDACO_EDESK_INFO_CORP_NAME), C INDEX (FK_ARDACO_EDESK_ADDRESS_INFO)))

-- 3.0.9 PLAN SORT (HASH (JOIN (C NATURAL, A INDEX (PK_ARDACO_EDESK_INFO)), B INDEX (RDB$PRIMARY3)))
```

The point here is that A depends on both B and C and one of these dependencies is unique (`A.JEDIN`). The optimizer wrongly assumed that A is independent from B, but it also considered B independent from anything else, because filter on B is also unique (`B.JEDIN = 0`). Hence the nested loop join was used only for (A, C) and B was hash joined to the result.

The bug was introduced while fixing #3357 / #7118.

**Comment by rotursoft** [comment]
I want to confirm that your fix returned back the same plan as it was in 3.0.8 and on my test database the stored procedure is executed in less that second instead of many minutes with 3.0.9.
Thanks for fixing it.

**Comment by danidummer** [comment]
I've got the 3.0.10 snapshot release and still is executing with the incorrect plan.
Meanwhile, I downgraded to 3.0.8, that is working fine.

**Comment by dyemanov** [comment]
Can you show both "good" and "bad" plans? Or even better prepare a test case?

**Comment by danidummer** [comment]
I try to create a new, minified, database and I could not reproduce.

So, I made a video of the my database, where I am having problems.

It's simple and demonstrate how the index selection is wrong.

https://youtu.be/hoXtWkedXhc

If you have any questions, I'm here to help!

**Comment by danidummer** [comment]
I've created one new database with only those 3 tables used on example video above.

If this can help, please contact me that I can send you the link for this FDB for tests.

**Comment by dyemanov** [comment]
Please send me the link to dimitr@firebirdsql.org.

**Comment by danidummer** [comment]
> Please send me the link to [dimitr@firebirdsql.org](mailto:dimitr@firebirdsql.org).

Sent!
