### ISSUE TITLE
Services manager breaks long lines into 1023 bytes portions when using isc_info_svc_line in Service::query()

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7141]
Using long lines of base64 text with isc_info_svc_line is useful when dealing with trace plugin in order to transfer actually binary data to the client. This may appear strange choice but it helps to make trace process better interactive at the same time using single packet per trace event. But currently services manager is not ready for long (>=1Kb) lines transfer, causing need of strange code on client to process such packets and network traffic overhead (more packets than really needed).

**Comment by aafemt** [comment]
Shouldn't such truncated lines be ended with isc_info_truncated?

**Comment by AlexPeshkoff** [comment]
They will be ended with isc_info_truncated - if do not fit into user's buffer. Normally services manager will send as long lines as fit into that buffer. Limitation of 1Kb is/was artificial and caused by code of services manager.
