### ISSUE TITLE
Replication not restarting after network failure

### ISSUE THREAD

**Issue by lwennekers** [FirebirdSQL/firebird#7150]
When Firebird starts and the configurerd journal_source_directory is inaccessible it does not retry later on. This behaviour would be nice when using a network share, the share might
not be available when firebird starts but can be available later on.

Perhaps I'm missing some settings but I noticed this behavior
With kind regards, 
Leonard Wennekers

**Comment by dyemanov** [comment]
Please test the next snapshot build, it should be fixed there.

**Comment by lwennekers** [comment]
Already tested from your build and I succeeded to run my tests. Hopefully 4.0.2 is coming soon :)

**Comment by pavel-zotov** [comment]
@@@ QA issue @@@
To be discussed. Perhaps, test may not be implemented using current QA suite.

**Comment by lwennekers** [comment]
Hello,
I don't know if it's the same issue but I see some network problems while replicating inside the replication.log. See below. It seems reporting network problems but while investigating it is possible to connect on both machines and the UNC paths are available. It also seems that once a while all replication-files remain and we get a full disk error.
We are using Firebird 4.0.2.   

P063ST101-1 (replica) Tue Sep 26 15:04:28 2023
	Database: D:\PROGRAM FILES\IOLAN\SPHERE\DATA\DATABASE\W063_SMS.FDB
	ERROR: operating system directive FindFirstFile failed
	Kan het netwerkpad niet vinden. 

P063ST101-1 (replica) Tue Sep 26 15:31:54 2023
	Database: D:\PROGRAM FILES\IOLAN\SPHERE\DATA\DATABASE\W063_SMS.FDB
	ERROR: operating system directive FindFirstFile failed
	Kan de netwerklocatie niet bereiken. Raadpleeg Windows Help voor informatie over het oplossen van netwerkproblemen. 

P063ST101-1 (replica) Mon Oct  2 12:03:04 2023
	Database: D:\PROGRAM FILES\IOLAN\SPHERE\DATA\DATABASE\W063_SMS.FDB
	ERROR: operating system directive FindFirstFile failed
	Kan de netwerklocatie niet bereiken. Raadpleeg Windows Help voor informatie over het oplossen van netwerkproblemen. 

P063ST101-1 (replica) Mon Oct  2 12:03:35 2023
	Database: D:\PROGRAM FILES\IOLAN\SPHERE\DATA\DATABASE\W063_SMS.FDB
	ERROR: operating system directive FindFirstFile failed
	Kan het netwerkpad niet vinden. 

P063ST101-1 (replica) Mon Oct  2 12:04:26 2023
	Database: D:\PROGRAM FILES\IOLAN\SPHERE\DATA\DATABASE\W063_SMS.FDB
	ERROR: operating system directive FindFirstFile failed
	Kan het netwerkpad niet vinden.

**Comment by AlexPeshkoff** [comment]
Looks like network sometimes has connectivity problems.

**Comment by lwennekers** [comment]
Oke I accept but in that case will the replication stop? It seems that the network was correct later on but the replication didn't continue and the number of files where increasing????
