### ISSUE TITLE
Table corruption in FB 3.02 (page N of wrong type)

### ISSUE THREAD

**Issue by Formtrap** [FirebirdSQL/firebird#7151]
Hello,

Error happens in 3 different sites, fb setup file is Firebird-3.0.2.32703_0_x64.exe

Database file appears corrupt (path to database)
wrong page type
page N of wrong type (expected pointer, found purposely undefined)

Example of one of firebird.log files:

MYPRVWINDOCF03	Sun Dec 05 13:00:02 2021

	I/O error during "ReadFile" operation for file "D:\FTHOME\V7\FORMTRAP.FB3"

	Error while trying to read from file

MYPRVWINDOCF03	Sun Dec 05 13:00:12 2021

	Database: D:\FTHOME\V7\FORMTRAP.FB3

	database file appears corrupt (D:\FTHOME\V7\FORMTRAP.FB3)

	wrong page type

	page 6 is of wrong type (expected pointer, found purposely undefined)

Please let me know if you need anything else

**Comment by AlexPeshkoff** [comment]
I suggest you to upgrade FB version first of all. 3.0.2 is very old and we had dozens of bugs fixed since it.

**Comment by Formtrap** [comment]
Thanks Alex, it did happen with 3.0.7 too.
Do you think upgrading to 3.0.9 which I understand is latest of 3 is a good idea or we should go to 4?

**Comment by AlexPeshkoff** [comment]
Does "it did happen with 3.0.7 too" mean:
- new version of FB4, running with old database, reports same error.
or
- clean database running on FB 3.0.7 after some time gets corrupted too?

**Comment by Formtrap** [comment]
clean database running on FB 3.0.7 after some time gets corrupted too?

**Comment by Formtrap** [comment]
clean database running on FB 3.0.7 after some time gets corrupted too

**Comment by AlexPeshkoff** [comment]
In that case we need a way (script or something like it) to reproduce that bug. Or at least corrupted DB.

**Comment by Formtrap** [comment]
Corrupted DB is not a problem. I'm trying hard reproduce on my machine - no luck. Customer running Symantec but database folder whitelisted. Will send a file in 5 minutes

**Comment by EPluribusUnum** [comment]
@Formtrap we had similar issues (FB2.5.x). The problem was that clienst were connection with TCP/IP, but the daily gbak was using local protocol for connection the database. Switched gbak to TCP/IP and the issue was gone.

**Comment by hvlad** [comment]
Such "wrong page type" error sooner af all is consequence of previous read failure. I.e. it is not related with read problem, just incorrect error handling by engine.
Run `gfix -v -f` against database.

**Comment by Formtrap** [comment]
Thanks @EPluribusUnum, gbak is not used, one multi-threaded process accessing database for r/w from within threads, each separate tcp/ip connection.
We use FB for more than 10 years now but this only started to happen in fb3, but only some customers, intermittently.
Please find attached zip with db
[formtrap-db.zip](https://github.com/FirebirdSQL/firebird/files/8214904/formtrap-db.zip)
s

**Comment by Formtrap** [comment]
@hvlad but error persists after even restarting fb service, so file seems really got corrupted

**Comment by Formtrap** [comment]
To be clear, I'm not interested in recovering database file, but rather solution to prevent this from happening

**Comment by hvlad** [comment]
> @hvlad but error persists after even restarting fb service, so file seems really got corrupted

Is there the reason to not run validation (gfix) ?

**Comment by Formtrap** [comment]
Yes, @hvlad. I'm actually asking customer to just delete db and copy empty db, as it contains intermediate data which is not really for storage, but for processing. But the problem is that the process runs unattended as service, and part of bigger process, and such disruption is unacceptable to customer. Besides it makes us look somewhat incompetent, because there is something that was working for years and after software upgarde which includes new FB it stops working as before, so from their point of view it is not an upgrade but rather downgrade.

**Comment by hvlad** [comment]
In such conditions you should upgrade to 3.0.9 and carefully observe the system.
BTW, I validate your attached db and confirm heavy corruption - most pages are just zero's.
It looks like #7109 but 
- there is a lot of used pages at the tail and at the beginning of db,
- bug 7109 was introduced in 3.0.6, it should not happens in 3.0.2

**Comment by Formtrap** [comment]
Thanks @hvlad, much appreciated.
I will do as you suggest, and will close the issue. Let's see if 3.0.9 solves it.
Again thanks to all involved, very prompt and professional.

**Comment by EPluribusUnum** [comment]
We have the same issue with FB v3.0.10.

**Comment by dyemanov** [comment]
What is the exact corruption (as reported by gfix) you experience?

**Comment by EPluribusUnum** [comment]
The latest error message:

"database file appears corrupt (/vol/ssd/data/dak.gdb3s); wrong page type; page
153452 is of wrong type (expected data, found blob) [SQLState:XX001, ISC error
code:335544335]"

It's reported by the engine, not by gfix. It comes from a SELECT which reads reads blob data.

**Comment by dyemanov** [comment]
And what is the gfix output (both in console and in firebird.log) during validation after you've seen that error?
And please provide the exact FB version you use.

**Comment by EPluribusUnum** [comment]
We'll get the database from customer later. Will upload to FTP and send the password in PM.
Attached the current .conf and .log
This customer had corruption issues multiple times since switched from FB2.5.9 to FB3.0.10.
Current version : 3.0.10, official Linux release, Classic mode.

[fb.zip](https://github.com/FirebirdSQL/firebird/files/10243987/fb.zip)

**Comment by EPluribusUnum** [comment]
@dyemanov , tuns out it was https://github.com/FirebirdSQL/firebird/issues/7301
The customers gbak backup script was not using TCP connection.

**Comment by dyemanov** [comment]
Is `/vol/ssd/ `a true local disk or some other storage?

**Comment by EPluribusUnum** [comment]
Yes, it is true local.

**Comment by dyemanov** [comment]
Could you please check that files open by _firebird_ and _isql_ (connected to the same db) are the same. Using `ls /proc/<pid>/fd`, for example. I'm mostly interested in files located inside `/tmp/firebird`.

**Comment by EPluribusUnum** [comment]
Both connected at the same time

**ISQL (./isql -u xxxxx -p yyyyyy /vol/ssd/data/oma.fdb):**
lrwx------ 1 root root 64 dec   16 12:59 0 -> /dev/pts/3
lrwx------ 1 root root 64 dec   16 12:59 1 -> /dev/pts/3
lr-x------ 1 root root 64 dec   16 12:59 10 -> /opt/firebird/firebird.msg
lrwx------ 1 root root 64 dec   16 12:59 2 -> /dev/pts/3
lrwx------ 1 root root 64 dec   16 12:59 3 -> /tmp/firebird/fb_init
lrwx------ 1 root root 64 dec   16 12:59 4 -> /tmp/firebird/fb12_trace
lrwx------ 1 root root 64 dec   16 12:59 5 -> /tmp/firebird/fb_trace_Tl8P0d
lrwx------ 1 root root 64 dec   16 12:59 6 -> /vol/ssd/data/oma.fdb
l-wx------ 1 root root 64 dec   16 12:59 7 -> pipe:[275956563]
lrwx------ 1 root root 64 dec   16 12:59 8 -> /tmp/firebird/fb_lock_08080000000000000800010000000000
lrwx------ 1 root root 64 dec   16 12:59 9 -> /tmp/firebird/fb12_monitor_08080000000000000800010000000000

**Non ISQL client: (127.0.0.1/7777:/vol/ssd/data/oma.fdb)**
lrwx------ 1 firebird firebird 64 dec   16 12:56 0 -> socket:[275934668]
lrwx------ 1 firebird firebird 64 dec   16 12:56 1 -> socket:[275934668]
lrwx------ 1 firebird firebird 64 dec   16 12:56 10 -> /vol/ssd/data/oma.fdb
lrwx------ 1 firebird firebird 64 dec   16 12:56 11 -> /ramdisk/firebird_temp/fb_lock_08080000000000000800010000000000
lrwx------ 1 firebird firebird 64 dec   16 12:56 12 -> /ramdisk/firebird_temp/fb12_monitor_08080000000000000800010000000000
lrwx------ 1 firebird firebird 64 dec   16 12:56 2 -> socket:[275942502]
lrwx------ 1 firebird firebird 64 dec   16 12:56 3 -> /ramdisk/firebird_temp/fb_init
lrwx------ 1 firebird firebird 64 dec   16 12:56 4 -> /ramdisk/firebird_temp/fb12_trace
lrwx------ 1 firebird firebird 64 dec   16 12:56 5 -> /ramdisk/firebird_temp/fb_trace_TFQQ3J
lrwx------ 1 firebird firebird 64 dec   16 12:56 9 -> /ramdisk/firebird_temp/fb_user_mapping

SELECT * FROM mon$attachments
In both case they see themselfs only (single connection), and the other connection not shown.
For ISQL, the PID is the isql bin itself, not the firebird bin.


It would be greate to have an option in firebird.conf to list the allowed protocol types, and deny connection using not listed protocol types.

**Comment by dyemanov** [comment]
I see usage of `/tmp/firebird` vs `/ramdisk/firebird_temp` for the same files. This may surely cause corruptions. How could it happen if you say `FIREBIRD_LOCK` is not specified?

**Comment by dyemanov** [comment]
Location of the shared files **must** be the same for all Firebird processes, otherwise corruption is unavoidable. If `FIREBIRD_LOCK` is used, then it must be globally defined for all users and all processes in the system. In your case _gbak_ sees a different copy of the lock table than the server process, thus lack of synchronization and database corruption as a result.

**Comment by EPluribusUnum** [comment]
`FIREBIRD_LOCK` not specified.
In firebird.conf we have `TempDirectories = /ramdisk/firebird_temp;/vol/ssd/firebird_temp`
`/ramdisk/firebird_temp` defined nowhere else in the system.

**Comment by dyemanov** [comment]
You use Classic, so `FIREBIRD_LOCK` could be defined in the xinetd/systemd configuration for the Firebird service.

**Comment by EPluribusUnum** [comment]
We use systemd, and it not contains `FIREBIRD_LOCK`.

isql/gbak might not use firebird.conf?

**Comment by dyemanov** [comment]
Location of the shared files is hardcoded as `/tmp/firebird/`, it may be altered only via `FIREBIRD_LOCK` variable. Given that Firebird service usually runs under "_firebird_" user credentials, it's also worth looking for `FIREBIRD_LOCK` inside that user profile (`/home/firebird/.profile` or alike).

**Comment by EPluribusUnum** [comment]
`firebird:x:84:84:Firebird Database Owner:/opt/firebird:/bin/false`
firebird user exists, but not allowed to login. `/home/firebird/` not exists

**Comment by dyemanov** [comment]
I don't believe in miracles ;-) so keep searching. It must be defined somewhere.
`sudo find / -type f -exec grep FIREBIRD_LOCK '{}' \; -print`

**Comment by EPluribusUnum** [comment]
root@daklibra3s:/# find / \( -path /vol/attachment -o -path /vol/attachmentn -o -path /vol/winshared -prune \) -prune -o -type f -exec grep FIREBIRD_LOCK '{}' \; -print
/vol/ssd/firebird_2.5/lib/libfbembed.so.2.5.9 binary file matches
/vol/ssd/firebird_2.5/lib/libfbembed.so.2.5.9
/vol/ssd/firebird_2.5/lib/libfbclient.so.2.5.9 binary file matches
/vol/ssd/firebird_2.5/lib/libfbclient.so.2.5.9
/vol/ssd/firebird.3nemjo/lib/libfbclient.so.3.0.10 binary file matches
/vol/ssd/firebird.3nemjo/lib/libfbclient.so.3.0.10
#define isc_info_svc_get_env_lock               60      /* Retrieves the setting of $FIREBIRD_LOCK */
/vol/ssd/firebird.3nemjo/include/ibase.h
/vol/ssd/firebird.3nemjo/plugins/libfbtrace.so binary file matches
/vol/ssd/firebird.3nemjo/plugins/libfbtrace.so
/vol/sas/backup_firebird_set/fb_2.5.6_backup/firebird/lib/libfbembed.so.2.5.6 binary file matches
/vol/sas/backup_firebird_set/fb_2.5.6_backup/firebird/lib/libfbembed.so.2.5.6
/vol/sas/backup_firebird_set/fb_2.5.6_backup/firebird/lib/.debug/libfbclient.so.2.5.6.debug binary file matches
/vol/sas/backup_firebird_set/fb_2.5.6_backup/firebird/lib/.debug/libfbclient.so.2.5.6.debug
/vol/sas/backup_firebird_set/fb_2.5.6_backup/firebird/lib/.debug/libfbembed.so.2.5.6.debug binary file matches
/vol/sas/backup_firebird_set/fb_2.5.6_backup/firebird/lib/.debug/libfbembed.so.2.5.6.debug
/vol/sas/backup_firebird_set/fb_2.5.6_backup/firebird/lib/libfbclient.so.2.5.6 binary file matches
/vol/sas/backup_firebird_set/fb_2.5.6_backup/firebird/lib/libfbclient.so.2.5.6
grep: /proc/sys/fs/binfmt_misc/register: Invalid argument
grep: /proc/sys/net/ipv4/route/flush: Access denied
grep: /proc/sys/net/ipv6/conf/all/stable_secret: IO error
grep: /proc/sys/net/ipv6/conf/default/stable_secret: IO error
grep: /proc/sys/net/ipv6/conf/eth0/stable_secret: IO error
grep: /proc/sys/net/ipv6/conf/eth1/stable_secret: IO error
grep: /proc/sys/net/ipv6/conf/eth2/stable_secret: IO error
grep: /proc/sys/net/ipv6/conf/eth3/stable_secret: IO error
grep: /proc/sys/net/ipv6/conf/lo/stable_secret: IO error
grep: /proc/sys/net/ipv6/route/flush: Access denied
grep: /proc/sys/vm/compact_memory: Access denied
grep: /proc/sys/vm/drop_caches: Access denied



/vol/ssd/firebird_2.5, /vol/ssd/firebird.3nemjo, /vol/ssd/backup_firebird_set not used

**Comment by asfernandes** [comment]
Any chance you have `/tmp` mapped to `/ramdisk/firebird_temp` only in one case by some other mean (container, chroot, something else)?

**Comment by mrotteveel** [comment]
I think this is a discussion that should happen on firebird-devel, or on its own issue, not on an already closed issue.

**Comment by dyemanov** [comment]
In fact, this looks more like a support issue. So far I don't see any evidence of a bug, just some weird misconfiguration.
