### ISSUE TITLE
Serious issue with SYSDBA user after a Windows install with EnableLegacyClientAuth

### ISSUE THREAD

**Issue by tomaszdubiel18** [FirebirdSQL/firebird#7158]
Hello.
The problem is verified on both Linux and Windows systems.
When you install Firebird 3.0.9 with checked "Generate client library as GDS32.DLL for legacy InterBase support?" and you set your own password for SYSDBA user, after the installation you can log in as SYSDBA with changed password AND with masterkey as well.
SRP user SYSDBA has changed password, but Legacy_Auth user SYSDBA has masterkey password.
In the result, although we changed SYSDBA user's password while installation, Firebird still accepts SYSDBA logins with masterkey password.

**Comment by AlexPeshkoff** [comment]
On 3/21/22 14:09, Tomasz Dubiel wrote:
>
> Hello.
> The problem is verified on both Linux and Windows systems.
> When you install Firebird 3.0.9 with checked "Generate client library 
> as GDS32.DLL for legacy InterBase support?" and you set your own 
> password for SYSDBA user, after the installation you can log in as 
> SYSDBA with changed password AND with masterkey as well.
> SRP user SYSDBA has changed password, but Legacy_Auth user SYSDBA has 
> masterkey password.
> In the result, although we changed SYSDBA user's password while 
> installation, Firebird still accepts SYSDBA logins with masterkey 
> password.
>

If you care about secutiy do not use legacy auth. It does not matter 
what password is set in it - it's anyway passed over the wire in almost 
unencrypted form.

**Comment by mrotteveel** [comment]
Credentials exist per authentication plugin. If you want to use both Srp and Legacy_Auth, you need to change the password for both plugins (with the `using` clause of `alter user`). Alternatively: disable legacy_auth. It is utterly unsafe as it supports only max 8 character passwords (and ignores further characters).

**Comment by tomaszdubiel18** [comment]
> Credentials exist per authentication plugin. If you want to use both Srp and Legacy_Auth, you need to change the password for both plugins (with the using clause of alter user). Alternatively: disable legacy_auth. It is utterly unsafe as it supports only max 8 character passwords (and ignores further characters).

But why is Firebird installator asking for password, when it doesn't set it for Legacy_Auth SYSDBA? That's not a bug?

**Comment by mrotteveel** [comment]
You're right, that does sounds like a bug.

**Comment by reevespaul** [comment]
On Mon, 21 Mar 2022 04:09:14 -0700
Tomasz Dubiel ***@***.***> wrote:

> The problem is verified on both Linux and Windows systems.
> When you install Firebird 3.0.9 with checked "Generate client library as
> GDS32.DLL for legacy InterBase support?" and you set your own password for
> SYSDBA user, after the installation you can log in as SYSDBA with changed
> password AND with masterkey as well. 


I think you are confusing to install options. Legacy InterBase support just
means to install fbclient as gds32 in <System32>. This is not at all
connected with the security database. You are actually talking about
EnableLegacyClientAuth.

> SRP user SYSDBA has changed password, but Legacy_Auth user SYSDBA has 
> masterkey password. In the result, although we changed SYSDBA user's 
> password while installation, Firebird still accepts SYSDBA logins with 
> masterkey password.

This is what the installer executes if EnableLegacyClientAuth is NOT
checked:

'create user ' + GetAdminUserName + ' password ''' + GetAdminUserPassword +
  ''' using plugin Srp;'

and the SEC$USERS shows a single entry for SYSDBA. 

If EnableLegacyClientAuth is checked then this line is also executed:

'create or alter user ' + GetAdminUserName + ' password ''' +
        GetAdminUserPassword + ''' using plugin Legacy_UserManager;'

and I end up with these two lines in sec$users:

USER_NAME FULL USER NAME           SEC$ACTIVE SEC$ADMIN SEC$PLUGIN
========= ======================== ========== ========= ==================
SYSDBA    Sql Server Administrator <null>     <true>    Legacy_UserManager
SYSDBA    <null>                   <true>     <true>    Srp


so, theoretically at least, the provided password should be set.

But yes, you seem to be correct - users can log in with masterkey.

You also mentioned that you confirmed this on linux. That would rule this out
as a Windows installer bug. Can you confirm that a linux install is showing
the same problem?


Paul
-- 

Paul Reeves
http://www.ibphoenix.com
Supporting users of Firebird

**Comment by tomaszdubiel18** [comment]
Yes, my manager was installing Firebird 3 on Linux and the same bug persists there. Verification takes seconds. We take optimized configs from https://ib-aid.com/en/optimized-firebird-configuration/

**Comment by mrotteveel** [comment]
> Sorry, it is not verified yet on Linux. The problem is 100% present on Windows.

Please specify the exact steps to reproduce this on Windows, and on Linux.

**Comment by hvlad** [comment]
Make sure you not using embedded when checks password.

**Comment by tomaszdubiel18** [comment]
On Windows, fresh install on different computer, with fresh security database and default configuration:
![obraz](https://user-images.githubusercontent.com/85760200/159328380-1ebd567a-a80e-47cd-a0fe-7781f4484117.png)
setting password 1111
![obraz](https://user-images.githubusercontent.com/85760200/159328492-702b8d69-0a6f-4944-adfb-de3fdfae4bd7.png)
As you can see, after installing Firebird, I can connect to the database with masterkey
![obraz](https://user-images.githubusercontent.com/85760200/159331965-841211f8-7d50-4e90-bd54-93eece8b54f0.png)
So it's very easy, out of the box install and masterkey password for SYSDBA is ok for Firebird

**Comment by tomaszdubiel18** [comment]
Previously I checked with IBExpert and with masterkey and with changed password I could log in. Now, just using pure ISQL:
![obraz](https://user-images.githubusercontent.com/85760200/159332583-e7c555f7-f40f-49c9-a94b-f5a771d6b4d8.png)
How is installation incomplete? Installer didn't tell me any error occured

**Comment by reevespaul** [comment]
Additionally, if you can reproduce that error after a clean install then please let me know how/what you did. 
I've seen this error before but do not know how to produce it, nor how to fix it.

**Comment by tomaszdubiel18** [comment]
> Additionally, if you can reproduce that error after a clean install then please let me know how/what you did. I've seen this error before but do not know how to produce it, nor how to fix it.

I just showed you. I tried it on my personal computer, with no previous history of installing Firebird. I showed you all the steps with screenshots on fresh installation of Firebird 3. What you else want from me? ;)

**Comment by tomaszdubiel18** [comment]
I tested again one more time on my work PC. I installed Firebird just as before to completely another location:
![obraz](https://user-images.githubusercontent.com/85760200/159427474-813742cb-3aaa-46bd-b426-b20ae3811350.png)
You're right, I meant "Enable authorization for legacy Firebird clients" check, not "Generate client .." check. I entered SYSDBA password 1234.
After installation I can connect to, for example, employee database with 1234 password:
![obraz](https://user-images.githubusercontent.com/85760200/159427778-c9213d19-0737-42e9-a7ae-ff1e6070c319.png)
![obraz](https://user-images.githubusercontent.com/85760200/159427897-22c11cba-6e7e-4e51-a13a-785b5e3c17ff.png)
and masterkey password as well.
It's should be very easy for you to reproduce this bug.

**Comment by mrotteveel** [comment]
The install incomplete message means you tried to authenticate with a client that only supports Srp, while the security database was not initialized for Srp. Initialization of the security database with Srp happens when the first Srp user is created.

As to your IB Expert screenshot, it shows you're connecting locally, which means you're using Firebird Embedded to connect, which means there is *no* password check. Connect through localhost instead.

**Comment by tomaszdubiel18** [comment]
OK, is everything now ok? If so, this is even worse
![obraz](https://user-images.githubusercontent.com/85760200/159475839-a7d045ed-06de-456c-b2b9-f66c7cc9892a.png)
I entered 12345 password, but connecting this way is only successful with masterkey...
12345 password - "Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
"
![obraz](https://user-images.githubusercontent.com/85760200/159476171-c56cd505-5e2b-4a36-8347-42afb486964c.png)

**Comment by tomaszdubiel18** [comment]
OK, edit: I used firebird 2.5 gds32.dll
With firebird 3 gds32.dll both passwords are valid.
So, @mrotteveel, are those informations sufficient? Is this bug confirmed already?

**Comment by tomaszdubiel18** [comment]
So that's a really serious issue. Every user who installed Firebird 3.0.9 on Windows is not aware of possibility that it's still possible to login with masterkey password.

**Comment by mrotteveel** [comment]
> So that's a really serious issue. Every user who installed Firebird 3.0.9 on Windows is not aware that it's still possible to login with masterkey password.

Only if they enabled legacy authentication, but yes.

**Comment by tomaszdubiel18** [comment]
Without legacy authentication isql can not at all connect to database :-)
![obraz](https://user-images.githubusercontent.com/85760200/160437140-dc1d768c-4117-481a-8692-fa9ed6025a1b.png)

**Comment by hvlad** [comment]
Whe you start to read the docs ?
Sorry, can't resist.

**Comment by tomaszdubiel18** [comment]
@hvlad, is it place to report issues with Firebird or not? What am I doing? Is it normal for you to expect errors in fresh Firebird installation?

**Comment by hvlad** [comment]
Here is not a place to ask for support. There is NO issue in what you wrote in message (with smiling face) that I've answered. 
Read the error message, then read the docs. Repeat 3 times. 
Then, if you still have questions about it - ask for support at [firebird-support](https://groups.google.com/g/firebird-support) google group.

**Comment by tomaszdubiel18** [comment]
This is the topic about the bug in Windows Installer and it's already confirmed

> > are those informations sufficient? Is this bug confirmed already?
> 
> Yes, I can confirm that when you enable legacy authentication in the installer then
> 
>     1. The password of sysdba for the legacy user manager is not changed and remains the default (masterkey)
> 
>     2. The password for sysdba for Srp has not been set (and the security database is not initialized for Srp)
> 
> 
> **If you don't enable legacy authentication in the installer then the password for sysdba for Srp has not been set (and the security database is not initialized for Srp).**

**Comment by hvlad** [comment]
Your comment

> Without legacy authentication isql can not at all connect to database :-)

have nothing common with confirmed *minor* bug in installer and looks like silly trolling: since the bug in installer is confirmed - what was your intention at that comment ? 

Again - did you read the error message and follow it ?

**Comment by mrotteveel** [comment]
> Without legacy authentication isql can not at all connect to database :-) ![obraz](https://user-images.githubusercontent.com/85760200/160437140-dc1d768c-4117-481a-8692-fa9ed6025a1b.png)

The workaround is to use `isql -user sysdba employee` (which connects using embedded, which doesn't verify passwords) and then execute `create user sysdba password '<your desired password>` using plugin srp;`, which will initialize the security database for Srp, and create the SYSDBA account under Srp.

**Comment by tomaszdubiel18** [comment]
Why are your attitude so negative, Vlad? I simply reported the bug (which also Mark thinks it's serious, not "minor"), then Mark wrote as well about the issue even without legacy authentication, so when I came across another bug, I also mentioned this.
Yes, I read it. I followed the instructions and they didn't work for the first time, but somehow, when I uninstalled Firebird, deleted the folder and installed Firebird again, it didn't appear again so as I don't have repeating bug, I end with this.
Thanks Mark :-)

**Comment by hvlad** [comment]
The "another bug" you "found" is asked about zillion times since the FB3 was released. And every  time it was because people not reading the error message or the docs. 
So, where you see the negative ? In the suggestion to read the docs ? Or when I showed you where support questions should be asked ?

**Comment by tomaszdubiel18** [comment]
You don't find it negative, I find. You are Firebird developer, I'm not. Not everything you see obvious is obvious for others.
Let's already stop this, there is no use in prolonging this.

**Comment by tomaszdubiel18** [comment]
Hello @reevespaul How should we understand "Remove option to enable legacy_auth during windows installation.'"?
https://github.com/FirebirdSQL/firebird/commit/e10b0b864d6372d9775fb278a9e5566e3944de50
Firebird 3 works on it. Our ERP system only works on legacy. Since Firebird 3.0.10 there will be no longer legacy authentication on Windows?

**Comment by AlexPeshkoff** [comment]
On 4/27/22 16:02, Tomasz Dubiel wrote:
>
> Hello @reevespaul <https://github.com/reevespaul> How should we 
> understand "Remove option to enable legacy_auth during windows 
> installation.'"?
> e10b0b8 
> <https://github.com/FirebirdSQL/firebird/commit/e10b0b864d6372d9775fb278a9e5566e3944de50>
>

That means that can not turn on legacy authentication in installer.

> Firebird 3 works on it.
>

That's plain wrong.

> Our ERP system only works on legacy.
>

Interesting - what prevents use of other authentication method?

> Since Firebird 3.0.10 there will be no longer legacy authentication on 
> Windows?
>

It's OS independent issue. Legacy authentication is (and will be) 
supported in FB3, is supported in FB4, and will be supported in FB5. For 
details see release notes.

**Comment by tomaszdubiel18** [comment]
I meant "Firebird supports that".
Our developers probably didn't have the time to adjust the system to the new authentication method. Legacy is required.

**Comment by mrotteveel** [comment]
> I meant "Firebird supports that". Our developers probably didn't have the time to adjust the system to the new authentication method. Legacy is required.

If you install Firebird with the default setting (that is, it uses the new authentication options), and assuming you either use fbclient of Firebird 3 and higher, or a connection library that supports the new authentication (e.g. Jaybird), then the new authentication method should be entirely transparent to you and not require work for your developers.

**Comment by reevespaul** [comment]
@mrotteveel 
> This order for AuthServer and AuthClient is unsafe, because it results in trying the less secure Legacy_Auth before the more secure Srp. In addition, it doesn't include the more secure Srp256 which should be preferred over Srp. I would also prefer not putting Legacy_UserManager first in UserManager, but that could impact legacy clients using gsec to create legacy users.

My assumption here is that this is exactly what a typical user would require. If they want Legacy_Auth give them Legacy_Auth. 

Anyway, I tried building the installer with this order:
```
  AuthServer = Srp, Win_Sspi, Legacy_Auth 
  AuthClient = Srp, Srp256, Win_Sspi, Legacy_Auth
  UserManager = Srp, Legacy_UserManager
```
and can still log in with masterkey even though I set a different password during the install. :-(

```
isql -user SYSDBA -password masterkey localhost:employee
Database: localhost:employee, User: SYSDBA
SQL> select mon$user, mon$auth_method from mon$attachments;

MON$USER                        MON$AUTH_METHOD       
=============================== ======================
SYSDBA                          Legacy_Auth           
Cache Writer                    <null>                
Garbage Collector               <null> 
```

> Isn't this the same issue as we had in one of the alpha or beta releases of Firebird 3, where some wrong order of operations (starting Firebird before modifying firebird.conf or something like that) caused the ISQL script to actually fail instead of getting executed successfully?

No - that would be a different issue. The security database has been initialised, so the script did not fail. I should also add that the tests I tried today included a commit after the first `create user... using plugin srp` statement.

I really do feel I've covered all the options now. It remains a mystery as to why this works if done manually and fails if done as part of the installer.

**Comment by tomaszdubiel18** [comment]
> On 4/27/22 17:40, Mark Rotteveel wrote: I meant "Firebird supports that". Our developers probably didn't have the time to adjust the system to the new authentication method. Legacy is required. If you install Firebird with the default setting (that is, it uses the new authentication options), and assuming you either use fbclient of Firebird 3 and higher, or a connection library that supports the new authentication (e.g. Jaybird), then the new authentication method should be entirely transparent to you and not require work for your developers.
> One job for your sysadmin - after upgrade of security database 'legacy => srp' legacy passwords are lost (list of users remains). Existing upgrade process creates random passwords for all users. And that passwords must be delivered to users.

That was one of the reasons I think we chose the legacy_auth - we have a plenty of customers using Firebird 2.5 who have a lot of integrations, different users with different priviliges, various apps connecting to the database using those users (apps sometimes can have credentials compiled into themselves ;)) and then switching from FB 2.5 to FB 3.0 and loosing all those users' passwords would be complicated and require a lot of preparations.
Thanks to sticking to legacy_auth and script from IBAID
https://ib-aid.com/en/articles/how-to-migrate-copy-users-from-security2-fdb-firebird-2-5-to-security3-fdb-firebird-3/
we could very easily move our customers to FB 3.0.

**Comment by hvlad** [comment]
@reevespaul 

> and can still log in with masterkey even though I set a different password during the install. :-(

I see function `InitSecurityDB` in [FirebirdInstall_30.iss](https://github.com/FirebirdSQL/firebird/blob/B3_0_Release/builds/install/arch-specific/win32/FirebirdInstall_30.iss#L863) that set the SYSDBA password. 
Could you explain if firebird is running when `InitSecurityDB` is called ?
Also, does you check contents of `temp.sql.txt` ? 
Does you look at `ResultCode` value after `Exec` ?

IIRS, security.db contains record for legacy SYSDBA with 'masterke' right after the build and it looks like attempt to change the password by installer is failed.

**Comment by reevespaul** [comment]
Thanks Vlad, 

You pointed me in the right direction. There was one error of logic and one error of syntax. 
I've straightened those out and fixed the main problem.

And thanks also to Mark and Tomas - your input has been very helpful.

I shall commit the fix later today, I hope. There are still some minor points I want to tidy up.

**Comment by tomaszdubiel18** [comment]
Is everything ok with Firebird 3.0.10 Windows installer? On my PC with Avast Antivirus it scans it for a long time during the installation and eventually let it install. However, on my work computer with ESET, no browser can finish downloading the installer - it either goes to a 5,8 out of 9,4 MB and stops, or its downloaded to 100%, but process can not finish downloading.

**Comment by AlexPeshkoff** [comment]
On 6/8/22 19:35, Tomasz Dubiel wrote:
>
> Is everything ok with Firebird 3.0.10 Windows installer? On my PC with 
> Avast Antivirus it scans it for a long time during the installation 
> and eventually let it install. However, on my work computer with ESET, 
> no browser can finish downloading the installer - it either goes to a 
> 5,8 out of 9,4 MB and stops, or its downloaded to 100%, but process 
> can not finish downloading.
>

Please do not post offtopic in old issues - your message is unrelated to 
'Serious issue with SYSDBA...'

**Comment by dyemanov** [comment]
I can download both 32-/64-bit installers successfully.
