### ISSUE TITLE
Issue or feature? Union all between procedure and temporary table works differently in FB2.5 

### ISSUE THREAD

**Issue by gilbertoximenes** [FirebirdSQL/firebird#7163]
Teste case using EMPLOYEE.FDB:

```
CREATE GLOBAL TEMPORARY TABLE T_PHONE_LIST (
  EMP_NO SMALLINT,
  FIRST_NAME VARCHAR(15),
  LAST_NAME VARCHAR(20),
  PHONE_EXT VARCHAR(4),
  LOCATION VARCHAR(15),
  PHONE_NO VARCHAR(20)
) ON COMMIT DELETE ROWS;


SET TERM ^ ;

CREATE PROCEDURE P_PHONE_LIST
returns (
  EMP_NO SMALLINT,
  FIRST_NAME VARCHAR(15),
  LAST_NAME VARCHAR(20),
  PHONE_EXT VARCHAR(4),
  LOCATION VARCHAR(15),
  PHONE_NO VARCHAR(20))
as
begin
 if (not exists(select * from T_PHONE_LIST)) then begin
   INSERT INTO T_PHONE_LIST
   SELECT * FROM PHONE_LIST;
 end
 exit;
 suspend;
end^

SET TERM ; ^
```

This command below returns 42 records on Firebird 2.5 and returns 0 records on firebird 3 and 4
```
SELECT * FROM P_PHONE_LIST UNION ALL
SELECT * FROM T_PHONE_LIST
```

**Comment by mrotteveel** [comment]
This is likely related to the changes to cursor stability in Firebird 3.0 (see [Cursor Stability](https://www.firebirdsql.org/file/documentation/release_notes/html/en/3_0/rlsnotes30.html#rnfb30-dml-curstability) and [“Cursor Stability” Effects](https://www.firebirdsql.org/file/documentation/release_notes/html/en/3_0/rlsnotes30.html#rnfb30-compat-cursorstability)

**Comment by mrotteveel** [comment]
However, your example is not complete. What is PHONE_LIST and how is it populated?

**Comment by dyemanov** [comment]
As designed, due to cursor stability. Both parts of UNION belong to the same cursor, thus records inserted inside its first part cannot be seen in its second part.

**Comment by mrotteveel** [comment]
The appropriate solution is to return the rows from P_PHONE_LIST.

```sql
CREATE PROCEDURE P_PHONE_LIST
returns (
  EMP_NO SMALLINT,
  FIRST_NAME VARCHAR(15),
  LAST_NAME VARCHAR(20),
  PHONE_EXT VARCHAR(4),
  LOCATION VARCHAR(15),
  PHONE_NO VARCHAR(20))
as
begin
  if (not exists(select * from T_PHONE_LIST)) then 
  begin
    for select emp_no, first_name, last_name, phone_ext, location, phone_no from phone_list
        into emp_no, first_name, last_name, phone_ext, location, phone_no do
    begin
      insert into t_phone_list(emp_no, first_name, last_name, phone_ext, location, phone_no) 
        values (:emp_no, :first_name, :last_name, :phone_ext, :location, :phone_no);
      suspend;
  end
end
```

**Comment by AlexPeshkoff** [comment]
Procedure not needed:
insert into t_phone_list select * from phone_list where not exists (select * from t_phone_list) returning *;

**Comment by gilbertoximenes** [comment]
> However, your example is not complete. What is PHONE_LIST and how is it populated?
This is part of EMPLOYEE.FDB that is included in firebird install package.

**Comment by gilbertoximenes** [comment]
> The appropriate solution is to return the rows from P_PHONE_LIST.
> 
> ```sql
> CREATE PROCEDURE P_PHONE_LIST
> returns (
>   EMP_NO SMALLINT,
>   FIRST_NAME VARCHAR(15),
>   LAST_NAME VARCHAR(20),
>   PHONE_EXT VARCHAR(4),
>   LOCATION VARCHAR(15),
>   PHONE_NO VARCHAR(20))
> as
> begin
>   if (not exists(select * from T_PHONE_LIST)) then 
>   begin
>     for select emp_no, first_name, last_name, phone_ext, location, phone_no from phone_list
>         into emp_no, first_name, last_name, phone_ext, location, phone_no do
>     begin
>       insert into t_phone_list(emp_no, first_name, last_name, phone_ext, location, phone_no) 
>         values (:emp_no, :first_name, :last_name, :phone_ext, :location, :phone_no);
>       suspend;
>   end
> end
> ```
> 
> You can also add an `else`-branch to return the existing rows from `T_PHONE_LIST`, removing the need for the union entirely.

This union is a tiny part of a bigger select that is executed several times. When it is executed for the second time, firebird plans uses the indexes from the temporary table. Firebird can't use indexes when records are returned form the procedure.

**Comment by gilbertoximenes** [comment]
> Procedure not needed: insert into t_phone_list select * from phone_list where not exists (select * from t_phone_list) returning *;

It doesn't work. Error: "multiple rows in singleton select"

**Comment by AlexPeshkoff** [comment]
On 4/4/22 04:52, gilbertoximenes wrote:
>
>     Procedure not needed: insert into t_phone_list select * from
>     phone_list where not exists (select * from t_phone_list) returning *;
>
> It doesn't work. Error: "multiple rows in singleton select"
>

I've tried to advertise FB5 feature ;-)
You may try using snapshot.
