### ISSUE TITLE
Firebird 3.0.9 Plan Optimizer Datatype Conversion

### ISSUE THREAD

**Issue by BenjaminBac** [FirebirdSQL/firebird#7170]
On Firebird 3.0.x the Plan-Index extension for Datatype comparison seem to not work properly in Comparison to defined fields.

1. A Table with a Field, Type Char and a Select with an variable of an other Datatype causes 
   1. non Indexed Read, if Data in Table can be convert
   2. Conversion error if Table containing other Data.

Simple Sample Projekt: 
* Database relatet Structure: [TestDB.txt](https://github.com/FirebirdSQL/firebird/files/8513426/TestDB.txt)
* Data for the Table: [Insert into Test.txt](https://github.com/FirebirdSQL/firebird/files/8513434/Insert.into.Test.txt)
* Zipped Database: [Performance FB3.0.zip](https://github.com/FirebirdSQL/firebird/files/8513518/Performance.FB3.0.zip)

1. Execute Procedur `PERFORMANCE_TEST` with Lokal Variable  `declare variable L_AUFTRAGSNUMMER Char(16);`
   1. Used Plan:  PLAN (TEST INDEX (TEST_IDX2)) Everything is fine
   2. ![grafik](https://user-images.githubusercontent.com/104010524/164016551-3d65e60a-be4c-44b7-a2d0-c20845133e7b.png)
2. Execute Procedure `PERFORMANCE_TEST` with lokal Varaible `declare variable L_AUFTRAGSNUMMER integer;` 
   1. If Field `Auftragsnummer` contains a Value that is not compatible to integer --> conversion Error from String
   2. if Field `Auftragsnummer` contains only Data compatible to integer -->   non indexed Reads
   3. Used PLAN (TEST NATURAL)  --> not correct
   4. Performance drops rapidly 
   5.  Using of coding `plan (test index (test_idx2))` into the procedure is not possible. `Index cannot be used in the specified plan`. `Error while parsing procedure 's BLR`

It seems that the plan optimizer converts the Datatype of the table field  into the datatype of the lokal variable. normaly the conversion must be a datatype compatible conversion. So a cast into the Table field (where naturally the index exists) should have a higher priority. Or the datatype conversion must be done with safe datatype conversion only.

**Comment by dyemanov** [comment]
Your understanding of comparison priorities is incorrect. Strings are converted to date/number before comparing, not the opposite way. So these equalities can work: '0' == 0, '000' == 0, '0.0' == 0, '+0' == 0. It would be impossible with your rules.

Thus if you compare indexed [VAR]CHAR field with a numeric value, the index cannot be used. However, if you compare indexed numeric field with a string value, the index can (and will) be used.
