### ISSUE TITLE
since update to 3.09 big Query over several rows is very slow downgrade to 3.08 will bring back to much faster execution time.

### ISSUE THREAD

**Issue by ffischerH** [FirebirdSQL/firebird#7175]
the same Query in 3.09 takes about 30 seconds
and in 3.08 it takes only 1 second

**Comment by dyemanov** [comment]
Already reported and fixed. Update to a fresh snapshot build or wait for v3.0.10 (coming soon).

**Comment by mrotteveel** [comment]
@dyemanov Can you link the issue that fixed it for reference.

**Comment by dyemanov** [comment]
Duplicates #7137 and #7154.
