### ISSUE TITLE
Incorrect error "Invalid token. Malformed string." with union + blob + non utf8 varchar

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7176]
Hello!

CREATE TABLE test (TXT VARCHAR(10) CHARACTER SET WIN1250 COLLATE PXW_HUNDC)
INSERT INTO test(txt) VALUES ('öüóőúéáűí')

Run this select on a client with UTF8 charset

SELECT CAST(NULL AS BLOB SUB_TYPE 1) x
FROM rdb$database
UNION ALL
SELECT txt
FROM test

Invalid token.
Malformed string.
SQLCODE: -104
SQLSTATE: 22000
GDSCODE: 335544849

Server : FB 3.0.9
Client : Jaybird with charSet=UTF-8 in connstring, or IBExpert with UTF8

This works on FB25 as expected.

**Comment by EPluribusUnum** [comment]
This was fast, thank you! :)

@asfernandes , will it be backported to 3.0.10?

**Comment by asfernandes** [comment]
> This was fast, thank you! :)
> 
> @asfernandes , will it be backported to 3.0.10?

Must ask @dyemanov

**Comment by dyemanov** [comment]
The patch looks trivial, so I think it can be backported.
