### ISSUE TITLE
False-negative outcome is issued when DB state is changed to shut_single or shut_multi, and this is done by NON-SYSDBA who has all necessary system privileges for that

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7189]
1. Create temporary DB and user who has necessary grants to change shutdown state of this DB via role with system privileges:
```
set bail on;
set wng off;
set echo on;
shell del c:\temp\tmp4test.fdb 2>nul;

create database 'localhost:c:\temp\tmp4test.fdb' user sysdba password 'masterkey';
create or alter user tmp_user password '123' revoke admin role;
create role tmp_role set system privileges to CHANGE_SHUTDOWN_MODE, USE_GFIX_UTILITY, IGNORE_DB_TRIGGERS;
grant default tmp_role to user tmp_user;
commit;
```
2. Prepare config launch trace session:
```
database = (%[\\/](security[[:DIGIT:]]).fdb|(security.db))
{
    enabled = false
}

database = (%[\\/]%test%.fdb)
{
	enabled = true
	log_initfini = false
	log_warnings = true
	log_errors = true
	time_threshold = 0
	log_connections = true
}

services 
{
	enabled = true
	log_initfini = false
	log_services = true
	log_errors = true
}
```

3. Try to change DB shutdown mode to 'shut single', using Services API. First, we do that as SYSDBA:
```
D:\FB\fb401rls\fbsvcmgr localhost:service_mgr user sysdba password masterkey action_properties dbname c:\temp\tmp4test.fdb prp_shutdown_mode prp_sm_single prp_force_shutdown 0
D:\FB\fb401rls\gstat -h c:\temp\tmp4test.fdb | findstr /i /c:"attributes"
```
Output:
```
Attributes              force write, single-user maintenance
```
(no errors, attribute has been changed as expected)

Trace log for this case will be following:
```
2022-05-20T09:04:40.4230 (6056:00000000014311C0) START_SERVICE
        service_mgr, (Service 0000000001269DC0, SYSDBA, TCPv6:::1/59130, D:\FB\fb401rls\fbsvcmgr.exe:13920)
        "Database Properties"
        c:\temp\tmp4test.fdb -SHUTDOWN SINGLE -FORCE_SHUTDOWN 0

2022-05-20T09:04:40.4230 (6056:00000000014311C0) DETACH_SERVICE
        service_mgr, (Service 0000000001269DC0, SYSDBA, TCPv6:::1/59130, D:\FB\fb401rls\fbsvcmgr.exe:13920)
```

Then bring DB to online mode either by gfix or fbsvcmgr (no matter).

4. Try to do the same action but as NON dba (i.e. 'TMP_USER') who has all necessary grants for that:

4.1. By specifying only USER and PASSWORD, but not role ('TMP_ROLE'):
```
D:\FB\fb401rls\fbsvcmgr localhost:service_mgr user tmp_user password 123 action_properties dbname c:\temp\tmp4test.fdb prp_shutdown_mode prp_sm_single prp_force_shutdown 0
```

STDERR will be not empty:
```
database C:\TEMP\TMP4TEST.FDB shutdown
```
Also, if we run this command in the batch scenario then we get here **errorlevel = 1**

Looking at the trace log, one could conclude that an error has occurred:
```
2022-05-20T09:11:11.5910 (6056:00000000014311C0) ATTACH_SERVICE
        service_mgr, (Service 0000000001269DC0, TMP_USER, TCPv6:::1/59138, D:\FB\fb401rls\fbsvcmgr.exe:8612)

2022-05-20T09:11:11.6690 (6056:00000000014311C0) FAILED START_SERVICE
        service_mgr, (Service 0000000001269DC0, TMP_USER, TCPv6:::1/59138, D:\FB\fb401rls\fbsvcmgr.exe:8612)
        "Database Properties"
        c:\temp\tmp4test.fdb -SHUTDOWN SINGLE -FORCE_SHUTDOWN 0

2022-05-20T09:11:11.6690 (6056:00000000014311C0) DETACH_SERVICE
        service_mgr, (Service 0000000001269DC0, TMP_USER, TCPv6:::1/59138, D:\FB\fb401rls\fbsvcmgr.exe:8612)
```

**But DB state *will* be changed as required**, gstat -h issues: "Attributes              force write, single-user maintenance".

4.2. By specifying all three parameters: user/password and role ('TMP_ROLE'):

Result is the same as in 4.1:
* STDERR contains "database C:\TEMP\TMP4TEST.FDB shutdown", errorlevel = 1
* DB state is changed to required
* Trace:
```
2022-05-20T09:17:46.5160 (6056:00000000014311C0) ATTACH_SERVICE
        service_mgr, (Service 0000000001269DC0, TMP_USER:TMP_ROLE, TCPv6:::1/59147, D:\FB\fb401rls\fbsvcmgr.exe:2772)

2022-05-20T09:17:46.7660 (6056:00000000014311C0) FAILED START_SERVICE
        service_mgr, (Service 0000000001269DC0, TMP_USER:TMP_ROLE, TCPv6:::1/59147, D:\FB\fb401rls\fbsvcmgr.exe:2772)
        "Database Properties"
        -role TMP_ROLE c:\temp\tmp4test.fdb -SHUTDOWN SINGLE -FORCE_SHUTDOWN 0

2022-05-20T09:17:46.7660 (6056:00000000014311C0) DETACH_SERVICE
        service_mgr, (Service 0000000001269DC0, TMP_USER:TMP_ROLE, TCPv6:::1/59147, D:\FB\fb401rls\fbsvcmgr.exe:2772)
```

Checked on: WI-T5.0.0.497; WI-V4.0.2.2767.

PS.
Same problem for shutdown mode = MULTI;  but *no* error when we choose shutdown mode = FULL, i.e.:
```
fbsvcmgr localhost:service_mgr user tmp_user password 123 role TMP_ROLE action_properties dbname c:\temp\tmp4test.fdb prp_shutdown_mode prp_sm_full prp_force_shutdown 0
```
(no error message will be issued in this case)

**Comment by pavel-zotov** [comment]
QA note: separate test not needed, actions must be covered by functional/syspriv/test_change_shutdown_mode.py (when this issue will be fixed).

**Comment by hvlad** [comment]
To change shutdown mode of the database one need to attach with appropriate DPB.
gfix (directly or via services) does exactly this.

When attachment puts database into single shutdown mode it needs to have system privilege ACCESS_SHUTDOWN_DATABASE to continue. SYSDBA have this privilege while tmp_user doesn't, thus attach by tmp_user successfully put db into single shutdown mode and then can't continue and fails with isc_shutdown error.

When attachment puts database into full shutdown mode it can't continue and fails immediately with isc_shutdown error. This case is handled by gfix as expected.

**Comment by pavel-zotov** [comment]
2 Vlad: thanks, I've checked with adding privilege ACCESS_SHUTDOWN_DATABASE - and all became fine.
AFAIU, this is not a bug, rather it is by design.
