### ISSUE TITLE
ISQL -ch utf8 (Windows only): either silently quits to OS or issues non-expected 'malformed string' when non-ascii character occurs in the typed command

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7202]
[Windows only]
Interactive work in ISQL with commands that contain non-ascii characters can be either abnormally interrupted (ISQL silently quits to OS, without any record in firebird.log) or lead to wrong error message ('malformed string' instead of expected 'can not transliterate characters...').

Following are examples which use character 'Á' (Latin Capital Letter A with Acute).

**Example-1.**
Windows Server 2016, version 1607, OS Build 14393.5066, system locale: en-us
```
C:\iBase\FB308>chcp 65001
Active code page: 65001

C:\iBase\FB308>C:\iBase\FB308\isql localhost:employee -user sysdba -pas masterkey -ch utf8
Database: localhost:employee, User: SYSDBA
SQL> set list on;
SQL> select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database;

C:\iBase\FB308>
```
No any error here. ISQL just quits to OS, without any message.
The same result will be if  we even do not enter any command and just type:  Á -- without quotes and delimiter ';'

But if we use PIPE then all fine:
```
C:\iBase\FB308>echo select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database; | C:\iBase\FB308\isql localhost:employee -user sysdba -pas masterkey -ch utf8
Database: localhost:employee, User: SYSDBA
SQL>
C1
====================
Statement failed, SQLSTATE = 22018
arithmetic exception, numeric overflow, or string truncation
-Cannot transliterate character between character sets
SQL>
```

Also, all OK if we put this statement into file and use non-interactive mode then all OK:
```
C:\iBase\FB308>C:\iBase\FB308\isql localhost:employee -user sysdba -pas masterkey -ch utf8 -i test-utf8.sql
select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database;

Statement failed, SQLSTATE = 22018
arithmetic exception, numeric overflow, or string truncation
-Cannot transliterate character between character sets
After line 2 in file test-utf8.sql
```

####################################################################

**Example-2.**
Windows-10, ver. 1703 (build 15063.1088), localized (Russian), system locale: ru

2.1) by typing command "inside" ISQL:
```
D:\FB\firebird-qa>chcp
Active code page: 65001

D:\FB\firebird-qa>D:\FB\fb308\isql localhost:employee -ch utf8
Database: localhost:employee, User: SYSDBA
SQL> set list on;
SQL> select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database;
Statement failed, SQLSTATE = 22000
Dynamic SQL Error
-SQL error code = -104
-Malformed string
SQL> quit;
```
(WRONG / STRANGE)

2.2) using PIPE mechanism:
```
D:\FB\firebird-qa>echo select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database; | D:\FB\fb308\isql localhost:employee -ch utf8 -user sysdba -pas masterkey
Database: localhost:employee, User: SYSDBA
SQL>
C1
====================
Statement failed, SQLSTATE = 22018
arithmetic exception, numeric overflow, or string truncation
-Cannot transliterate character between character sets
```
(i.e. all OK)

Non-interactive - the same as in example-1 (i.e. all fine):
```
D:\FB\firebird-qa>D:\FB\fb308\isql localhost:employee -ch utf8 -i test-utf8-b.sql
set list on;

select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database;

Statement failed, SQLSTATE = 22018
arithmetic exception, numeric overflow, or string truncation
-Cannot transliterate character between character sets
After line 2 in file test-utf8-b.sql
```

####################################################################

**Example-3 (LINUX, expected output)**:
```
[ibase@glb-srv-ik-test firebird-qa]$ /opt/fb30/bin/isql localhost:employee -ch utf8 -user sysdba -pas masterkey
Database: localhost:employee, User: SYSDBA
SQL> set list on;
SQL> select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database;

Statement failed, SQLSTATE = 22018
arithmetic exception, numeric overflow, or string truncation
-Cannot transliterate character between character sets
SQL> quit;

[ibase@glb-srv-ik-test firebird-qa]$ /opt/fb30/bin/isql localhost:employee -ch utf8 -user sysdba -pas masterkey -i test-utf8-b.sql
set list on;

select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database;

Statement failed, SQLSTATE = 22018
arithmetic exception, numeric overflow, or string truncation
-Cannot transliterate character between character sets
After line 2 in file test-utf8-b.sql
```

PS.

This problem is very old. 
It was discussed at least 10 year ago in DBMS forum sql.ru - but it is currently inaccessible, and I can't find universal solution how to avoid this (when use ISQL without "-i" switch).
May be this ticket duplicates some other, but this problem strongly impedes to normal tests implementing flow.
Please consider how it can be fixed, at least in FB 4.x.

**Comment by asfernandes** [comment]
@pavel-zotov please test build https://github.com/FirebirdSQL/firebird/actions/runs/2506263386 after it's done.

It would be interesting to test it in old Windows versions too.

I tested only in Windows 11.

**Comment by pavel-zotov** [comment]
> It would be interesting to test it in old Windows versions too.

I checked this build (4.0.2.2780) on:
1) Windows-10, ver. 1703 (build 15063.1088), localized (Russian), system locale: ru
2) Windows 2008 Server R2, ver 6.1(build 7601: Service Pack 1), system locale: en_us

All seems fine:
```
SQL> select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database;
Á

SQL> select cast('∩' as varchar(20) character set win1251) as c1 from rdb$database;
∩

SQL> select cast('Ð' as varchar(20) character set win1251) as c1 from rdb$database;
Ð
```
(i.e. characters *can* be seen and no more 'silent quit' from ISQL).

But on Windows Server 2016, version 1607, OS Build 14393.5066, system locale: en-us --  this snapshot can not start: it requires VCRUNTIME140_1.dll (note on suffix "_1" after 140).

And one more Q (@Vlad ?) .
There is no ability to see in the trace characters like 'Á' or 'Ð'.
They are shown as "??", despite that I did 'chcp 65001' before trace start.
Can it be fixed ?

**Comment by asfernandes** [comment]
> But on Windows Server 2016, version 1607, OS Build 14393.5066, system locale: en-us -- this snapshot can not start: it requires VCRUNTIME140_1.dll (note on suffix "_1" after 140).

Can you install the latest MSVC redistributable package?

https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by asfernandes** [comment]
Another good test to be done is if pasting (Ctrl+V) some large script in the console window would become visibly slower than before.

**Comment by pavel-zotov** [comment]
> Can you install the latest MSVC redistributable package?
This is not my own host. I've requested their admin about that.

> Another good test to be done is if pasting (Ctrl+V) some large script in the console window would become visibly slower than before.

Should this text contain lot of non-ascii characters ? And how we can compare 'speed' of drawing (rendering ?) on console ?..

**Comment by asfernandes** [comment]
> Should this text contain lot of non-ascii characters ?

No.

> And how we can compare 'speed' of drawing (rendering ?) on console ?

It's only about perception, i.e., if things become very much slower.

Because the new code reads characters one by one using the Windows API instead of with a buffer.

**Comment by reevespaul** [comment]
On Thu, 16 Jun 2022 03:57:36 -0700
Adriano dos Santos Fernandes ***@***.***> wrote:

> > But on Windows Server 2016, version 1607, OS Build 14393.5066, system
> > locale: en-us -- this snapshot can not start: it requires
> > VCRUNTIME140_1.dll (note on suffix "_1" after 140).  
> 
> Can you install the latest MSVC redistributable package?
> 
> https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
> 

This is slightly off-topic but I'm already working on fixing this in HEAD. The
snapshots are built from make_all.bat and VCRUNTIME140_1.dll is not copied.
The windows installer has always included that library so this problem will
only show up in shapshots where the host does not have the required runtimes
installed in the system. 

IAC, I'll update make_all.bat for FB4 as well.


Paul
-- 

Paul Reeves
http://www.ibphoenix.com
Supporting users of Firebird

**Comment by pavel-zotov** [comment]
> > But on Windows Server 2016, version 1607, OS Build 14393.5066, system locale: en-us -- this snapshot can not start: it requires VCRUNTIME140_1.dll (note on suffix "_1" after 140).
> 
> Can you install the latest MSVC redistributable package?
> 
> https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

Installed, checked.
Result: all fine.
```
C:\iBase\FB40>isql /:employee -z -user sysdba -pas masterkey
ISQL Version: WI-V4.0.2.2780 Firebird 4.0
Server version:
WI-V4.0.2.2780 Firebird 4.0
WI-V4.0.2.2780 Firebird 4.0/tcp (MSk1-SRV-RDS-05)/P17:C
WI-V4.0.2.2780 Firebird 4.0/tcp (MSk1-SRV-RDS-05)/P17:C
Database: /:employee, User: SYSDBA
SQL> select cast('Á' as varchar(20) character set win1251) as c1 from rdb$database;

C1
====================
Á
. . .
```

PS.
```
baseboard: C:\WINDOWS\System32\wbem\WMIC.exe /locale:ms_409 baseboard get Manufacturer, Product, Version /format:list | more
baseboard: Manufacturer=Microsoft Corporation
baseboard: Product=Virtual Machine
baseboard: Version=Hyper-V UEFI Release v4.0
.........................................................
os: C:\WINDOWS\System32\wbem\WMIC.exe /locale:ms_409 os get Version,Caption,ServicePackMajor /format:list | more
os: Caption=Майкрософт Windows Server 2016 Standard
os: ServicePackMajorVersion=0
os: Version=10.0.14393
```

**Comment by pavel-zotov** [comment]
QA: could not find way how to send text from clipboard to ISQL *without* using PIPE mechanism, i.e. how to imitate pressing of Ctrl-V  inside ISQL when it is launched and is idle.

**Comment by pavel-zotov** [comment]
QA note. See test for #8524
