### ISSUE TITLE
Segfault in gbak when restoring broken backup file over the wire

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7204]
Reported by Vlad privately.

gbak predicts the size of data buffer in XDR operations required for table record. But in case of broken data in backup file data is reallocated which together with a fact that original buffer is freed in Array's dtor once again causes double deallocation and segfault.

**Comment by pavel-zotov** [comment]
::: test issues :::
Not enough info. Sent letter to Alex, 26.02.2023 12:28. Waiting for reply.

**Comment by pavel-zotov** [comment]
In that letter I meant the following: what must be written in a fbk file to make it in such 'broken state' that attempt to restore from it caused crash ?
I've tried to put some kind of garbage in .fbk but got every time
```
gbak: ERROR:string truncated
gbak:Exiting before completion due to errors
```
(or some other error, but FB not crashed
Checked on 5.0.0.509 (date of build: 07-jun-2022)

![failed-attempt-to-broke-fbk](https://user-images.githubusercontent.com/17821573/234042147-ab1ed0d4-0fb6-4a9f-9526-c8747b6a15c3.png)

**Comment by AlexPeshkoff** [comment]
I suggest not to have special test for it - even if you reproduce a crash with some particular version (fb4 for example) that does not mean that same data kills fb3 or fb5.
