### ISSUE TITLE
Fixed RemoteAuxPort and Eventalerter: Error reading data from the connection

### ISSUE THREAD

**Issue by realcolaflasche** [FirebirdSQL/firebird#7205]
Hi,

im Running Firebird 4.0.1 on Windows 10 with the following config:
RemoteServicePort = 30400
RemoteAuxPort = 30401

In the firewall i have a rule that allows firebird.exe everything.

I can connect and execute querys but if I start an EventAlerter (Delphi 10.3, IBDAC or Firedac) i get Error reading data from the connection. If I didn't set the RemoteAuxPort, it works.

With Firebird 3 on the same machine with Port 30300 and 30301 I don't have the problem.

Is this a problem in 4.0 or do I somethin rong?

**Comment by hvlad** [comment]
Could you provide reproducible test case ?

**Comment by hvlad** [comment]
Good to know, thanks
