### ISSUE TITLE
gbak regresion in FB3.0.10

### ISSUE THREAD

**Issue by skopaliks** [FirebirdSQL/firebird#7207]
Windows 10 x64, FB3.0.10 x64.
Installed over previous FB3.0.9 by installer.

In case that default service is running and try to restore DB by this command:
D:\ElektLabs\cebalsol\db>c:\fb\gbak.exe -R -VERBI 100000 -K -REP -PAGE_SIZE 16384 -use_all_space -SE service_mgr "D:\ElektLabs\cebalsol\db\2017_03_15_aerocan.fbk" D:\fbdata\2017_03_15_aerocan.fdb
gbak:opened file D:\ElektLabs\cebalsol\db\2017_03_15_aerocan.fbk
gbak:transportable backup -- data in XDR format
gbak:           backup file is compressed
gbak:backup version is 9
gbak: ERROR:Database is probably already opened by another engine instance in another Windows session
gbak: ERROR:    failed to create database D:\fbdata\2017_03_15_aerocan.fdb
gbak: ERROR:    Exiting before completion due to errors
gbak:Exiting before completion due to errors

In case that service is stops, restore performs without error.
In case of FB3.0.9 restore performs without error with or without service running.

If I copy engine12.dll from FB3.0.9 into FB3.0.10, gbak works fine.

**Comment by AlexPeshkoff** [comment]
gbak: ERROR:Database is probably already opened by another engine instance in another Windows session

**Comment by AlexPeshkoff** [comment]
The best way for you to avoid the bug right now is to use xnet:// prefix in the command:

gbak.exe -R -VERBI 100000 -K -REP -PAGE_SIZE 16384 -use_all_space -SE xnet://service_mgr "D:\ElektLabs\cebalsol\db\2017_03_15_aerocan.fbk" D:\fbdata\2017_03_15_aerocan.fdb

**Comment by AlexPeshkoff** [comment]
BTW - using -SE service_mgr (i.e. w/o xnet://) makes absolutely no sense, you will get same (or 1-2 %%) better performance w/o it, restore anyway runs locally in embedded access process.

**Comment by livius2** [comment]
@AlexPeshkoff interesting, is this somewhere documented? When i read it it have sense, but you know, it make sense after seeing it.

**Comment by AlexPeshkoff** [comment]
xnet:// vs. 127.0.0.1: will sooner of all give better performance - xnet protocol is faster compared with tcp/ip. How bug is that difference - depends upon how and where are you using them. In a case of service, restoring DB from backup located on server, better xnet performance is hardly visible, it affects only flow of verbose messages.

**Comment by AlexPeshkoff** [comment]
Was fixed by https://github.com/FirebirdSQL/firebird/commit/d0e33f118a69c38de1996089d131c8bcef2b6151
