### ISSUE TITLE
Select statement with Calculated Fields and Existential Predicates

### ISSUE THREAD

**Issue by MuellerAndr** [FirebirdSQL/firebird#7223]
Hi I encountered some unexpected behavior in my Firebird database version 3.0.5.33220-0_x64 a while ago. And wanted to ask if this was intentional or a bug. For illustration a simple example:

CREATE TABLE B(
    fk_ID Integer PRIMARY key      
   ,intern_State SMALLINT);

SET TERM !! ;
create or alter function calc(ID INTEGER)
Returns smallint not null
AS
	DECLARE tmp SMALLINT;
BEGIN
	Select intern_State from B where fk_ID = :ID INTO :tmp;
	RETURN tmp;
END!!
SET TERM ; !!

CREATE TABLE A(
    ID Integer PRIMARY key      
   ,State Smallint GENERATED ALWAYS AS (calc(ID)));

SET TERM !! ;
create or alter function check(ID INTEGER)
Returns smallint not null
AS
BEGIN
	if(Exists(Select 1 from A where ID = :ID and State in (0,2,4))) THEN Return 0;
	ELSE Return 1; 
END !!
SET TERM ; !!

INSERT INTO B (fk_ID,intern_State) Values(1,0);
INSERT INTO A (ID) Values(1);

The case situation:
I have a program that consists of several threads that can change the state of the column intern_state in the table in very short intervals between the values 0 and 2.

If I now retrieve the value State from the table A with the check function 'Select check(1) from RDB$DATABASE;' it can happen that I get back '1' although intern_state is always '0' or '2'.

It seems that in the Existential Predicate 'State in (0,2,4)' can give false back when the switch between '0' and '2' in intern_state is in the wrong moment.

**Comment by livius2** [comment]
Support questions should go to  firebird-support@googlegroups.com
Ask questions there you will got the answers. 
As a hint, check your transaction isolations and the moment of call.

**Comment by MuellerAndr** [comment]
Sorry my fault and thanks.
