### ISSUE TITLE
SQLite string to DateTime

### ISSUE THREAD

**Issue by Jerkoviz** [FirebirdSQL/firebird#7224]
Hi. I have a problem with date time format in database. It has format dd.MM.yyyy. I want to change this format to yyyy-MM-dd. 
I have a query that works perfectly in SQL compiler, but it doesn't work in DBeaver Firebird 3 database using SQLite 3.
When I try to run this I get following error:
_SQL Error [335544634] [42000]: Dynamic SQL Error; SQL error code = -104; Token unknown_ 

I'm presuming that Firebird 3 doesn't implement some SQL functions. So my question is, how can I write this query differently?

`SELECT SDC_TIME_SERVER_TIMEZONE  FROM SDC_INVOICES 
WHERE DATE(substr(SDC_TIME_SERVER_TIMEZONE ,7,4) || '-' || substr(SDC_TIME_SERVER_TIMEZONE ,4,2) || '-'  || substr(SDC_TIME_SERVER_TIMEZONE ,1,2))
BETWEEN DATE('2022-01-01') AND ('2022-04-08')`

Thank you in advance!

**Comment by asfernandes** [comment]
Please use support list (https://firebirdsql.org/en/mailing-lists/) for support question.
