### ISSUE TITLE
Hash function doesn't work with <using> since 4.0.1 in embedded 32bit

### ISSUE THREAD

**Issue by SkliarOleksandr** [FirebirdSQL/firebird#7230]
-- works fine in 4.0.0.2175, but has been broken in the 4.0.1 release (4.0.1.2692), also doesn't work in the latest snapshot 4.0.2.2798

SELECT hash('text' using sha256) from rdb$database;

Unsuccessful execution caused by system error that does not preclude successful execution of subsequent statements.
Invalid HASH algorithm SHA256.
-------------------------------------------------------------------------------------------------------------------
SQLCODE: -901
SQLSTATE: 42000
GDSCODE: 335545152

**Comment by hvlad** [comment]
Cryptographic hashes was moved into new `CRYPT_HASH` built-in function.

See
https://firebirdsql.org/file/documentation/release_notes/html/en/4_0/rlsnotes40.html#rnfb40-dml-new-built-in-functions
https://firebirdsql.org/file/documentation/release_notes/html/en/4_0/rlsnotes40.html#rnfb40-dml-changes-built-in-functions

**Comment by mrotteveel** [comment]
Firebird 4.0.0.2175 was a snapshot version for testing purposes, it was not a released version. The released 4.0.0 was 4.0.0.2496, which already used `CRYPT_HASH` instead of `HASH`
