### ISSUE TITLE
Attributes and owners mismatch in Firebird-debuginfo-4.0 tarball

### ISSUE THREAD

**Issue by basid-irk** [FirebirdSQL/firebird#7236]
gebug-files in Firebird-debuginfo-4.0 tarball have minor inconsistency:
```
examples/prebuilt/bin/.debug:
total 808K
-rwxr-xr-x. 1 bluser root 655K Jul 20 09:37 fbSampleDbCryptApp.debug*
-rwxr-xr-x. 1 bluser root 152K Jul 20 09:37 fbSampleExtAuthKeygen.debug*

examples/prebuilt/plugins/.debug:
total 1.8M
-rw-r--r--. 1 bluser root 687K Jul 20 09:37 libfbSampleDbCrypt.so.debug
-rw-r--r--. 1 bluser root 337K Jul 20 09:37 libfbSampleExtAuth.so.debug
-rw-r--r--. 1 bluser root 728K Jul 20 09:37 libfbSampleKeyHolder.so.debug
```
no eXecutable bit on files in
``examples/prebuilt/plugins/.debug/``
and owner (all) debug-files is not root, but user with id=1000 (Ben Lee User on my test system)

**Comment by AlexPeshkoff** [comment]
I do not see non-root files in tgz:

# tar tvzf Firebird-debuginfo-4.0.2.2816-0.amd64.tar.gz 
drwxr-xr-x root/root         0 2022-08-10 13:51 ./
drwxr-xr-x root/root         0 2022-08-10 13:51 ./opt/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/misc/
-rw-r--r-- root/root      1594 2022-08-10 13:52 ./opt/firebird/misc/manifest_debug.txt
drwxr-xr-x root/root         0 2022-08-10 13:51 ./opt/firebird/plugins/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/plugins/.debug/
-rwxr-xr-x root/root  14480960 2022-08-10 13:51 ./opt/firebird/plugins/.debug/libChaCha.so.debug
-rwxr-xr-x root/root  15544808 2022-08-10 13:52 ./opt/firebird/plugins/.debug/libSrp.so.debug
-rwxr-xr-x root/root  15410192 2022-08-10 13:51 ./opt/firebird/plugins/.debug/libudr_engine.so.debug
-rwxr-xr-x root/root  24218088 2022-08-10 13:51 ./opt/firebird/plugins/.debug/libfbtrace.so.debug
-rwxr-xr-x root/root  15179136 2022-08-10 13:51 ./opt/firebird/plugins/.debug/libLegacy_UserManager.so.debug
-rwxr-xr-x root/root 163142504 2022-08-10 13:51 ./opt/firebird/plugins/.debug/libEngine13.so.debug
-rwxr-xr-x root/root  15409728 2022-08-10 13:52 ./opt/firebird/plugins/.debug/libLegacy_Auth.so.debug
drwxr-xr-x root/root         0 2022-08-10 13:51 ./opt/firebird/plugins/udr/
drwxr-xr-x root/root         0 2022-08-10 13:51 ./opt/firebird/plugins/udr/.debug/
-rwxr-xr-x root/root   2744256 2022-08-10 13:51 ./opt/firebird/plugins/udr/.debug/libudrcpp_example.so.debug
-rwxr-xr-x root/root   1248032 2022-08-10 13:51 ./opt/firebird/plugins/udr/.debug/libudf_compat.so.debug
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/lib/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/lib/.debug/
-rwxr-xr-x root/root     70072 2022-08-10 13:52 ./opt/firebird/lib/.debug/libib_util.so.debug
-rwxr-xr-x root/root  34187264 2022-08-10 13:52 ./opt/firebird/lib/.debug/libfbclient.so.4.0.2.debug
-rwxr-xr-x root/root    431656 2022-08-10 13:52 ./opt/firebird/lib/.debug/libtomcrypt.so.1.0.1.debug
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/examples/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/plugins/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/plugins/.debug/
-rw-r--r-- root/root    744880 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/plugins/.debug/libfbSampleKeyHolder.so.debug
-rw-r--r-- root/root    702816 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/plugins/.debug/libfbSampleDbCrypt.so.debug
-rw-r--r-- root/root    344424 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/plugins/.debug/libfbSampleExtAuth.so.debug
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/bin/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/bin/.debug/
-rwxr-xr-x root/root    669840 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/bin/.debug/fbSampleDbCryptApp.debug
-rwxr-xr-x root/root    154720 2022-08-10 13:52 ./opt/firebird/examples/prebuilt/bin/.debug/fbSampleExtAuthKeygen.debug
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/bin/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/bin/.debug/
-rwxr-xr-x root/root  26795032 2022-08-10 13:52 ./opt/firebird/bin/.debug/gbak.debug
-rwxr-xr-x root/root  14880304 2022-08-10 13:52 ./opt/firebird/bin/.debug/fb_lock_print.debug
-rwxr-xr-x root/root  17936400 2022-08-10 13:52 ./opt/firebird/bin/.debug/isql.debug
-rwxr-xr-x root/root  16014560 2022-08-10 13:52 ./opt/firebird/bin/.debug/gsec.debug
-rwxr-xr-x root/root  15210144 2022-08-10 13:52 ./opt/firebird/bin/.debug/gstat.debug
-rwxr-xr-x root/root  19422848 2022-08-10 13:52 ./opt/firebird/bin/.debug/gpre.debug
-rwxr-xr-x root/root  14943560 2022-08-10 13:52 ./opt/firebird/bin/.debug/nbackup.debug
-rwxr-xr-x root/root  24739416 2022-08-10 13:52 ./opt/firebird/bin/.debug/firebird.debug
-rwxr-xr-x root/root  14727248 2022-08-10 13:52 ./opt/firebird/bin/.debug/fbtracemgr.debug
-rwxr-xr-x root/root  18335104 2022-08-10 13:52 ./opt/firebird/bin/.debug/qli.debug
-rwxr-xr-x root/root  15092304 2022-08-10 13:52 ./opt/firebird/bin/.debug/gfix.debug
-rwxr-xr-x root/root  14196960 2022-08-10 13:52 ./opt/firebird/bin/.debug/gsplit.debug
-rwxr-xr-x root/root  14682032 2022-08-10 13:52 ./opt/firebird/bin/.debug/fbsvcmgr.debug
-rwxr-xr-x root/root  14185704 2022-08-10 13:52 ./opt/firebird/bin/.debug/fbguard.debug
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/intl/
drwxr-xr-x root/root         0 2022-08-10 13:52 ./opt/firebird/intl/.debug/
-rwxr-xr-x root/root  17021720 2022-08-10 13:52 ./opt/firebird/intl/.debug/fbintl.debug

What about executable bit in debug info files - for gdb it makes no difference is it set or not.

**Comment by aafemt** [comment]
IIRC tar on decompress sets owner to the current user if stored owner is root thus this visual issue.

**Comment by AlexPeshkoff** [comment]
If untaring user is not root all ownership will be set to current user, 
no matter what was in tar file.
