### ISSUE TITLE
Starting operator become unstable on indexed varchar fields

### ISSUE THREAD

**Issue by aschegolskiy** [FirebirdSQL/firebird#7237]
Afer upgrading FB from version 3.0.6.33328 to 3.0.10.33601 behaviour of starting operator become unstable.
Sometimes it doesn't match strings that shoud be matched.
```
-- Metadata. Database created with default character set UTF8 and collation UNICODE_CI

CREATE TABLE TEST (STR_FIELD VARCHAR(10) CHARACTER SET UTF8 COLLATE UNICODE_CI);
CREATE INDEX TEST_IDX1 ON TEST (STR_FIELD);
INSERT INTO TEST (STR_FIELD) VALUES ('ПАПА');
-- Tests
select * from test where str_field starting 'П'    -- Found
select * from test where str_field starting 'ПА'   -- Not found
select * from test where str_field starting 'ПАП'  -- Found
select * from test where str_field starting 'ПАПА' -- Not found

Plan
--------------------------------------------------------------------------------
PLAN (TEST INDEX (TEST_IDX1))
```
I think it related with index on this field. If index isn't used, it works as expected.
```
-- Tests
select * from test where str_field || '' starting 'П'    -- Found
select * from test where str_field || '' starting 'ПА'   -- Found
select * from test where str_field || '' starting 'ПАП'  -- Found
select * from test where str_field || '' starting 'ПАПА' -- Found

Plan
--------------------------------------------------------------------------------
PLAN (TEST NATURAL)
```

**Comment by asfernandes** [comment]
I cannot reproduce this in Linux.

I even created the database, table and data in 3.0.6 and used it in 3.0.10.

All queries return data.

**Comment by aschegolskiy** [comment]
I've tested it on: 
Microsoft Windows Server 2008 R2 Enterprise 6.1.7601 Service Pack 1 build 7601
Microsoft Windows 10 Pro 10.0.19044 build 19044

**Comment by dyemanov** [comment]
What is the connection charset?

**Comment by aschegolskiy** [comment]
UTF8

**Comment by hvlad** [comment]
I can confirm it using non-unicode console in Windows. 
Checked with both dos866 and win1251 charset\codepage.

**Comment by aschegolskiy** [comment]
Do I need to provide additional information?

**Comment by asfernandes** [comment]
I now reproduced it in Windows.

**Comment by asfernandes** [comment]
Please test fix in the next snapshot.

**Comment by aschegolskiy** [comment]
I can confirm that it works on the snapshot build 3.0.11.33615 (Microsoft Windows 10 Pro 10.0.19044)
Thank you
