### ISSUE TITLE
mac installer - firebird user not created correctly if group already exists

### ISSUE THREAD

**Issue by hmoffatt** [FirebirdSQL/firebird#7241]
If the firebird group already exists but the user doesn't (which can occur if you use the new Mac transfer process / migration assistant), the installer creates a new user that is has no primary group, which is invalid, and the Firebird service won't start.

This occurs because of a bug in the [install-script](firebird/blob/master/builds/install/arch-specific/darwin/install-script):

1. line 25 determines that the group already exists, so $gid is not set
2. line 58 uses the unset $gid as the primary group id of the user

Now macOS won't use the new user, and you can't "su - firebird" etc to it, until the group id is set.

**Comment by e787** [comment]
Hi @hmoffatt,

I've added this code after line 25:
`gid=$(dscl localhost -read /Local/Default/Groups/firebird PrimaryGroupID | awk '($1 == "PrimaryGroupID:") { print $2 }')`
Which should get the ID from the group if it's found by the script.

Here's a patch file: [patch.tar.gz](https://github.com/FirebirdSQL/firebird/files/9351643/firebird_user_not_created_correctly_if_group_already_exists.patch.tar.gz)

Could you try if this solves the problem?

P.S.: I'm no shell script expert, just trying my best to help.

**Comment by hmoffatt** [comment]
Thanks @e787 , it looks good to me on code review, and your command certainly extracts the existing gid ok. I don't have the failing environment any more and I don't know how to build Firebird including the Mac packaging, so I didn't test it in context.

**Comment by asfernandes** [comment]
Thanks, I committed the fix in master and v4 branch.

You may download installer [here](https://github.com/FirebirdSQL/firebird/actions/runs/2871874379) after the build is done.
