### ISSUE TITLE
getTemporaryFolder() always returns NULL

### ISSUE THREAD

**Issue by mariuszzy** [FirebirdSQL/firebird#7250]
I'm trying to figure out where temporary files are created under UNIX and have found a ridiculous function getTemporaryFolder() in src/common/os/mac_utils.h used a couple of times in: 

src/common/classes/TempFile.cpp
src/yvalve/gds.cpp

Maybe I've missed something but It looks like it needs a bit of rethinking.

Trying to build firebird-4.0.1.2692-0 under Solaris.

**Comment by hvlad** [comment]
Path for temporary files is evaluated as follows
a) look for FIREBIRD_TMP environment variable, if empty
b) try to get OS-specific way, if empty
c) try hard-coded folder (also OS specific)

b) implemented as
b1) call GetTempPath() on Windows
b2) look for TMP env var on Linux 
b3) call getTemporaryFolder() on MacOS (DARWIN)

To simplify code a bit, there is hand-made impl of getTemporaryFolder() for UNIX (not DARWIN)
that always return NULL and makes engine to fallback to (b2).

Hope it is less ridiculous  now.

**Comment by mariuszzy** [comment]
Thanks for shedding significant amount of light on that. Indeed, the file name mac_utils.h made me thinking it is MAC OS not Media Access Control related, but it sits in os/common not os/darwin folder. Stupid me. I'd expect conditional where getTemporaryFolder() gets called not where it is implemented to avoid useless call. That way I wouldn't dig that deep searching where getTemporaryFolder() is implemented as it is not my case, I mean UNIX/Solaris build.

Now, I think I understand the portion of code in src/yvalve/gds.cpp where similar schema is used. There is just another set of read-only viariables: FB_TMP_ENV vs ENV_VAR and WORKFILE vs DEFAULT_PATH. Yeah, I know I'm picking on. I'm just trying to find the best place to create /tmp/firebird folder. I can do that in a wrapper script but prefer to avoid that for some reasons.

Any way, open source is nice in that we can change everything to our liking.
