### ISSUE TITLE
Firebird 5 crash executing statement

### ISSUE THREAD

**Issue by cincuranet** [FirebirdSQL/firebird#7263]
After sending `op_execute` for `select MON$REMOTE_PROCESS from MON$ATTACHMENTS` Firebird 5.0.0.661 crashes with AV. Happens repeatedly. 

Attached is [memory dump](https://github.com/FirebirdSQL/firebird/files/9337005/firebird.exe_220815_134622.7z.txt) for the AV. And also builds of the app crashing the server for [Windows](https://github.com/FirebirdSQL/firebird/files/9337003/crash-win10-x64.7z.txt) and [Linux](https://github.com/FirebirdSQL/firebird/files/9337000/crash-linux-x64.7z.txt) (just start `FirebirdSql.Data.FirebirdClient.Tests` and have a `localhost`/`sysdba`/`masterkey` Firebird running).

**Comment by hvlad** [comment]
Check latest build, please.
See also #7261

**Comment by cincuranet** [comment]
At the moment I see [snapshot directory](http://web.firebirdsql.org/download/snapshot_builds/win/5.0/) empty. Is [this build](https://github.com/FirebirdSQL/firebird/actions/runs/2859449579) sufficient?

**Comment by cincuranet** [comment]
Looks like the build has it fixed.
