### ISSUE TITLE
Please document how to create a user mapping from a linux user to sysdba for use with embedded sql

### ISSUE THREAD

**Issue by DeanAnderson89** [FirebirdSQL/firebird#7279]
Grant RDB$ADMIN to 'kali'  has no effect.

SQLCODE: -551
SQL ERROR:
This user does not have privilege to perform this operation on this object.

ISC STATUS: 
no permission for SELECT access to TABLE FLAPSSVRALL

**Comment by DeanAnderson89** [comment]
This code worked with Firebird 1.5.
It appears something changed in Firebird 2.5, but the suggested solution (for Windows) doesn't work on Linux.

**Comment by mrotteveel** [comment]
This sounds more like a support question. Please use [firebird-support](https://groups.google.com/g/firebird-support) for support questions. Please make sure to include the exact command you tried, how you are connecting, and exactly what you're trying to achieve.

Also refer to [Mapping of Users to Objects](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-security-mapping) in the Firebird 4.0 Language Reference.
