### ISSUE TITLE
Concurrent NBackup crashes server on Linux

### ISSUE THREAD

**Issue by gerdus** [FirebirdSQL/firebird#7281]
I have a backup job that creates backups using nbackup for 20+ databases in batches of 3 at a time.
NBackup is called via C#/.Net Provider.
Since 4.0.2 it crashes the firebird server on Linux.  (4.0.1 didn't have this issue but did have the attach/detach crash that was fixed)
The only message in firebird.log is
`/opt/firebird/bin/fbguard: /opt/firebird/bin/firebird terminated abnormally (-1)`

When I try it on windows, it doesn't crash but I do get the following:
`Operating system call ReleaseSemaphore failed. Error code 6`

Firebird version: Firebird-4.0.2.2816-0-x64

**Comment by gerdus** [comment]
Switching to SuperClassic from SuperServer seems to be a workaround - last two backup runs worked. still monitoring.

**Comment by hvlad** [comment]
What params is used to create backup ?
Is there user attachments to the databases ?
Could you provide reproducible test case ?
Or coredump, when it crashes on Linux.
So far, I can't reproduce it on Windows.

**Comment by gerdus** [comment]
>What params is used to create backup 
backup level 1 with NoDatabaseTriggers
>Is there user attachments to the databases ?
Very likely that there are attachment/connections to some/most of the databases during the backup.
>Could you provide reproducible test case ?
I was unable to build a simple test. I can repro the "ReleaseSemaphore failed" on windows using a simple c# program but running the same code on linux does not.
>Or coredump, when it crashes on Linux.
Coredump: https://www.dropbox.com/s/kfz8hhk7mq86pyq/firebirdcrash.coredump.gz?dl=0
in system log this entry: 
kernel: Code: Bad RIP value.
kernel: firebird[1690364]: segfault at 0 ip 0000000000000000 sp 00007ffed66cf718 error 14 in firebird[400000+204000]

**Comment by hvlad** [comment]
> > Could you provide reproducible test case ?
> 
> I was unable to build a simple test. I can repro the "ReleaseSemaphore failed" on windows using a simple c# program

I can start with it.


> > Or coredump, when it crashes on Linux.
> 
> Coredump: https://www.dropbox.com/s/kfz8hhk7mq86pyq/firebirdcrash.coredump.gz?dl=0

@AlexPeshkoff: could you look at it, pls ?

**Comment by gerdus** [comment]
Link to c# test program that gives the "ReleaseSemaphore failed" error on windows
[https://infireal.com/github-issues/firebird-nbackup-crashes-server.zip](https://infireal.com/github-issues/firebird-nbackup-crashes-server.zip)

The code is nearly identical to what is used in the production app.

Precompiled binaries for windows and linux are in publish directory. Change the username/password in config.ini next to the binary to fit own environment.

**Comment by AlexPeshkoff** [comment]
On 8/31/22 14:10, Vlad Khorsun wrote:
>
>         Could you provide reproducible test case ?
>
>     I was unable to build a simple test. I can repro the
>     "ReleaseSemaphore failed" on windows using a simple c# program
>
> I can start with it.
>
>         Or coredump, when it crashes on Linux.
>
>     Coredump:
>     https://www.dropbox.com/s/kfz8hhk7mq86pyq/firebirdcrash.coredump.gz?dl=0
>
> @AlexPeshkoff <https://github.com/AlexPeshkoff>: could you look at it, 
> pls ?
>

Download now.

**Comment by hvlad** [comment]
> Link to c# test program that gives the "ReleaseSemaphore failed" error on windows

Reproduced, thanks. Investigating now.

**Comment by gerdus** [comment]
Thank you for the quick work!
Seems the "ReleaseSemaphore failed" message on windows is gone.

I have also perhaps unwisely installed the nightly build (4.0.3.2831) on the production server after some quick tests.
Will be monitoring closely for the next few days to see if the problem happens again.

Thank You

**Comment by AlexPeshkoff** [comment]
@gerdus 
Recommend to check snapshot status here http://firebirdtest.com/ before installing in production.

**Comment by AlexPeshkoff** [comment]
Fixed frontported to master (https://github.com/FirebirdSQL/firebird/commit/c3be5edecb1492e4e61e6f1d64e35d31eb85ed0b) but not marked in tags cause we did not have releases with this bug.

**Comment by hvlad** [comment]
Should add that the bug itself is not related with nbackup, it is about interaction of services manager with network server and dispatcher.

**Comment by AlexPeshkoff** [comment]
On 8/29/22 16:20, Gerdus van Zyl wrote:
>
> I have a backup job that creates backups using nbackup for 20+ 
> databases in batches of 3 at a time.
> NBackup is called via C#/.Net Provider.
> Since 4.0.2 it crashes the firebird server on Linux.
> The only message in firebird.log is
> |/opt/firebird/bin/fbguard: /opt/firebird/bin/firebird terminated 
> abnormally (-1)|
>
Article http://www.ibphoenix.com/resources/documents/search/doc_36

It's rather old but method recommended in it does work.
