### ISSUE TITLE
install.sh for ARM64 missing functions

### ISSUE THREAD

**Issue by mgkahn** [FirebirdSQL/firebird#7289]
ARM64: Firebird-4.0.2.2816-0.arm64.tar.gz
Host: Ubuntu 22.04.1 LTS (jammy) (aarch64)

No install.sh script at installation root directory
/bin/install.sh missing all functions.

Tried install.sh from amd64 tar.gz w/o success.

**Comment by mrotteveel** [comment]
The Firebird-4.0.2.2816-0.arm64.tar.gz from https://firebirdsql.org/en/firebird-4-0-2/ is not a generic Linux ARM64 build, as that download page shows, it is meant for Android only. The Firebird project currently does not offer a Linux build for ARM64. I believe it is possible to build it yourself, but I suggest you ask about that on the firebird-devel mailinglist.
