### ISSUE TITLE
Unique index and charset UTF8 collate UNICODE_CI_AI

### ISSUE THREAD

**Issue by bibilen** [FirebirdSQL/firebird#7290]
database character set is UTF8.

CREATE TABLE DEMO (
    ID    INTEGER NOT NULL,
    NAME  VARCHAR(80) COLLATE UNICODE_CI_AI
);

ALTER TABLE DEMO ADD CONSTRAINT PK_DEMO PRIMARY KEY (ID);
**CREATE UNIQUE INDEX IDX_DEMO__1 ON DEMO COMPUTED BY (lower(name));**

insert into demo(id, name) values (1, 'A'); -> done. ok
insert into demo(id, name) values (2, 'a'); -> error. ok. This is correct mistake. No problem. : attempt to store duplicate value (visible to active transactions) in unique index "IDX_DEMO__1". Problematic key value is (<expression> = 'a').

insert into demo(id, name) values (3, 'i'); -> done. ok
insert into demo(id, name) values (4, 'ı'); -> **done. not ok :  Shouldn't Firebird be throwing an error here?**

**Comment by mrotteveel** [comment]
As far as I'm aware, except maybe for Turkey, 'ı' is not considered a variant of 'i'. If you need Turkish rules, you need to create ansd use a custom collation.
