### ISSUE TITLE
gbak: -service and -fetch_password don't work together

### ISSUE THREAD

**Issue by Bangaio65** [FirebirdSQL/firebird#7297]
gfix version LI-V2.5.7.27050 Firebird 2.5
OS: CentOS 6.1

Either of these commands work:
`gbak -user SYSDBA -pas masterkey -rep -service localhost:service_mgr db.gbk db.gdb`
`gbak -user SYSDBA -fetch_password fbird.pwd -rep db.gbk localhost:db.gdb`

But this doesn't work:
`gbak -user SYSDBA -fetch_password fbird.pwd -rep -service localhost:service_mgr db.gbk db.gdb`

Error is:
```
gbak: ERROR:Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
gbak:Exiting before completion due to errors
```

**Comment by AlexPeshkoff** [comment]
Dup https://github.com/FirebirdSQL/firebird/issues/6250 (fixed almost 3 years ago). Upgrade please - fb2.5 is not supported long ago.
