### ISSUE TITLE
New constants for psql for better clean code

### ISSUE THREAD

**Issue by gladiston** [FirebirdSQL/firebird#7310]
Will be welcome a new constants to do more clean psql code.
New constant *emptyStr* for empty string, examples:  
old: if (:param1<>'') then...
new: if (:param1<>emptyStr) then...

New constant *LineEnding* for correct identification for line ending:
old: while position(ASCII_CHAR(13), str)>0 do...
new:while position(LineEnding, str)>0 do...
well that usefull include : LineEndingUnix and LineEndingWindows to make more especific.

There is much more constants that I will lke to see, but this ones is more repetitive.

**Comment by mrotteveel** [comment]
I think using `''` is far more readable and less verbose than `emptyStr`, and instead of `ASCII_CHAR(13)`, you could use `x'0D'`

**Comment by gladiston** [comment]
Sometimes, won´t see ' ' with whitespace inside(#32) or inverse, specially when looking for a bug. I won´t remove '', just add alternate way to write the same code and maximize clean code with usefully constants.

**Comment by aafemt** [comment]
Fixed-size font is useful for that.

**Comment by gladiston** [comment]
> Fixed-size font is useful for that.
You think only in sql editors, that by way, always use mono-fonts. I think that ellegant code can be use as a documentation.

**Comment by gladiston** [comment]
> Fixed-size font is useful for that.

You think only in sql editors, that by way, always use mono-fonts. I think that ellegant code can be use as a documentation.

**Comment by asfernandes** [comment]
General packaged constants would be much more useful for you name things the way you want.
https://github.com/FirebirdSQL/firebird/issues/3411 could be changed for constants too.
