### ISSUE TITLE
New notation to identify ansi char to make better clean code psql

### ISSUE THREAD

**Issue by gladiston** [FirebirdSQL/firebird#7311]
A new predicative or notation to identify ansi string like:
old: while (position(ASCII_CHAR(13), str)>0) do...
new:while (position(#13, str)>0) do...
or new:while (position('\n', str)>0) do...

Just to make better clean code psql.

**Comment by mrotteveel** [comment]
Your second example cannot be implemented in that way, as that would change how literals work (a '\n' is two characters, a `\` and a `n`, not a single character), and thus would break existing applications. As an aside, generally, the character escape \n is character 10/x0A, not character 13/x0D.

**Comment by gladiston** [comment]
> You can use `x'0D'`, or if you really want it as ASCII, `_ascii x'0D'`. Although there might be a good use for a general escape mechanism, that would be better served by implementing SQL standard Unicode string literals.

For a better world, less quotes in psql, in think ;-)
I know about hexa notation, but my intentation is maximize clean code in psql.
The second way, I know that is hard and complex. I put only becase escape codes are much common in very languages. I don't expect you to implement it because  its too complex.
