### ISSUE TITLE
FB 4.0.2 execute statement on remote randomly raises error with codes: 335544344, 335545107 Super server on Linux

### ISSUE THREAD

**Issue by andrewkip** [FirebirdSQL/firebird#7312]
After upgrading FB to 4.0.2 (and same error on snapshot build 2845) we start receiving randomly arasing errors
on execute statment on remote DB see below.

Both DB otc_blob202203.fdb and so.fdb queried by execute statement on remote. 
Error does not apear If we have at least 1 connect to remote DB.

Fb 4.0.1 has no this error.

Unsuccessful execution caused by system error that does not preclude successful execution of subsequent statements.
Execute statement error at attach :
335544344 : I/O error during "lock" operation for file "/DATA_HDD/fb/blob/otc_blob202203.fdb"
335545107 : Database already opened with engine instance, incompatible with current
Data source : Firebird::dbsrvblob02.otc.pharm:otc_blob202203.
At procedure SYS_BLOB_DATA_GET line: 34, col: 9
At procedure PM_BLOB_DATA_GET line: 22, col: 7
At block line: 19, col: 9.

DBD::Firebird::st fetchrow_hashref failed: Unsuccessful execution caused by system error that does not preclude successful execution of subsequent statements -Execute statement error at attach :
335544344 : I/O error during "lock" operation for file "/DATA_SSD/fb/so.fdb"
335545107 : Database already opened with engine instance, incompatible with current Data source : Firebird::otcsodb.otc.pharm:so -At procedure 'DB_REMOTE_AVAILABLE_FLAG_GET2' line: 14, col: 3 At procedure 'DB_CONNECTION_INFO_GET' line: 53, col: 9 At procedure 'SYNC_EXT_SOURCE_GET' line: 19, col: 9 at /opt/etms/modules//ETMSExtSyncTools.pm line 60.

**Comment by AlexPeshkoff** [comment]
Almost for sure your databases sometimes accessed embedded. What other tasks (except access using execute statement on external) are performed with that DBs?

**Comment by andrewkip** [comment]
About embeded connection was our first thought.
We have session logging  and there are no embeded connections.
All conncetions to this db are using execute statement on external.
there is no error if at least 1 connection exisst to this db.
One more thing: as I can see - error raises when many short (session lasts <1 second) concurrent connections  (all  execute statement on external) to this DB.

**Comment by aafemt** [comment]
Switch server mode to superserver.

**Comment by andrewkip** [comment]
> Switch server mode to superserver.

Server is in superserver mode.

**Comment by AlexPeshkoff** [comment]
Andrew, you've written:
> After upgrading FB to 4.0.2 (and same error on snapshot build 2845)

I must say that for 2845 observed behavior is known (to me) bug and will be fixed soon. Can you confirm (once again) it also takes place on release 4.0.2?

**Comment by andrewkip** [comment]
I've checked carefully once again and I was wrong.
It takes place on snapshot build 2845 only.
It does not take place on release 4.0.2
I'm sorry for misleading you.

**Comment by andrewkip** [comment]
Should I rename issue?
