### ISSUE TITLE
Multitreaded activating indices restarts server process

### ISSUE THREAD

**Issue by aschegolskiy** [FirebirdSQL/firebird#7314]
I did backup and resored database without inices. After that I used a program for multithreaded activation of indices - plume (https://github.com/NeoZX/plume).
Server hangs with error:
Fatal lock manager error: invalid lock id (173352), errno: 0
It was about 5-10 times with the same results. I've tested it on two different machines, HQBird 3.0.11.33622, Firebird 3.0.6.33328. Both x64 Win versions.
Shoud the activation of indices be used only using only one thread?
[server_log.txt](https://github.com/FirebirdSQL/firebird/files/9631410/server_log.txt)

**Comment by hvlad** [comment]
Coudl you provide reproducible test case ?
Or stack trace\full memory dump of hung process.

**Comment by aschegolskiy** [comment]
Of course. Could you please provide the instructions, how can I do it?

**Comment by hvlad** [comment]
How to create reproducible test case:
- provide application
- provide database
- provide steps to reproduce the issue

How to get full memory dump on Windows for given process:
- [procdump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump) -ma \<process name or ID\>

**Comment by hvlad** [comment]
For memory dumps, please, use Firebird 3.0.10 release or latest snapshot build.

**Comment by aschegolskiy** [comment]
I am not shure, I can predict the moment when FB restart occures, to exectute procdump. Is there a way to catch this?

**Comment by hvlad** [comment]
You told that process is hung, isn't it ?

If process crashed actually, you could read carefully description of procdump above or this article
[Collecting User-Mode Dumps](https://learn.microsoft.com/uk-ua/windows/win32/wer/collecting-user-mode-dumps)

**Comment by hvlad** [comment]
Any new info ?

**Comment by aschegolskiy** [comment]
I installed Firebird-3.0.10.33601_0_x64.exe, with pdb. Then run plume and the procdump64 (in another window) and got the 10Gb dump file.
E:\>procdump64.exe -ma -e -t 10772
If the command is correct, where can I store the dump?

**Comment by aschegolskiy** [comment]
Compressed dump is 28 MB

**Comment by hvlad** [comment]
Dump 10GB - looks like you uses big page cache. Anyway, 28MB compressed is not big for download.

Is google drive ok for you ?

**Comment by aschegolskiy** [comment]
Sorry, the previous dump was get on a broken database. I'm not shure it can be useful.
I prepared two another dumps, one with db page cache = 625000 pages, other with default page cache but big temporary space (TempCacheLimit = 30311M).
Both dumps have 10Gb size, but 7z archives not as small as previous: 924Mb and 1,28Gb respectively. Google Drive is OK for me. Are the file sizes OK for you?
Restore with both options crashes server process, with such messages in firebird log:
	Fatal lock manager error: invalid lock id (300832), errno: 0
After each crash, sweep finds a lot of orphan pages in the database:
	Warning: Page 14319679 is an orphan

**Comment by aschegolskiy** [comment]
I've got the smaller dump. Archive only 42MB. How can I pass the link to Google Drive?

**Comment by hvlad** [comment]
All mentioned above file sizes are not a problem for me.
You may put link here or send it to me privately (hvlad at users sf net) if required.

**Comment by aschegolskiy** [comment]
Great! I sent the email with links.

**Comment by aschegolskiy** [comment]
Actually even default server configuration with default db cache pages gives mentioned above behaviour. I can provide dump if necessary.

**Comment by aschegolskiy** [comment]
@hvlad Test build looks working. There were no server crushes after 5-7 restores of indexes with different number of threads.

**Comment by aschegolskiy** [comment]
@hvlad Thanks a lot!
