### ISSUE TITLE
4.0.2 : bin_and not avaiable

### ISSUE THREAD

**Issue by drcrck** [FirebirdSQL/firebird#7325]
Hi, i have error with last stable release versione with "bin_and" command.
it seems not available. 
(it's used by Firedac in Delphi in some way to get metadata.)

in 4.0.1 it's all ok.

**Comment by hvlad** [comment]
Works OK:
```
SQL> show version;
ISQL Version: WI-V4.0.2.2816 Firebird 4.0
Server version:
Firebird/Windows/AMD/Intel/x64 (access method), version "WI-V4.0.2.2816 Firebird 4.0"
on disk structure version 13.0
SQL>
SQL> select bin_and(15, 3) from rdb$database;

     BIN_AND
============
           3
```

Do you have a test case ?

**Comment by drcrck** [comment]
thanks Vlad. 
this issue seems to be related to Delphi Firedac library.

it execute this query to retrive tables list, and there's same parsing error settings parameters.
thanks


SELECT CAST(NULL AS NUMERIC) AS RECNO, CAST(NULL AS VARCHAR(67)) AS CATALOG_NAME, CAST(NULL AS VARCHAR(67)) AS SCHEMA_NAME,
RDB$RELATION_NAME AS TABLE_NAME, 
CASE WHEN RDB$VIEW_BLR IS NULL THEN 
CASE BIN_AND(COALESCE(RDB$FLAGS, 0), 31) WHEN 0 THEN 1 WHEN 1 THEN 1 WHEN 2 THEN 3 WHEN 8 THEN 3 WHEN 16 THEN 3 
END
ELSE 2 END AS TABLE_TYPE, 
CASE COALESCE(RDB$SYSTEM_FLAG, 0) WHEN 0 THEN CASE COALESCE(RDB$OWNER_NAME, '') 
WHEN USER THEN 0 ELSE 1 END ELSE 2
 END AS TABLE_SCOPE FROM RDB$RELATIONS
 
WHERE (BIN_AND(COALESCE(RDB$FLAGS, 0), 31) IN (0, 1) AND RDB$VIEW_BLR IS NULL OR RDB$VIEW_BLR IS NOT NULL) 
AND TRIM(TRAILING ' ' FROM RDB$RELATION_NAME) LIKE ? AND ((RDB$SYSTEM_FLAG IS NULL OR RDB$SYSTEM_FLAG = 0) 
AND COALESCE(RDB$OWNER_NAME, '') = USER OR (RDB$SYSTEM_FLAG IS NOT NULL AND RDB$SYSTEM_FLAG > 0)) 
ORDER BY 4

**Comment by drcrck** [comment]
Hi, it seems related to some of out FDB files. 
with some DBs it works, with others no

```
ISQL Version: WI-V4.0.1.2692 Firebird 4.0
Use CONNECT or CREATE DATABASE to specify a database
SQL> connect db;
Server version:
WI-V4.0.1.2692 Firebird 4.0
Database: db, User: DIEGO
SQL> select bin_and(15, 3) from rdb$database;
Statement failed, SQLSTATE = 39000
invalid request BLR at offset 36
-function BIN_AND is not defined
-module name or entrypoint could not be found
SQL>

```

**Comment by dyemanov** [comment]
You have BIN_AND defined as UDF in some databases, thus the issue.

**Comment by drcrck** [comment]
> You have BIN_AND defined as UDF in some databases, thus the issue.

i'll check thanks!
