### ISSUE TITLE
CURRENT_TIMESTAMP doesnt use index

### ISSUE THREAD

**Issue by MaartenJB** [FirebirdSQL/firebird#7327]
Hi,

Is there a reason why when I use CURRENT_TIMESTAMP in the where clause it doesn't use my index? If I replace it with CURRENT_DATE it does use my index.

Fieltype I query = TIMESTAMP

example index is NOT used:
`SELECT 
  TIME_STAMP
FROM 
  TB_RESULTS 
WHERE TIME_STAMP < CURRENT_TIMESTAMP`

example index is used:
`SELECT 
  TIME_STAMP
FROM 
  TB_RESULTS 
WHERE TIME_STAMP < CURRENT_DATE`

Best regards,

Maarten

**Comment by aafemt** [comment]
By design: CURRENT_TIMESTAMP has type TIMESTAMP WITH TIME ZONE. You must use LOCALTIMESTAMP.

**Comment by MaartenJB** [comment]
> By design: CURRENT_TIMESTAMP has type TIMESTAMP WITH TIME ZONE. You must use LOCALTIMESTAMP.

Aah, ok, thank you for your fast response!

> PS: And don't use issue tracker for support questions, please.

Sorry for that, I didn't know where to put it.

**Comment by MaartenJB** [comment]
Wrongly put support request here (sorry)

**Comment by mrotteveel** [comment]
> Sorry for that, I didn't know where to put it.

The correct replace is https://groups.google.com/g/firebird-support 

Also check the Firebird 4.0 release notes, section [Changes in DDL and DML Due to Timezone Support](https://www.firebirdsql.org/file/documentation/release_notes/html/en/4_0/rlsnotes40.html#rnfb40-compat-sql-timezone-changes)

**Comment by livius2** [comment]
Sorry for the question. But why it do not use the index. Even if CURRENT_TIMESTAMP is TIMESTAMP WITH TIME ZONE it should use the index isynt it? 
Isn't CURRENT_TIMESTAMP converted to something and compared then with the field "TIME_STAMP"?
It looks like it work now in reverse order. Convert field "TIME_STAMP" to TIMESTAMP WITH TIME ZONE and then compare with CURRENT_TIMESTAMP. Isn't this bad?
