### ISSUE TITLE
Firebird - Silently install with SYSDBA password

### ISSUE THREAD

**Issue by Brownie9** [FirebirdSQL/firebird#7330]
Hello,

I'm trying to install Firebird silently with Ansible: https://github.com/FirebirdSQL/firebird/releases/download/R2_5_9/FirebirdSS-2.5.9.27139-0.amd64.tar.gz
Is there an option to enter the requested password for SYSDBA on the command line ?

I didn't find it in the documentation.

Thank you so much.

**Comment by AlexPeshkoff** [comment]
No - there is no such option, with silent install auto-generated password is always used. 
Later please use https://groups.google.com/g/firebird-support for support questions.
