### ISSUE TITLE
Rows affected not being returned when performing a "MERGE ... WHEN MATCHING ..."

### ISSUE THREAD

**Issue by dalezz** [FirebirdSQL/firebird#7343]
Hi,
I'm having issues in Delphi trying get back the number of rows affected when performing a "MERGE ... WHEN MATCHING ...".  The rows affected always returns 0(zero).  I'm using Delphi with Firebird 3.0.8.3353.  The rows affected count works for all insert, update, and delete statements successfully.

A similar issue has been raised previously, but for ISQL.  [#1927](https://github.com/FirebirdSQL/firebird/issues/1927)

To get the rows affected, I'm just calling `TIBQuery.RowsAffected;`  Is this still an issue, or is there a method to retrieve the count when executing a merge script?

**Comment by mrotteveel** [comment]
For support questions, please ask on https://groups.google.com/g/firebird-support. 

If you want to report a bug, please provide a minimal, reproducible example that demonstrates the problem. For reference, I cannot reproduce your problem with ISQL under Firebird 3.0.10, using the example of #1927, it correctly reports "Records affected: 5".

Firebird itself does not count "affected records", it counts inserts, deletes and updates separately, so likely `TIBQuery.RowsAffected` returns the wrong count (e.g. by only looking at updates, not inserts, etc).
