### ISSUE TITLE
sh_mem_length_mapped is 0 failed; The operation completed successfully.

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7344]
Hi!

We got this error message from FB server

"operating system directive shmem_data->sh_mem_length_mapped is 0 failed; The operation
completed successfully.  [SQLState:HY000, ISC error code:335544373]"

This is contradictory.

(will attach firebird.log when I get from customer)

**Comment by EPluribusUnum** [comment]
Server log does not contain this error.
Firebird 2.5.9 on Windows

[firebird.zip](https://github.com/FirebirdSQL/firebird/files/9771755/firebird.zip)

**Comment by AlexPeshkoff** [comment]
Firebird 2.5 is not supported for a long time
