### ISSUE TITLE
internal Firebird consistency check (Incorrect attempt to release shared memory) version LI-V4.0.3.2858 Firebird 4.0

### ISSUE THREAD

**Issue by andrewkip** [FirebirdSQL/firebird#7348]
I started receiving this message in firebird.log:

internal Firebird consistency check (Incorrect attempt to release shared memory) 

I'm using Firebird version LI-V4.0.3.2858 Firebird 4.0, in classic mode.

**Comment by mrotteveel** [comment]
For support questions, please go to https://groups.google.com/g/firebird-support. If you want to report a bug, please provide as much information as possible, which at minimum includes your Firebird version, platform, the message(s) in firebird.log and - if possible - steps to reproduce.

**Comment by mrotteveel** [comment]
Do you have a reproduction recipe that triggers this error?

**Comment by AlexPeshkoff** [comment]
Please set

**Comment by andrewkip** [comment]
> Do you have a reproduction recipe that triggers this erro


unfortunately we have no recipe but we have dumps - later we will send.

**Comment by sszaytsev83** [comment]
this is the error dump "internal Firebird consistency check (Incorrect attempt to release shared memory)"

[core.firebird.1665745028.1028654.zip](https://github.com/FirebirdSQL/firebird/files/9785597/core.firebird.1665745028.1028654.zip)

**Comment by sszaytsev83** [comment]
this is the error "Error while trying to read from file Resource temporarily unavailable" and "internal Firebird consistency check (Incorrect attempt to release shared memory)"

otcou2  Fri Oct 14 11:50:53 2022
        Database: /DATA_NVME/fb/otc_dev.fdb
        internal Firebird consistency check (Incorrect attempt to release shared memory)


otcou2  Fri Oct 14 11:50:53 2022
        I/O error during "read" operation for file "/DATA_NVME/fb/otc_dev.fdb"
        Error while trying to read from file
        Resource temporarily unavailable


[core.firebird.1665737453.854239.zip](https://github.com/FirebirdSQL/firebird/files/9785639/core.firebird.1665737453.854239.zip)

**Comment by AlexPeshkoff** [comment]
I also need snapshot binaries used by you to read core dump - they are already missing on our site.

**Comment by sszaytsev83** [comment]
if I understand correctly, then

[fb-bin.zip](https://github.com/FirebirdSQL/firebird/files/9786893/fb-bin.zip)

**Comment by AlexPeshkoff** [comment]
All /opt/firebird is needed.
Or install file + debuginfo file.

**Comment by andrewkip** [comment]
[/opt/firebird](https://oc.otcpharm.ru/index.php/s/5BDpB843tR5TZWW)

**Comment by andrewkip** [comment]
> All /opt/firebird is needed. Or install file + debuginfo file.

Sent link to your e-mail.

**Comment by andrewkip** [comment]
One more strange error :
otcou2  Sun Oct 16 19:24:07 2022
        Error in blocking action thread

        unavailable database

**Comment by AlexPeshkoff** [comment]
I've analyzed (more or less) core dump. But results are so strange that I want you to send me some libraries from your linux to make sure stack traces and specially memory state are correct. I need:

libatomic.so.1
libdl.so.2
libm.so.6
libgcc_s.so.1
libpthread.so.0
libthread_db.so.1
libc.so.6
libstdc++.so.6

**Comment by sszaytsev83** [comment]
this archive contains
specified libraries, no symlinks

[fb-so.zip](https://github.com/FirebirdSQL/firebird/files/9801261/fb-so.zip)

**Comment by AlexPeshkoff** [comment]
thanks that helped
strange effects gone

**Comment by sszaytsev83** [comment]
on firebird version -V4.0.3.2860 in super server mode, an error occurs
dmesg log: [Вт окт 18 12:50:18 2022] traps: firebird[148917] general protection fault ip:496aee sp:7f2f5f881378 error:0 in firebird[400000+20b000]

dump:
https://oc.otcpharm.ru/index.php/s/dnXpHdDdNgNB2TT

**Comment by AlexPeshkoff** [comment]
With your bug everything is rather confusing. There is one hypothesis - but we ourselves cannot verify it, because it is not clear how to reproduce it in the laboratory conditions. If I make a special build of current 4.0.3, can you check does it help?

**Comment by sszaytsev83** [comment]
> Can you show stack trace?
https://oc.otcpharm.ru/index.php/s/dnXpHdDdNgNB2TT

**Comment by sszaytsev83** [comment]
> With your bug everything is rather confusing. There is one hypothesis - but we ourselves cannot verify it, because it is not clear how to reproduce it in the laboratory conditions. If I make a special build of current 4.0.3, can you check does it help?

yes we can check

**Comment by AlexPeshkoff** [comment]
Special build at https://drive.google.com/drive/folders/1owLpvEbwTwy_bT2g91YVeMnFFaPNV4XV?usp=sharing

**Comment by AlexPeshkoff** [comment]
> Can you show stack trace?
> https://oc.otcpharm.ru/index.php/s/dnXpHdDdNgNB2TT

Please send me txt trace file separately to alexander.peshkoff@gmail.com, I use mobile connection to internet till Monday and do not want 5Gb archive right now.

**Comment by sszaytsev83** [comment]
na versii fb V4.0.3.2860 - voznikla yeshche odna oshibka: zavisla baza, pri popytke yeye razlochit' v dmesg poyavilas' oshibka:
[Cht okt 20 17:12:15 2022] fb_lock_print[1114421]: segfault at 7f7cf5667200 ip 00000000004102c0 sp 00007fff45c91210 error 4 in fb_lock_print[400000+146000]
[Cht okt 20 17:12:15 2022] Code: 48 81 ec 18 02 00 00 49 63 45 00 41 8b 55 04 48 89 bd c8 fd ff ff 39 c8 0f 84 24 01 00 00 48 01 f0 31 db 49 39 c5 74 10 66 90 <48> 63 00 83 c3 01 48 01 f0 49 39 c5 75 f2 48 c7 c0 81 f9 74 00 45

Nuzhen li damp dannoy oshibki?
on version fb V4.0.3.2860 - another error occurred: the database hung, when trying to unlock it in dmesg, an error appeared:
[Thu Oct 20 17:12:15 2022] fb_lock_print[1114421]: segfault at 7f7cf5667200 ip 00000000004102c0 sp 00007fff45c91210 error 4 in fb_lock_print[400000+146000]
[Thu Oct 20 17:12:15 2022] Code: 48 81 ec 18 02 00 00 49 63 45 00 41 8b 55 04 48 89 bd c8 fd ff ff 39 c8 0f 84 24 01 00 00 48 01 f0 31 3db 49 c5 74 10 66 90 <48> 63 00 83 c3 01 48 01 f0 49 39 c5 75 f2 48 c7 c0 81 f9 74 00 45

Do you need a dump of this error?

**Comment by sszaytsev83** [comment]
on version fb V4.0.3.2860 - another error occurred: the database hung, when trying to unlock it in dmesg, an error appeared:
[Thu Oct 20 17:12:15 2022] fb_lock_print[1114421]: segfault at 7f7cf5667200 ip 00000000004102c0 sp 00007fff45c91210 error 4 in fb_lock_print[400000+146000]
[Thu Oct 20 17:12:15 2022] Code: 48 81 ec 18 02 00 00 49 63 45 00 41 8b 55 04 48 89 bd c8 fd ff ff 39 c8 0f 84 24 01 00 00 48 01 f0 31 3db 49 c5 74 10 66 90 <48> 63 00 83 c3 01 48 01 f0 49 39 c5 75 f2 48 c7 c0 81 f9 74 00 45

Do you need a dump of this error?

**Comment by AlexPeshkoff** [comment]
On 10/20/22 18:11, sszaytsev83 wrote:
>
> on version fb V4.0.3.2860 - another error occurred: the database hung, 
> when trying to unlock it in dmesg, an error appeared:
> [Thu Oct 20 17:12:15 2022] fb_lock_print[1114421]: segfault at 
> 7f7cf5667200 ip 00000000004102c0 sp 00007fff45c91210 error 4 in 
> fb_lock_print[400000+146000]
> [Thu Oct 20 17:12:15 2022] Code: 48 81 ec 18 02 00 00 49 63 45 00 41 
> 8b 55 04 48 89 bd c8 fd ff ff 39 c8 0f 84 24 01 00 00 48 01 f0 31 3db 
> 49 c5 74 10 66 90 <48> 63 00 83 c3 01 48 01 f0 49 39 c5 75 f2 48 c7 c0 
> 81 f9 74 00 45
>
> Do you need a dump of this error?
>

Let's begin with stack trace...

**Comment by sszaytsev83** [comment]
stack trace
[fb_lock_print.txt](https://github.com/FirebirdSQL/firebird/files/9832421/fb_lock_print.txt)

**Comment by AlexPeshkoff** [comment]
It’s a kind of normal behavior — no real danger. When working with live database add switch ‘-c’ to lockprint to avoid it. n the other hand in a case of hang that switch should not be used.  
 
--
Александр Пешков
Отправлено из Почты  Mail.ru

**Comment by sszaytsev83** [comment]
On a special build (LI-V4.0.3.2860 Firebird 4.0 TPC-bugcheck) errors also got out, here are their traces:
[core.firebird.1666331812.772957.txt](https://github.com/FirebirdSQL/firebird/files/9837787/core.firebird.1666331812.772957.txt)
[core.firebird.1666333486.819507.txt](https://github.com/FirebirdSQL/firebird/files/9837788/core.firebird.1666333486.819507.txt)
[core.firebird.1666336072.894981.txt](https://github.com/FirebirdSQL/firebird/files/9837790/core.firebird.1666336072.894981.txt)
[core.firebird.1666336324.905307.txt](https://github.com/FirebirdSQL/firebird/files/9837792/core.firebird.1666336324.905307.txt)
[core.firebird.1666337198.930312.txt](https://github.com/FirebirdSQL/firebird/files/9837795/core.firebird.1666337198.930312.txt)
[core.firebird.1666337405.936620.txt](https://github.com/FirebirdSQL/firebird/files/9837796/core.firebird.1666337405.936620.txt)
[core.firebird.1666337434.937557.txt](https://github.com/FirebirdSQL/firebird/files/9837798/core.firebird.1666337434.937557.txt)
[core.firebird.1666339963.1019584.txt](https://github.com/FirebirdSQL/firebird/files/9837799/core.firebird.1666339963.1019584.txt)
[core.firebird.1666341978.1079884.txt](https://github.com/FirebirdSQL/firebird/files/9837801/core.firebird.1666341978.1079884.txt)

**Comment by AlexPeshkoff** [comment]
Something interesting in firebird.log? Like "tpc_block_blocking_ast BUG". If yes - send it here please.

Also please send me core dumps for 819507.txt & 1079884.txt.

**Comment by sszaytsev83** [comment]
now another error has occurred, in which the database is blocked, I post a trace to it and dumps to the corresponding traces
[core.firebird.1666350763.771398.txt](https://github.com/FirebirdSQL/firebird/files/9838630/core.firebird.1666350763.771398.txt)

[core.firebird.1666333486.819507.zip](https://github.com/FirebirdSQL/firebird/files/9838638/core.firebird.1666333486.819507.zip)

[core.firebird.1666341978.1079884.zip](https://github.com/FirebirdSQL/firebird/files/9838640/core.firebird.1666341978.1079884.zip)

**Comment by sszaytsev83** [comment]
firebird.log
[firebird.log](https://github.com/FirebirdSQL/firebird/files/9838651/firebird.log)

**Comment by AlexPeshkoff** [comment]
Problem decompressing core dump:

> dump: https://oc.otcpharm.ru/index.php/s/dnXpHdDdNgNB2TT

# unzip -t -v core.firebird.1666086625.47429.zip
Archive:  core.firebird.1666086625.47429.zip
    testing: core.firebird.1666086625.47429  
  error:  invalid compressed data to inflate
    testing: firebird.trace_12:51.txt   OK
At least one error was detected in core.firebird.1666086625.47429.zip.

Tried to dowload twice, but still same error.
Can you re-upload it to the site?

**Comment by sszaytsev83** [comment]
re-uploaded the dump
https://oc2.otcpharm.ru/index.php/s/iWoBqATrQexesLd

**Comment by sszaytsev83** [comment]
In a special build of LI-V4.0.3.2863 Firebird 4.0 TPC-bugcheck in superserver mode, there was also a crash:

firebird.log:
otcou2  Mon Oct 31 17:35:23 2022
        REMOTE INTERFACE/gds__detach: Unsuccesful detach from database.
        Uncommitted work may have been lost.
        Error writing data to the connection.

otcou2  Mon Oct 31 17:39:44 2022
        /opt/firebird/bin/fbguard: /opt/firebird/bin/firebird terminated abnormally (-1)

otcou2  Mon Oct 31 17:39:44 2022
        /opt/firebird/bin/fbguard: guardian starting /opt/firebird/bin/firebird


dmesg:
[Пн окт 31 17:37:30 2022] firebird[1692481]: segfault at 2cc ip 00007ff9899e4af6 sp 00007fe9f5cd2930 error 4 in libEngine13.so[7ff989819000+95f000]
[Пн окт 31 17:37:30 2022] Code: 00 00 00 00 55 48 89 e5 41 57 41 56 41 55 41 54 53 48 83 ec 38 48 85 ff 48 89 7d b0 48 89 75 b8 0f 84 94 05 00 00 48 8b 45 b8 <f6> 80 cc 02 00 00 01 0f 84 24 01 00 00 4c 8b 60 08 41 8b 94 24 00

trace:
[firebird.trace_core.firebird.1667227085.1386046.txt](https://github.com/FirebirdSQL/firebird/files/9903519/firebird.trace_core.firebird.1667227085.1386046.txt)

dump:
https://oc2.otcpharm.ru/index.php/s/7EmHC8j7JCCT4NG

**Comment by AlexPeshkoff** [comment]
Other bug. BTW, original problem with bugcheck releasing shared memory will never take place on SS, only CS (and SC) are affected.

**Comment by andrewkip** [comment]
Original problem with bugcheck releasing shared memory seems to be gone in specail build LI-V4.0.3.2863 Firebird 4.0 TPC-bugcheck in classic mode.
