### ISSUE TITLE
contradictory licensing/distribution statements in several charset-support files

### ISSUE THREAD

**Issue by real-dam** [FirebirdSQL/firebird#7349]
While doing licensing/copyright review of firebird4.0 for inclusion in Debian, I've discovered following statement in four files:

 * src/intl/charsets/cs_big5.h
 * src/intl/charsets/cs_jis_0208_1990.h
 * src/intl/charsets/cs_next.h
 * src/intl/charsets/cs_sjis.h

```
This file is provided as-is by Unicode, Inc. (The Unicode Consortium).
No claims are made as to fitness for any particular purpose. …
…
Recipient is granted the right to make copies in any form for
internal distribution and to freely use the information supplied
in the creation of products supporting Unicode.  Unicode, Inc.
specifically excludes the right to re-distribute this file directly
to third parties or other organizations whether for profit or not.
```

Note the last sentence which explicitly forbids redistribution.

Later there is the standard Interbase Public License which claims that the file is created by Inprise Corporation.

Either it is created by Unicode Iinc. and can't be re-distributed at all, or it is created by Inprise and can be re-distributed under IPL. It can't be both.

According to git history, this contradiction is present from day 1 in 2001 (but the files were in the src/intl/ directory back then). Strange nobody noticed it for over 20 years.

**Comment by AlexPeshkoff** [comment]
On 10/15/22 14:00, real-dam wrote:
>
> While doing licensing/copyright review of firebird4.0 for inclusion in 
> Debian, I've discovered following statement in four files:
>
>   * src/intl/charsets/cs_big5.h
>   * src/intl/charsets/cs_jis_0208_1990.h
>   * src/intl/charsets/cs_next.h
>   * src/intl/charsets/cs_sjis.h
>
> |This file is provided as-is by Unicode, Inc. (The Unicode 
> Consortium). No claims are made as to fitness for any particular 
> purpose. … … Recipient is granted the right to make copies in any form 
> for internal distribution and to freely use the information supplied 
> in the creation of products supporting Unicode. Unicode, Inc. 
> specifically excludes the right to re-distribute this file directly to 
> third parties or other organizations whether for profit or not. |
>
> Note the last sentence which explicitly forbids redistribution.
>
> Later there is the standard Interbase Public License which claims that 
> the file is created by Inprise Corporation.
>
> Either it is created by Unicode Iinc. and can't be re-distributed at 
> all, or it is created by Inprise and can be re-distributed under IPL. 
> It can't be both.
>
> According to git history, this contradiction is present from day 1 in 
> 2001 (but the files were in the src/intl/ directory back then). 
> Strange nobody noticed it for over 20 years.
>

Is it possible to choose required license in a case of double licensing? 
I've always thought yes. Files were published by Inprise with Inprise 
license, presence of Unicode Consortium license does not decline 
presence of Inprise one.

**Comment by real-dam** [comment]
License grants which give the receiver the right to choose between several licenses explicitly say so. I don't see such choice here.

I see "specifically excludes the right to re-distribute this file directly to third parties or other organizations". I read this as Inprise (or anyone else) not having the right to publish this file at all.

If you know/believe that these files are authored by Inprise (or Inprise had the right to distribute them under IPL, perhaps because of an agreement with Unicode), and the Unicode Inc.'s statement is void/incorrect, then please remove it and leave only the Inprise boilerplate.

**Comment by aafemt** [comment]
I think these files must be removed from Firebird and corresponding charsets (if needed) should be supported using ICU. Actually all old INTL tables can go.

**Comment by mrotteveel** [comment]
As far as I can tell, that license header is from the `asia/OTHER/BIG5.TXT` that is mentioned. The source code itself was generated using that file, so it is not the license of that file itself, but the license of the file that was used to generate the file. The file itself is licensed under the IPL.

Specifically, see this file that carries the same terms: http://www.in853.com/inc/gbkcode/big5-unicode.table and a more recent version from the Unicode  consortium itself, which seems to have changed license to be less restrictive: https://unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/OTHER/BIG5.TXT

**Comment by mrotteveel** [comment]
Specifically, the source file was (originally) generated using https://github.com/FirebirdSQL/firebird/blob/master/src/intl/utils/mapgen4.c

**Comment by mrotteveel** [comment]
Specifically, the mapgen4c will read the mapping file, write the contents of that mapping file into the header comment, and then write the lookup table. Specifically for this file, the content of the mapping file after the header comment was removed, likely because of that license. 

On the other hand, some files contain the entire file contents of the mapping file in the header comment, for example: https://github.com/FirebirdSQL/x-cvs-interbase/blob/master/intl/charsets/cs_437.h

**Comment by mrotteveel** [comment]
Technically, https://github.com/FirebirdSQL/firebird/blob/master/src/intl/charsets/cs_next.h and https://github.com/FirebirdSQL/firebird/blob/master/src/intl/charsets/cs_sjis.h are in violation of that license, as they replicate the source mapping file in their comments. The solution would be to remove that part of the header comment, or regenerate the file using a newer version of the mapping file (as found on https://www.unicode.org/Public/MAPPINGS/), as the Unicode license is now more relaxed (see https://www.unicode.org/copyright.html)

**Comment by mrotteveel** [comment]
The pull requests #7353, #7354 and #7355 remove the copy of the original mapping files from the header comments of the generated character set files, except for the identifying version information. This should address the concerns of this ticket, as it removes the code that is potentially in violation of the license of those mapping files.

**Comment by mrotteveel** [comment]
@real-dam If you have any further concerns, let us know.

**Comment by real-dam** [comment]
Thank you for the prompt response. I will roll snapshot releases for Debian soon.
