### ISSUE TITLE
Releasing Memory after backup with gbak (memory mapped standby)

### ISSUE THREAD

**Issue by w3ich3rt** [FirebirdSQL/firebird#7352]
Hey guys,

we have a problem with our firebird installation, that causes a crash if we do not restart the server frequently.
We tried to restart the firebird after the backup, but that does not free the memory.

If we do not restart the server frequently the memory consumption will cause a crash!

We are using the provided backupscript from the vendor of the application that uses the firebird db.

```bat
@ECHO OFF
REM - Beenden der geplanten Aufgaben -
NET STOP ASSFINETSchedulerService
REM - TASKKILL im Falle eines hängeneden Prozesses -
Taskkill /F /IM ASSFINETScheduler.exe /T
ECHO Veraltete Datenbankbackups werden geloescht...
forfiles /p E:\ASSFINET\BACKUP /d -3 /m assfinetbackup_*.bak /c "cmd /c del  @path"
ECHO.
ECHO Veraltete Logdateien werden geloescht...
forfiles /p E:\ASSFINET\BACKUP /s /d -3 /m assfinetbackup_*.log /c "cmd /c del  @path"
ECHO.
SET ZEIT=%TIME:~0,2%-%TIME:~3,2%-%TIME:~6,2%
ECHO Datenbank wird gesichert, bitte warten...
"C:\Program Files\Firebird\Firebird_3_0\gbak.exe" -b -v -y "E:\ASSFINET\BACKUP\assfinetbackup_%DATE%_%ZEIT%.log" -user SYSDBA -password masterkey "E:\ASSFINET\DB\DB0\db0.fdb" "E:\ASSFINET\BACKUP\assfinetbackup_%DATE%_%ZEIT%.bak"
FIND /I "finishing" "E:\ASSFINET\BACKUP\assfinetbackup_%DATE%_%ZEIT%.log"
if errorlevel 1 goto Abbruch_Backup
ECHO Datenbank wurde gesichert.
REM - Stop und Start der Dienste -
Net Stop FirebirdServerDefaultInstance
REM - im Falle eines hängeneden Prozesses -
Taskkill /F /IM Firebird.exe /T
Net Start FirebirdServerDefaultInstance
NET Start ASSFINETSchedulerService
EXIT

:Abbruch_Backup (
ECHO Es ist ein Fehler beim Backup aufgetreten!
ECHO.
ECHO Fehlerdetails:
FIND /I "error" "E:\ASSFINET\BACKUP\assfinetbackup_%DATE%_%ZEIT%.log"
NET Start ASSFINETSchedulerService
ECHO ------------------------------------------------------------------------------
PAUSE
EXIT
)
```
Please see this screenshots for further information about the memory mapping.
<img width="863" alt="screen_file_mapping" src="https://user-images.githubusercontent.com/68917715/196613145-491a3b4e-eab8-4f22-8065-3fdc72ca4b28.png">
<img width="863" alt="screen_ram_mapping" src="https://user-images.githubusercontent.com/68917715/196613148-58e6aedc-5798-488d-84ad-b7ff5822151a.png">

How can we solve this issue? Is there a way to free the memory?

Additional information:

- **CPU:** 10 Cores 3,5 Ghz
- **RAM:** 80,00 GB
- Firebird 3.0.5    (Windows Build)

**Comment by hvlad** [comment]
The memory mapping you show is the file system cache that is managed by the OS automatically.
This memory can be reused by system at any time it needed.
I have a big doubt it could cause any kind of crash.
Could you explain the issue ?

**Comment by w3ich3rt** [comment]
It's like the described problems from #4047

**Comment by hvlad** [comment]
I see no direct relation with #4047. 

gbak in FB5 have new switch 
`-D(IRECT_IO)          direct IO for backup file(s)`
that disables caching of backup file by the OS.
It was introduced for very different reasons.

As workaround you may empty standby lists either via menu in `RamMap` or run `RamMap -Et` (administrator account required)

**Comment by hvlad** [comment]
I believe #4047 was related with (already fixed) #4134, see also #4434.
In your case file cache contains backup files, not database itself.
There is a lot of free RAM at the moment and it could be a reason for OS to not evict this files so far.

**Comment by w3ich3rt** [comment]
@hvlad thanks for your suggestions, we will try that and come back.
I'm not quite sure if we can update the tools to a newer version, but I'll try that as well.

**Comment by w3ich3rt** [comment]
We will investigate the behavior of the server.
Currently there is no need. @hvlad  is right with his assumptions
