### ISSUE TITLE
Migrating from 2.5 to 4.0 is impossible if used a domain "BOOLEAN" in primary keys and constraints

### ISSUE THREAD

**Issue by happymax-dbs** [FirebirdSQL/firebird#7360]
In a complex FB 2.5 database if a BOOLEAN domain is used by many fields which are included in primary keys and constraints it's impossible to modify the domain connected to the fields since the constraints between the tables are too complex and numerous to perform a deletion and creation at the end of the modification of the fields.

It could be possible to activate a command that allows to inhibit the constraints (after deactivating the indexes) so that you can modify the domain directly on the fields with an identical one but with a different name or alternatively allow to rename the field present in an index and then create one with the same name and different domain to avoid conflict with the FB 4 BOOLEAN keyword?

**Comment by mrotteveel** [comment]
This is more a support question. Please ask questions like this on [firebird-support](https://groups.google.com/g/firebird-support).
You will need to fix this in the Firebird 2.5 database before migration.
