### ISSUE TITLE
RAND() function always returns 1.0

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/firebird#7363]
On Firebird 4.0.2 on Windows 11 x64 (haven't tested on other platforms), the `RAND()` function always returns 1.0. On Firebird 4.0.1 it returns random values between 0 and 1 as expected.

Reproduction:

```sql
select rand() from rdb$relations;
```

Output in Firebird 4.0.2 (wrong):

```none
                   RAND
=======================
      1.000000000000000
      1.000000000000000
      1.000000000000000
      1.000000000000000
      1.000000000000000
      1.000000000000000
...
```

Output in Firebird 4.0.1 (correct):

```none
                   RAND
=======================
     0.7649899254366608
     0.2960777491609540
     0.9581856286981573
     0.8808563359625776
    0.04253016894413923
     0.1175615507461551
...
```

**Comment by EPluribusUnum** [comment]
This is just loo good to pass up : https://dilbert.com/strip/2001-10-25

**Comment by mrotteveel** [comment]
False alarm, it seems that at one time while experimenting with something, I created a function `RAND` that always returned 1...
