### ISSUE TITLE
Installer commadline don't add Guardian

### ISSUE THREAD

**Issue by TommiPrami** [FirebirdSQL/firebird#7377]
FB 4.02 32bit installer

Command line used : 

 /SP- /SILENT /NORESTART /RESTARTEXITCODE=0 /NOICONS /SUPPRESSMSGBOXES /LOG /TASKS="UseGuardianTask,!UseApplicationTask,UseServiceTask,AutoStartTask,InstallCPLAppletTask,!MenuGroupTask,CopyFbClientToSysTask,!CopyFbClientAsGds32Task"

Also did not find what this actually does AutoStartTask

As pointed out on mailing list,  that Guardian is more than less obsolete, maybe not too high on the priority list. Which is OK.

**Comment by reevespaul** [comment]
You should probably try using the correct syntax :-)
Take a look at installation_scripted.txt in the doc directory.
