### ISSUE TITLE
BLOB_APPEND with existing blob accepts malformed string

### ISSUE THREAD

**Issue by asfernandes** [FirebirdSQL/firebird#7379]
```sql
create table t (b_utf8 blob sub_type text character set utf8)!


-- Correct: "Malformed string" error
execute block
as
    declare b blob sub_type text character set utf8;
begin
    b = blob_append(b, x'FF');
end!


-- Wrong: no "Malformed string" error
execute block
as
    declare b blob sub_type text character set utf8;
begin
    b = blob_append(b, 'a');
    -- No error
    b = blob_append(b, x'FF');
    -- Malformed blob is saved to table
    insert into t (b_utf8) values (:b);
end!
```

**Comment by aafemt** [comment]
IMHO the logic is wrong. It prevents gathering of a valid UTF8 BLOB from invalid pieces. Perhaps validation should be performed on end product during INSERT but not intermediate values. Also performance may be concern as well.

**Comment by asfernandes** [comment]
Then the BLOB should be initially created as binary or text with octets.
Or the BLOB_APPEND weirdness will invade even more inside PSQL.

**Comment by aafemt** [comment]
That also would be wrong. Your fix is basically right, the BLOB must have proper attributes on creation. What I'm talking about is that comments in your testcase implies BLOB content validation in the middle of work which may be undesirable in some cases.
