### ISSUE TITLE
extend Merge statement do do nothing in some condition

### ISSUE THREAD

**Issue by livius2** [FirebirdSQL/firebird#7381]
currently there is no way to do nothing on some condition e.g.
```
MERGE INTO customers c
	USING (SELECT * FROM customers_delta WHERE id > 10) cd
		ON (c.id = cd.id)
		    WHEN MATCHED ABD c.NAME=cd.NAME THEN !!!nothing_to_do!!! 
            WHEN MATCHED THEN
                UPDATE SET
                    name = cd.name
            WHEN NOT MATCHED THEN
            INSERT (id, name)
                VALUES (cd.id, cd.name)
```

I do not like to do dummy update and generate new record version when all fields are the same.

**Comment by aafemt** [comment]
What does prevent you from using
```
WHEN MATCHED AND c.NAME is distinct from cd.NAME THEN 
    UPDATE SET c.name = cd.name
```
?

**Comment by livius2** [comment]
Good point :) Instead of checking when something is meet you have checked negation :)
So to check more fields simply `MATCHED AND (c.NAME is distinct from cd.NAME or c.XXX is distinct from cd XXX) THEN`
