### ISSUE TITLE
Broken lock of statements cache during multithreaded index activation

### ISSUE THREAD

**Issue by dmitry-starodubov** [FirebirdSQL/firebird#7385]
Server (last 5.0) crashes when trying to dereference NULL pointer (self->lock) in DsqlStatementCache::blockingAst.
The crash stacks are in the attachment.

It can be reproduced in this way.
In attachment there is a backup of a database with 1000 empty tables and 4000 indexes.
Restore it if with "-i" option to leave the indexes inactive.
Set MaxParallelWorkers = 64 in firebird.conf.
Download the [plume utility](https://github.com/neozx/plume) and build it.

Then run it as follows:
./plume -u sysdba -p masterkey -t 24 -P 4 -d localhost:/tmp/t5.fdb 

I get the server crash after two - four runs.
[stacks.txt](https://github.com/FirebirdSQL/firebird/files/9981104/stacks.txt)
[t5.zip](https://github.com/FirebirdSQL/firebird/files/9981108/t5.zip)

**Comment by dmitry-starodubov** [comment]
Hello. The crash on the artificial test is fixed, but when I try to activate the indexes on the real database, the server hangs with the stack in the attachment.
[hang_stack.txt](https://github.com/FirebirdSQL/firebird/files/10002551/hang_stack.txt)
According to the lock table the lock is acquired by thread 229152, but there is no such thread in the server process.
[locks.txt](https://github.com/FirebirdSQL/firebird/files/10002588/locks.txt)

The server hangs after an error:

Warning trouble on index IDX_O_OTHER_GUID
COLLATION WIN1251_UNICODE for CHARACTER SET WIN1251 is not installed
-An ICU library with collation version 153.88 is required but was not found. You may try to install ICU version 63.1, used to register the collation in this database or look for 'gfix -icu' in Firebird documentation.

Perhaps, that thread have got this error and finished but did not release the lock.

**Comment by asfernandes** [comment]
If you do not send another reproducible test case, things will be difficult.

I'm not sure we didn't have some fundamental problem in Lock class or its usage. Before my change, the usage pattern was almost identical to others cases (for example, `att_repl_lock`), except a possible memory release.

Tests for `lck_logical` seems weird when multiple threads may be using the same instance, even considering that the AST / other code has some protection with `AsyncContextHolder`.

Also its usage (for example, inside `Attachment`).

AFAIU we need to use some atomics for safety/correctness.

**Comment by dmitry-starodubov** [comment]
> On 11/14/22 14:52, Dmitry Starodubov wrote: According to the lock table the lock is acquired by thread 229152, but there is no such thread in the server process.
> To make sure - our thread ID on linux is LWP's PID.

Yes, I know. There are threads 229151 and 229153 in the server process, but 229152 is absent.

**Comment by dmitry-starodubov** [comment]
> If you do not send another reproducible test case, things will be difficult.

I sent you an email with a link to download the database. The problem is reproduced in 1 or 2 runs of plume on it.

**Comment by asfernandes** [comment]
> I sent you an email with a link to download the database. The problem is reproduced in 1 or 2 runs of plume on it.

Thanks. Investigating.

**Comment by aafemt** [comment]
```
+	if (lock)
 		LCK_release(tdbb, lock);
+	missingLock = true;
```
IMHO, `if (!missingLock)` would be more consistent here but in any case I'm afraid it only decrease probability of thread races not eliminate them.

**Comment by dyemanov** [comment]
> AFAIU we need to use some atomics for safety/correctness.

I believe atomics are needed only for dbb-owned locks. On other cases flags should be enough.

**Comment by asfernandes** [comment]
> I'm unable to reproduce the freeze after applying the following patch:

It changed nothing for me.

I'm running plume without parallel workers as following:

```
plume -u sysdba -p masterkey -t 128 -P 1 -d localhost:/tmp/db.fdb
```

**Comment by asfernandes** [comment]
> It changed nothing for me.

Then I changed `missingLock` to `std::atomic_bool` and it started to work without freeze.

But then I revert `missingLock` type to `bool` and it still worked.

Then I revert to master code and it still worked.

Very weird.

**Comment by asfernandes** [comment]
> Then I changed `missingLock` to `std::atomic_bool` and it started to work without freeze.
> 
> But then I revert `missingLock` type to `bool` and it still worked.
> 
> Then I revert to master code and it still worked.
> 
> Very weird.

I had a theory and confirmed it.

I started these test runs with laptop unplugged from power.

In first runs it was charged and was freezing.

Then it started to drain battery and all tests started to work correctly.

When I plugged it in the power all three code versions started to freeze again.

**Comment by dyemanov** [comment]
I confirm my patch does not solve the issue, it only moves it a few iterations later. However, the extra check seems to solve it:

```c++
	if (missingLock)
	{
		missingLock = false;
		ensureLockIsCreated(tdbb);
		LCK_lock(tdbb, lock, LCK_SR, LCK_WAIT);

		if (missingLock)
		{
			// Our cache has been cleared in background while we were waiting for the lock.
			// We must release the just taken lock to keep in sync with the cache state.
			fb_assert(!cacheSize);
			LCK_release(tdbb, lock);
		}
	}
```

I have it testing now and _plume_ has already passed 251 iterations (with `-P 8`) successfully.

**Comment by hvlad** [comment]
The real problem is that in some conditions (such as parallel creation of indices) such cache is useless - it have no chance to get even one entry and creates a constant useless load on LM. Worse - there is no need at all to clear cache in this case.
Engine clears MET cache when there is real need. We can follow this way and even try improve it.
And no new lock will be needed.

**Comment by hvlad** [comment]
@dyemanov: see also this 86f2550ba commit, it deal with similar issue. 
Look at `while` loop at the start of `scan_partners` and how `REL_check_partners` flag is used.

**Comment by aafemt** [comment]
> However, the extra check seems to solve it:

Are you sure that in second check `missingLock` should be checked for true?
And for such tricks shouldn't the variable declared `volatile`? Otherwise optimizer is free to ignore piece of code it thinks will never be executed.

**Comment by dyemanov** [comment]
> @dyemanov: see also this [86f2550](https://github.com/FirebirdSQL/firebird/commit/86f2550ba3f5b813cb316fac0e88376463662a2f) commit, it deal with similar issue. Look at `while` loop at the start of `scan_partners` and how `REL_check_partners` flag is used.

Retry loop is needed if we insist in keeping our object cached. In this case we'll need to redo putStatement()'s work again, as it makes no sense to get the lock with the empty cache. I went another route and decided to leave the cache empty (and thus release the lock), as I don't see it critical to preserve the cache. I'm not 100% this choice is better, but it surely makes the patch smaller ;-)

**Comment by dyemanov** [comment]
> > I have it testing now and _plume_ has already passed 251 iterations (with `-P 8`) successfully.
> 
> Still hanging for me with:
> 
> ```
> plume -u sysdba -p masterkey -t 128 -P 1 -d localhost:/tmp/test.fdb
> ```

Hmmm. I tried `"-t 24 -P 4"` and `"-t 24 -P 8"`, both succeeded with 500 iterations. Now running `"-t 128 -P1"` as you suggest, so far 52 iterations without freezing.

**Comment by dyemanov** [comment]
> Are you sure that in second check `missingLock` should be checked for true?

Yes, otherwise it does not make sense. If we cleared it ourselves but it's `true` again after LM, then AST was called in the meantime. Note that I moved `missingLock = false;` before `LCK_lock`.

> And for such tricks shouldn't the variable declared `volatile`? Otherwise optimizer is free to ignore piece of code it thinks will never be executed.

Maybe (although IMHO tricks with `volatile` are not often a guarantee anyway). But ignoring that code by the compiler would definitely lead to freezes again, but this is not what's happening.

**Comment by dyemanov** [comment]
`LCK_release()` does not have a checkout inside, so it does not affect concurrency. It's possible only inside `LCK_lock()`.

**Comment by hvlad** [comment]
Below is the one of the possible ways to avoid races with LCK_lock and AST handler when lck_id is not known yet:
- use SR state for empty cache, take a lock immediately after creating
- use SW state for non empty cache, convert existing SR lock with NO_WAIT when adding first entry,
  if LCK_convert returns false, purge cache (don't add first entry)
- use PW state to signal others to purge caches, use separate temporary Lock instance for it with no AST handler set
  (as in @dyemanov patch above)
- in AST handler check if cache is not already purged, then purge and convert lock to the SR state (or downgrade).

I can prepare a patch but can't test it as I have no test DB nor Windows build of plume.

**Comment by hvlad** [comment]
Here it is, minimally tested

```diff
 src/dsql/DsqlStatementCache.cpp | 42 +++++++++++++++++++++++++++--------------
 src/dsql/DsqlStatementCache.h   |  2 +-
 src/jrd/Attachment.cpp          |  2 +-
 src/jrd/jrd.cpp                 |  3 ++-
 4 files changed, 32 insertions(+), 17 deletions(-)

diff --git a/src/dsql/DsqlStatementCache.cpp b/src/dsql/DsqlStatementCache.cpp
index e28c9282c4..f3522314cc 100644
--- a/src/dsql/DsqlStatementCache.cpp
+++ b/src/dsql/DsqlStatementCache.cpp
@@ -46,7 +46,7 @@ DsqlStatementCache::DsqlStatementCache(MemoryPool& o, Attachment* attachment)
 
 DsqlStatementCache::~DsqlStatementCache()
 {
-	purge(JRD_get_thread_data());
+	purge(JRD_get_thread_data(), true);
 }
 
 int DsqlStatementCache::blockingAst(void* astObject)
@@ -62,7 +62,7 @@ int DsqlStatementCache::blockingAst(void* astObject)
 		const auto dbb = self->lock->lck_dbb;
 		AsyncContextHolder tdbb(dbb, FB_FUNCTION, self->lock);
 
-		self->purge(tdbb);
+		self->purge(tdbb, false);
 	}
 	catch (const Exception&)
 	{} // no-op
@@ -119,6 +119,10 @@ void DsqlStatementCache::putStatement(thread_db* tdbb, const string& text, USHOR
 {
 	fb_assert(dsqlStatement->isDml());
 
+	ensureLockIsCreated(tdbb);
+	if (cacheSize == 0 && !LCK_convert(tdbb, lock, LCK_SW, LCK_NO_WAIT))
+		return;
+
 	const unsigned statementSize = dsqlStatement->getSize();
 
 	RefStrPtr key;
@@ -141,11 +145,6 @@ void DsqlStatementCache::putStatement(thread_db* tdbb, const string& text, USHOR
 	activeStatementList.pushBack(std::move(newStatement));
 	map.put(key, --activeStatementList.end());
 
-	ensureLockIsCreated(tdbb);
-
-	if (lock->lck_logical == LCK_none)
-		LCK_lock(tdbb, lock, LCK_SR, LCK_WAIT);
-
 #ifdef DSQL_STATEMENT_CACHE_DEBUG
 	dump();
 #endif
@@ -175,8 +174,13 @@ void DsqlStatementCache::statementGoingInactive(Firebird::RefStrPtr& key)
 		shrink();
 }
 
-void DsqlStatementCache::purge(thread_db* tdbb)
+void DsqlStatementCache::purge(thread_db* tdbb, bool releaseLock)
 {
+	if (cacheSize == 0)
+		return;
+
+	fb_assert(lock && lock->lck_logical == LCK_SW);
+
 	for (auto& entry : activeStatementList)
 	{
 		entry.dsqlStatement->addRef();
@@ -189,20 +193,27 @@ void DsqlStatementCache::purge(thread_db* tdbb)
 
 	cacheSize = 0;
 
-	if (lock && lock->lck_logical != LCK_none)
+	if (releaseLock)
 		LCK_release(tdbb, lock);
+	else
+	{
+		const bool ret = LCK_convert(tdbb, lock, LCK_SR, LCK_NO_WAIT); // never fails
+		fb_assert(ret);
+	}
 }
 
 void DsqlStatementCache::purgeAllAttachments(thread_db* tdbb)
 {
-	purge(tdbb);
+	purge(tdbb, false);
 
-	fb_assert(!lock || lock->lck_logical == LCK_none);
+	fb_assert(!lock || lock->lck_logical == LCK_SR);
 
-	ensureLockIsCreated(tdbb);
+	Lock tempLock(tdbb, 0, LCK_dsql_statement_cache);
 
-	LCK_lock(tdbb, lock, LCK_EX, LCK_WAIT);	// notify others
-	LCK_release(tdbb, lock);
+	if (!LCK_lock(tdbb, &tempLock, LCK_PW, LCK_WAIT))	// notify others
+		status_exception::raise(tdbb->tdbb_status_vector);
+
+	LCK_release(tdbb, &tempLock);
 }
 
 void DsqlStatementCache::buildStatementKey(thread_db* tdbb, RefStrPtr& key, const string& text, USHORT clientDialect,
@@ -264,7 +275,10 @@ void DsqlStatementCache::shrink()
 void DsqlStatementCache::ensureLockIsCreated(thread_db* tdbb)
 {
 	if (!lock)
+	{
 		lock = FB_NEW_RPT(getPool(), 0) Lock(tdbb, 0, LCK_dsql_statement_cache, this, blockingAst);
+		LCK_lock(tdbb, lock, LCK_SR, LCK_WAIT);	// never fails
+	}
 }
 
 #ifdef DSQL_STATEMENT_CACHE_DEBUG
diff --git a/src/dsql/DsqlStatementCache.h b/src/dsql/DsqlStatementCache.h
index 2c70f11460..2ee94322a2 100644
--- a/src/dsql/DsqlStatementCache.h
+++ b/src/dsql/DsqlStatementCache.h
@@ -103,7 +103,7 @@ public:
 
 	void statementGoingInactive(Firebird::RefStrPtr& key);
 
-	void purge(thread_db* tdbb);
+	void purge(thread_db* tdbb, bool releaseLock);
 	void purgeAllAttachments(thread_db* tdbb);
 
 private:
diff --git a/src/jrd/Attachment.cpp b/src/jrd/Attachment.cpp
index 1419e63b46..dd96627067 100644
--- a/src/jrd/Attachment.cpp
+++ b/src/jrd/Attachment.cpp
@@ -840,7 +840,7 @@ void Jrd::Attachment::releaseLocks(thread_db* tdbb)
 	// Release dsql statement cache lock
 
 	if (att_dsql_instance)
-		att_dsql_instance->dbb_statement_cache->purge(tdbb);
+		att_dsql_instance->dbb_statement_cache->purge(tdbb, true);
 
 	// Release the remaining locks
 
diff --git a/src/jrd/jrd.cpp b/src/jrd/jrd.cpp
index 5a1091db6e..b649552567 100644
--- a/src/jrd/jrd.cpp
+++ b/src/jrd/jrd.cpp
@@ -7633,8 +7633,9 @@ void release_attachment(thread_db* tdbb, Jrd::Attachment* attachment, XThreadEns
 
 	attachment->att_replicator = nullptr;
 
+	// duplicated at attachment->releaseLocks below
 	if (attachment->att_dsql_instance)
-		attachment->att_dsql_instance->dbb_statement_cache->purge(tdbb);
+		attachment->att_dsql_instance->dbb_statement_cache->purge(tdbb, true);
 
 	while (attachment->att_repl_appliers.hasData())
 	{

```

**Comment by asfernandes** [comment]
> I can prepare a patch but can't test it as I have no test DB nor Windows build of plume.

After fix two assertion problems it started to work with simple connections and stop hang in the test.

Another assertion left happening with fbtcs.

> * use SW state for non empty cache, convert existing SR lock with NO_WAIT when adding first entry,
>   if LCK_convert returns false, purge cache (don't add first entry)

It makes many statements to not be put in cache. In this way it looks easy to avoid hangs.

I doubt this is generally correct and I'm sure the problematic pattern is spread in many places that cannot have the luxury of ignore lock failures.

> * use PW state to signal others to purge caches, use separate temporary Lock instance for it with no AST handler set
>   (as in @dyemanov patch above)

A simple test with two ISQL connections shows a hang due to this.

```
-- C1
select 1 from rdb$database;

-- C2
select 1 from rdb$database;

-- C1
recreate table tz1 (n1 integer);
select 1 from rdb$database;

-- C2
recreate table tz2 (n1 integer);
```

**Comment by hvlad** [comment]
If you going to be constructive, you'll find that check for cache emptyness `cacheSize == 0` is not correct and should be replaced by:
```
	bool isEmpty() const
	{
		return activeStatementList.isEmpty() &&
			   inactiveStatementList.isEmpty();
	}
```

[gh7385-2.diff](https://github.com/FirebirdSQL/firebird/files/10111040/gh7385-2.diff.txt)

**Comment by hvlad** [comment]
This fixed assert in `~DsqlStatementCache()`
[gh7385-3.diff](https://github.com/FirebirdSQL/firebird/files/10111177/gh7385-3.diff.txt)

**Comment by asfernandes** [comment]
You must initialize the tdbb status vector after fail of LCK_convert.

**Comment by asfernandes** [comment]
```
if (!isEmpty())
    fb_assert(isEmpty() || ...
```

?

**Comment by asfernandes** [comment]
While I do not see more hangs and crashes, as I stated before and nobody answered, I'm still not totally convinced of this fix due to reasons:
- It looks like it did not cover others usage of lock manager. Should (or why they shouldn't) be changed? Saying it's working by 20 years is not something I can just trust. Is it load tested (how?) in different hardwares? How is that patterns different for example than Collation.cpp existenceLock?
- Why is `LCK_convert` failings ignored in `putStatement`? In what conditions that failings happens? In this restore test this code was able to lock 12210 times, while it was unable to lock 28319 times! What is the purpose of a cache that fail to work? How others usage of the lock manager that just can't afford to ignore locks may work?

**Comment by dyemanov** [comment]
It's surely possible that (some) other usage cases were not stress-tested and thus may be affected too. So far we were fixing races only after proving them with test cases.
As for your second question, IMO the plume test simply cannot allow the cache to work properly, regardless of its locking implementation. If it wouldn't be requested to clear so many times, we couldn't see races and freezes.

**Comment by dyemanov** [comment]
I don't want it to be a showstopper, so I suggest to accept the latest version of the Vlad's patch and proceed with Beta 1. A better (or more generic) solution, if any, is welcome afterwards.

**Comment by asfernandes** [comment]
Let @hvlad commit it then.
