### ISSUE TITLE
AV when compiling stored procedure.

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#7391]
```
create or alter procedure list_to_rows(i_list varchar(1024))
  returns (o_id int)
as
begin
  suspend;
end
^
commit
^
create or alter procedure sp_bug (i_list varchar(1024))
as
declare id int;
begin
  if (not (:id in (select o_id from list_to_rows(:i_list))))
  then exit;
end
^
commit
^
```
When `sp_bug` is committed, Firebird crashed.

**Comment by hvlad** [comment]
Stack trace [7391-stack.txt](https://github.com/FirebirdSQL/firebird/files/10049734/7391-stack.txt)

Exception message:

> Exception thrown: read access violation.
> this->message.ptr was nullptr.
> 

Looks like this commit 5369bd9 is related to the bug

**Comment by hvlad** [comment]
@asfernandes: could you look at it, please, I'm not sure how to fix it correctly

**Comment by asfernandes** [comment]
> @asfernandes: could you look at it, please, I'm not sure how to fix it correctly

Yes, I will look.
