### ISSUE TITLE
autoconf 2.72

### ISSUE THREAD

**Issue by pmakowski** [FirebirdSQL/firebird#7394]
Reported by Fedora : https://bugzilla.redhat.com/show_bug.cgi?id=2144802

Autoconf 2.72 seems to be under preparation upstream, I therefore started to build dependent components to verify that they can be built once it lands in Fedora.

Your component fails to build with the new version of autoconf, due to the following error:

```
---
checking for cc_r... gcc
./configure: line 5993: syntax error near unexpected token `;;'
./configure: line 5993: `printf "%s\n" "$as_me: WARNING: --with-system-editline specified, not found. Using bundled editline" >&2;} ;;'
error: Bad exit status from /var/tmp/rpm-tmp.yKcOUe (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.yKcOUe (%build)
Child return code was: 1
---
```

The error is due to a misplace 'fi' in configure.ac.

The proposed patch is the following:

```
---
diff -r -U5 Firebird-4.0.2.2816-0/configure.ac Firebird-4.0.2.2816-0.new/configure.ac
--- Firebird-4.0.2.2816-0/configure.ac	2022-11-22 12:03:35.566718554 +0100
+++ Firebird-4.0.2.2816-0.new/configure.ac	2022-11-22 12:03:28.606705774 +0100
@@ -652,12 +652,13 @@
   AC_CHECK_LIB(edit, readline, [READLINE=edit EDITLINE_FLG=Y],
     AC_CHECK_LIB(editline, readline, [READLINE=editline EDITLINE_FLG=Y],
       AC_CHECK_LIB(readline, readline, [READLINE=readline EDITLINE_FLG=Y],
         [STD_EDITLINE=false
          if test "$EDITLINE_FLG" = "Y"; then
-           AC_MSG_WARN([[[--with-system-editline specified, not found. Using bundled editline]]])])))
+           AC_MSG_WARN([[[--with-system-editline specified, not found. Using bundled editline]]])
 		 fi
+           ])))
 fi
 XE_RESTORE_ENV()
 
 AC_SUBST(READLINE)
 AC_SUBST(STD_EDITLINE)
---
```

Please have a look and get it fixed upstream.

**Comment by AlexPeshkoff** [comment]
@pmakowski In what branches do we need this fix?

**Comment by azhu26** [comment]
#7394 is for version 4.0.2 and address the issue to the point. Hoever, the same confirgure issue kept coming out, even for 4.0.4. so could it be the obsolete configure.ac still living somewhere on the line passing to the repo?

**Comment by AlexPeshkoff** [comment]
Fix versions were not added to this ticket (my fault), and issue was reported not for up-to-date versions (4.0.4 was tagged just a few days before the fix). I've added all intermediate affected versions here.

**Comment by azhu26** [comment]
Hi, a bit confused. Are those "fix version" available through github? or have to got to firebird website's download page to get the tarball?

thanks.

**Comment by AlexPeshkoff** [comment]
Fix versions were not released yet. I.e. you may use tarball from snapshot or clone appropriate branch from github.
