### ISSUE TITLE
Specify service instance name on install  (question)

### ISSUE THREAD

**Issue by ocsike** [FirebirdSQL/firebird#7400]
Hi,
Can I specify  service instance name when I install FB from official installer or is there any servertask which is doesn't  call   instsvc.exe ?
Thanks,
 Laszlo

**Comment by mrotteveel** [comment]
You can untick the box to install Firebird as a service, and run instsvc afterwards and use the `-name` option to specify an explicit name.

As an aside, for support questions, please use [firebird-support](https://groups.google.com/g/firebird-support) instead of the bug tracker.
