### ISSUE TITLE
CHARACTER SET ISO8859_1 is not installed

### ISSUE THREAD

**Issue by hcrufio88** [FirebirdSQL/firebird#7401]
Hello, i'm on a mac os ventura 13.0.1, i have installed a firebird superserver 2.5.9.

when i've updated mac os i can't get any query from my db, and get the error
"Errore SQL [335544854] [2C000]: CHARACTER SET ISO8859_1 is not installed [SQLState:2C000, ISC error code:335544854]
  CHARACTER SET ISO8859_1 is not installed [SQLState:2C000, ISC error code:335544854]
  CHARACTER SET ISO8859_1 is not installed [SQLState:2C000, ISC error code:335544854]
    CHARACTER SET ISO8859_1 is not installed
    CHARACTER SET ISO8859_1 is not installed
"

i try to reinstall firebird server but nothing works! 
i can connect to database but i cant't perform any query.
please help

**Comment by asfernandes** [comment]
v2.5 is not maintained anymore. Please try v4.
