### ISSUE TITLE
Regression - trusted role does not work with version 3.0.10

### ISSUE THREAD

**Issue by pwbzh** [FirebirdSQL/firebird#7406]
Hello,

Tested on GNU/Linux and Windows, the Mapping of Users to Objects does not work with version 3.0.10 but works with version 3.0.7

https://firebirdsql.org/file/documentation/release_notes/html/en/3_0/rnfb30-security-mapping.html

Thanks

**Comment by AlexPeshkoff** [comment]
Doubt that:

# ./isql -user sysdba -pas masterkey localhost:employee
Database: localhost:employee, User: SYSDBA
SQL> select current_user from rdb$database;

USER                            
=============================== 
SYSDBA                          

SQL> create mapping sysg using * from user sysdba to user guest;
SQL> 

# ./isql -user sysdba -pas masterkey localhost:employee
Database: localhost:employee, User: GUEST
SQL> select current_user from rdb$database;

USER                            
=============================== 
GUEST                           

SQL>

**Comment by pwbzh** [comment]
The problem seems to come from the `engine12` DLL between version 3.0.7 and 3.0.8.

**Comment by AlexPeshkoff** [comment]
An issue is specific for 3.0.x,  no need front-porting.
