### ISSUE TITLE
DELETE not consisten behaviour

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7408]
Hi *!

This command sometimes ssucceeded, and sometimes throws exception in FB 3.0.10.
In FB25 it works always never throws exception. No exception it the expected behaviour.

`EXECUTE BLOCK
AS
BEGIN
  INSERT INTO fk_tabla_fej (ID, KOD, NEV) VALUES (1, 'XXX', 'ss');
  
  INSERT INTO fk_tabla_idoszak (id, fk_tabla_fej_id, gysor, nev) VALUES (1, 1, 5, 'sss');
  INSERT INTO fk_tabla_idoszak (id, fk_tabla_fej_id, gysor, nev) VALUES (2, 1, 4, 'zzz');
  INSERT INTO fk_tabla_idoszak (id, fk_tabla_fej_id, gysor, nev) VALUES (3, 1, 3, 'ggg');
  INSERT INTO fk_tabla_idoszak (id, fk_tabla_fej_id, gysor, nev) VALUES (4, 1, 2, 'aaa');
  INSERT INTO fk_tabla_idoszak (id, fk_tabla_fej_id, gysor, nev) VALUES (5, 1, 1, 'fff');
  
  DELETE FROM fk_tabla_idoszak WHERE fk_tabla_fej_id = 1 ORDER BY gysor ASC;--error
END`

The exception is

`Invalid insert or update value(s): object columns are constrained - no 2 table rows can have duplicate column values.
violation of PRIMARY or UNIQUE KEY constraint "FK_TABLA_IDOSZAK_UK1" on table "FK_TABLA_IDOSZAK".
Problematic key value is ("FK_TABLA_FEJ_ID" = 1, "GYSOR" = 2).`

[ddl.txt](https://github.com/FirebirdSQL/firebird/files/10141026/ddl.txt)

**Comment by EPluribusUnum** [comment]
Hi Mark!

The DDL is attached to the opening post.
Also the EXECUTE BLOCK is not necessary to reproduce the problem, you can run the command individually, it's just easier to execute a singe command. The error definiately comes from the DELETE.

**Comment by hvlad** [comment]
The error definitely from DELETE trigger. And it looks like it is related with the cursor stability that was absent before fb3.

**Comment by EPluribusUnum** [comment]
@hvlad , my bet was also cursor stability, but the inconsitent behaviour is very strange.

**Comment by hvlad** [comment]
DELETE now see no changes made by DELETE TRIGGER

**Comment by EPluribusUnum** [comment]
In this attached FB30 database the DELETE is successful.

[success_delete.ZIP](https://github.com/FirebirdSQL/firebird/files/10141171/success_delete.ZIP)

**Comment by EPluribusUnum** [comment]
Upsz. The delete is wrong in the example it is ORDER BY gysor ASC

**Comment by hvlad** [comment]
I going to look at it closer at next 1-2 days and will report back

**Comment by EPluribusUnum** [comment]
@hvlad , I upoaded the database to FTP where the DELETE succeeded.
I sent the details for the FTP in mail.

**Comment by EPluribusUnum** [comment]
@hvlad , any news on this issue?

**Comment by hvlad** [comment]
Sorry for delay, it got out of my attention after a few blackouts...

I've run scripts above on 3.0.11 and 2.5.9 and it both shows the same error message.

Looking closely at DDL I can confirm that it is not related with cursor stability.

After INSERT's data in the table is as follows (due to INSERTING branch of the trigger):

ID	| FK_TABLA_FEJ_ID	| GYSOR	| NEV
---|---|---|---
1	| 1	| 1	| sss
2	| 1	| 2	| zzz
3	| 1	| 3	| ggg
4	| 1	| 4	| aaa
5	| 1	| 5	| fff

Thus the DELETE will handle the row with ID = 1.  The trigger's DELETING branch first set  `gysor` to the 2147483647 (old value was 1) and then start to update other records setting `gysor = gysor - 1`. When it handle record with `gysor` = 2 and tries to set `gysor` = 1, unique index violation happens as there is still active record version of the first row with the same value (1) of field `gysor` (new value 2147483647 is not committed yet).

**Comment by hvlad** [comment]
BTW, on 3.0.11 full error message is

```
Invalid insert or update value(s): object columns are constrained - no 2 table rows can have duplicate column values.
violation of PRIMARY or UNIQUE KEY constraint "FK_TABLA_IDOSZAK_UK1" on table "FK_TABLA_IDOSZAK".
Problematic key value is ("FK_TABLA_FEJ_ID" = 1, "GYSOR" = 2147483647).
At trigger FK_TABLA_IDOSZAK_DEF line: 26, col: 9
At trigger FK_TABLA_IDOSZAK_DEF line: 62, col: 7
At block line: 15, col: 5.
```

**Comment by hvlad** [comment]
As I see it - error is expected. Unless real test case is different ;)
3.0.10 should get the same error message as 3.0.11.
3.0.11 should be released soon after 5.0 Beta1, I suppose.

**Comment by EPluribusUnum** [comment]
@hvlad , have you tried with the database mentioned in https://github.com/FirebirdSQL/firebird/issues/7408#issuecomment-1335338138 ? where the DELETE is succesful?

**Comment by hvlad** [comment]
No, as I can't connect to the host.

**Comment by EPluribusUnum** [comment]
@hvlad , forgot to sent the FTP details mail, sent the email now.

**Comment by hvlad** [comment]
Downloaded, thanks.

Triggers on `fk_tabla_idoszak` in database is completely different than trigger at the initial message
https://github.com/FirebirdSQL/firebird/issues/7408#issue-1472795966

**Comment by EPluribusUnum** [comment]
@hvlad , thank you. 
(looks like I was an idiot, sorry)

**Comment by hvlad** [comment]
Everybody makes mistakes, don't worry ;)
