### ISSUE TITLE
Nested IIFs is returning blanks at the end of the field

### ISSUE THREAD

**Issue by luronumen** [FirebirdSQL/firebird#7409]
**Actual Result**
- Nested IIFs is returning blanks at the end of the field:
  - A: It is returning "12________" instead of "12" (8 blank spaces at the end of the field)
  - B: It is returning "1234______" instead of "1234" (6 blank spaces at the end of the field)
  - C: It is returning "123456____" instead of "123456"  (4 blank spaces at the end of the field)
  - D: It is returning "12345678__" instead of "12345678" (2 blank spaces at the end of the field)

**Expected Result**
- Nested IIFs should not return blanks at the end of the field.
  - E: It is returning "1234567890" (No blank spaces at the end of the field)

**Steps to Reproduce the Issue**
- Run the following query on a database:
```
SELECT
  IIF(FALSE,IIF(FALSE,IIF(FALSE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') A,
  IIF(TRUE,IIF(FALSE,IIF(FALSE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') B,
  IIF(TRUE,IIF(TRUE,IIF(FALSE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') C,
  IIF(TRUE,IIF(TRUE,IIF(TRUE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') D,
  IIF(TRUE,IIF(TRUE,IIF(TRUE,IIF(TRUE,'1234567890','12345678'),'123456'),'1234'),'12') E
FROM
  RDB$DATABASE
```
**Environment Setup**
- Windows 11 Pro Version 22H2
- FirebirdSQL 3.0.10.33601 (x64)

**Comment by arvanus** [comment]
This behavior is expected if you consider that '1234567890' is a char(10), you would need to cast as varchar or trim your data

**Comment by luronumen** [comment]
Hi @arvanus 

Thank you very much for your prompt reply!
This issue is also happening when cast it as VARCHAR(10):

```
SELECT
 CAST(IIF(FALSE,IIF(FALSE,IIF(FALSE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') AS VARCHAR(10)) A,
 CAST(IIF(TRUE,IIF(FALSE,IIF(FALSE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') AS VARCHAR(10)) B,
 CAST(IIF(TRUE,IIF(TRUE,IIF(FALSE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') AS VARCHAR(10)) C,
 CAST(IIF(TRUE,IIF(TRUE,IIF(TRUE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') AS VARCHAR(10)) D,
 CAST(IIF(TRUE,IIF(TRUE,IIF(TRUE,IIF(TRUE,'1234567890','12345678'),'123456'),'1234'),'12') AS VARCHAR(10)) E
FROM
  RDB$DATABASE
```

**Comment by arvanus** [comment]
Try this
```
SELECT
  IIF(FALSE,IIF(FALSE,IIF(FALSE,IIF(FALSE,cast('1234567890' as varchar(10)),'12345678'),'123456'),'1234'),'12') A,
  IIF(TRUE,IIF(FALSE,IIF(FALSE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') B,
  IIF(TRUE,IIF(TRUE,IIF(FALSE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') C,
  IIF(TRUE,IIF(TRUE,IIF(TRUE,IIF(FALSE,'1234567890','12345678'),'123456'),'1234'),'12') D,
  IIF(TRUE,IIF(TRUE,IIF(TRUE,IIF(TRUE,'1234567890','12345678'),'123456'),'1234'),'12') E
FROM
  RDB$DATABASE
```

**Comment by asfernandes** [comment]
You must cast the literal string, not the IIF result.

**Comment by luronumen** [comment]
Hi @arvanus  and @asfernandes 

The issue is NOT reproducible using the following query:

```
SELECT
  IIF(FALSE,IIF(FALSE,IIF(FALSE,IIF(FALSE,CAST('1234567890' AS VARCHAR(10)),'12345678'),'123456'),'1234'),'12') A,
  IIF(TRUE,IIF(FALSE,IIF(FALSE,IIF(FALSE,CAST('1234567890' AS VARCHAR(10)),'12345678'),'123456'),'1234'),'12') B,
  IIF(TRUE,IIF(TRUE,IIF(FALSE,IIF(FALSE,CAST('1234567890' AS VARCHAR(10)),'12345678'),'123456'),'1234'),'12') C,
  IIF(TRUE,IIF(TRUE,IIF(TRUE,IIF(FALSE,CAST('1234567890' AS VARCHAR(10)),'12345678'),'123456'),'1234'),'12') D,
  IIF(TRUE,IIF(TRUE,IIF(TRUE,IIF(TRUE,CAST('1234567890' AS VARCHAR(10)),'12345678'),'123456'),'1234'),'12') E
FROM
  RDB$DATABASE
```

Is this a firebird issue or is the current behavior expected? For me this current behavior is very strange.

**Comment by dyemanov** [comment]
Expected. Literal is CHAR string, and IIF(CHAR, CHAR) also returns CHAR with the longest length (padded with spaces).
