### ISSUE TITLE
Unify display of system procedures & packages with other system objects

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7411]
System objects should be displayed in ISQL when SHOW SYSTEM is used and should not be displayed when user objects (by default) to be shown.

**Comment by pavel-zotov** [comment]
AFAIU, command 'SHOW SYSTEM' shows:
1) name of each package followed by its procedures;
2) list of packages;

Currently it looks like this:
```
Package: RDB$BLOB_UTIL
    CANCEL_BLOB
    CLOSE_HANDLE

Package: RDB$PROFILER
    CANCEL_SESSION
    DISCARD
    FINISH_SESSION
    FLUSH
    PAUSE_SESSION
    RESUME_SESSION
    SET_FLUSH_INTERVAL

Package: RDB$TIME_ZONE_UTIL
    TRANSITIONS

Packages:
    RDB$BLOB_UTIL
    RDB$PROFILER
    RDB$TIME_ZONE_UTIL
```
(i've added indentation for readability)

But what about packaged *functions* ? They aren't shown.
Consider query:
```set width pkg_name 31;
set width obj_name 31;

select pg.rdb$package_name as pkg_name, 'packaged proc' as obj_type, sp.rdb$procedure_name as obj_name
from rdb$packages pg
left join rdb$procedures sp on pg.rdb$package_name = sp.rdb$package_name

UNION ALL

select pg.rdb$package_name, 'packaged func', sf.rdb$function_name
from rdb$packages pg
left join rdb$functions sf on pg.rdb$package_name = sf.rdb$package_name
;

PKG_NAME            OBJ_TYPE       OBJ_NAME
==================  =============  ================
. . .               . . .          . . .
RDB$TIME_ZONE_UTIL  packaged func  DATABASE_VERSION
RDB$PROFILER        packaged func  START_SESSION
RDB$BLOB_UTIL       packaged func  IS_WRITABLE
RDB$BLOB_UTIL       packaged func  NEW_BLOB
RDB$BLOB_UTIL       packaged func  OPEN_BLOB
RDB$BLOB_UTIL       packaged func  SEEK
RDB$BLOB_UTIL       packaged func  READ_DATA
```
None of lines marked as 'packaged func' can be found in SHOW SYSTEM output.
Is it expected ?

**Comment by AlexPeshkoff** [comment]
According to ticket HDR (procedures & packages) - yes, expected, I think. Add new ticket for functions pls.

**Comment by pavel-zotov** [comment]
> Add new ticket for functions pls.

https://github.com/FirebirdSQL/firebird/issues/7475

**Comment by mrotteveel** [comment]
One minor nitpick, I find it odd that the individual packages are listed *before* the list of packages, I think that order should be reversed.
