### ISSUE TITLE
Regression: bad plan in FB 3.0.9+ (correct in FB 3.0.8)

### ISSUE THREAD

**Issue by fdcastel** [FirebirdSQL/firebird#7413]
Today I found a problem with Firebird 3.0.10 which forced me to rollback all my installs to 3.0.8. 😢 

The original database had 4M rows in the affected table. It took me some hours but I managed to create a smaller database with a reproducible case attached. 

Sorry for the large script. I tried to make it smaller but the problem did not occurs without data. The index selectivity appears to be a factor. 

Some key facts about the database structure:
  - Tables `T1` and `T2` have a `subtype` relationship (`T2 IS_A T1`). 
  - Tables `T1` and `T3` have a `1:N` relationship (`T3 HAS_N T1`).
  - All tables have composite primary keys

The following query reproduces the problem:

```sql
SELECT
  t1.id_x,
  t1.id_t1,
  t1.total,
  t3.invoice_no,
  t3.created_at
FROM
  t1
--/*
  JOIN t2
    ON t2.id_t2 = t1.id_t1 AND
       t2.id_x = t1.id_x
--*/
  JOIN t3
    ON t3.id_t3 = t1.id_t3 AND
       t3.id_x = t1.id_x
WHERE
  t3.invoice_no = 1683998
```

Firebird 3.0.8 plan:

```
PLAN JOIN (T3 INDEX (XAK2T3), T1 INDEX (R_542), T2 INDEX (XPKT2))
```

Firebird 3.0.10 plan:

```
PLAN JOIN (T3 INDEX (XAK2T3), T2 NATURAL, T1 INDEX (XPKT1))
```

That `T2 NATURAL` is the problem. In this sample database it returns quickly but in the original database (4M rows on `T2`) it took more than 1 minute.

Removing the JOIN with `T2` table the plan is the same in both Firebird versions:

```
PLAN JOIN (T3 INDEX (XAK2T3), T1 INDEX (R_542))
```

I hope this sample may help. I'm available for more tests or any other information needed.

Attached files:

[TEST-AN.zip](https://github.com/FirebirdSQL/firebird/files/10175307/TEST-AN.zip) Sample database.
[create-database-an.zip](https://github.com/FirebirdSQL/firebird/files/10175308/create-database-an.zip) Script to build the sample database.

**Comment by dyemanov** [comment]
It should already be fixed in snapshot builds.

**Comment by fdcastel** [comment]
Thank you, Dmitry, for the prompt feedback. 

Indeed. Using the latest snapshot Firebird 3.0.11 built the expected plan:

```
PLAN JOIN (T3 INDEX (XAK2T3), T1 INDEX (R_542), T2 INDEX (XPKT2))
```

Could you give me some pointers about what caused this problem? 

There was another issue here in GitHub about this problem or it was an unregistered bugfix?

**Comment by dyemanov** [comment]
It was registered and fixed in prior versions, but it recently appeared that the fix was incomplete and a post-fix was committed into v3.0.11 without registering a new issue.

**Comment by dyemanov** [comment]
It's related to #3357 and #7118.

**Comment by fdcastel** [comment]
_Please read what follows only with the best of intentions for the project and for the community._

Forgive me for being a bit inquisitive but we had a similar problem months ago when we were forced to pull back Firebird 3.0.9 from production due https://github.com/FirebirdSQL/firebird/issues/7137. 



When 3.0.10 was out we were relieved to see that the problem was fixed... Until yesterday. And now this makes the *second consecutive release* with problems in the optimizer.

And because of these two events some customers are now reluctant to upgrade their systems beyond Firebird 3.0.8.

All that said:

- Folowing [This list](https://github.com/FirebirdSQL/firebird/commits/B3_0_Release) I could find [this commit](https://github.com/FirebirdSQL/firebird/commit/78583ab3ee5e7cd1a3aae41bc9c3a6fdb28918e8) of yours which, I believe, is the fix for the problem. However:
  - I see no test case added with this commit. What measures are in place to avoid problems like these in the future?
  - This test case of mine (or another, smaller but similar) would be added to the QA test suite?

- There are any plans to adopt a more strict [Semantic Versioning](https://semver.org/) practices?
  - This kind of change (query optimizer) surely could be made into a MINOR version. But not into a PATCH one.
  - I certainly wasn't the only one surprised to find a significant break when migrating from 3.0.8 to 3.0.9.
  - Sysadmins expect to keep their systems updated against vulnerabilities and potential crashes. They know what to expect when upgrading a MAJOR or MINOR version. But now my customers are afraid of to update even a PATCH version of Firebird due to these events.

Please don't misunderstand me. I really have no knowledge about your development processes nor QA. But I wish to understand a bit more to explain what occurred to my customers and, also, collaborate with QA test cases if possible.

**Comment by dyemanov** [comment]
Sometimes it happens, unfortunately. And the optimizer is such a beast where touching X is very likely to affect Y. A minor improvement looked simple but later caused undesirable side effects. I agree it would be better to avoid such changes in point releases, the lesson was learned. And of course, your test will be included into QA (which currently slightly lags behind due to internal restructuring).

**Comment by fdcastel** [comment]
Confirmed to work in Firebird 3.0.11.

Firebird 3.0.11 plan:

```
PLAN JOIN (T3 INDEX (XAK2T3), T1 INDEX (R_542), T2 INDEX (XPKT2))
```

Thanks guys! 👍
