### ISSUE TITLE
BIGINT + Dialect1

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7416]
Hi *!

SELECT *
FROM mon$transactions t
WHERE t.mon$transaction_id = :transaction_id

In Dialect1 transaction_id parameter reported az BIGINT after preparing the statement. But BIGINT is supported only in Dialect3. In Dialect1 it shoud be reported az INTEGER.

**Comment by aafemt** [comment]
Dialect 1 is deprecated years ago. There is no point to fix it.

**Comment by aafemt** [comment]
To have different rules doesn't mean to be "broken". Either you accept these rules or perform calculations by other means. Calculations in dialect 3 comply with ANSI SQL standard.

**Comment by EPluribusUnum** [comment]
ANSI SQL standard also doesn't mean that it is usabe. The standartd is too loosely defined.

Discussions

https://www.mail-archive.com/firebird-devel@lists.sourceforge.net/msg20326.html
https://www.mail-archive.com/firebird-devel@lists.sourceforge.net/msg20343.html
https://www.mail-archive.com/firebird-devel@lists.sourceforge.net/msg20382.html
https://www.youtube.com/watch?v=KvI6tPVFVNY&t=3090s

**Comment by mrotteveel** [comment]
> In Dialect3 math is broken.

Stop repeating this frame. The math in dialect 3 is not broken, so there is nothing to fix.

> We get a promise that Dialect1 will be supported until the math issue is fixed.

Who promised you that?

**Comment by EPluribusUnum** [comment]
@mrotteveel , see youtube link above.

**Comment by mrotteveel** [comment]
That doesn't sound like a hard promise to me though (there were a lot of conditionals and reservations in Dmitry's statement there). Also nice that such "decisions" are not communicated on firebird-devel, but only in some Q&A session.
