### ISSUE TITLE
Transactions/cache not synchronized correctly for distinct remote connections in CS

### ISSUE THREAD

**Issue by mariuszzy** [FirebirdSQL/firebird#7417]
I'm testing Classic Firebird LI-V4.0.2.2816 under Linux Mint 5.15.0-56-generic. 

Created is a database with the following table:

CREATE GENERATOR GEN_TEST_TABLE;
CREATE TABLE TEST_TABLE (
    ID integer not null,
    CT TIMESTAMP default current_timestamp,
    NAME varchar(64) not null,
    PHONE varchar(16),
    EMAIL varchar(128),
    constraint TEST_TABLE_PK primary key (ID)
);

When connected remotely from another host (isql on Solaris or  IBExpert on Windows) I'm inserting one row to that table:

insert into TEST_TABLE (ID, NAME) values (gen_id(GEN_TEST_TABLE, 1), 'B'); commit;

On Linux server host issuing:

rollback; select count(*) from TEST_TABLE;

most of the time returns wrong number of rows. It doesn't reflect the inserted row. After repeating rollback-select statements the correct  number of rows is returned.  

When both connections are local the problem does not arise.

Under Linux Super and SuperClassic are not affected. At least for a couple of tests I did. 

BTW under Solaris Super is not affected but both SuperClassis and Classic behave as described above.

**Comment by dyemanov** [comment]
Please re-try with the latest snapshot build.

**Comment by mariuszzy** [comment]
Confirmed, 4.0.3.2882 works flawlessly under Linux and Solaris.
