### ISSUE TITLE
Many concurrent connections can occasionally cause access violation in 3.0.10 (3.0.8 OK)

### ISSUE THREAD

**Issue by stavikpetr** [FirebirdSQL/firebird#7419]
Hello, this issue can be easily reproduced by the following code (this is excerpt from a test with IBPP library).

```cpp
    std::vector<std::thread> threads;
    for (size_t i = 0; i < 200; i++)
    {		
        threads.emplace_back(std::thread([=]() {
	    while (true) 
            {
                IBPP::Database db1;
                db1 = IBPP::DatabaseFactory(ServerName, DbName, UserName, Password);
                db1->Connect();
                db1->Disconnect();
                std::this_thread::sleep_for(std::chrono::milliseconds(50));
            }
            }));
    }
	
    std::this_thread::sleep_for(std::chrono::seconds(10000));
```
The access violation is caused by this line in function `disconnect()` in file interface.cpp `port->port_context = NULL;` (fbclient.dll). It seems that this line was added in fix #7147. After a bit of investigation, it basically seems that it is possible that the `port` that was passed into this function was dealloacated with the deleting of the port context and therefore this access is invalid.

I can provide additional details if necessary.

Issue happens with both ODBC and IBPP library.

As the title suggests, 3.0.8 is OK and we did a revert.

**Comment by omachtandras** [comment]
@stavikpetr According to our tests, classic is not affected, only Superserver and SuperClassic. Until the release of 3.0.11, the option can be changed to classic.
