### ISSUE TITLE
Add REPLICA MODE to the output of the isql SHOW DATABASE command

### ISSUE THREAD

**Issue by sim1984** [FirebirdSQL/firebird#7425]
Now, to find out in what mode the current database is, one of the queries needs to be executed:

```sql
SELECT MON$REPLICA_MODE FROM MON$DATABASE;
```

or

```sql
SELECT RDB$GET_CONTEXT('SYSTEM', 'REPLICA_MODE') FROM RDB$DATABASE;
```

However, we have a nice SHOW DATABASE command in isql that shows a lot of things, but not the replication mode:

```
SQL> show database;
Database: inet://localhost/horses
        Owner: SYSDBA
PAGE_SIZE 16384
Number of DB pages allocated = 142752
Number of DB pages used = 139414
Number of DB pages free = 3338
Sweep interval = 20000
Forced Writes are ON
Transaction - oldest = 1044
Transaction - oldest active = 1045
Transaction - oldest snapshot = 1045
Transaction - Next = 1048
ODS = 13.0
Database not encrypted
Wire crypt plugin: ChaCha64
Creation date: Dec 14, 2022 15:03:28 GMT
Protocol version = 17
Default Character set: UTF8
SQL SECURITY DEFINER
```

In addition, it would be nice to know if replication is enabled at all with the command:

```sql
ALTER DATABASE
ENABLE PUBLICATION;
```

What can be done with a request:

```sql
SELECT RDB$ACTIVE_FLAG
FROM RDB$PUBLICATIONS
WHERE RDB$PUBLICATION_NAME = 'RDB$DEFAULT';
```

**Comment by dyemanov** [comment]
Agreed about the replica mode. As for publication state, I'm not that sure. Multiple (named) publications will be allowed in future versions, with ALTER DATABASE managing only the default one (as a shortcut command). Why should we report status of the default publication but ignore the others? Replication may be working but you'll see it as inactive. I'd rather go for explicit `SHOW PUBLICATIONS` | `SHOW PUBLICATION <name>`commands instead, maybe with `SHOW PUBLICATION` (without name) showing the default publication.

**Comment by sim1984** [comment]
Commands  `SHOW PUBLICATIONS | SHOW PUBLICATION <name>` is a good idea.

**Comment by dyemanov** [comment]
Should `SHOW DATABASE` print nothing for a regular (non-replica) database or something like "Database is not a replica"?

**Comment by sim1984** [comment]
It should look something like the arguments to `gfix -replica`.

```
....
Replica mode: {NONE | READ ONLY | READ WRITE}
```

**Comment by dyemanov** [comment]
Done re. the replica node, in v4 so far (to be frontported into v5 soon). As for SHOW PUBLICATION[S], I'll create a separate ticket.

**Comment by aafemt** [comment]
Isn't #7001 enough?

**Comment by dyemanov** [comment]
Thanks for reminding.

**Comment by pavel-zotov** [comment]
::: qa issues :::
1) Test name: functional/basic/isql/test_07.py
2) Currently avaliable only in Firebird-4.x. Waiting for frontport.

**Comment by dyemanov** [comment]
Closing this ticket. Publication status will be covered separately by #7001.

**Comment by aafemt** [comment]
Aren't replica mode and publication status two separate things? Former is on target side of replication while later is in source.

**Comment by dyemanov** [comment]
Yes, but I miss your point. Replica mode is already shown, thus this ticket is closed. #7001 is about publication status, it will be implemented (shown by ISQL) separately. SHOW DATABASE will print either "Replica mode" or "Publication" status strings (or both).

**Comment by aafemt** [comment]
Ah, sorry, I misread your comment.
