### ISSUE TITLE
Different Batch Statements - error on second one 

### ISSUE THREAD

**Issue by apz28** [FirebirdSQL/firebird#7429]
Test using latest .NET driver with Firebird v4.2

           using (var con = new FbConnection(Firebird_Connection_String...))
            {
                con.Open();

                using (var cmd = con.CreateCommand())
                {
                    cmd.CommandText = "create table batch (i int check (i < 1000), ts timestamp)";
                    cmd.ExecuteNonQuery();
                }

                try
                {
                    var @is = new[] { 1, 2, 3, 4 };
                    var ts = new[] { new DateTime(2022, 01, 17, 1, 0, 0), 
                        new DateTime(2022, 01, 17, 2, 0, 0),
                        new DateTime(2022, 01, 17, 2, 1, 0),
                        new DateTime(2022, 01, 17, 2, 2, 0)};

                    // No problem on this insert
                    using (var cmd = con.CreateBatchCommand())
                    {
                        cmd.CommandText = "insert into batch values (@i, @ts)";
                        var batch1 = cmd.AddBatchParameters();
                        batch1.Add("i", @is[0]);
                        batch1.Add("ts", ts[0]);
                        var batch2 = cmd.AddBatchParameters();
                        batch2.Add("i", @is[1]);
                        batch2.Add("ts", ts[1]);
                        var result = cmd.ExecuteNonQuery();
                    }

                    // Getting below error on this second
                    // Dynamic SQL Error
                    // SQL error code = -804
                    // Count of read-write columns does not equal count of values
                    using (var cmd = con.CreateBatchCommand())
                    {
                        cmd.CommandText = "insert into batch values (@i)";
                        cmd.Prepare();
                    }
                }
                finally
                {
                    using (var cmd = con.CreateCommand())
                    {
                        cmd.CommandText = "drop table batch";
                        cmd.ExecuteNonQuery();
                    }
                }
            }

**Comment by sim1984** [comment]
This is your mistake. The error will also occur without CreateBatchCommand

**Comment by dyemanov** [comment]
Correct command text in the second case should be: `"insert into batch (i) values (@i)"`
