### ISSUE TITLE
zlib version 1.2.13 released 2022-10-13

### ISSUE THREAD

**Issue by basid-irk** [FirebirdSQL/firebird#7437]
https://zlib.net/ChangeLog.txt

ChangeLog file for zlib

Changes in 1.2.13 (13 Oct 2022)
- Fix configure issue that discarded provided CC definition
- Correct incorrect inputs provided to the CRC functions
- Repair prototypes and exporting of new CRC functions
- Fix inflateBack to detect invalid input with distances too far
- Have infback() deliver all of the available output up to any error
- Fix a bug when getting a gzip header extra field with inflate()
- Fix bug in block type selection when Z_FIXED used
- Tighten deflateBound bounds
- Remove deleted assembler code references
- Various portability and appearance improvements

**Comment by hvlad** [comment]
I'll update the Windows build of zlib a bit later.
