### ISSUE TITLE
Firebird 4.0.2.2816 Object Identifiers cannot exceed 31 charakters 

### ISSUE THREAD

**Issue by BenjaminBac** [FirebirdSQL/firebird#7439]
Testet with Firebird 4.0.2.2816 & nightly Build 4.0.3.2885 

we tried using more than 31 characters for new meta object names. with Firebird 4.0 it should be possible (63)
its a complete new server with blank firebird installation but every statments failed. Just using 31 char max is ok. exceeding characters in alle meta-object names are causing the same arithmetic exception.

```
This operation is not defined for system tables.
unsuccessful metadata update.
CREATE SEQUENCE GEN_SOME_NEW_GENERATOR_TO_TEST_ID failed.
arithmetic exception, numeric overflow, or string truncation.
string right truncation.
expected length 31, actual 33.
<Missing arg #1 - possibly status vector overflow>.
-------------------------------------------------------------
SQLCODE: -607
SQLSTATE: 22001
GDSCODE: 335544351
```

example: `create sequence GEN_some_new_generator_to_test_ID`

tried with IBExpert & IBDAC latest versions. 
Even setting `MaxIdentifierCharLength = 63` in `Firebird.conf` but nothing solved the Problem.

Fields in system tables are all correct. 
![grafik](https://user-images.githubusercontent.com/104010524/209675448-247bebc8-c6f6-4257-8e14-be473d507c5e.png)

is there some kind of configurations that we are missing or is this bugged?

**Comment by aafemt** [comment]
Have you tested with isql? According to error message you most likely have older client library.

**Comment by BenjaminBac** [comment]
nope. all gds32.dll and fbclient.dll were deletet from this system. using the firebird.dll from the installation pack. 
![grafik](https://user-images.githubusercontent.com/104010524/209677100-d1f46946-a3a2-4163-91dd-cc274b6acd0f.png)


with isql i can create the metanames 🤔 but the behavior seems not to be ok.   
tree:
![grafik](https://user-images.githubusercontent.com/104010524/209677868-af9d35e6-f114-4f46-96e2-4a2916840410.png)

Data:
![grafik](https://user-images.githubusercontent.com/104010524/209677893-972c7029-c406-4756-b57a-93c27a3566c2.png)

**Comment by aafemt** [comment]
It is behavior of IBExpert, using ISC API. Use isql for tests.

**Comment by AlexPeshkoff** [comment]
On 12/27/22 16:47, BenjaminBac wrote:
>
> Testet with Firebird 4.0.2.2816 & nightly Build 4.0.3.2885
>

isql -z employee
ISQL Version: LI-V4.0.2.2816 Firebird 4.0
Server version:
LI-V4.0.2.2816 Firebird 4.0
Database: employee, User: SYSDBA
SQL> CREATE SEQUENCE GEN_SOME_NEW_GENERATOR_TO_TEST_ID;
SQL> show gen;
Generator CUST_NO_GEN, current value: 1015, initial value: 1, increment: 1
Generator EMP_NO_GEN, current value: 145, initial value: 1, increment: 1
Generator GEN_SOME_NEW_GENERATOR_TO_TEST_ID, current value: 0, initial 
value: 1, increment: 1
SQL>

**Comment by BenjaminBac** [comment]
yeah... seems to be an Issue with IBExpert and IBDAC .... with ISQL everything is quite right...🤦‍♂️
I assumed it had something to do with the Firebird or a missing configuration, due to the message.
