### ISSUE TITLE
FB refuses to create unique index on col with no dups [CORE400]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird#744]
Submitted by: jamincat (jamincat)

Attachments:
[PROB.FBK](https://github.com/FirebirdSQL/jira-attachments/raw/main/CORE/CORE-400/10036_PROB.FBK)

SFID: 1183051#&#x2060;
Submitted By: jamincat

Cannont create unique index\. Database running fine with
unique index on column\. While restoring a backup the
following error was logged\. 

gbak: ERROR: attempt to store duplicate value \(visible
to active transactions\) in unique index
"SMS\_GATEWAY\_TRANS\_NO"\.

I put together some java code to find duplicate values
but found none\. I also used IBExpert to make the index
inactive and then active on a copy of the original
database\. The same error was reported when i tried to
make the index active\.

Windows XP SP2\.
Firebird Super Server versions 1\.5\.0\.4290 and 1\.5\.2\.4731

I have attached the backup database\. I have removed all
tables and columns except the one that causes the problem\.

Output from restore operation\.

#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;

IBE: Starting restore\. Current time: 13:37:45
gbak: opened file C:\\Documents and Settings\\Jamin\\My
Documents\\work\\firebird problem\\PROB\.FBK 
gbak: transportable backup \-\- data in XDR format 
gbak:   backup file is compressed 
gbak: created database C:\\Documents and
Settings\\Jamin\\My Documents\\work\\firebird
problem\\PROB\.FDB, page\_size 4096 bytes 
gbak: started transaction 
gbak: restoring domain RDB$216 
gbak: restoring domain RDB$217 
gbak: restoring domain RDB$228 
gbak: restoring domain RDB$229 
gbak: restoring table SMS\_GATEWAY\_TRANS\_DETAILS 
gbak:     restoring column TRANS\_NO 
gbak:     restoring column ID 
gbak: committing metadata for table
SMS\_GATEWAY\_TRANS\_DETAILS 
gbak: restoring generator SMS\_GATEWAY\_TRANS\_DETAILS\_ID
value: 5346 
gbak: restoring stored procedure
SMS\_GATEWAY\_TRANS\_DETAILS\_ID 
gbak: restoring parameter NUMBERTOALLOCATE for stored
procedure 
gbak: restoring parameter NEWID for stored procedure 
gbak:     committing metadata 
gbak:     restoring index RDB$PRIMARY21 
gbak:     restoring index SMS\_GATEWAY\_TRANS\_NO 
gbak: restoring data for table SMS\_GATEWAY\_TRANS\_DETAILS 
gbak: committing data for table SMS\_GATEWAY\_TRANS\_DETAILS 
gbak:    5346 records restored 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user PUBLIC 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user SYSDBA 
gbak:     restoring privilege for user SYSDBA 
gbak: creating indexes 
gbak:     restoring index RDB$PRIMARY21                   
gbak: cannot commit index SMS\_GATEWAY\_TRANS\_NO            
gbak: ERROR: attempt to store duplicate value \(visible
to active transactions\) in unique index
"SMS\_GATEWAY\_TRANS\_NO" 
gbak:     restoring index SMS\_GATEWAY\_TRANS\_NO            
gbak: finishing, closing, and going home 

IBE: Restore completed\. Current time: 13:37:49\. Elapsed
time: 00:00:0

Java test class

#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;#&#x2060;

import java\.sql\.\*;

public class DBTest
    \{
    public static void main\(String\[\] args\)
        \{
        try
            \{
            Class\.forName\("org\.firebirdsql\.jdbc\.FBDriver"\);

            final Connection connection =
DriverManager\.getConnection\("jdbc:firebirdsql:localhost:C:/PROB\.FDB",
"SYSDBA", "masterkey"\);

            try
                \{
                searchForDuplicates\(connection\);
                \}
            finally
                \{
                connection\.close\(\);
                \}

            \}
        catch \(ClassNotFoundException e\)
            \{
            e\.printStackTrace\(\);
            \}
        catch \(SQLException e\)
            \{
            e\.printStackTrace\(\);
            \}
        \}

    public static void searchForDuplicates\(Connection
connection\) throws SQLException
        \{
        final Statement statement =
connection\.createStatement\(\);
        final PreparedStatement preparedStatement =
connection\.prepareStatement\("SELECT \* FROM
SMS\_GATEWAY\_TRANS\_DETAILS WHERE TRANS\_NO = ?"\);

        final ResultSet results =
statement\.executeQuery\("SELECT \* FROM
SMS\_GATEWAY\_TRANS\_DETAILS"\);

        try
            \{
            int recordCount = 0;
            int duplicates = 0;

            while \(results\.next\(\) == true\)
                \{
                recordCount\+\+;

                final byte\[\] bytes =
results\.getBytes\("TRANS\_NO"\);

                preparedStatement\.clearParameters\(\);
                preparedStatement\.setBytes\(1, bytes\);

                final int matching =
recordsMatchingCurrent\(preparedStatement\);

                if \( matching \> 1 \)
                    duplicates \+= \(matching \-1\);

                \}

            System\.out\.println\("Scanned " \+ recordCount
\+ " records"\);
            System\.out\.println\("Found " \+ duplicates \+
" duplicate records"\);
            \}
        finally
            \{
            results\.close\(\);
            \}
        \}

    public static int
recordsMatchingCurrent\(PreparedStatement
preparedStatement\) throws SQLException
        \{
        final ResultSet resultSet =
preparedStatement\.executeQuery\(\);
        try
            \{
            int count = 0;

            while \(resultSet\.next\(\)\)
                count\+\+;

            return count;
            \}
        finally
            \{
            resultSet\.close\(\);
            \}
        \}

    \}

**Comment by dyemanov** [comment]
The backup attached to this ticket restores successfully on v3.0.11, v4.0.4 and v5.0.0. Shouldn't this issue be closed?

**Comment by mrotteveel** [comment]
@dyemanov Given the age of this ticket, shouldn't it just be closed?
