### ISSUE TITLE
fbSampleExtAuthKeygen and libfbSampleExtAuth.so example files contain '$ORIGIN' in rpath

### ISSUE THREAD

**Issue by cboltz** [FirebirdSQL/firebird#7449]
While building firebird 4.0.2.2816 for openSUSE, rpmlint found the following issues:

```
binary-or-shlib-defines-rpath (Badness: 10000) /usr/share/doc/packages/firebird/sample/prebuilt/bin/fbSampleExtAuthKeygen (RUNPATH: $ORIGIN/../lib)
binary-or-shlib-defines-rpath (Badness: 10000) /usr/share/doc/packages/firebird/sample/prebuilt/plugins/libfbSampleExtAuth.so (RUNPATH: $ORIGIN/../lib) 
```

Checking these two files with `strings` shows that these files _literally_ include `$ORIGIN/../lib` (really the variable name, while you probably expect it to get expanded).

My guess is that this is caused by the single quotes (`'`) used in `examples/extauth/Makefile`:
```
LDFLAGS=-pthread -L$(LIB) -Wl,-rpath,'$$ORIGIN/../lib' $(TOMCRYPT_LINK) 
```
These single quotes probably prevent the variable to be expanded.

That said: the even better solution would be not to embed any rpath.

**Comment by asfernandes** [comment]
The rpath is correct, it's used in all Firebird binaries and make them relocatable. It's a sample, if you need a different thing change it in your code.
