### ISSUE TITLE
database error internal Firebird consistency check while open with new build of Firebird 5.0

### ISSUE THREAD

**Issue by virgonia** [FirebirdSQL/firebird#7450]
I have a database that i create using Firebird 5.0 a while ago.
This database has no problem when opened using build WI-T5.0.0.890 Firebird 5.0 Beta 1 but an error occurs when opened with build WI-T5.0.0.905 until last build WI-T5.0.0.910
![ss_905](https://user-images.githubusercontent.com/30924531/212501204-c429a043-600d-4bfd-83e1-0468f6477954.jpg)
![ss_910_lastest](https://user-images.githubusercontent.com/30924531/212501205-c0eaa16c-4702-46ef-8f26-72ea0f93a9c7.jpg)
![ss_890](https://user-images.githubusercontent.com/30924531/212501206-31a3b460-3957-45dd-ae85-05d261dd3e55.jpg)
[inventory.zip](https://github.com/FirebirdSQL/firebird/files/10419082/inventory.zip)

**Comment by virgonia** [comment]
other databases also happen the same thing
![other_db](https://user-images.githubusercontent.com/30924531/212501307-b341eecc-f5af-4a0b-ab6b-0828b59958ae.jpg)

**Comment by asfernandes** [comment]
We do not maintain compatibility of databases before a final release of a major version.

**Comment by virgonia** [comment]
ok thanks
