### ISSUE TITLE
Cant build on Oracle Linux 8 Ampere V1 (arm64)

### ISSUE THREAD

**Issue by zeduardo2000** [FirebirdSQL/firebird#7452]
Greetings,
i´m not, by any means, a c++ expert and linux neither. i just want to take the oracle free tier a spin.
4 cpu´s with 24gb seems too good for personal projects.

i´m trying to build v4.0.2 from source but i´m stuck with this message:

make[3]: Entering directory '/home/opc/firebird/gen'
g++   -static-libstdc++  -pthread  -Wl,-rpath,/lib -Wl,-rpath,/intl  -Wl,--version-script,empty.vers /home/opc/firebird/temp/Release/gpre/c_cxx.o /home/opc/firebird/temp/Release/gpre/cmd.o /home/opc/firebird/temp/Release/gpre/cme.o /home/opc/firebird/temp/Release/gpre/cmp.o /home/opc/firebird/temp/Release/gpre/exp.o /home/opc/firebird/temp/Release/gpre/gpre.o /home/opc/firebird/temp/Release/gpre/hsh.o /home/opc/firebird/temp/Release/gpre/int_cxx.o /home/opc/firebird/temp/Release/gpre/jrdmet.o /home/opc/firebird/temp/Release/gpre/movg.o /home/opc/firebird/temp/Release/gpre/msc.o /home/opc/firebird/temp/Release/gpre/obj_cxx.o /home/opc/firebird/temp/Release/gpre/par.o /home/opc/firebird/temp/Release/gpre/pat.o /home/opc/firebird/temp/Release/gpre/sqe.o /home/opc/firebird/temp/Release/gpre/sql.o /home/opc/firebird/temp/Release/gpre/boot/gpre_meta_boot.o /home/opc/firebird/temp/Release/yvalve/gds.o /home/opc/firebird/temp/Release/common.a -o /home/opc/firebird/gen/Release/firebird/bin/gpre_boot -L/home/opc/firebird/gen/Release/firebird/lib -latomic -lm -ldl   -ldecFloat -lre2
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status

after the machine was created (Linux Oracle 8 a branch of centos 8) i´ve run the following commands :

git clone -b v4.0.2 https://github.com/FirebirdSQL/firebird.git
sudo yum group install "Development Install"
sudo yum install llvm-toolset libicu libicu-devel ncurses ncurses-devel
./autogen.sh --with-system-editline=yes --with-system-icu 
./configure --with-builtin-tommath --with-builtin-tomcrypt --prefix=/opt/firebird
Make

it´s seems something with static libraries, wich i´ve tried to find without any luck ...

Any help ?
Thanks

**Comment by asfernandes** [comment]
Try install something like `libstdc++-devel`

**Comment by zeduardo2000** [comment]
Package libstdc++-devel-8.5.0-16.0.1.el8_7.aarch64 is already installed.

**Comment by AlexPeshkoff** [comment]
On 1/18/23 04:52, zeduardo2000 wrote:
>
> Package libstdc++-devel-8.5.0-16.0.1.el8_7.aarch64 is already installed.
>

Just to try to understand what happens - try to run last command, i.e. 
starting
g++ -static-libstdc++ -pthread -Wl,-rpath,/lib -Wl,-rpath,/intl 
-Wl,...............
from command line without -static-libstdc++ :
g++ -pthread -Wl,-rpath,/lib -Wl,-rpath,/intl -Wl,...............

**Comment by zeduardo2000** [comment]
Greetings 

As suggested by @AlexPeshkoff, removing -static-libstdc++ advanced a little bit further.
Now it stops on

make[3]: Entering directory '/home/opc/firebird/gen'
/home/opc/firebird/gen/Release/firebird/bin/gpre_current -m -z -n /home/opc/fibird/src/yvalve/array.epp /home/opc/firebird/temp/Release/yvalve/array.cpp
make[3]: /home/opc/firebird/gen/Release/firebird/bin/gpre_current: Command not found

**Comment by zeduardo2000** [comment]
Should i post this question on https://groups.google.com/g/firebird-devel ?

Thanks

**Comment by AlexPeshkoff** [comment]
Yes, asking in devel good idea.

What about your last question - missing gpre_current is for sure result of building gpre_boot manually, not by make. 
To move on you should fix your build environment - that's not OK when use of supported gcc switch causes message about missing library in linker.

**Comment by mariuz** [comment]
confirmed the static-libstdc++ issue is on x86-64 host also on oracle linux 8.x 

cat /etc/redhat-release
Red Hat Enterprise Linux release 8.6 (Ootpa)

cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD EPYC 7551 32-Core Processor
stepping        : 2
microcode       : 0x1000065
cpu MHz         : 1996.249
cache size      : 512 KB

https://www.oracle.com/cloud/free/#always-free

**Comment by mariuz** [comment]
@zeduardo2000 @AlexPeshkoff 

I found a way to compile it on x86-64 
install and configure gcc-toolset-12
https://docs.oracle.com/en/operating-systems/oracle-linux/8/relnotes8.7/ol8-NewFeaturesandChanges.html#ol-features-gcc

scl enable gcc-toolset-12 bash
./configure --with-builtin-tommath --with-builtin-tomcrypt

make finishes without errors 

```
/home/opc/firebird/gen/examples/isql -i empbld.sql
Use CONNECT or CREATE DATABASE to specify a database
ISQL Version: LI-T5.0.0.978 Firebird 5.0 Beta 1
Server version:
Firebird/Linux/AMD/Intel/x64 (access method), version "LI-T5.0.0.978 Firebird 5.0 Beta 1"
on disk structure version 13.1
/home/opc/firebird/gen/Release/firebird/bin/gpre_current -m -z -n /home/opc/firebird/gen/examples/empbuild.epp /home/opc/firebird/gen/examples/empbuild.cpp
gpre version LI-T5.0.0.978 Firebird 5.0 Beta 1
    Version(s) for database "empbuild.fdb"
        Firebird/Linux/AMD/Intel/x64 (access method), version "LI-T5.0.0.978 Firebird 5.0 Beta 1"
        on disk structure version 13.1
```

**Comment by mariuz** [comment]
@zeduardo2000 @AlexPeshkoff @asfernandes 

the above instructions works ok also on ARM64 , so i guess we can close the issue 

```
/home/opc/firebird/gen/examples/isql -i empbld.sql
Use CONNECT or CREATE DATABASE to specify a database
ISQL Version: LI-T5.0.0.978 Firebird 5.0 Beta 1
Server version:
Firebird/Linux/ARM64 (access method), version "LI-T5.0.0.978 Firebird 5.0 Beta 1"
on disk structure version 13.1
/home/opc/firebird/gen/Release/firebird/bin/gpre_current -m -z -n /home/opc/firebird/gen/examples/empbuild.epp /home/opc/firebird/gen/examples/empbuild.cpp
gpre version LI-T5.0.0.978 Firebird 5.0 Beta 1
    Version(s) for database "empbuild.fdb"
        Firebird/Linux/ARM64 (access method), version "LI-T5.0.0.978 Firebird 5.0 Beta 1"
        on disk structure version 13.1
g++ -I/home/opc/firebird/src/include/gen -I/home/opc/firebird/src/include   -I/home/opc/firebird/extern/boost -I/home/opc/firebird/extern/libcds -DCDS_BUILD_STATIC_LIB -I/home/opc/firebird/extern/libtommath -I/home/opc/firebird/extern/libtomcrypt/src/headers -I/home/opc/firebird/extern/re2 -O3 -DLINUX -DARM64 -pipe -p -MMD -fPIC -fsigned-char -fmessage-length=0 -fno-rtti -std=c++17   -pthread  -c /home/opc/firebird/gen/examples/empbuild.cpp -o /home/opc/firebird/gen/examples/empbuild.o
g++   -static-libstdc++  -pthread  -Wl,-rpath,/home/opc/firebird/gen/Release/firebird/lib -Wl,-rpath,/home/opc/firebird/gen/Release/firebird/lib/../intl -Wl,-rpath,@loader_path/../Release/firebird   /home/opc/firebird/gen/examples/empbuild.o /home/opc/firebird/temp/Release/common.a -o /home/opc/firebird/gen/examples/empbuild -L/home/opc/firebird/gen/Release/firebird/lib -L/home/opc/firebird/gen/Release/firebird/lib -L/home/opc/firebird/temp/Release -lfbclient -ltommath -ltomcrypt -lm -ldl   -ldecFloat
cp /home/opc/firebird/examples/empbuild/empdml.sql /home/opc/firebird/gen/examples/empdml.sql
cp /home/opc/firebird/examples/empbuild/indexoff.sql /home/opc/firebird/gen/examples/indexoff.sql
cp /home/opc/firebird/examples/empbuild/indexon.sql /home/opc/firebird/gen/examples/indexon.sql
cp /home/opc/firebird/examples/empbuild/job.inp /home/opc/firebird/gen/examples/job.inp
cp /home/opc/firebird/examples/empbuild/lang.inp /home/opc/firebird/gen/examples/lang.inp
cp /home/opc/firebird/examples/empbuild/proj.inp /home/opc/firebird/gen/examples/proj.inp
cp /home/opc/firebird/examples/empbuild/qtr.inp /home/opc/firebird/gen/examples/qtr.inp
rm -f /home/opc/firebird/gen/examples/employee.fdb
./empbuild /home/opc/firebird/gen/examples/employee.fdb
creating database /home/opc/firebird/gen/examples/employee.fdb
Turning forced writes off
Creating tables
Turning  off indices and triggers
Loading  column data
Turning  on indices and triggers
Loading Language arrays
Added 10 language arrays.
Loading Job blobs
Added 30 job requirement descriptions.
Loading project blobs
Added 6 project descriptions.
Loading quarter arrays
Added 24 quarter arrays.
/home/opc/firebird/gen/Release/firebird/bin/gfix -write sync /home/opc/firebird/gen/examples/employee.fdb
chmod 666 /home/opc/firebird/gen/examples/employee.fdb
```

**Comment by AlexPeshkoff** [comment]
Certainly. IMO that's not FB but Oracle Linux issue. With new gcc version it was fixed.
