### ISSUE TITLE
DECIMAL not accepted as stored procedure parameter type

### ISSUE THREAD

**Issue by tautf** [FirebirdSQL/firebird#7457]
We are using Firebird 3.0.10
I did the following with a procedure, take a look at the last parameter `TOTALUNITS`:
```sql
SET TERM ^;
CREATE OR ALTER PROCEDURE ADD_BATCH (IDTBPRORECIPE BIGINT, IDTBPROMACHINE BIGINT, PLANSTART TIMESTAMP, PLANFINISH TIMESTAMP, BATCH_COMMENT VARCHAR(1000), LOADINGTIME INTEGER, IDTBCORECONTAINER BIGINT, IDTBSYSUSRUSER BIGINT, TOTALUNITS DECIMAL)
RETURNS (
	IDTBPROBATCH BIGINT
)
AS
DECLARE VARIABLE IDTBPROBATCHCONTENT ID;
    DECLARE VARIABLE INTERNALNUMBER BIGINT;
BEGIN
    SELECT MAX(b.INTERNALNUMBER) FROM TBPROBATCH b
    LEFT JOIN TBPROBATCHCONTENT bc ON bc.IDTBPROBATCHCONTENT = b.IDXTBPROBATCHCONTENT
    JOIN (SELECT m.IDTBPROMACHINE, m.IDXTBACCCOSTUNIT 
            FROM TBPROMACHINE m
            WHERE m.IDXTBACCCOSTUNIT = (SELECT cm.IDXTBACCCOSTUNIT 
                                            FROM TBPROMACHINE cm 
                                            WHERE cm.IDTBPROMACHINE = :IDTBPROMACHINE)) m 
    ON m.IDTBPROMACHINE = bc.IDXTBPROMACHINE
    INTO INTERNALNUMBER;
    INTERNALNUMBER = INTERNALNUMBER + 1;
    IF (INTERNALNUMBER IS NULL) then
    BEGIN
        INTERNALNUMBER = 1;
    END

    INSERT INTO TBPROBATCHCONTENT (IDXTBPROMACHINE, IDXTBPRORECIPE)
        VALUES(:IDTBPROMACHINE, :IDTBPRORECIPE) RETURNING IDTBPROBATCHCONTENT INTO :IDTBPROBATCHCONTENT;
    INSERT INTO TBPROBATCH (PLANSTART,PLANFINISH, COMMENT, LOADINGTIME,
        IDXTBCORCONTAINER, IDXTBPROBATCHSTATUS, IDXTBPROBATCHCONTENT, INTERNALNUMBER, CREATEDBY, TOTALUNITS)
    VALUES (
        :PLANSTART,
        :PLANFINISH,
        :BATCH_COMMENT,
        :LOADINGTIME,
        :IDTBCORECONTAINER,
        (SELECT r.IDTBPROBATCHSTATUS
            FROM TBPROBATCHSTATUS r
            WHERE r.NAME = 'PENDING'),
        :IDTBPROBATCHCONTENT,
        :INTERNALNUMBER,
        :IDTBSYSUSRUSER,
        :TOTALUNITS
    ) RETURNING IDTBPROBATCH INTO :IDTBPROBATCH;
END^
SET TERM ;^
```

This runs successfully but is converted to the following:
![Bildschirmfoto 2023-01-23 um 13 49 10 PM](https://user-images.githubusercontent.com/18403881/214043892-37523079-056d-47ad-8146-a5c31ab2a1b9.png)

The DECIMAL parameter got converted to INTEGER.
Is it not supported to use `DECIMAL` as parameter type in stored procedures?

**Comment by aafemt** [comment]
DECIMAL data type has default precision zero which, yes, makes it effective an INTEGER.

Support questions are better in firebird-support mail list.

**Comment by dyemanov** [comment]
While effectively it's INTEGER, DECIMAL can be distinguished using the descriptor's subtype. Maybe the used GUI tool is not able to report it properly?

**Comment by dyemanov** [comment]
Just a quick test using the latest v3 snapshot:

```
SQL> create procedure p (a int, b numeric, c decimal) as begin end;
SQL> set sqlda_display;
SQL> execute procedure p(?, ?, ?);

INPUT message field count: 3
01: sqltype: 496 LONG Nullable scale: 0 subtype: 0 len: 4
  :  name:   alias: 
  : table:   owner: 
02: sqltype: 496 LONG Nullable scale: 0 subtype: 1 len: 4
  :  name:   alias: 
  : table:   owner: 
03: sqltype: 496 LONG Nullable scale: 0 subtype: 2 len: 4
  :  name:   alias: 
  : table:   owner: 

OUTPUT message field count: 0

```

The subtype is different, so it's definitely a tool problem.

**Comment by tautf** [comment]
Thanks for the quick help, will try to use a different tool and if so, report to the tool creator!

**Comment by tautf** [comment]
@dyemanov I can confirm that it does not work with DBeaver and FlameRobin. Is there a different tool i could use to try it out.

**Comment by tautf** [comment]
> @tautf , maybe you use old Jaybird version?

Just forced an update inside DBeaver, still the same behaviour.

**Comment by mrotteveel** [comment]
DBeaver uses its own metadata determination, and only infers NUMERIC/DECIMAL for BIGINT (see https://github.com/dbeaver/dbeaver/blob/a8afcb8f9eb1980534b379b5d11e878cc9f1d3b8/plugins/org.jkiss.dbeaver.ext.firebird/src/org/jkiss/dbeaver/ext/firebird/model/FireBirdFieldType.java#L67) please report a bug to them (https://github.com/dbeaver/dbeaver/issues)
