### ISSUE TITLE
TomCrypt library error: Invalid input packet.

### ISSUE THREAD

**Issue by Lanpingner** [FirebirdSQL/firebird#7459]
Good afternoon everyone

I am having a little bit of an issue with cryptographic functions.
Version : LI-V4.0.1.2692 Firebird 4.0 

Both on Linux/ Windows

The SP which is the error

`create or alter procedure PROC_DECRYPT_CARD_INFO (
    I_CARD_ID integer)
returns (
    O_CARD_STRING D_LONGTEXT)
as
begin
  rdb$set_context('USER_SESSION', 'private_key_comp', (select first 1 CK.RSA_PRIVATE_KEY from COMPANIES CK));

  rdb$set_context('USER_SESSION', 'msg', (select FIRST 1 CCI.profile_card_rsa from cards CCI));

  RDB$SET_CONTEXT('USER_SESSION','msgres',
    RSA_DECRYPT( RDB$GET_CONTEXT('USER_SESSION', 'msg')
    key RDB$GET_CONTEXT('USER_SESSION', 'private_key_comp'))
  );

  O_CARD_STRING = CAST(RDB$GET_CONTEXT('USER_SESSION','msgres') as D_LONGTEXT);
  SUSPEND;
end`

The error message :
Unsuccessful execution caused by system error that does not preclude successful execution of subsequent statements.
TomCrypt library error: Invalid input packet.
Decrypting using cipher RSA.
At procedure PROC_DECRYPT_CARD_INFO line: 11, col: 3.

I hope someone will able to help
Regards Romeo

**Comment by mrotteveel** [comment]
Please use [firebird-support](https://groups.google.com/g/firebird-support) for support questions, the GitHub issues are intended for bug reports.
