### ISSUE TITLE
DATEDIFF HOUR INCORRECT ANSWER

### ISSUE THREAD

**Issue by Gugu04** [FirebirdSQL/firebird#7460]
Hello, someone has experienced something similar with the DATEDIFF function  **Firebird  3.0.10**

Example
`SELECT DATEDIFF(HOUR, TIMESTAMP '14.12.2022, 11:46:33.405', TIMESTAMP '14.12.2022, 12:00:21.710')
FROM RDB$DATABASE`

![Captura desde 2023-01-27 13-12-14](https://user-images.githubusercontent.com/54090651/215176148-3ca68064-8571-4613-bf61-999538af91c3.png)

As a result, it shows me 1 hour when it should show 0 since it is a difference of minutes and it does not meet the fact that it is an hour.

**Comment by aafemt** [comment]
Miguel Angel wrote 27.01.2023 20:20:
> As a result, it shows me 1 hour when it should show 0 since it is a difference 
> of minutes and it does not meet the fact that it is an hour.

   12 - 11 = 1.

   Your desired result is difference in minutes divided by 60.

-- 
   WBR, SD.

**Comment by Gugu04** [comment]
Hi @aafemt , thanks for your reply, do you know any firebird community or channel on discord? to express doubts or suggestions

**Comment by mrotteveel** [comment]
The main support list is https://groups.google.com/g/firebird-support, you can find more on https://firebirdsql.org/en/mailing-lists/

Also, it is always good to take a look at the documentation, for example, this behaviour is explicitly mentioned in the _"Computation"_ section of [`DATEDIFF`](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-scalarfuncs-datediff)
