### ISSUE TITLE
Error create new database Fb4 x86 on Window 11

### ISSUE THREAD

**Issue by kollerpal** [FirebirdSQL/firebird#7470]
Hello!

After update my os windows 10 pro to window 11 pro Can't create new database.
My os: Windows 11 pro, Machine: Asus ROG Zephirus G14, 1Gb sshd hdd, 24Gb RAM, AMD Ryzen 9...

firebird.log excerpt

KP-LAPTOP	Mon Feb  6 15:50:05 2023
	Operating system call MapViewOfFile failed. Error code 8

KP-LAPTOP	Mon Feb  6 15:50:05 2023
	MappingIpc: Cannot initialize the shared memory region
	operating system directive MapViewOfFile failed
	unknown Win32 error 8

KP-LAPTOP	Mon Feb  6 15:50:52 2023
	Database: C:\TEMP\FB4.FDB
	Allocated 118455 page buffers of 131072 requested

KP-LAPTOP	Mon Feb  6 15:50:52 2023
	Operating system call MapViewOfFile failed. Error code 8

KP-LAPTOP	Mon Feb  6 15:50:52 2023
	MappingIpc: Cannot initialize the shared memory region
	operating system directive MapViewOfFile failed
	Nincs elegendő memória-erőforrás a parancs feldolgozásához. 

KP-LAPTOP	Mon Feb  6 15:52:30 2023
	Database: C:\TEMP\FB4-TEST.FDB
	Allocated 118532 page buffers of 131072 requested

KP-LAPTOP	Mon Feb  6 15:52:30 2023
	Operating system call MapViewOfFile failed. Error code 8

KP-LAPTOP	Mon Feb  6 15:52:30 2023
	MappingIpc: Cannot initialize the shared memory region
	operating system directive MapViewOfFile failed
	unknown Win32 error 8

MapViewOfFile windows api returned is NULL because file size is 0.
ErrorCode 8 is ERROR_NOT_ENOUGH_MEMORY code. But I think this is another error. 

the file exist but size 0.

I tried to create a database with ISQL. Got the same error.
![fb4-error](https://user-images.githubusercontent.com/43698463/217007303-4db08251-430d-43fa-bc7e-b39d538a59af.png)

I created a virtual machine with windows 10 pro operating system. The database was created without error.

Is there a solution for this? Or, for now, only Windows 10 can be used.

with thanks
bigbit

**Comment by aafemt** [comment]
ERROR_NOT_ENOUGH_MEMORY
  8 (0x8)
 Not enough memory resources are available to process this command.

You run out of memory. Find out how. Task Manager or Process Explorer can help with it.
Issue tracker is not for support questions.

**Comment by hvlad** [comment]
32-bit process address space is limited by 2GB.
Use 64-bit Firebird or reduce page cache setting in firebird.conf (database.conf).

**Comment by kollerpal** [comment]
thanks for the quick response. 
The configuration was indeed incorrect
