### ISSUE TITLE
'SHOW SYSTEM' command: provide list of functions belonging to system packages

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7475]
Packaged *functions* currently aren't shown in the output of SHOW SYSTEM (unlike packaged *procedures*).
It will be good if they also will be displayed there.
Currently system packages and their functions can be obtained using query:
```
select pg.rdb$package_name, 'packaged func', sf.rdb$function_name
from rdb$packages pg
left join rdb$functions sf on pg.rdb$package_name = sf.rdb$package_name
;

PKG_NAME            OBJ_TYPE       OBJ_NAME
==================  =============  ================
RDB$TIME_ZONE_UTIL  packaged func  DATABASE_VERSION
RDB$PROFILER        packaged func  START_SESSION
RDB$BLOB_UTIL       packaged func  IS_WRITABLE
RDB$BLOB_UTIL       packaged func  NEW_BLOB
RDB$BLOB_UTIL       packaged func  OPEN_BLOB
RDB$BLOB_UTIL       packaged func  SEEK
RDB$BLOB_UTIL       packaged func  READ_DATA
```
PS.
Ticked was created after discussion in  #7411

**Comment by AlexPeshkoff** [comment]
Also unified display format for functions & procedures, made it a bit better readable when dealing with packages.

**Comment by pavel-zotov** [comment]
QA: test not needed. Issue is covered by functional/basic/isql/test_02.py and test_03.py
