### ISSUE TITLE
small typos where  2&>1 should be 2>&1

### ISSUE THREAD

**Issue by peutch** [FirebirdSQL/firebird#7492]
Hi,

There are two small typos in `builds/install/arch-specific/darwin/install-script` at lines 25 and 44 where 2&>1 should be 2>&1.
But even doing the change, I am a little wary about the whole condition expression of those lines, specifically then with `/dev/null`.

Regards,
Patrice

**Comment by asfernandes** [comment]
The code seems to be doing things correctly.

**Comment by mrotteveel** [comment]
I'm not sure this should be closed. Bash and sh redirection of stderr to stdin is `2>&1`, so the script seems to be in error.

**Comment by AlexPeshkoff** [comment]
On 5/6/23 13:26, Mark Rotteveel wrote:
>
> I'm not sure this should be closed. Bash and sh redirection of stderr 
> to stdin is |2>&1|, so the script seems to be in error.
>

https://stackoverflow.com/questions/24793069/what-does-do-in-bash

But here we deal with MacOS, I'm not sure how does redirection work on 
it. IMHO that should anyway  better be fixed.
