### ISSUE TITLE
Firebird 5.0 snapshot blob not found error after first commit / rollback

### ISSUE THREAD

**Issue by omachtandras** [FirebirdSQL/firebird#7493]
DB charset win1250, dialect 1 or 3 doesn’t metter.

CREATE DOMAIN XSZOVEGN AS BLOB SUB_TYPE 1 SEGMENT SIZE 80 NOT NULL;

CREATE GLOBAL TEMPORARY TABLE TEST (
    TXT  XSZOVEGN /* XSZOVEGN = BLOB SUB_TYPE 1 SEGMENT SIZE 80 NOT NULL */
) ON COMMIT DELETE ROWS;

CREATE OR ALTER TRIGGER TEST_BI1 FOR TEST
ACTIVE BEFORE INSERT POSITION 1
as
begin
  if (char_length(new.txt) > 8000) then
    begin
    end
end;

1. run: 
insert into test(txt) values ('Something');
insert into test(txt) values ('Something');
insert into test(txt) values ('Something');
insert into test(txt) values ('Something');
rollback;     -- or commit

Everything is ok.

2. run:
insert into test(txt) values ('Something');

Error: BLOB not found.
At trigger TEST_BI1 line: 5, col: 3.

rollback;

3. run:
insert into test(txt) values ('Something');

Error: BLOB not found.
At trigger TEST_BI1 line: 5, col: 3.

rollback;

n. run:
insert into test(txt) values ('Something');

Error: BLOB not found.
At trigger TEST_BI1 line: 5, col: 3.

rollback;

Reconnect to database and first run is ok again, but after the first commit/rollback, the error can be reliably reproduced. The insert can be performed any number of times on the first transaction after connect to the database, but then failed.

**Comment by hvlad** [comment]
I have a fix for this. 
@asfernandes do you have any objections if I'll commit it ?

**Comment by asfernandes** [comment]
> I have a fix for this. @asfernandes do you have any objections if I'll commit it ?

No.

**Comment by hvlad** [comment]
Affected only GLOBAL TEMPORARY TABLE's with ON COMMIT DELETE ROWS clause.

**Comment by omachtandras** [comment]
Thanks Vlad, it works fine in the last snapshot.
