### ISSUE TITLE
Server (4.0.2) stopped responding

### ISSUE THREAD

**Issue by TommiPrami** [FirebirdSQL/firebird#7500]
Hello

Superserver on Windows (don't have further details on system, sadly)

Reason was that there was no enough free (or continuous maybe) memory for Page buffer. 

Log had this:
SERVER	Mon Mar  6 07:23:32 2023
	Database: C:\DATABASES\DATA.FDB
	Allocated 25337 page buffers of 32768 requested
	
Which kind of tells what is going on, but as server stops responding in that situation, would be cool to have ERROR: or similar prefix in the log to alarm one reading it. First one that was reading log, thought it was just message of server started OK.

Maybe even better would be that server would just use as much page buffer it can allocate etc. and march on, and write to log: WARNING: Allocated 25337 page buffers of 32768 requested (not enough memory, buy more).

Also tried to find out details of the SuperServer page buffer. Is it per Database or per Server process buffer on Super server?

-Tee-

PS. This might be as designed, but I don't know, that's why made issue, not email to support mailing lists. Saw something vaguely similar on mailing list tough. Might be related.

**Comment by hvlad** [comment]
It is possibly that Windows actively swaps memory and very buzy - thus you get impression that Firebird is not responded.
How many time you waits ?


> Maybe even better would be that server would just use as much page buffer it can allocat

It works exactly this way, this is not a fatal error from Firebird POV.


> Also tried to find out details of the SuperServer page buffer. Is it per Database or per Server process buffer on Super server?

See in firebird.conf:

---
Number of cached database pages

This sets the number of pages from any one database that can be held
in cache at once. If you increase this value, the engine will
allocate more pages to the cache for every database. By default, the
SuperServer allocates 2048 pages for each database and the classic
allocates 256 pages per client connection per database.

 **Per-database configurable**.
---

**Comment by TommiPrami** [comment]
> It is possible that Windows actively swaps memory and very busy - thus you get impression that Firebird is not responded. How many time you waits ?

Server was tested with remotely with our software, and locally with iSQL, what is the default timeout for iSQL? 

I think this is not an reason, because there was free memory available, but I suspect not continuous memory for Firebird page buffer. I can't remember the free memory available in this case, but it should have been enough for Firebird page cache, if I recall.

There have been at least two identical issues like this. Bot solved by making page buffer setting smaller, in this example from 32k to 16k. In other case I think from 32 to 20, if I recall.

In this case after server reiboot also the 32k page buffer setting was totally OK. 

And there was no significant slowness at the server locally. If server would be heavily swapping, I would guess you would see it in everything you do at the server., Like what happens at desktop when you saturate the memory totally.



> 
> > Maybe even better would be that server would just use as much page buffer it can allocat
> 
> It works exactly this way, this is not a fatal error from Firebird POV.

OK.

Interesting thing is then that why server stops responding. 

btw. Just remembered I got this same effect on desktop few months ago, I put too large page buffers on local virtual machine. and had same effect. Server stopped responding.

We use, (at least for now in these cases) 32bit 4.0.2 server. 

How much 32bit FBserer can allocate, on 64bit windows. Is the FB server large address aware and can allocate full 4GB of memory?

> This sets the number of pages from any one database that can be held in cache at once. If you increase this value, the engine will allocate more pages to the cache for every database. By default, the SuperServer allocates 2048 pages for each database and the classic allocates 256 pages per client connection per database.
> 

Did not spot the FOR EACH DATABASE :)

**Comment by hvlad** [comment]
It is very important to know that you use 32-bit Firebird !
32-bit Firebird is not large address aware and its address space is limited by 2GB.
In this case Firebird really could have a lot of OOM errors and, probably, one of the consequences is some kind of freeze.
I would recommend to switch to 64-bit Firebird or to make it use less memory (if possible).
If you really need to continue use 32-bit, please, provide reproducible test case or full memory dump of non-responding process.

PS I doubt it is related with #7495, it is very different case: SC vs SS, non-crash vs responding, 64-bit vs 32-bit

**Comment by TommiPrami** [comment]
> It is very important to know that you use 32-bit Firebird ! 

Sorry, forgot to mention that at the first place.

> 32-bit Firebird is not large address aware and its address space is limited by 2GB. 

OK, thanks for info.

> In this case Firebird really could have a lot of OOM errors and, probably, one of the consequences is some kind of freeze. 

OK.

> I would recommend to switch to 64-bit Firebird or to make it use less memory (if possible). 

Sure is possible, I think I will propose that we would move to 64bit server in these special cases.  At SaaS server we use 64bit Firebird.  Only thing standing in the way to move to the 64bit server would be make changes to our installer and test everything.

> If you really need to continue use 32-bit, please, provide reproducible test case or full memory dump of non-responding process.

This might be hard to reproduce, but If can figure out one, sure tell...

> PS I doubt it is related with #7495, it is very different case: SC vs SS, non-crash vs responding, 64-bit vs 32-bit

OK, thanks.

**Comment by hvlad** [comment]
Closed as not-reproducible.
Feel free to write here new info, if any, and I'll re-open the ticket

**Comment by TommiPrami** [comment]
could not reproduce exact problem.

Put Paage cache to 59K  (if I recall exact number) and connected to the DB

DESKTOP-LMQS6NR	Tue Mar 14 14:10:18 2023
	Guardian starting: "C:\Program Files (x86)\Firebird\Firebird_4_0\firebird.exe"



DESKTOP-LMQS6NR	Tue Mar 14 14:10:42 2023
	Operating system call MapViewOfFile failed. Error code 8


DESKTOP-LMQS6NR	Tue Mar 14 14:10:42 2023
	MonitoringData: Cannot initialize the shared memory region
	operating system directive MapViewOfFile failed
	unknown Win32 error 8


DESKTOP-LMQS6NR	Tue Mar 14 14:11:08 2023
	"C:\Program Files (x86)\Firebird\Firebird_4_0\firebird.exe": normal shutdown
	
	With poage cache larder that 32 server can allocate leads to 
	
DESKTOP-LMQS6NR	Tue Mar 14 14:11:54 2023
	Database: C:\DATA\MASTER\THMASTER.FDB
	Allocated 60409 page buffers of 92160 requested


DESKTOP-LMQS6NR	Tue Mar 14 14:11:54 2023
	"C:\Program Files (x86)\Firebird\Firebird_4_0\firebird.exe": terminated abnormally (4294967295)


This is kind of close what we saw, except server did not crash.

Best I can do for now. 

when we got those server hanghs page buffers where set to 32K or lower.
