### ISSUE TITLE
Firebird statement never returns

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7507]
Hi *!

Running this command from Java (Jaybird 5.0.1) never returns. 
This worked for years with no problem.
I uploaded the dump (created with ProcDump) to FTP. I'll send the details on request.
The dump was created running Firebird-3.0.11.33666-0_x64

```
execute block as begin
in autonomous transaction do
execute statement ('ALTER TRIGGER U_CIM_T_FMT INACTIVE')
        AS USER 'SYSDBA'
        PASSWORD 'masterkey';
end
```

**Comment by mrotteveel** [comment]
Does this specifically only not work when executing with Jaybird, or does it also hang when running it from - for example - ISQL?

**Comment by aafemt** [comment]
Executing DDL can meet locks or raise errors depending on transaction isolation level. If lock is met it can wait as long as the lock is help by someone else.

**Comment by hvlad** [comment]
The process in a dump waits for EX lock on table RDB$RELATION_FIELDS. 
This is relation reservation lock that every user transaction takes on access of table. 
EX lock is taken by CONSISTENCY transactions for WRITE access, and the code going to update RDB$RELATION_FIELDS. 
Could you confirm you use `SNAPSHOT TABLE STABILITY WAIT` transaction at this place ?

There is another attachment to this database that could hold relation lock for RDB$RELATION_FIELDS. 
Or it could be the main transaction of the same attachment (remember, the code runs in autonomous transaction).

So far I can't reproduce the issue, btw.

**Comment by EPluribusUnum** [comment]
@hvlad , thank you, managed to find the bug in our code. Transaction should not be in table stability wait mode.

(BTW, I don't thing that is norma that Firebird can't be stopped from this state, only os level kill worked)

**Comment by hvlad** [comment]
> @hvlad , thank you, managed to find the bug in our code. Transaction should not be in table stability wait mode.

Thanks for confirming.

> (BTW, I don't thing that is norma that Firebird can't be stopped from this state, only os level kill worked)

Agree.
