### ISSUE TITLE
Firebird 4.0 Silent Setup with Installation Script Does Not Write SYSDBA Password

### ISSUE THREAD

**Issue by erkankurtaga** [FirebirdSQL/firebird#7519]
I use the installation script below for firebird 4.02 silent installation both x64 and x32 setup. After Installation I couldn't restore or connect the database. I understand that silent setup doesn't create SYSDBA user on security.db. How could I solve the problem. 

Firebird-4.0.2_Win32.exe or Firebird-4.0.2_Win64.exe /SP- /SILENT /SUPPRESSMSGBOXES /NOCANCEL /NORESTART /COMPONENTS="ServerComponent,DevAdminComponent,ClientComponent" /TASKS="UseSuperServerTask\UseGuardianTask,UseServiceTask,AutoStartTask,MenuGroupTask,CopyFbClientToSysTask,CopyFbClientAsGds32Task" /SYSDBAPASSWORD="masterkey" /FORCE

**Comment by reevespaul** [comment]
Carefully read the doc/installation_scripted.txt and take note that /TASKS is broken. At least, I have never managed to make it work. However /MERGETASKS does work so that should be enough.

**Comment by erkankurtaga** [comment]
@reevespaul thanks for advise. I got it, but whether I use it or not SYSDBA user doesn't create. My problem is SYSDBA user creation. Thanks.

**Comment by erkankurtaga** [comment]
Thanks for advice. I read again the document. I reach the correct script below. Thanks again.

/SP- /SILENT /SUPPRESSMSGBOXES /NOCANCEL /NORESTART 
/MERGETASKS="UseSuperServerTask\UseGuardianTask,MenuGroupTask,CopyFbClientAsGds32Task" 
/SYSDBAPASSWORD="masterkey" /FORCE

**Comment by TommiPrami** [comment]
Could someone point me to the Documentation tried googling and could not find it. (Only very old ones, like for the Fb1.5 and 2.5)
