### ISSUE TITLE
Ordering and limited and restricted selecting - performance during using index for sorting

### ISSUE THREAD

**Issue by Dzyszla** [FirebirdSQL/firebird#7520]
When selecting small part of large table with ordering by indexed column, FB first do order, and next limiting results. Performance, when selecting f.ex. 10 records from 10M records database in this case is horrible. Example:
```sql
SELECT FIRST 1 col2
FROM table t
WHERE col3 = :something
ORDER BY col1
```

Plan of this is:
`PLAN (t ORDER idx_col1 INDEX (idx_col3))`

When exclude index from order, for example like:
```sql
SELECT FIRST 1 col2
FROM table t
WHERE col3 = :something
ORDER BY col1 + 1
```

Getting following plan:
`PLAN SORT ((t INDEX (idx_col3)))`

This case is much faster, anyway statistics is same like in first case.

In simple query execution time isn't felt, but in more complex difference can be larger, in my case the sql:
```sql
UPDATE table2 
SET col2 = (SELECT FIRST 1 col2 
          FROM table1 
          WHERE table1.indexed_col2 = table2.col3 AND table1.indexed_col3 = table2.col4
          ORDER BY table1.indexed_col1)
WHERE table2.col2 IS NULL AND table2.indexed_col3 = :something
```
```
PLAN (table1 ORDER idx_col1 INDEX (idx_col2, ird_col3))
PLAN (table1 ORDER idx_col1 INDEX (idx_col2, ird_col3))
PLAN (table2 INDEX (idx_col4))
```
executed in **1 hour**, and this:
```sql
UPDATE table2 
SET col2 = (SELECT FIRST 1 col2 
          FROM table1 
          WHERE table1.indexed_col2 = table2.col3 AND table1.indexed_col3 = table2.col4
          ORDER BY table1.indexed_col1 + 1 /* disable orderind index */ )
WHERE table2.col2 IS NULL AND table2.indexed_col3 = :something
```
```
PLAN SORT (table1 INDEX (idx_col2, ird_col3))
PLAN SORT (table1 INDEX (idx_col2, ird_col3))
PLAN (table2 INDEX (idx_col4))
```
executed in **15 seconds**!

Whole table1 has 10M records, but WHERE directive restrict to a few records in first condition, and thousands in second condition.
Affected and tested versions: 2.1 and 3.0

**Comment by mrotteveel** [comment]
Which Firebird version are you using?

**Comment by Dzyszla** [comment]
> Which Firebird version are you using?

2.1 and 3.0 (I just added this information :) )

**Comment by Dzyszla** [comment]
Now I have not possibility to check in 4.0 or higher, but I think this can be simple check by look on plan - if ORDER is before INDEX, then will be slow too, because sorting small result is faster than searching after getting sorted index.
But I realize this can be difficult to avoid in engine/optimizer. But maybe can base on index statistic and expected result records count related to all records count?
