### ISSUE TITLE
Shared memory area is probably already created by another engine instance in another Windows session, failed to create database

### ISSUE THREAD

**Issue by tomaszdubiel18** [FirebirdSQL/firebird#7522]
Hello. I'm not sure whether this is a bug. If so, please tell me what Im doing wrong. Tried on latest snapshot 3.0.11.33666-0 x64 Windows
gbak.exe -c path_to_gbk path_to_fdb

gbak error Shared memory area is probably already created by another engine instance in another Windows session, failed to create database
It only works when I add localhost: to the fdb path.

**Comment by hvlad** [comment]
It is side effect after fix for #7122, looking for solution.

**Comment by tomaszdubiel18** [comment]
Don't you think that this bug needs more attention? It's one of the basic uses of backing up the database. Every customer backing the databases this way in FB 2.5 the next day he installs Firebird finds out (if he is a responsible Firebird admin ;)) that backups stopped being performed, reads this message and it doesnt give gim any idea what it is about.

**Comment by mariuz** [comment]
LibreOffice has a building issue , might be related to this fix 

https://ci.libreoffice.org/job/gerrit_windows/161172/consoleFull#1408899889d893063f-7f3d-4b7e-b56f-4e0f225817cd
https://bugs.documentfoundation.org/show_bug.cgi?id=134526#c18

**Comment by hvlad** [comment]
It produces another error message, as I see in log:

> An uncaught exception of type com.sun.star.sdbc.SQLException
> - firebird_sdbc error:
> *Wrong file for memory mapping, see details in firebird.log
> caused by
> 'isc_create_database'

Does anybody reads that logs and look into firebird.log for details ?

**Comment by th1722** [comment]
> It produces another error message, as I see in log:
> 
> > An uncaught exception of type com.sun.star.sdbc.SQLException
> > 
> > * firebird_sdbc error:
> >   *Wrong file for memory mapping, see details in firebird.log
> >   caused by
> >   'isc_create_database'
> 
> Does anybody reads that logs and look into firebird.log for details ?

> > 
> > * firebird_sdbc error:
> >   *Wrong file for memory mapping, see details in firebird.log
> >   caused by
> >   'isc_create_database'
> 
> Does anybody reads that logs and look into firebird.log for details ?

[firebird(make).log](https://github.com/FirebirdSQL/firebird/files/13258914/firebird.make.log)
[firebird(make_check).log](https://github.com/FirebirdSQL/firebird/files/13258915/firebird.make_check.log)

**Comment by hvlad** [comment]
The second log contains 

>	Wrong file for memory mapping:
	      expected C:\cygwin64\tmp\lu22164rcgvl.tmp\fb_user_mapping
	already mapped C:\cygwin64\tmp\lu18692rcgvk.tmp\fb_user_mapping
	Check for presence of another Firebird instance with different lock directory

Looks like someone (build script ?) set `FIREBIRD_LOCK=C:\cygwin64\tmp\lu18692rcgvk.tmp` and run Firebird server or embedded application, 
then it set `FIREBIRD_LOCK=C:\cygwin64\tmp\lu22164rcgvl.tmp` (different value) and run second Firebird server or embedded application.
Such configuration is wrong and not allowed.
It is impossible to simultaneously run few instances of the Firebird engine using different lock directory.

`FIREBIRD_LOCK` should be set, if absolutely necessary, for the whole system, not per process or per-user.

**Comment by mikekaganski** [comment]
> Looks like someone (build script ?) set `FIREBIRD_LOCK=C:\cygwin64\tmp\lu18692rcgvk.tmp` and run Firebird server or embedded application, then it set `FIREBIRD_LOCK=C:\cygwin64\tmp\lu22164rcgvl.tmp` (different value) and run second Firebird server or embedded application. Such configuration is wrong and not allowed. It is impossible to simultaneously run few instances of the Firebird engine using different lock directory.
> 
> `FIREBIRD_LOCK` should be set, if absolutely necessary, for the whole system, not per process or per-user.

Please see #6937, and our discussion there about the specific use case in LibreOffice, which requires a per-process lock.
