### ISSUE TITLE
loongarch64 make error

### ISSUE THREAD

**Issue by szlbz** [FirebirdSQL/firebird#7525]
hi, the following error occurred while making longarch64 (CPU). Please ask how can I compile correctly?
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:80:28: error: redefinition of ‘uint64_t cds::beans::log2floor(uint64_t)’
     static inline uint64_t log2floor( uint64_t n )
                            ^~~~~~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:13:26: note: ‘size_t cds::beans::log2floor(size_t)’ previously defined here
     static inline size_t log2floor( size_t n )
                          ^~~~~~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:86:28: error: redefinition of ‘uint64_t cds::beans::log2ceil(uint64_t)’
     static inline uint64_t log2ceil( uint64_t n )
                            ^~~~~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:19:26: note: ‘size_t cds::beans::log2ceil(size_t)’ previously defined here
     static inline size_t log2ceil( size_t n )
                          ^~~~~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:106:28: error: redefinition of ‘uint64_t cds::beans::floor2(uint64_t)’
     static inline uint64_t floor2( uint64_t n )
                            ^~~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:39:26: note: ‘size_t cds::beans::floor2(size_t)’ previously defined here
     static inline size_t floor2( size_t n )
                          ^~~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:125:28: error: redefinition of ‘uint64_t cds::beans::ceil2(uint64_t)’
     static inline uint64_t ceil2( uint64_t n )
                            ^~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:58:26: note: ‘size_t cds::beans::ceil2(size_t)’ previously defined here
     static inline size_t ceil2( size_t n )
                          ^~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:131:34: error: redefinition of ‘constexpr bool cds::beans::is_power2(uint64_t)’
     constexpr static inline bool is_power2( uint64_t n ) noexcept
                                  ^~~~~~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:64:34: note: ‘constexpr bool cds::beans::is_power2(size_t)’ previously defined here
     constexpr static inline bool is_power2( size_t n ) noexcept
                                  ^~~~~~~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:137:28: error: redefinition of ‘uint64_t cds::beans::log2(uint64_t)’
     static inline uint64_t log2( uint64_t n )
                            ^~~~
/home/lbz/fb/firebird/extern/libcds/cds/algo/int_algo.h:70:26: note: ‘size_t cds::beans::log2(size_t)’ previously defined here
     static inline size_t log2( size_t n )
                          ^~~~
make[7]: *** [CMakeFiles/cds-s.dir/build.make:63：CMakeFiles/cds-s.dir/src/init.cpp.o] 错误 1
make[7]: 离开目录“/home/lbz/fb/firebird/extern/libcds/lib/Release”
make[6]: *** [CMakeFiles/Makefile2:73：CMakeFiles/cds-s.dir/all] 错误 2
make[6]: 离开目录“/home/lbz/fb/firebird/extern/libcds/lib/Release”
make[5]: *** [Makefile:152：all] 错误 2
make[5]: 离开目录“/home/lbz/fb/firebird/extern/libcds/lib/Release”
make[4]: *** [Makefile:306：libcds] 错误 2
make[4]: 离开目录“/home/lbz/fb/firebird/gen”
make[3]: *** [Makefile:191：external] 错误 2
make[3]: 离开目录“/home/lbz/fb/firebird/gen”
make[2]: *** [Makefile:325：master_process] 错误 2
make[2]: 离开目录“/home/lbz/fb/firebird/gen”
make[1]: *** [Makefile:98：firebird] 错误 2
make[1]: 离开目录“/home/lbz/fb/firebird/gen”
make: *** [Makefile:6：firebird] 错误 2

**Comment by AlexPeshkoff** [comment]
On 3/30/23 04:37, szlbz wrote:
> hi, the following error occurred while making longarch64 (CPU). Please 
> ask how can I compile correctly?

Looks like configure treats somewhere your CPU as 32-bit, though 
actually it's definitely 64-bit. Therefore an error. Not too strange - 
as far as I know CDS is not ported to longarch64.
To tell more I need full logs - first of aLL configure logs and it's 
stdout/stderr.

**Comment by szlbz** [comment]
[config.log](https://github.com/FirebirdSQL/firebird/files/11117256/config.log)

**Comment by szlbz** [comment]
www.loongson.cn

**Comment by szlbz** [comment]
[龙芯3A5000_3B5000处理器数据手册.pdf](https://github.com/FirebirdSQL/firebird/files/11117317/3A5000_3B5000.pdf)

**Comment by szlbz** [comment]
[龙芯3A5000_3B5000处理器寄存器使用手册.pdf](https://github.com/FirebirdSQL/firebird/files/11117318/3A5000_3B5000.pdf)

**Comment by AlexPeshkoff** [comment]
see https://github.com/FirebirdSQL/firebird/pull/7531
