### ISSUE TITLE
install Firebird3 and Firebird4 on one Linux system

### ISSUE THREAD

**Issue by hhfiddelke** [FirebirdSQL/firebird#7533]
For support purposes i need a Firebird 3 and Firebird 4 server on a Suse SLES 15.3.
I was able to install FB3 and FB4 and to get them run once together (separate ports/paths,services,FIREBIRD..) by installing first FB3 and then FB4. But after stopping FB3 i was not able to start FB3 again, because i got the following error message:
`/usr/local/firebird3/security3.fdb
unavailable database
Security database error
`
also gsec 
`bin/gsec -database /usr/local/firebird3/security3.fdb -user SYSDBA -pass masterkey` 
returns:
`use gsec -? to get help
Unable to complete network request to host "localhost".
Failed to establish a connection.
unable to open database
`
it seems to be a shared library problem, but i was not able to fix it until now.

Is there a way to get both instances running on the same system?

**Comment by mrotteveel** [comment]
For support questions, please use https://groups.google.com/g/firebird-support
