### ISSUE TITLE
Hang when changing user password

### ISSUE THREAD

**Issue by Noremos** [FirebirdSQL/firebird#7541]
There is a  way to hang a connection.
It is a kinda stupid but legal.

If you run
isql -u SYSDBA -p masterkey localhost:security.db
```SQL
Database: localhost:security.db, User: SYSDBA
SQL> alter user  A set password '1234567';
SQL> update plg$users set plg$passwd = 'IYXB2GxfK1r8lEKqcgWgxgvsXwEJEmQNPe/R46k=' where plg$user_name = 'A'; 
```
There will be a deadlock
```
Statement failed, SQLSTATE = 40001
deadlock
-update conflicts with concurrent update
-concurrent transaction number is 109
```

But without AUTODLL a hang appears
```SQL
SQL> set autoddl off;
SQL> alter user  A set password '1234567';
SQL> update plg$users set plg$passwd = 'IYXB2GxfK1r8lEKqcgWgxgvsXwEJEmQNPe/R46k=' where plg$user_name = 'A'; 
SQL> commit;
... Endless waiting
```

**Comment by AlexPeshkoff** [comment]
Kind of duplicate https://github.com/FirebirdSQL/firebird/issues/6861

**Comment by Noremos** [comment]
> Kind of duplicate #6861

Indeed. Sorry for the distraction

**Comment by aafemt** [comment]
Isn't deadlock detection supposed to find such self-locks?

**Comment by AlexPeshkoff** [comment]
Such - not. Transaction A waits for transaction B to commit or rollback. Transaction B waits for A outside lock manager, and that wait is causing obviously undetected by LM deadlock.
