### ISSUE TITLE
Server crash on some LockMemSize values

### ISSUE THREAD

**Issue by basid-irk** [FirebirdSQL/firebird#7545]
Server crash on databases.conf with:

security.db = $(dir_secDb)/security3.fdb
{
  RemoteAccess = false
  DefaultDbCachePages = 320
  LockMemSize
} 

LockMemSize=1  # crash too

**Comment by AlexPeshkoff** [comment]
That happened due to two unrelated bugs:
- Incorrectly entered parameter (i.e. w/o '=' sign) is treated as having empty/false/0 value.
- Lower bound for LockMemSize did not change since 1.5 and got too small starting at least with 3.0.
