### ISSUE TITLE
Firebird 5 wrong parallel workers value

### ISSUE THREAD

**Issue by tonne1** [FirebirdSQL/firebird#7552]
Testing parallel backup/restore, Firebird server is WI-T5.0.0.973 Firebird 5.0 Beta 1: 

gbak -b -par 8  -user auser -pass <pwd> adb.fdb adb.fbk

backup runs as expected, full CPU utilization. But restore 

gbak -c -par 8  -user auser -pass <pwd> adb.fbk adb.fdb
or
gbak -r -par 8  -user auser -pass <pwd> adb.fbk adb.fdb

gives

ERROR: Wrong parallel workers value 8, valid range are from 1 to 1

gbak statements are exactly like the examples in the release notes. Initially no configuration changes in firebird.conf. Only if the values in firebird.conf are set to a higher value, gbak restore -par <n> runs as expected, too.

**Comment by hvlad** [comment]
> Only if the values in firebird.conf are set to a higher value, gbak restore -par runs as expected, too.

Yes, exactly. Read also notes in doc\README.gbak
