### ISSUE TITLE
Advanced plan not fully returned for big SELECT

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7560]
Hi *!

Attached the SELECT, the plan, and the advanced plan.
Note the "..." at the end of plan_advanced.txt

If size is limited to 32K please us TAB for ident instead of 4 spaces.
And when still not fit, than you can still reduce plan size by
- not ident at all
- remove quotes from table and index names
- do not put space after ':', ',' and '->'
- abbrevate terms, eg.: "Singularity Check" -> "Sing ch"; "First N Records" -> "Frst N"; "Aggregate" -> "Aggr"; etc...
- remove "as..." parts

[plan.zip](https://github.com/FirebirdSQL/firebird/files/11381105/plan.zip)

**Comment by aafemt** [comment]
Duplicate #7451
