### ISSUE TITLE
Remove need for referring to RDB$DATABASE for singleton selects

### ISSUE THREAD

**Issue by DaltonCalford** [FirebirdSQL/firebird#7561]
Currently it is always required to refer to RDB$DATABASE when needing to get a singleton select response on a function or other such coding requirement.

With MSSQL you can perform queries such as "SELECT GETDATE()" without needing to provide a from clause.

Firebird can provide the same functionality by defaulting to RDB$DATABASE if no from clause is provided.

This reduces code size, makes code more readable and makes it easier to have MS developers to use FIREBIRD.

**Comment by aafemt** [comment]
Does ANSI standard in addition to syntax that must be accepted describes also syntax that must not be accepted? I.e. how strong is this requirement?

**Comment by mrotteveel** [comment]
Duplicates: https://github.com/FirebirdSQL/firebird/issues/1654

**Comment by mrotteveel** [comment]
> Does ANSI standard in addition to syntax that must be accepted describes also syntax that must not be accepted? I.e. how strong is this requirement?

That was not specifically my point. We generally strive to implement SQL-standard features, and the SQL standard equivalent would be `VALUES (...)` (e.g. `VALUES (CURRENT_USER)`), which would require Firebird to implement table value constructors (which are also more powerful than just select without tablename).

**Comment by hvlad** [comment]
> the SQL standard equivalent would be `VALUES (...)` (e.g. `VALUES (CURRENT_USER)`), which would require Firebird to implement table value constructors (which are also more powerful than just select without tablename).

+1

**Comment by EPluribusUnum** [comment]
Also new Oracle started to support SELECT without FROM.

But this leads far, makes SQL parsing more harder. (think about subselects and derived table cases also)

Table value constructor how would help? The TVC syntax still requires FROM keyword, TVC replaces tables/sub-/selects:
"... FROM rdb$database" -> "... FROM VALUES ()" 
Does Firebird allow 0 column datasource, or have to use "... FROM VALUES('')"
And I think in this case column aliasing also would be mandatory so extry typing.

**Comment by dyemanov** [comment]
@EPluribusUnum : 
`SELECT <expression>` (w/o `FROM`) == `VALUES (<expression>)` in the SQL specification. I.e. you don't need `SELECT` at all.

**Comment by mrotteveel** [comment]
Using a table value constructor in the `FROM`, would require enclosing it in parentheses (that is `SELECT * FROM (VALUES (expr1, expr2), (expr3, expr4))`, as it is considered a subquery in that case.
