### ISSUE TITLE
Firebird 5 profiler precision is 100 nanoseconds on Windows

### ISSUE THREAD

**Issue by tonne1** [FirebirdSQL/firebird#7563]
Referring to Adrianos last comments in https://github.com/FirebirdSQL/firebird/issues/7553.

time resolution / precison of total_elapsed_time and other timings apparently are in 100 nanoseconds on Windows as opposed to single nanoseconds on Linux - which is how they should be on Windows, too. Start and finish timestamps are correct and match execution times reported by dba tools.

Testing WI-T5.0.0.1035 Firebird 5.0 Beta 2

**Comment by asfernandes** [comment]
Duplicates #7562
