### ISSUE TITLE
Cannot nbackup a firebird 3.0 database in firebird 4.0 service with engine12 setup in Providers

### ISSUE THREAD

**Issue by ccy** [FirebirdSQL/firebird#7579]
In firebird 4.0, I configure `firebird.conf` to support both `engine12` and `engine13` plugins:

    Providers = Remote,Engine13,Engine12,Loopback

The firebird service may access both Firebird 3.0 and 4.0 database.

Next, I try to nbackup a Firebird 4.0 employee database and it works:

    fbsvcmgr service_mgr action_nbak dbname c:\4.0\employee.fdb nbk_file r:\fb40.nb0 nbk_level 0

Finally, I try to use nbackup a Firebird 3.0 employee database:

    fbsvcmgr service_mgr action_nbak dbname c:\3.0\employee.fdb nbk_file r:\fb30.nb0 nbk_level 0

and it fail with message:

    unsupported on-disk structure for file c:\3.0\employee.fdb; found 12.0, support 13.0

**Comment by AlexPeshkoff** [comment]
сейчас гляну и там
