### ISSUE TITLE
Improve DECLARE VARIABLE to accept complete value expressions

### ISSUE THREAD

**Issue by asfernandes** [FirebirdSQL/firebird#7590]
Currently `DECLARE VARIABLE` allows only `default_value` expressions in its initializer:

```
default_value
	: constant
	| current_user
	| current_role
	| internal_info
	| null_value
	| datetime_value_expression
	;
```

So for example, `declare v integer = 1 + 1` is invalid.

This is very limiting specially considering topic "New statement: EXECUTE SQL" discussed in firebird-devel.

There must be some caution to not allow the same or following variable be used in its declaration, but former ones could be.

**Comment by asfernandes** [comment]
This is an interesting case:

```
execute block
as
    declare function sf1 returns integer;

    declare function sf2 returns integer
    as
    begin
        return sf1();
    end

    declare v integer = sf2();

    declare function sf1 returns integer
    as
    begin
        return v;
    end
begin
end
```

Except for the `v` initializer, everything is valid in previous versions.

But when `v` initializer calls sub routines (maybe indirectly) that may read its own value, we have a problem.

**Comment by asfernandes** [comment]
In JavaScript, the somewhat equivalent code gives error `Uncaught ReferenceError: Cannot access 'v1' before initialization`

```
(function () {
    let v1 = f();
    
    function f() {
        return v1;
    }
})()
```

I think it's the way to go.

**Comment by aafemt** [comment]
For years PSQL allowed read uninitialized variables as NULL. Such error will break a lot of code. Warning should be enough, IMHO. Otherwise self-assignment is pointless but legal.

**Comment by asfernandes** [comment]
Looks like you didn't understood the problem, and much less the solution.

First, you did not understood what is the equivalence of JavaScript with the Firebird problem, so given that this JavaScript code works without error may show to you that there is no relation of a declare without initializer breaking things:

```
(function () {
    let v1;
    console.log(`v1: ${v1}`);
})()
```

Second, your say about uninitialized PSQL variables being NULL is wrong, as there is domain-with-default based variables.

So let me explain, the thing is about execution nodes.

Currently a given `DeclareVariableNode` did not need to be executed for a `VariableNode` read the same variable. So the change would be about it. It breaks no valid PSQL code, as currently no valid PSQL code may generate it.

With the given PSQL examples that would be possible and it makes no sense specially in the case of domain-with-default or domain-with-constraint based variables.

**Comment by aafemt** [comment]
Such `DeclareVariableNode` makes no sense to me. Initialization is just a syntax sugar for assignment-at-begin so should follow the same rules as assignment and following pieces of code must be equivalent:
```
declare v integer = 1 + 1;
begin
end
```
and
```
declare v integer;
begin
 v = 1 + 1;
end
```
The simplest way to achieve that is to initialize impure area with domain default and then execute an ordinary assignment node.

**Comment by aafemt** [comment]
PS: All we need to decide or read in the standard is whether the initializer replaces domain default or expand it. It first case NOT NULL domain based self-initialized variable should throw usual check error as if was assigned to invalid value and in the latter it should be initialized twice.
