### ISSUE TITLE
Add abbility to manage database.conf entries with database level params via remote API

### ISSUE THREAD

**Issue by andrewkip** [FirebirdSQL/firebird#7593]
Hello!

We have servers with hundres DBs  on them.

It would be nice to have such kinde of abbility for:

1 Create DB from other remote servervice (create alias).
2 Move DB between block devices (SSD HDD and so on) (edit alias).
3 Manage DB params remotely (DBs grows so we need change DBCache pages and so on)
4 move/remove DB and alias from server remotely

With best regards.

**Comment by aafemt** [comment]
It would open quite big remote vulnerability.

**Comment by mrotteveel** [comment]
Duplicate of #1840
