### ISSUE TITLE
CASE statement different result compared to FB 2.5.9

### ISSUE THREAD

**Issue by psryan** [FirebirdSQL/firebird#7600]
Simple repro example:

> select replace(
       case when 'N' = 'Y' then cast('YES' as varchar(30)) 
            when 'N' = 'N' then 'NO' 
            else 'DUNNO' 
       end,
       ' ', '_') as test
  from rdb$database;

Firebird 2.5 result:
NO

Firebird 4.0 result:
NO___

Based on what I understand of the CASE statement, if there is the presence of a VARCHAR type in the resulting expressions, the whole CASE statement should result in a VARCHAR result. It appears that when including the "ELSE" of the CASE statement in FB4.0, it ignores the cast VARCHAR and runs with padding out the result to 5 characters (right padded with spaces). I've replaced spaces with underscores to highlight the difference.

**Comment by asfernandes** [comment]
Problem is not only with `ELSE`:

```
select replace(
       case when 'N' = 'Y' then cast('YES' as varchar(30)) 
            when 'N' = 'X' then 'XXX' 
            when 'N' = 'N' then 'NO' 
       end,
       ' ', '_') as test
  from rdb$database;
```

Result: `NO_`

**Comment by psryan** [comment]
Also, on the flip side when using different form of CASE without any cast to VARCHAR:
```
select replace(
       case 'N'
          when 'Y' then 'YES' 
          when 'X' then 'XXX' 
          when 'N' then 'NO' 
       end,
       ' ', '_') as test
  from rdb$database;
```
FB2.5 Result:
NO_
FB4.0 Result:
NO

**Comment by mrotteveel** [comment]
@asfernandes Is it intentional that it now always coerces to VARCHAR? (see the example in https://github.com/FirebirdSQL/firebird/issues/7600#issuecomment-1560406510)

**Comment by asfernandes** [comment]
> [@asfernandes](https://github.com/asfernandes) Is it intentional that it now always coerces to VARCHAR? (see the example in [#7600 (comment)](https://github.com/FirebirdSQL/firebird/issues/7600#issuecomment-1560406510))

@mrotteveel `REPLACE` always returns `VARCHAR`.

Result would be very weird if it returns CHAR, as it should pre-calculate a max length to describe the output.

**Comment by mrotteveel** [comment]
> > [@asfernandes](https://github.com/asfernandes) Is it intentional that it now always coerces to VARCHAR? (see the example in [#7600 (comment)](https://github.com/FirebirdSQL/firebird/issues/7600#issuecomment-1560406510))
> 
> `REPLACE` always returns `VARCHAR`.
> 
> Result would be very weird if it returns CHAR, as it should pre-calculate a max length to describe the output.

So you mean the type is now pushed down into the CASE expression, so it also returns VARCHAR instead of CHAR?

**Comment by asfernandes** [comment]
Maybe that was changed by some side effect?

Maybe due to that, we are not receiving bug reports about CASE anymore?

We should track when this change started.

**Comment by asfernandes** [comment]
The thing is `case <expr> when ...` is generating blr_decode and decode do not put a cast in the whole expression so each variant returns the same type.

`case when <boolean expr>` is working like described by the standard.
