### ISSUE TITLE
Disallow replication of RDB$BACKUP_HISTORY

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#7605]
By design, replica database can be physically backed up. However, RDB$BACKUP_HISTORY (and its generator) is allowed for replication, which was incorrect decision per se, because it contains physical-level information (SCN) which is incorrect for replica. Besides, this also causes conflicts during replication (if RDB$BACKUP_HISTORY is modified on both sides), finally ending with a stopped replication (because the standard conflict resolution rules do not work for this table, as it explicitly prohibits updates inside).

**Comment by pavel-zotov** [comment]
5.x is also affected.
