### ISSUE TITLE
Firebird 2.5.9 incorrectly handle surrogate pairs in identifiers

### ISSUE THREAD

**Issue by MaceWindu** [FirebirdSQL/firebird#7606]
Following SQL creates table with invalid column name leading to `arithmetic exception, numeric overflow, or string truncation` error when try to drop table.

```sql
CREATE TABLE "testparams"
(
    "Test-葛󠄀城市-End" Int NOT NULL
)
```

FB 3.0 handles it correctly: `unsuccessful metadata update; CREATE TABLE testparams failed; Malformed string` and FB4.0 supports such identifiers creation

**Comment by asfernandes** [comment]
2.5 is not maintained anymore. Try it in new versions and it should work.
