### ISSUE TITLE
Can't backup/restore database from v3 to v4 with SEC$USER_NAME field longer than 10 characters

### ISSUE THREAD

**Issue by dmitry-starodubov** [FirebirdSQL/firebird#7611]
If I have such a simple database 

CREATE TABLE T (ID INTEGER NOT NULL,
        USER_NAME SEC$USER_NAME,
        PASSWD VARCHAR(256) CHARACTER SET OCTETS,
        ALG VARCHAR(32) CHARACTER SET UNICODE_FSS);
		
insert into t values(1, 'aaabbbcccddd', '12345678', '123');

I can backup/restore in on v3.
But when I try to restore backup from v3 on v4 I get an error:
gbak: ERROR:arithmetic exception, numeric overflow, or string truncation
gbak: ERROR:    string right truncation
gbak: ERROR:    expected length 10, actual 12
gbak: ERROR:gds_$send failed
gbak:Exiting before completion due to errors

Because maximum length of USER_NAME field is calculated wrong.

**Comment by sim1984** [comment]
v3 and v4, the SEC$USER_NAME domain has a different definition

```sql
CREATE DOMAIN SEC$USER_NAME AS
VARCHAR(31) CHARACTER SET UNICODE_FSS;
```

vs

```sql
CREATE DOMAIN SEC$USER_NAME AS
VARCHAR(63) CHARACTER SET UTF8;
```

**Comment by aafemt** [comment]
Both of them should be enough for 12 characters. Expected 10 in the error message is strange.

**Comment by pavel-zotov** [comment]
I could not reproduce described problem.
What *exact* versions of FB 3.x and FB 4.x / 5.x ?

**Comment by asfernandes** [comment]
Try restore in v4 using embedded.

**Comment by pavel-zotov** [comment]
Adriano, thanks. Now all OK.
