### ISSUE TITLE
[FR]: Implement stdnul as cross-platform null-output

### ISSUE THREAD

**Issue by basid-irk** [FirebirdSQL/firebird#7619]
Sometimes it's usefull to do "dry-run backup" (for "timing and sizing").
Would be helpful have standard (cross-platform) null-destination as:
`fbsvcmgr ... action_backup ... bkp_file stdnul` or `gbak ... -se ... -b ... stdnul`
`fbsvcmg ... action_nbak ... nbk_file stdnul` or `nbackup -b ... stdnul`

**Comment by AlexPeshkoff** [comment]
use 'nbk_file /dev/null'

**Comment by Kyogre** [comment]
Can you give full example of command for gbak?

**Comment by basid-irk** [comment]
```
gbak ... -b -g db-or-alias stdnul
```
should expand on Windows as:
```
gbak ... -b -g db-or-alias nul
```
and expand on POSIX as:
```
gbak ... -b -g db-or-alias /dev/nul
```

**Comment by pavel-zotov** [comment]
Why this ticket was closed ? Requested feature definitely is useful.

**Comment by aafemt** [comment]
I personally see no point in this ticket because batch scripts are not cross-platform anyway.

**Comment by pavel-zotov** [comment]
Lot of times i used such commands without enclosing them into .bat / .sh; just "as is" (yes, on Linux prefix "./" is needed - but this is only two characters).
Though, more actual is:
```
out nul;
set stat on;
select ... from ....
out;
```
This .sql must be adjusted on Linux by replacing 'nul' with '/dev/null', and this is definitely annoying.

**Comment by Kyogre** [comment]
Dudes, I still can't get it to work... Trying to perform dry-run restore to check that logs contain no errors, but the restore gives me error:
```
[root@localhost tmp]# /opt/RedDatabase/bin/gbak -c -v "/home/bac.fbk" -user SYSDBA -pass 'masterkey' /dev/null
gbak:started at Wed Jan 31 10:50:05 2024
gbak:opened file /home/bac.fbk
gbak:transportable backup -- data in XDR format
gbak:           backup file is compressed
gbak:backup version is 10
gbak: ERROR:I/O error during "lock" operation for file "/dev/null"
gbak: ERROR:    Database already opened with engine instance, incompatible with current
gbak: ERROR:failed to create database /dev/null
gbak:Exiting before completion due to errors
gbak:stopped at Wed Jan 31 10:50:05 2024
```

I have RedHat 8.3, RedDatabase 3.0.9.

Do somebody has working command example for what I want to achieve?

**Comment by basid-irk** [comment]
Don't use character device as database file.
Импоссибиль :)

**Comment by Kyogre** [comment]
Why impossible? How can we restore to the void then?
I can't just restore 10 terabytes DB on the drive (and remove it later) just to check if the backup is valid 😉

**Comment by pavel-zotov** [comment]
> Why impossible? How can we restore to the void then?

You can't use nul or /dev/nul. Restore requires random access while it creates .fdb - at least for indices and (maybe) for metadata.
```
C:\temp>gbak -rep -i C:\temp\tmp.fbk nul
gbak: ERROR:operating system directive GetFileInformationByHandle failed
gbak: ERROR:    Неверная функция. // localized message here: "wrong function"
gbak: ERROR:failed to create database nul
gbak:Exiting before completion due to errors
```

**Comment by basid-irk** [comment]
Because. Character device has zero size and lack space for ramdom access.
You may check only metadata, but you must provide about 10-12 TB for database restore.

**Comment by EPluribusUnum** [comment]
> Why impossible? How can we restore to the void then? I can't just restore 10 terabytes DB on the drive (and remove it later) just to check if the backup is valid 😉

@Kyogre, you have to restore form back to verify if backup was correct.
You can get successful gbak run, but unrestorable backup file.

**Comment by AlexPeshkoff** [comment]
On 1/31/24 11:05, Roman wrote:
> I can't just restore 10 terabytes DB on the drive (and remove it 
> later) just to check if the backup is valid 😉

That means you can't verify your backup :(

**Comment by aafemt** [comment]
Terrabyte-sized databases just use other techniques for backup. Standby, for example.
And yes, if you don't have space on disk - you cannot restore the backup anyway so its validity is irrelevant.
