### ISSUE TITLE
Segfault when new attachment is done to shutting down database

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7626]
In core dump, received from user, I see same attachment released in 2 threads simultaneously - in attachments shutdown thread and in worker thread from unwindAttach. Not strange that this causes segfault in one of that threads.

**Comment by AlexPeshkoff** [comment]
Bug happens cause in internalAttach (and createDatabase) blocking mutex is released too early, before unwindAttach. This makes me sure that it can affect other branches too, starting with FB3.

**Comment by omachtandras** [comment]
> but bug affects other branches too, starting with FB3.

Yes, we have also had the problem since we switched to FB3.0.10.
In the case of classic, if you start killing the processes at the operating system level, then if you are lucky, after killing the stuck process, the remaining connections will revive again, and mon$ queries will also be run on them.

**Comment by AlexPeshkoff** [comment]
@omachtandras What you mention is quite unrelated with this bug. What I've seen in core dump has absolutely nothing to do with mon$ tables.

**Comment by omachtandras** [comment]
> @omachtandras What you mention is quite unrelated with this bug. What I've seen in core dump has absolutely nothing to do with mon$ tables.

Sorry, I mixed up the issues, that's why I deleted my comment.
