### ISSUE TITLE
The size of the database with big records becomes bigger after backup/restore

### ISSUE THREAD

**Issue by ilya071294** [FirebirdSQL/firebird#7627]
FB5 is affected. Seems like bulk inserts don't work correctly with big records. The problem is in locate_space() where the dpg_large flag is checked when the cached primary page number is used. The page is released if it has this flag, and the new record is inserted on the next empty page. As a result, each primary page has only one record. I would suggest to remove the dpg_large flag check from the locate_space(), and also from DPM_get() and DPM_next() because it prevents the cache of data page numbers to work. FB3 and FB4 don't have issues with the database size but the problem with cached page numbers is there and can be fixed the same way.

**Comment by hvlad** [comment]
While I didn't verify it with tests, seems you right. 
Would you prepare the PR ? Or I'll fix it by myself.

**Comment by ilya071294** [comment]
> Would you prepare the PR ?

Yes, I will prepare the PR.

**Comment by hvlad** [comment]
Fix is backported into v4 also, not sure about v3 yet.
