### ISSUE TITLE
There is a bug in savepoints FB 4.0

### ISSUE THREAD

**Issue by raksadamzukowski** [FirebirdSQL/firebird#7633]
To trigger an error, you must use the same pair of savepoints at least twice.
The situation is 100% reproducible.
Recipe:
```sql
create table T_MASTER (
    ID  integer not null
);

alter table T_MASTER add constraint KP_PK_T_MASTER primary key (ID);



create table T_DETAIL (
    ID         integer not null,
    ID_PARENT  integer not null
);

alter table T_DETAIL add constraint KP_PK_T_DETAIL primary key (ID);

alter table T_DETAIL
  add constraint KP_FK_T_DETAIL_1
  foreign key (ID_PARENT)
  references T_MASTER (ID)
  on delete cascade
  on update cascade;
```

Error-causing instructions
```sql
insert into T_MASTER values (1);
insert into T_DETAIL values (1, 1);

savepoint a;
savepoint b;

insert into T_DETAIL values (2, 1);

savepoint a;
savepoint b;

insert into T_DETAIL values (3, 1);

rollback;

/* Final */
select * from T_MASTER; /* Empty */
select * from T_DETAIL; /* ONE RECORD LEFT !!! */
```
If I add deleting before rollback, it won't do anything in the end, because the record will stay
```sql
delete from T_DETAIL where ID_PARENT = 1;
```
If there is only "a" savepoint, there is no error, there must be two savepoints.

--old message
Hi

Until recently, we used Firebird 2.5. **In September 2021, we migrated to version 4.0**. Now we've started to detect that our foreign keys are breaking. This is for now about 8 different tables out of about 600 tables in the database. Recently, several of our clients have come to us with this problem. They noticed this during the operation of restoring the database from a backup copy. Databases are not very large, a few to several GB. We also have working databases in which foreign keys are damaged, so the backup-restore itself is not the cause.

We also suspect that errors in foreign keys may occur after the AccessViolation error after which the program closes.

_Error report:_

```
gbak:cannot commit index FK_FI_REJESTR_VAT
gbak: ERROR:violation of FOREIGN KEY constraint "FK_FI_REJESTR_VAT" on table "FI_REJESTR_VAT"
gbak: ERROR:    Foreign key reference target does not exist
gbak: ERROR:    Problematic key value is ("ACCOUNT_DOC_ID" = 699920)

gbak:    activating and creating deferred index FK_R3_SETTLEMENT
gbak:cannot commit index FK_R3_SETTLEMENT
gbak: ERROR:violation of FOREIGN KEY constraint "FK_R3_SETTLEMENT" on table "R3_SETTLEMENT"
gbak: ERROR:    Foreign key reference target does not exist
gbak: ERROR:    Problematic key value is ("ACCOUNT_DOC_ID" = 699920)

gbak:cannot commit index FK_FI_DEKRETY
gbak: ERROR:violation of FOREIGN KEY constraint "FK_FI_DEKRETY" on table "FI_DEKRETY"
gbak: ERROR:    Foreign key reference target does not exist
gbak: ERROR:    Problematic key value is ("ACCOUNT_DOC_ID" = 699920)
```

We have from a few to several dozen such records. Based on the date in the records, we know that there are regularly several records corrupted per month in one of the tables. Approximately 1,000 records are added to the R3_ACCOUNT_DOCUMENTS table per month, and about a few are lost per month.

Our Foreign keys and their tables and primary keys:

```sql
create table FI_REJESTR_VAT (
    ID                         id integer default 0 not null,
    ACCOUNT_DOC_ID             id integer default 0 not null
    /*another fields*/
);

create table R3_ACCOUNT_DOCUMENTS (
    ID                        integer not null
    /*another fields*/
);

alter table R3_ACCOUNT_DOCUMENTS
  add constraint R3_ACCOUNT_DOCUMENTS_PK
  primary key (ID);

alter table FI_REJESTR_VAT
  add constraint FK_FI_REJESTR_VAT
  foreign key (ACCOUNT_DOC_ID)
  references R3_ACCOUNT_DOCUMENTS (ID)
  on delete cascade on update cascade;

create table KP_ZDARZENIA (
    ID                        ID integer default 0 not null,
    ID_ZDARZENIA_SRD          integer
    /*another fields*/
);

alter table KP_ZDARZENIA
  add constraint KP_PK_ZDARZENIA primary key (ID);

alter table KP_ZDARZENIA
  add constraint KP_FK_ZDARZENIA_SRD
  foreign key (ID_ZDARZENIA_SRD)
  references KP_ZDARZENIA (ID)
  on delete set null;
```

If it helps, our database runs on Linux as SuperClassic. Both used to be 2.5 and 4.0 now. Our clients also use Windows and Linux, probably as SuperServer or as SuperClassic.

What can we do apart from fixing (deleting) records that don't have a parent?
Do you have any knowledge that foreign key corruption can happen on a walking database under Firebird 4.0?
We know that on the server in version 2.5 such damage did not occur, maybe only with the exception of hardware failures.

**Comment by mrotteveel** [comment]
You may also want to post a question on https://groups.google.com/g/firebird-support for more visibility. Also, a reproducible testcase would be very helpful.

**Comment by livius2** [comment]
Do you have corruption only on Linux or on Windows too?
What commit strategy do you use, hard commit or commit retaining?
GCPolicy = combined?

But as @mrotteveel better ask on support group, then more questions and possibilities can arrise.

**Comment by dyemanov** [comment]
Related to #7591, already fixed.

**Comment by raksadamzukowski** [comment]
I tested snapshot Firebird-4.0.3.2950-0.
On the latest snapshot work well.

**Comment by livius2** [comment]
@dyemanov 

look if some error still is not present as on support group ther is:
[firebird-support] Unable to find savepoint in insert with nestedquery and returning clause in FB4
and user report that tested on `WI-V4.0.3.2955 Firebird 4.0`

**Comment by dyemanov** [comment]
It looks like a different issue at the first glance.

**Comment by raksadamzukowski** [comment]
The bug reported in issue #7591 was created probably in version 4.0.2 but I reproducing it on the version 4.0.0. I am talking about my case described in the beginning.
Fortunately, on snapshot 4.0.3.2950-0 the bug is gone.
