### ISSUE TITLE
Attempt to setup firebird cluster with glusterfs

### ISSUE THREAD

**Issue by ccy** [FirebirdSQL/firebird#7636]
I setup a 3 hosts gluster cluster and create a replica=3 volume to keep a firebird database.

I have another machine with this configuration:
- Firebird 3.0.10 classic server listen to 3050/TCP
- mount to the gluster volume

Next, I try multiple client process connect to the firebird service.  Each client process can see each other commit changes immediately.  So far so good.

As the firebird classic service open new process for new established connection, perhaps I can setup firebird classic server on multiple machine and accessing same gluster volume:

```
Host 1 firebird classic 3050/tcp -> mygluster:firebird/employee.fdb
Host 2 firebird classic 3050/tcp -> mygluster:firebird/employee.fdb
Host 3 firebird classic 3050/tcp -> mygluster:firebird/employee.fdb
```
I also try configure a gluster volume (`mygluster:lock`) to keep locks files and configure `firebird_lock` on each machine to point to `mygluster:lock`.  I can see the `mygluster:lock` fill ups lock files for each connection.

My multiple connections test can establish connection from any firebird Host1, 2, 3 to same `employee.fdb` database without issue.

However, I notice a process can't see latest commit changes made by others connections.  Is there something I miss in my configuration?  Or firebird is not design for such deployment strategy?

**Comment by mrotteveel** [comment]
I think this is more suitable to ask on https://groups.google.com/g/firebird-devel (or maybe https://groups.google.com/g/firebird-support).

**Comment by aafemt** [comment]
Firebird is not designed for that. I have no idea what "gluster" is but unless it is shared-memory cluster, you'll end with corrupted database.

**Comment by romansimakov** [comment]
I find it as an interesting experiment. Especially if you get a result of performance profiling.
All open files (as well as mmapped) you can find and investigate via lsof. I'm not sure if it's possible at all, but for further research it would be nice to estimate pros and cons.
In the same time you can investigate glusterfs as a storage to keep async replication journals for hot standby.
