### ISSUE TITLE
fb5.beta.1  < select list() from (select .. order by) group by >  reorder internal select

### ISSUE THREAD

**Issue by Khalyutin** [FirebirdSQL/firebird#7644]
Good day to All...

Problem in fb 5.0 beta 1.  In fb 3.0.10 orfder is correct.

incorrect oreder in case:
```  
      select  list( myListItem ), myListName  
       from  ( select  myListItemNumber
                           , myListItem
                           , myListName 
                    from myTable  
              order by myListItemNumber
                ) 
group by myListName
```
myListItem is ordered alphabetically by name instead of directly given number in inner selection

This is a blocking problem: a general logic failure in our Firebird database metadata update application.
We dynamically generate SQL statements;

reproducible example:

```
create or alter procedure nm$test_proc_1
( a_par_1 integer
, b_par_2 integer
, c_par_3 integer
, d_par_4 integer
) returns
( a_res_1 integer
, b_res_2 integer
, c_res_3 integer
, d_res_4 integer
) as begin end ;

create or alter procedure nm$test_proc_2
( d_par_1 integer
, b_par_2 integer
, c_par_3 integer
, a_par_4 integer
) returns
( c_res_1 integer
, a_res_2 integer
, b_res_3 integer
, d_res_4 integer
) as begin end ;

    select list(nm$No) nm$ord_in_list 
        ,  'execute procedure ' ||nm$proc ||'('||  list(nm$param, ', ' ) ||')  returning_values ' || list(nm$result, ', ')  nm$sql
      from (
              select lower(trim(rdb$procedure_name)) nm$proc 
                   , rdb$parameter_number nm$No  
                   , iif(rdb$parameter_type = 0, trim(':'||lower(rdb$parameter_name||' ')), null) nm$param
                   , iif(rdb$parameter_type = 1, trim(     lower(rdb$parameter_name||' ')), null) nm$result         
                from rdb$procedure_parameters 
               where rdb$procedure_name = upper(trim( 'nm$test_proc_1')) 
                     or rdb$procedure_name = upper(trim( 'nm$test_proc_2'))  
            order by rdb$parameter_number
           )  
group by nm$proc;

```

in result order of parametrs incorect:
```
execute procedure nm$test_proc_1(:a_par_1, :b_par_2, :c_par_3, :d_par_4)  returning_values a_res_1, b_res_2, c_res_3, d_res_4
execute procedure nm$test_proc_2(:a_par_4, :b_par_2, :c_par_3, :d_par_1)  returning_values a_res_2, b_res_3, c_res_1, d_res_4
```

**Comment by aafemt** [comment]
Order of a derived table is irrelevant. Outer join has no "order by" clause so behavior is undefined.

**Comment by EPluribusUnum** [comment]
@Khalyutin , I thing the SQL standard allows to omit the internal order by, and FB 50 now implements this feature. Prev FB versions using order was an implementation detail, not a guaranteed SQL behaviour.

**Comment by mrotteveel** [comment]
Related: #2756, #7632

**Comment by mrotteveel** [comment]
BTW, try changing your order by to `order by myListName, myListItemNumber`, maybe you'll get lucky.

**Comment by Khalyutin** [comment]
How difficult is it to implement the  LISTADD / WITHIN GROUP  functionality from myself? 
We are able to build firebird 4.0 with CMake+LLVM for Windows, Linux & MacOS.

**Comment by Khalyutin** [comment]
719 calls of list()..  used in macros for generate ~5000 stored proc...
Now we need check where order is important.
Please tell me,
in case:
```
 select  list( myFieldValue )
         ,  list( myFieldName )
   from  myStoredProcedure  -- !!!
   into:   myValuesList
           , myFieldsList
```
order of  myValuesList and myFieldsList  does not match with myStoredProcedure   record order too?

**Comment by aafemt** [comment]
As a workaround because you do it in PSQL anyway, why you just don't remove list() and concatenate values by hand in the loop? It would let you exactly control the order of records.

BTW, in most cases order of fields in queries are not important.

**Comment by mrotteveel** [comment]
The order of `LIST()` is -- and always has been -- undefined. The fact that two `LIST()` in the same select apply different orders is (or at least, seems) odd, but given the order is undefined, this is also not a bug. (Though maybe it warrants some double checking?)

**Comment by Khalyutin** [comment]
I understand that this is not a bug.
Is it possible to leave in 5.0 adding to the end of the list, as would be the obvious behavior. Reordering alphabetically, rather contradicts the standard SQL.  Is alphabetically reordering good, If in cursor 1 000 000 records?

**Comment by Khalyutin** [comment]
Sorry.   
...It does add to the end...
  If  I`m use  "stored procedure" as input  record stream,  record ordered insaide "stored procedure". No "group by" out of "stored procedure" ,
order in LIST() result such as order of record of "stored procedure" or not?

Use concatenation in loop for a defined order...  This is what i`m want to avoid. At least in the near future...

**Comment by aafemt** [comment]
Once again: order in LIST() **is undefined**. For defined order use concatenation in loop.

**Comment by Khalyutin** [comment]
Thanks!
