### ISSUE TITLE
Connection crash when debugging procedures with blob_append

### ISSUE THREAD

**Issue by aschegolskiy** [FirebirdSQL/firebird#7646]
Server Version: WI-V4.0.2.2816 Firebird 4 Server Version: WI-V4.0.2.2816 Firebird 4 
Server Version: WI-V3.0.11.33646 Firebird 3.0 HQbird
Both in Super Server mode 

IBExpert: 2022.3.4.1

When debugging in the IBExpert code below, server returns error on line with blob_append.

```
execute block
returns (
    res_object_detail blob sub_type text)
as
declare variable n integer;
begin
  res_object_detail = blob_append(res_object_detail, '');
  suspend;
end
```
```
Unsuccessful execution caused by a system error that precludes successful execution of subsequent statements.
internal Firebird consistency check (EVL_assign_to: invalid operation (229), file: evl.cpp line: 205).
-------------------------------------------------------------------------------------------------------------
SQLCODE: -902
SQLSTATE: XX000
GDSCODE: 335544333

```
After that, the connection becomes unusable, all next statements give an error:

```
Unsuccessful execution caused by a system error that precludes successful execution of subsequent statements.
internal Firebird consistency check (can't continue after bugcheck).
-------------------------------------------------------------------------------------------------------------
SQLCODE: -902
SQLSTATE: XX000
GDSCODE: 335544333

```
P.S.
While Firebird service remains alive, HQBird service hangs and cannot be restarted with Services Manager. But can be killed with Task Manager.

**Comment by AlexPeshkoff** [comment]
On 6/22/23 10:35, aschegolskiy wrote:
> While Firebird service remains alive, HQBird service hangs and cannot 
> be restarted with Services Manager. But can be killed with Task Manager.

In this case you should contact IBSurgeon.

**Comment by aschegolskiy** [comment]
According HQBird I've already contacted the IBSurgeon.
But I think that the bug is also in the Firebird 4. And it shouldn't invalidate the connection.

**Comment by hvlad** [comment]
Both FB4 and HQ4 is not affected

**Comment by aschegolskiy** [comment]
> Both FB4 and HQ4 is not affected

I didn't check the HQ4, but the FB4 is affected.

**Comment by hvlad** [comment]
Check current snapshot build of FB4, please

**Comment by aschegolskiy** [comment]
Checked then snapshot Firebird-4.0.3.2950-0. That's OK
