### ISSUE TITLE
Regression: Error in isc_array_lookup_bounds

### ISSUE THREAD

**Issue by pcisar** [FirebirdSQL/firebird#7647]
The Python firebird driver fails on all tests for ARRAY type handling due to next error returned from isc_array_lookup_bounds() call:
- SQLCODE: -206
- Dynamic SQL Error
- SQL error code = -206
- Column unknown
- FD.DIMENSION
- At line 6, column 16

**Comment by pavel-zotov** [comment]
Regression found, starting approx.  on 6.0.0.800-22fee85.
Following code ( "gh-7647.py" ):
* works OK on 6.0.0.800-1f226fc
* but raises "ValueError: Incorrect ARRAY field value" on 6.0.0.800-22fee85 

The fail occurs when trying to do: ```cur.execute("insert into array_table values (?)", (arrayIn,))```
```
#coding:utf-8

import os
import argparse as ap
from pathlib import Path
from firebird.driver import connect, driver_config, create_database
 
parser = ap.ArgumentParser()
parser.add_argument("fb_clnt", help="Path to FB client library")
args = parser.parse_args()

assert os.path.isfile(args.fb_clnt), "FB client library not found: '%s'" % args.fb_clnt

driver_config.fb_client_library.value = args.fb_clnt

##################
DB_NAME = Path(r'r:\temp\tmp4test.fdb')
##################
DB_NAME.unlink(missing_ok=True)

srv_cfg = driver_config.register_server(name = f'tmp_srv_cfg', config = '')
db_cfg_name = f'tmp_db_cfg'
db_cfg_object = driver_config.register_database(name = db_cfg_name)
db_cfg_object.server.value = srv_cfg.name
db_cfg_object.database.value = str(DB_NAME)

dsn = f'inet://{DB_NAME}'
dbc = create_database(db_cfg_name, user='SYSDBA', password='masterkey')
dbc.close()

with connect(dsn, user='SYSDBA', password='masterkey', charset = 'utf8') as con:
    print(con.info.firebird_version)
    con.execute_immediate('create table array_table (array_field int[3,4])')
    con.commit()
    cur = con.cursor()
    arrayIn = \
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9,10,11,12]
    ]
    print('Trying to insert data...')
    cur.execute("insert into array_table values (?)", (arrayIn,))
```

To reproduce run:
```python gh-7647.py C:\FB\60SS\fbclient.dll```
(where ```C:\FB\60SS``` = folder where checking FB instance lives)

**Comment by pavel-zotov** [comment]
> starting ap(prox. on 6.0.0.800-22fee85.

Correction: problem starting from 6.0.0.800-0-b8be591
(2025-06-10 Merge pull request #8445 from FirebirdSQL/work/schema)
