### ISSUE TITLE
Unable to find savepoint in insert with nested query and returning clause in FB4

### ISSUE THREAD

**Issue by MarcioKviatkovski** [FirebirdSQL/firebird#7651]
The commands below works fine with FB 2.5, but fails on FB 4 with the message 'Unable to find savepoint with name S in transaction context':

```
C:\>isql -user sysdba -password masterkey employee
Database: employee, User: SYSDBA
SQL> Savepoint S;
SQL> Insert Into Customer (Customer, Country) Values ('John Doe', (Select Country From Country Where Currency = 'Dollar')) Returning Cust_No, Country;

     CUST_NO COUNTRY
============ ===============
        1017 USA

SQL> Release Savepoint S;
Statement failed, SQLSTATE = 3B000
Unable to find savepoint with name S in transaction context
```

The error does not occur if the subquery or the returning clause is removed. 

Tested on Windows 10 64-bit and Firebird 64-bit 4.0.2.2816 and 4.0.3.2955 with all default settings. Both with the same result. 

Version 3.0 also seems to have the same problem, but I didn't get to test it. More details at https://groups.google.com/g/firebird-support/c/_ZE46kSoS30

**Comment by dyemanov** [comment]
Firebird v3 is not affected due to different savepoint logic, but I'd apply the fix there too (just to be safe).
v5 also seems to be not affected, may be due to different RETURNING behaviour (its execution is delayed, so INSERT is not interrupted in the middle).
