### ISSUE TITLE
Add "force older format" to the backup utility

### ISSUE THREAD

**Issue by gsbelarus** [FirebirdSQL/firebird#7653]
A significant stopper for upgrading Firebird server is the inability to downgrade database structure once the migration is done. For critical infrastructure, no one would dare to risk being locked into a newer version, potentially bringing new critical bugs, crashes, or performance bottlenecks.

The solution would be a "force version" switch in the gbak utility which would store the data in an older format.

In such a way, one who uses FB3 right now could try FB4 or FB5 and easily return to the previous version if some issues arise.

**Comment by aafemt** [comment]
Downgrade is simple: create a new database from master-script and pump data.
If you want backup in old format - you can use old version of gbak but it won't help because the main source of problems is stored BLR.
The solution for a seamless migration of a critical infrastructure is a bidirectional replication.

**Comment by gsbelarus** [comment]
When the size of the database is 400+GB and time is strictly limited, the data pump isn't a solution. Bidirectional replication is out of question due to the complexity.

I'm not asking for all possible scenarios of downgrading. Just the easiest one, when there were no newest data types used. SP and triggers could be compiled from sources.

**Comment by aafemt** [comment]
You asked for a switch for gbak. All that gbak do is exactly creation of a new database and pumping data. If it isn't a solution for you then the switch and gbak in common are useless for you so this ticket is pointless.

**Comment by EPluribusUnum** [comment]
@gsbelarus , data pump is the only soultion. Database file binary structures are different between versions. Each version has different ODS (On-Disk Structure), so you have to rewrite everything.

**Comment by hvlad** [comment]
> I'm not asking for all possible scenarios of downgrading. Just the easiest one, when there were no newest data types used. SP and triggers could be compiled from sources.

Then how is it differs from creating backup using previous version of gbak ?

**Comment by gsbelarus** [comment]
I didn't know that it would work. Going to test it.
