### ISSUE TITLE
"Attempt to evaluate index expression recursively"

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7676]
Hi *!

insert into kt_ev_elszamolas(id, kt_ev_sablon_id, ertekvesztes_napja, szur_ktfj_kod, fix_napos_visszairas)
values(1, 8003, '2023.01.01', 'BANAN', 'N');

We get "Attempt to evaluate index expression recursively" for this command with FB5.0.1111 (snapshot)
This works fine with 3.0.10 and 4.0.2

[libra3sdbteszt_fulldb.zip](https://github.com/FirebirdSQL/firebird/files/12028603/libra3sdbteszt_fulldb.zip)

**Comment by dyemanov** [comment]
What about UDFs?

-function TO_CHAR_DEPRECATED is not defined
-module name or entrypoint could not be found

**Comment by EPluribusUnum** [comment]
Attached (remove 32/64 from name)

[udf_and_conf.zip](https://github.com/FirebirdSQL/firebird/files/12028851/udf_and_conf.zip)

**Comment by EPluribusUnum** [comment]
@dyemanov , fix confirmed, works with 5.0.1121.

Could you delete the attached files?

Thank You!

**Comment by dyemanov** [comment]
I've removed links, but GitHub does not allow to delete attachments from the cloud. Could be via the support request, I suppose.
