### ISSUE TITLE
Profiler should not miss query's top-level access paths nodes

### ISSUE THREAD

**Issue by asfernandes** [FirebirdSQL/firebird#7688]
For example, when explaining this query:

```
SQL> select 1, (select 2 from rdb$database b) from rdb$database a;

Sub-query
    -> Singularity Check
        -> Table "RDB$DATABASE" as "B" Full Scan
Select Expression
    -> Table "RDB$DATABASE" as "A" Full Scan
```

The profiler `plg$prof_record_sources` table misses nodes for `Sub-query` and `Select Expression`.

**Comment by pavel-zotov** [comment]
=== QA issue ===
Have a question about explained plan 'reconstruction' and proper place of its 'blocks' related to sub-queries (when this plan have them).
Sent example to Adriano, waiting for reply.
