### ISSUE TITLE
Alternative String Literals and multibyte (UTF8) alternatives

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird#7715]
FB3 and FB4 don't support multibyte alternatives

Connection charset: **UTF8**

```sql
select  _win1251 q'Жмама, мама, что я буду делать?Ж' from rdb$database

select  _win1251 q'🙃мама, мама, что я буду делать?🙃' from rdb$database
```

---
Correct me, if I am not right:

Server expects that
1. **"мама, мама, что я буду делать?"** is the text with WIN1251 charset

2. **Ж** and 🙃 are the text with UTF8 charset

**Comment by asfernandes** [comment]
A problem with this is ISQL, it's not his job to interpret MBCS strings of different charsets, but it has logic to understand strings.

So maybe we should treat only UTF8 there.

**Comment by dmitry-lipetsk** [comment]
I ask only to fix the problem with 'Ж' and '🙃' in server.

**Comment by asfernandes** [comment]
> FB3 and FB4 don't support multibyte alternatives
> 
> Connection charset: **UTF8**
> 
> ```sql
> select  _win1251 q'Жмама, мама, что я буду делать?Ж' from rdb$database
> 
> select  _win1251 q'🙃мама, мама, что я буду делать?🙃' from rdb$database
> ```
> 
> Correct me, if I am not right:
> 
> Server expects that
> 
> 1. **"мама, мама, что я буду делать?"** is the text with WIN1251 charset
> 2. **Ж** and 🙃 are the text with UTF8 charset

While there is a bug, there is an error in your usage of connection charset / introducer syntax.

`_win1251` does not mean a cast. It means the string (including its alternate start/end) should be encoded in `win1251`.

Which is not your case as you mention UTF8 connection charset and WIN1251 does not have "🙃"

**Comment by dmitry-lipetsk** [comment]
> > Correct me, if I am not right:
> > Server expects that
> > 
> > 1. **"мама, мама, что я буду делать?"** is the text with WIN1251 charset
> > 2. **Ж** and 🙃 are the text with UTF8 charset
> 
> While there is a bug, there is an error in your usage of connection charset / introducer syntax.
> 
> `**_win1251` does not mean a cast.** 

Yes, I know it.

>It means the string (**including its alternate start/end**) should be encoded in `win1251`.

It is a surprise for me.

I thought (and implemented) that "alternate start/end" has the connection charset.

Thanks for information.
