### ISSUE TITLE
Wrong error message on login if the user doesn't exists and WireCrypt is disabled

### ISSUE THREAD

**Issue by aafemt** [FirebirdSQL/firebird#7723]
If WireCrypt is disabled an attempt to attach with non-existing user returns isc_login_error instead of isc_login.

Two problems here:
1. It leaks security information about user existence.
2. Some client code explicitly expect isc_login to be returned.

```
Use CONNECT or CREATE DATABASE to specify a database
SQL> connect localhost:atest user aaaa password 'bbb';
Statement failed, SQLSTATE = 08006
Error occurred during login, please check server firebird.log for details
SQL> connect localhost:atest user abc password 'bbb';
Statement failed, SQLSTATE = 28000
Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
SQL> connect localhost:atest user abc password 'def';
Database: localhost:atest, User: ABC
```

**Comment by aafemt** [comment]
Try with `WireCrypt=Disabled`.

**Comment by AlexPeshkoff** [comment]
On 8/28/23 12:49, Dimitry Sibiryakov wrote:
>
> Try with |WireCrypt=Disabled|.
>

Yes, that really changed execution path. Add a ticket please.

**Comment by aafemt** [comment]
I've updated this ticket.
