### ISSUE TITLE
"SET BIND OF TS WITH TZ TO VARCHAR(128)" uses the date format of dialect 1.

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird#7729]
FB 4.0.3.2973, database with **dialect 3**.

```sql
SET BIND OF TIMESTAMP WITH TIME ZONE TO varchar(128);
select timestamp '2023-08-29 01:02:03.0123 +3:0' from rdb$database;
```
Server returns string "29-AUG-2023 1:02:03.0123 +03:00"

I think. when client uses dialect 3, server should return "2023-08-29 1:02:03.0123 +03:00"

---
The second problem(?) - server ignores the size of VARCHAR. It returns the string with 57 symbols.

RDB$TIME_ZONES table says that TIME ZONE name can be up to 63 symbols.

---
![image](https://github.com/FirebirdSQL/firebird/assets/4594554/76d25485-4e95-4d8c-bd2d-b68d0efb1228)

**Comment by AlexPeshkoff** [comment]
> RDB$TIME_ZONES table says that TIME ZONE name can be up to 63 symbols.
I do not know where did this 63 symbols came from. Actual maximum length is 32.

**Comment by AlexPeshkoff** [comment]
Yep, when talking in dialect 1 overflow here is really possible. Will fix.

**Comment by dmitry-lipetsk** [comment]
The first thought of day - it is needed to check and correct the bind of TIMESTAMP and DATE, too :)

**Comment by dyemanov** [comment]
Should this ticket be closed?

**Comment by AlexPeshkoff** [comment]
The only reason why it and #7731 were not closed - I doubt should they be backported to fb4 or not. Certainly both are bugs, but IMO not too critical and (on the other hand) affecting possible end-user soft behavior (changed rules of date parsing, changed column width). 

Do you have an idea?
