### ISSUE TITLE
key size exceeds implementation restriction for index 

### ISSUE THREAD

**Issue by piervalli** [FirebirdSQL/firebird#7734]
Hello,

I should use Firebird in embedded mode instead of Sqlite,  I have the error "key size exceeds implementation restriction for index" when i create a unique index with two column

CREATE TABLE psequence("pmodel" VARCHAR(255) ,
"field" VARCHAR(255) ,
"value" VARCHAR(255) ,
"id" CHAR(36) CHARACTER SET OCTETS  NOT NULL ,
"deleted"  SMALLINT  DEFAULT 0 ,
"deleted_date"  date ,
"modified"  timestamp without time zone  DEFAULT 'now' ,
"created"  timestamp without time zone  DEFAULT 'now' ,
"sended"  SMALLINT  DEFAULT 0 ,CONSTRAINT psequence_pkey PRIMARY KEY ("id"),
 CONSTRAINT psequence_pmodel_field_unique UNIQUE("pmodel","field"),
 CONSTRAINT psequence_deleted_check CHECK("deleted" = 0 or "deleted" = 1) ,
 CONSTRAINT psequence_sended_check CHECK("sended" = 0 or "sended" = 1) );`
`
Error 
key size exceeds implementation restriction for index "PSEQUENCE_PMODEL_FIELD_UNIQUE")
Why, can not create a index with two field only of 255 char?

**Comment by piervalli** [comment]
Hi 

I finded a task on Stackoverfloow
https://stackoverflow.com/questions/21577674/fbsqlexception-key-size-exceeds-implementation

Thanks

**Comment by mrotteveel** [comment]
I guess your default character set is UTF8, and you're using a database with page size 4096. In that case you cannot create this index. This is also documented in [Limits on Indexes](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-ddl-idx-limits) in the Firebird 4.0 Language Reference.

For future reference, the project prefers questions to be asked on https://groups.google.com/g/firebird-support, not in the issues, as we use that for bug reports and feature requests.

**Comment by piervalli** [comment]
Hi,
thanks,I din't know the group on Google.
