### ISSUE TITLE
Cyrillic text encoding on Firebird 3.0

### ISSUE THREAD

**Issue by Polfath-gsbelarus** [FirebirdSQL/firebird#7736]
There was a problem with encoding Cyrillic characters in Firebird 3.0
1. Created a backup file of the Firebird 2.5 database
2. Restored it on Firebird 3.0 using a Delphi application
3.  Recompiled all stored procedures using the same application (alter procedure <proc_name> as <proc_soutce)
4. As a result, all Cyrillic characters were replaced by '?????...'

**Comment by Polfath-gsbelarus** [comment]
But if I do the same manipulations on FB 2.5, everything is OK

**Comment by aafemt** [comment]
That was a bug in 2.5. Fixed.

**Comment by Polfath-gsbelarus** [comment]
I tried alter 'character set WIN1251' before compiling. It did not help.

**Comment by aafemt** [comment]
You cannot fix your application altering server character set.

**Comment by hvlad** [comment]
> But if I do the same manipulations on FB 2.5, everything is OK

What manipulations ? Do you think we will guess what you are doing ?
Please, provide exact steps to reproduce the issue.

> I tried alter 'character set WIN1251' before compiling. It did not help.

Not sure, I understand what you tried and for what purpose...
Connection charset could be set at connection time using DPB only.

**Comment by Polfath-gsbelarus** [comment]
The application uses the following algorithm:
1. Execute query using IBSQL component: 
    'SELECT pr.RDB$PROCEDURE_NAME, pr.RDB$PROCEDURE_SOURCE FROM RDB$PROCEDURES pr'
2. Then in a loop for each procedure I execute the command: 
     q1.SQL.Text := 'ALTER PROCEDURE "' + q2.Fields[0].AsTrimString + '" ' + GetParamsText(q2.FieldByName('RDB$PROCEDURE_NAME').AsString , ADataBase) +
        ' AS ' + q2.Fields[1].AsTrimString;
3. As a result I get '????'

**Comment by aafemt** [comment]
Garbage in - garbage out.

**Comment by Polfath-gsbelarus** [comment]
Why garbage? It worked for FB 2.5

**Comment by Polfath-gsbelarus** [comment]
Thank you

**Comment by hvlad** [comment]
Next time ask in [support group](https://groups.google.com/g/firebird-support), please
