### ISSUE TITLE
Crash on multiple connections/disconnections

### ISSUE THREAD

**Issue by romansimakov** [FirebirdSQL/firebird#7738]
It's easily reproducable by attached python script on default build of master (SS).
[nbak-test.zip](https://github.com/FirebirdSQL/firebird/files/12525308/nbak-test.zip)

It looks like reallocated mem. And it might happen the second cache_writer for the same dbb.

**Comment by AlexPeshkoff** [comment]
The reason of a bug is ability to start more than one cache_writer thread simultaneously due to races on bcb_flags in CCH_init2.

**Comment by pavel-zotov** [comment]
Can'e reproduce on 5.0.0.1182 SS (Windows). Sent report to Alex and Roman.
