### ISSUE TITLE
Error restoring database which has system domains in user table with BLOBs using embedded connection

### ISSUE THREAD

**Issue by paolofai** [FirebirdSQL/firebird#7745]
Hi,
i'm backing up a db using firebird 2.5.6.27020 and restoring using 4.0.3.2975.
during restore process gbak crashed with this error:

C:\Program Files\Firebird\Firebird_4_0>GBAK -REP  c:\tmp\a.fbk a.fdb
gbak: ERROR:Dynamic SQL Error
gbak: ERROR:    SQL error code = -104
gbak: ERROR:    Blob buffer format error
gbak: ERROR:    Size of segment (15546) greater than current BLOB data (186)
gbak:Exiting before completion due to errors

C:\Program Files\Firebird\Firebird_4_0>

restore works fine with 4.0.0.2496

**Comment by AlexPeshkoff** [comment]
Can you provide test .fbk file?

**Comment by paolofai** [comment]
I send a download link on your mail.

**Comment by AlexPeshkoff** [comment]
Did not reproduce on linux. Please try with the following command line:

GBAK -REP localhost:c:\tmp\a.fbk a.fdb

**Comment by aafemt** [comment]
@AlexPeshkoff Are you sure in this command line?..

**Comment by paolofai** [comment]
I try GBAK -REP c:\tmp\a.fbk localhost:c:\tmp\a.fdb and it works ( of course locahost should be put on fdb file).
TCP/IP connection string works fine , the error apperars only with localhost connection string.
Paolo

**Comment by plillejo** [comment]
> Did not reproduce on linux. Please try with the following command line:
> 
> GBAK -REP localhost:c:\tmp\a.fbk a.fdb

Tnx. This fix worked for me, prefix with localhost. using FB 4.0.3.2975
Have not tried to see if this is a issue on older revisions.
