### ISSUE TITLE
SET BAIL  = ON prevents the execution of a connection if the "commit;" (or "rollback;") is written before the "connect" statement on the same line

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7750]
Consider following scenario:
```
set bail on;
set list on;
set echo on;
rollback; connect 'localhost:employee' user sysdba password 'masterkey';
select mon$database_name from mon$database;

commit; connect 'localhost:employee' user sysdba password 'masterkey';
select mon$database_name from mon$database;
```

Its output will contain only one row:
```
rollback; connect 'localhost:employee' user sysdba password 'masterkey';
```
(further commands will not be shown without any warning/error message; control immediately returns to OS).

If 'set bail on;' will be commented then output become expected:
```
rollback; connect 'localhost:employee' user sysdba password 'masterkey';
select mon$database_name from mon$database;

MON$DATABASE_NAME               C:\FB\50SS\examples\empbuild\employee.fdb


commit; connect 'localhost:employee' user sysdba password 'masterkey';
select mon$database_name from mon$database;

MON$DATABASE_NAME               C:\FB\50SS\examples\empbuild\employee.fdb
```

**Comment by mrotteveel** [comment]
This is the expected behaviour. The `ROLLBACK;` or `COMMIT;` will produce an error, which will result in ISQL terminating, because that is what `SET BAIL ON;` does.

**Comment by pavel-zotov** [comment]
OK, but why no warning or error issued ?

**Comment by mrotteveel** [comment]
In interactive mode, attempting to execute an statement that is not an ISQL command will result in the message _"Use CONNECT or CREATE DATABASE to specify a database"_ to be displayed. I guess the normal error is suppressed.

**Comment by mrotteveel** [comment]
I guess you execute ISQL with `-q` which will suppress displaying of _"Use CONNECT or CREATE DATABASE to specify a database"_.

**Comment by mrotteveel** [comment]
FYI: The exact same can be observed with a different statement:

```
set bail on;
set echo on;
select * from rdb$database;
select * from rdb$database;
```

Executing with `isql -q -input test.sql` results in output:

```
>isql -q -input test.sql
select * from rdb$database;

>
```

**Comment by mrotteveel** [comment]
BTW, maybe ISQL should report something here, but please create a new issue for that. The issue you reported is expected and intentional behaviour of `SET BAIL ON`, which is why I closed it.

**Comment by pavel-zotov** [comment]
> please create a new issue for that. The issue you reported is expected and intentional behaviour of SET BAIL ON,

This is strange (I mean no any message when bail = on).

Command-line help says that "-q" switch means do not show the message "Use CONNECT..."
And ONLY this. 
This command-line output does not say that error will be suppressed when we use commit/rollback without established connection and bail = on.

And if ISQL is started without "-q" then, of course, first message that we can see is "Use connect...".
But why THE SAME message is issued if we put 'commit;' (no matter whether we start ISQL with or without '-b') ? 
```
Use CONNECT or CREATE DATABASE to specify a database
SQL> commit;
Use CONNECT or CREATE DATABASE to specify a database <<< ! here at least warning must be ! NOT repeating 'Connect ....'
SQL>
```

**Comment by mrotteveel** [comment]
When you are not connected, executing any statement which is not an ISQL command is an error, but instead of an error, the "Use CONNECT ..." message is displayed, but you disabled that by using `-q`...

And yes, maybe a message should be displayed in this case, but please create a separate ticket for that. The issue you reported here (`SET BAIL ON` terminates a script if you execute something which requires a connection when there is no connection), is correct and expected behaviour.

And to be clear, this is not only with commit or rollback, it happens with **any** statement which requires a connection.

**Comment by pavel-zotov** [comment]
#7751
