### ISSUE TITLE
zlib version 1.3 released 2023-08-18

### ISSUE THREAD

**Issue by basid-irk** [FirebirdSQL/firebird#7755]
```
Version 1.3 has these key updates from 1.2.13:
    Building using K&R (pre-ANSI) function definitions is no longer supported.
    Fixed a bug in deflateBound() for level 0 and memLevel 9.
    Fixed a bug when gzungetc() is used immediately after gzopen().
    Fixed a bug when using gzflush() with a very small buffer.
    Fixed a crash when gzsetparams() is attempted for a transparent write.
    Fixed test/example.c to work with FORCE_STORED.
    Fixed minizip to allow it to open an empty zip file.
    Fixed reading disk number start on zip64 files in minizip.
    Fixed a logic error in minizip argument processing.
```

**Comment by asfernandes** [comment]
As the fix is Windows only, and Linux build requires different type of fixes for different versions, I think this issue must be renamed to be specific about Windows and another one must be created for Linux.

**Comment by AlexPeshkoff** [comment]
I doubt linux build requires anything - we always rely on system zlib.

**Comment by asfernandes** [comment]
> I doubt linux build requires anything - we always rely on system zlib.

Sorry, I get confused by the zlib used in the docker builder with crosstoolng, thinking it was statically linked in Firebird.
But this is about the toolchain only.

Anyway, this fix (ang bug) is really about Windows only.

**Comment by hvlad** [comment]
> Anyway, this fix (ang bug) is really about Windows only.

What bug ?

**Comment by asfernandes** [comment]
> > Anyway, this fix (ang bug) is really about Windows only.
> 
> What bug ? You mean - this ticket ?

Yes, it's arguable if update of a vulnerable library is improvement or bug, but no need to discuss it, I was just meaning "this issue".
