### ISSUE TITLE
Loading (32bit) fbClient.dll changes the FPU control word

### ISSUE THREAD

**Issue by mikerabat** [FirebirdSQL/firebird#7756]
When loading the dll all the FPU exceptions are masked (lowest 5bits). This has some side effects on other libraries/programs.
It seems that is something that reemerged and is also described here:
https://github.com/FirebirdSQL/firebird/issues/5386

**Comment by hvlad** [comment]
What Firebird version ? Any test case ?

**Comment by mikerabat** [comment]
Firebird 4.0.3. I have here a simple Delphi console program (shouldn't be hard to either code it in c++ or use FPC or a free delphi version to build it):

```
program TestLoadFBClient;

{$APPTYPE CONSOLE}

uses
  SysUtils,
  Windows;

var cwWord : word;
    hdl : THandle;
    HResource: TResourceHandle;
    HResData: THandle;
    PRes: Pointer;
    InfoSize: DWORD;
    FileInfo: PVSFixedFileInfo;
    FileInfoSize: DWORD;

    aMajor, aMinor, aRelease, aBuild : integer;
begin
  try
     cwWord := Get8087CW;
     Writeln('Original CW: ' + IntToHex( cwWord, 4 ) );
     hdl := LoadLibrary('fbClient.dll');

     aMajor := 0;
     aMinor := 0;
     aRelease := 0;
     aBuild := 0;
     if hdl <> 0 then
     begin
          HResource := FindResource(hdl,  MakeIntResource(VS_VERSION_INFO), RT_VERSION);
          if HResource <> 0 then
          begin
               HResData:=LoadResource(hdl, HResource);
               if HResData <> 0 then
               begin
                   PRes:=LockResource(HResData);
                   if Assigned(PRes) then
                   begin
                        InfoSize := SizeofResource(hdl, HResource);
                        if InfoSize = 0 then
                           raise Exception.Create('Can''t get version information.');
                        // Query the information for the version
                        VerQueryValue(PRes, '\', Pointer(FileInfo), FileInfoSize);
                        // Now fill in the version information
                        AMajor := FileInfo.dwFileVersionMS shr 16;
                        AMinor := FileInfo.dwFileVersionMS and $FFFF;
                        ARelease := FileInfo.dwFileVersionLS shr 16;
                        ABuild := FileInfo.dwFileVersionLS and $FFFF;
                   end;
               end;
          end
          else
              RaiseLastOSError;

          Writeln(Format('Loaded library with version %d.%d.%d.%d', [aMajor, aminor, aRelease, aBuild]));
     end
     else
         Writeln('Failed to load library');

     cwWord := Get8087CW;
     Writeln('Changed CW: ' + IntToHex( cwWord, 4 ) );

     readln;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.

```

**Comment by hvlad** [comment]
Can't confirm, tried with D7 and FB 4.0.2, 4.0.3, 4.0.4

Sample output:

```
...\Firebird-4.0.3.2975-0-Win32-pdb>TestLoadFBClient.exe
Original CW: 1372
Loaded library with version 4.0.3.2975
Changed CW: 1372
```

**Comment by mikerabat** [comment]
Now that is odd..

With Delphi 2010 and Delphi 11.3 I get:

Original CW: 1372
Loaded library with version 4.0.2.2816
Changed CW: 137F

and

Original CW: 1372
Loaded library with version 4.0.3.2975
Changed CW: 137F

and right - I can confirm that the control word is not changed in FPC (tested with CodeTyphon) so what kind of magic
could that be?

The dll's were downloaded from https://firebirdsql.org/en/firebird-4-0-3/

**Comment by hvlad** [comment]
With Delphi 10.2 I still can't reproduce it.

Some quick ideas for research:
- try your .exe with another version of fbclient.dll, say, v3.x or v2.5x 
- try your .exe with another DLL, not fbclient.dll 
- check if [SafeLoadLibrary](https://docwiki.embarcadero.com/Libraries/Sydney/en/System.SysUtils.SafeLoadLibrary) helps, if yes - add some FB API calls to ensure CW is not changed after fbclient loading

**Comment by mikerabat** [comment]
Dear Vlad,

first... thank you for looking into that!

I actually just tried it with 3.0 and get the output:

Original CW: 1372
Changed CW: 1372
Loaded library with version 3.0.11.33703

(I just moved the control word check above the version extraction...)

With 4.0 and the same exe I get the changed control word. Very strange.

I got the idea of SaveLoadLibrary. It does exactly that: stores the control
word, loads the lib,
restores it.

**Comment by EPluribusUnum** [comment]
32 or 64 bit client?

**Comment by mikerabat** [comment]
32bit

**Comment by mikerabat** [comment]
If there are still different results on your machine(s) then I suspect that the FPU control word is not changed by the fbclient but rather a dll the fbclient references and implicitly loads. What do you think?
And I will go with some sort of SafeLoadLibrary option.

**Comment by hvlad** [comment]
> If there are still different results on your machine(s) then I suspect that the FPU control word is not changed by the fbclient but rather a dll the fbclient references and implicitly loads. What do you think? 

Yes, it is possible. And this is why I asked you to check if CW changed on DLL load only, or after every API call also.
I'm looking if some initialization code of extern libraries added in v4 could change CW but no luck so far.

> And I will go with some sort of SafeLoadLibrary option.

Hope it helps ;)

**Comment by hvlad** [comment]
So, SafeLoadLibrary helps, correct ?

**Comment by mikerabat** [comment]
yes - this is the way we go now - I updated the 3rd party access package
(IBDac) such that it
restores the FPU control word.
