### ISSUE TITLE
Problem with RDB$RELATION_SOURCE of procedure that uses table with national name

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird#7757]
WI-V4.0.4.2988 Firebird 4.0

Database with dialect 3

1. Console codepage UTF8
2. ISQL: connection with NONE charset
3. CREATE TABLE "ПРЕВЕД" (ID INTEGER);
4. create procedure SP_PREVED as begin INSERT INTO "ПРЕВЕД" VALUES(1); end
5. select RDB$PROCEDURE_SOURCE from RDB$PROCEDURES where RDB$PROCEDURE_NAME='SP_PREVED';

The last statement returns

`begin INSERT INTO "????????????" VALUES(1); end`

TABLE and SP were created correctly and can be used without any problem.

The problem is only with RDB$PROCEDURE_SOURCE.

I tested with another tools (IBE, IBP) and got the same problem - bad RDB$PROCEDURE_SOURCE

When I use the connection charset WIN1251 - all is ok.

```
d:\Program_Files\Firebird_4_0_x64>chcp 65001
Active code page: 65001

d:\Program_Files\Firebird_4_0_x64>isql
Use CONNECT or CREATE DATABASE to specify a database
SQL> CONNECT inet4://localhost/d:\Database\FB_04_0_0\IBP_TEST_FB40_D3.GDB USER SYSDBA PASSWORD masterkey;
Database: inet4://localhost/d:\Database\FB_04_0_0\IBP_TEST_FB40_D3.GDB, User: SYSDBA
SQL> set term !!; recreate procedure SP_PREVED as begin end!! set term ;!!
SQL> recreate table "ПРЕВЕД" (ID INTEGER);
SQL> commit;
SQL> select RDB$RELATION_NAME from RDB$RELATIONS where RDB$RELATION_NAME='ПРЕВЕД';

RDB$RELATION_NAME
===============================================================
ПРЕВЕД

SQL> set term !!; recreate procedure SP_PREVED as begin INSERT INTO "ПРЕВЕД" VALUES(1); end!! set term ;!!
SQL> commit;
SQL> execute procedure sp_preved;
SQL> commit;
SQL> select * from "ПРЕВЕД";

          ID
============
           1

SQL> select RDB$PROCEDURE_SOURCE from RDB$PROCEDURES where RDB$PROCEDURE_NAME='SP_PREVED';

RDB$PROCEDURE_SOURCE
====================
             1a:da2f
==============================================================================
RDB$PROCEDURE_SOURCE:
begin INSERT INTO "????????????" VALUES(1); end
==============================================================================

SQL>
```

**Comment by aafemt** [comment]
Cannot reproduce with Firebird 5 and embedded connection and correct connection charset:
```
Microsoft Windows [Version 10.0.19045.3448]
(c) Microsoft Corporation. All rights reserved.

C:\Programs\Firebird\Firebird5>chcp 65001
Active code page: 65001

C:\Programs\Firebird\Firebird5>isql ctest -ch utf8
Database: ctest, User: SD
SQL> recreate table "ПРЕВЕД" (ID INTEGER);
SQL> commit;
SQL> select RDB$RELATION_NAME from RDB$RELATIONS where RDB$RELATION_NAME='ПРЕВЕД';

RDB$RELATION_NAME
===============================================================
ПРЕВЕД

SQL> set term !!; recreate procedure SP_PREVED as begin INSERT INTO "ПРЕВЕД" VALUES(1); end!! set term ;!!
SQL> execute procedure sp_preved;
SQL> commit;
SQL> select RDB$PROCEDURE_SOURCE from RDB$PROCEDURES where RDB$PROCEDURE_NAME='SP_PREVED';

RDB$PROCEDURE_SOURCE
====================
              1a:1e0
==============================================================================
RDB$PROCEDURE_SOURCE:
begin INSERT INTO "ПРЕВЕД" VALUES(1); end
==============================================================================

SQL>
```

**Comment by dmitry-lipetsk** [comment]
> Cannot reproduce with Firebird 5 and embedded connection and correct connection charset:

This question was about connection with **NONE** charset.

With UTF8 and WIN1251 connection charset problem does not exist.

**Comment by aafemt** [comment]
IMHO, charset NONE must be deprecated. ISQL and client library should detect current codepage/locale and set connection charset accordingly.

**Comment by dmitry-lipetsk** [comment]
May be you wanted to say - remove connection charset at all?

Because in FB4 with his SET BIND killed an correct behaviour of connection charset.

I don't mind.

**Comment by aafemt** [comment]
I said what I wanted to say. SET NAMES and scripts in different encodings cannot disappear at will. As well as application wanting to get data in different encoding from database to display/handle them correctly.

**Comment by AlexPeshkoff** [comment]
SET BIND does not break behavior of connection charset - it just makes it more flexible. Applications may get data from server not only to display them on tty or print immediately, sometimes one needs to send extracted data somewhere, and this can easily require another charset (for example utf8 instead win1251). Now server can change encoding itself. Are you sure that it's broken behavior?

**Comment by dmitry-lipetsk** [comment]
As I have said early in fb-devel - if I want to get text with an original (rebinded) charset I will use connection charset NONE.

When I define isc_dpb_lc_ctype with NOT NONE charset, I define exact charset that I want to see.

In this case, connection driver does not need to access RDB$CHARACTER_SETS to map (unknown) charsetID to (known) charsetName. It allows work with server more effectively.

---
In any case, FB4 broke backwards compatibility you're so worried about.

---
Please, this question was about another problem.

@asfernandes, could you look at original question?

I think it is problem with translation of SP body to UTF8 when is NONE connection charset is used. In this case substrings in double quotes are aleady have the UTF8-charset (FB4). In the previous versions (FB1-FB3) this quoted-names have UNICODE_FSS charset.

Thanks.

PS. Your implementation of TIME ZONES is really cool. Thanks.

**Comment by asfernandes** [comment]
This is by design. Engine should not map statements with NONE charset to system table metadata UTF8.
Metadata charset is implementation detail.
