### ISSUE TITLE
Routine calling overhead increased by factor 6 vs Firebird 4.0.0

### ISSUE THREAD

**Issue by tonne1** [FirebirdSQL/firebird#7759]
Noticed when upgrading from 4.0.0 to 4.0.3, 5.0.0 RC1 is equally affected, Win10, Win11. Test case, simply run an empty stored function one million times:

```sql
create or alter function empty_sf
returns varchar(10)
as
begin
  return '';
end;

execute block 
as 
declare i integer = 0;
begin
  while (i < 1000000) do
  begin
    empty_sf();
    i = i + 1;
  end  
end;
```

Execution times, local machine, factor 6:

4.0.3 10.9 sec
4.0.0   1.9 sec
5.0.0 10.8 sec

Stored procedures are also affected:

```sql
create or alter procedure empty_sp
returns (s varchar(10))
as
begin
  s = '';
  suspend;
end;

execute block 
as 
declare i integer = 0;
declare s varchar(10);
begin
  while (i < 1000000) do
  begin
    select s from empty_sp into :s;
    i = i + 1;
  end  
end;
```

Execution times, local machine, factor 4:

4.0.3 12.8 sec
4.0.0   3.5 sec
5.0.0 13.2 sec

**Comment by hvlad** [comment]
Looks like related with #7090 

@asfernandes : could you look at it ? 

The hot path started with `funcRequest->setGmtTimeStamp()` call that finally converts GMT timestamp into connection timezone, AFAIU.

```
engine13.dll!Firebird::TimeZoneUtil::decodeTimeStamp Line 769
	at f:\fb2\fb40\src\common\timezoneutil.cpp(769)
engine13.dll!Firebird::TimeZoneUtil::timeStampTzToTimeStamp Line 914
	at f:\fb2\fb40\src\common\timezoneutil.cpp(914)
[Inline Frame] engine13.dll!Jrd::jrd_req::TimeStampCache::update Line 252
	at f:\fb2\fb40\src\jrd\req.h(252)
[Inline Frame] engine13.dll!Jrd::jrd_req::TimeStampCache::setGmtTimeStamp Line 198
	at f:\fb2\fb40\src\jrd\req.h(198)
[Inline Frame] engine13.dll!Jrd::jrd_req::setGmtTimeStamp Line 496
	at f:\fb2\fb40\src\jrd\req.h(496)
engine13.dll!Jrd::UdfCallNode::execute Line 13040
	at f:\fb2\fb40\src\dsql\exprnodes.cpp(13040)
```

**Comment by hvlad** [comment]
Sorry, didn't saw last commit when writting comment. Anyway, idea might be considered at least ;)

**Comment by asfernandes** [comment]
> Perhaps, it is possible to assign both gmt- and local- timestamps at once, to avoid recalculation of local ts ?

It's the conversion from GMT to local that is slow (*), so the idea was to defer it.

* Pavel Zotov had some reports about slow down that I could not reproduce before. Some ICU function had different overheads from his machine and mine. This may even be related to the current time zone.

**Comment by asfernandes** [comment]
@tonne1 could you try a build from https://github.com/FirebirdSQL/firebird/actions/runs/6311514604 or the next v4 snapshot, please?

**Comment by hvlad** [comment]
> > Perhaps, it is possible to assign both gmt- and local- timestamps at once, to avoid recalculation of local ts ?
> 
> It's the conversion from GMT to local that is slow (*), so the idea was to defer it.

Yes, I understand. My offer is to avoid conversion if it was already done.

**Comment by tonne1** [comment]
tested snapshot 4.0.4.2993 on Win10 x64 with the two test cases, all times [seconds].

stored function: 

4.0.3 10.9
4.0.0 1.9
5.0.0 10.8
4.0.4 1.6

stored procedure:

4.0.3 12.8
4.0.0 3.5
5.0.0 13.2
4.0.4 3.2

Nice! Even faster than 4.0.0. Thanks a lot, Adriano!

**Comment by asfernandes** [comment]
@dyemanov let me know when to commit this to v5 branch, before or after rc1.
