### ISSUE TITLE
Parameters inside the IN list may cause a string truncation error

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7760]
Hi *!

With the latest FB50 snapshot (build 1225 RC1) we get the error : arithmetic exception, numeric overflow, or string truncation; string right truncation; expected length 0, actual 1.

Part of the procedure that causes the error : "... field IN (''M'', :sv) ..."
This is fine for FB30, FB40 and worked for FB50beta1.

The error only occures when the connection used with UTF8 (both via Jaybird or IBExpert), works fine on WIN1250 (IBExpert, Delphi 7). The database is WIN1250.

The SQL to reproduce
INSERT INTO pu_nav_xml_lines (id, head_id, line_number, description, quantity, unit_of_measure_nav, unit_price,
                              unit_price_huf, net_amount_huf, vat_percent, vat_amount_huf, gross_amount_huf,
                              line_expression_indicator, line_nature_indicator)
VALUES (11000, 10000, 1, 'EGYSZERŰSÍTETT 27%-KAL', 3, 'PIECE', 30000, 30000, 70866, 0.2126, 19134, 90000, 1,
        'PRODUCT')

I can send you the FTP details for the database.

**Comment by mrotteveel** [comment]
Is this dialect 1? So, is `"M"` a string literal, or is it a column reference? Have you tried recreating the stored procedure?

**Comment by EPluribusUnum** [comment]
@dyemanov , send the details to dimitr at users.sourceforge.net.

**Comment by dyemanov** [comment]
Please CC to firebird2 at yandex.ru, I'm not sure the sourceforge mail redirect is still alive...

**Comment by EPluribusUnum** [comment]
Done

**Comment by dyemanov** [comment]
Please retry with the next snapshot build.
