### ISSUE TITLE
WireProtocol Operational Error, Firebird 1.5.6 SuperServer 

### ISSUE THREAD

**Issue by GrayedFox** [FirebirdSQL/firebird#7765]
Hey all, I've just joined a company that is still using Firebird 1.5.6 (don't @ me).

The application codebase is written in Python and we are using the firebirdsql 1.2.2 package.

My local Firebird SuperServer lives inside a docker container ([this exact one here](https://hub.docker.com/r/mladenp87/firebird-1.5.6-ss)).

I can successfully log into the `security.fdb` using gsec and the username and password in question when I launch an interactive bash terminal on the Firebird container.

I was also able to set up DBeaver and can successfully connect to, edit, and persist changes on the PAYROLL.GDB file using that application using the same credentials.

Weirdly, our application is only able to successfully connect about 5% of the time, the other 95% of the time I get the following error:

```
firebirdsql.OperationalError: Connection is rejected
``` 

Digging a little deeper and we see that `wireprotocol.py` has a method that tries to parse the connection response which involves converting bytes to big int:

```
    def _parse_connect_response(self):
        # want and treat op_accept or op_cond_accept or op_accept_data
        b = self.recv_channel(4)
        while bytes_to_bint(b) == self.op_dummy:
            b = self.recv_channel(4)
        if bytes_to_bint(b) == self.op_reject:
            raise OperationalError('Connection is rejected')
```

We output some of our own stuff too when the connection fails, here it is with the username and password redacted (they are correct):

```
{'host': 'firebird', 'port': 3050, 'database': '/data/148/PAYROLL.GDB', 'user': 'redacted', 'password': 'redacted' 'charset': 'ISO8859_1', 'role': 'ADMINISTRATOR'}
```

Also, the fact that it connects some of the time with those exact credentials also suggests it's not a credentials issue.

Logging into the docker container and tailing the `firebird.log` shows something a little strange -- note how the connection rejected message, instead of outputting the username (which I think is expected), instead outputs a long line of spaces that ends with the `8` char:

```
febcec57c3e3 (Server)   Wed Sep 27 04:51:38 2023
SERVER/process_packet: connection rejected for                                                                                                 8

febcec57c3e3 (Client)   Wed Sep 27 04:51:38 2023
./fbguard: bin/fbserver terminated abnormally (-1)

febcec57c3e3 (Client)   Wed Sep 27 04:51:38 2023
./fbguard: guardian starting bin/fbserver
```

Here's a screenshot to show what I mean:

![image](https://github.com/FirebirdSQL/firebird/assets/6493307/1a500e7e-eeb3-4e4a-ae3f-58f4851ce6d1)

Is it possible that the byte to big int conversion is faulty in 1.5.6 SS? If so is there any way I could monkey patch it with the fix from a more recent Firebird client version?

The main goal here is to get the client to properly connect to my local Firebird SS instance - from what I have read (still new to the FB world) another approach would be to simply update the Python `firebirdsql` client package and implement the fix [described here](https://github.com/FirebirdSQL/firebird/issues/5958#issuecomment-826241428):

> Commented by: @AlexPeshkoff
> 
> There is a bug in FB 1.5 - some data that should be treated as unsigned bytes are treated as signed. That bug was fixed except others during code rework for FB 2.0. This always used to be not noticed cause we did not have big enough data at this place before FB3. In FB3 we kept an ability to connect to FB 1.x servers - just not to break something _probably_ useful, but without any connection guarantees cause we did not check connection to unsupported versions. And looks like nobody used to try this before you. The fact that 1.5 server steps on a kind of dirt after illegal use of byte value explains why do you connect to it sometimes. Probably sometimes it even segfaults - but with classic this is left not noticed.
> 
> The bug is at 1.5 side - but it can be easily avoided, just set (at the fb3 client side) AuthClient = Legacy_Auth, Srp in firebird.conf. 

Thanks for your time future eyeballs

**Comment by mrotteveel** [comment]
The firebirdsql Python driver (a.k.a. pyfirebirdsql) is not maintained by the Firebird project, and it is an independent project by Hajime Nakagami. You can find it at https://github.com/nakagami/pyfirebirdsql/. If you need something fixed in this driver, you need to contact Hajime there.

As an aside, the `byte_to_bint` in this specific case decodes a 32-bit int, not a "big int".

Alternatively, consider switching to one of the Python drivers that *is* maintained by the Firebird project ([FDB](https://github.com/FirebirdSQL/fdb) or [firebird-driver](https://github.com/FirebirdSQL/python3-driver)), though FDB is not actively developed anymore, for Firebird 1.5 it is probably the better choice.

As this repository is specifically for Firebird server itself, I'll close this ticket, because Firebird 1.5 is no longer maintained. If you are asking for input, or want to bounce ideas, please use the [firebird-devel Google Group instead](https://groups.google.com/g/firebird-devel).
