### ISSUE TITLE
Firebird 4 Windows Installer ommit DDLs during custom installation mode

### ISSUE THREAD

**Issue by JenWue** [FirebirdSQL/firebird#7766]
During Firebird 4 (v4.0.3 in my case) installation on Windows using the installer and the selection "custom installation" some plugin DDLs are omitted so e.g. no connection to the security database in embedded mode is possible. It is not obvious and not understandable why the installation of these DDLs is omitted despite all selectable features have been checked by the user.

**Comment by aafemt** [comment]
Can you compare two installations and tell exact names of DLL? I see no way for any missing plugin (except obvious engine) to limit embedded connection to security database.

**Comment by reevespaul** [comment]
Yes, custom install is definitely broken.

In the meantime I would suggest to just do a server install.
