### ISSUE TITLE
Slow drop trigger command execution under FB5.0

### ISSUE THREAD

**Issue by omachtandras** [FirebirdSQL/firebird#7767]
Hi,

something went wrong under 5.0.
Dropping 2366 triggers
5.0 RC1: 18 min
4.0.3: 38 sec
3.0.11: 43 sec

Sample code to test:
execute block
as
declare variable trg_drop type of column rdb$triggers.rdb$trigger_name;
begin
  for select 'DROP TRIGGER '||trim(rdb$trigger_name)
    from rdb$triggers
    where rdb$system_flag=0
  into :trg_drop do
    begin
      in autonomous transaction do
        begin
          execute statement :trg_drop;
        end
    end
end

**Comment by omachtandras** [comment]
We have the following time compared to the result of a test run a month ago:
(Unfortunately, I we do not know the number of the 5.0 snapshot used at the time.)

(Today's time -> Month ago's time)

- Check drop (1477 pieces) : 26s -> 50s (x2)
- Trigger drop (2366 pieces) : 60s -> ~18 min (x18)
- Altering views (387 pieces) : 12s -> ~200s (x16)
- Altering procedures (2208 pieces) : ~60s -> ~60s (x1)
- View drop (210 pieces) : 4s -> 4s (x1)
- Altering views/procedures (2888 pieces) : 90s -> ~410s (x4.5)
- Creating/altering views (512 pieces) : 20s -> ~450s (x22)
- Recompiling views (512 pieces) : 25s -> ~490s (x19)
- Creating/altering procedures (2277 pieces) : 110s -> 110s (x1)
- Creating triggers (1266 pieces) : 30s -> 30s (x1)
- Creating checks (1410 pieces) : 30s -> 45s (x1.5)
- Creating triggers (1067 pieces) : 30s -> 60s (x2)
- Creating triggers (290 pieces) : 10s -> 10s (x1)

**Comment by hvlad** [comment]
Could you provide a sample database for investigation ?

**Comment by EPluribusUnum** [comment]
@hvlad , sent the details in mail.

**Comment by hvlad** [comment]
Thanks, received.
But now I'm a bit confised: in [prior comment](https://github.com/FirebirdSQL/firebird/issues/7767#issuecomment-1738989767) I see that "Today's time" is much better (normal?) than "Month ago's time".
Could you explain this ?

**Comment by EPluribusUnum** [comment]
The post was incorrect, swapped the column names.

**Comment by omachtandras** [comment]
> The post was incorrect, swapped the column names.

Sorry, fixed

**Comment by hvlad** [comment]
Ok, thanks, will look at db

**Comment by hvlad** [comment]
Confirmed

**Comment by dyemanov** [comment]
It should be fixed in the latest snapshots (buildno >= 1246). Please test and report back.

**Comment by omachtandras** [comment]
> It should be fixed in the latest snapshots (buildno >= 1246). Please test and report back.

Thanks Dmitry and Vlad, confirmed, it works fast again!
(Maybe even faster than it was... But this will be seen exactly when our test system runs at night...)
