### ISSUE TITLE
Firebird 5.0 beta 1 : SQL command return "Attempt to reclose a close cursor'" on conversion string error.

### ISSUE THREAD

**Issue by ockham1** [FirebirdSQL/firebird#7771]
With database "employee" shipping with Firebird, the following SQL command:

Select * from customer where custno='a';

Produced:

Statement failed, SQLSTATE = 22018
conversion error from string "a"
Statement failed, SQLSTATE = 24000
Attempt to reclose a close cursor

This error in Delphi program crash the program.
This problem concern also Firebird-3.0.7.33374-1, Firebird-4.0.2.2816-0, 32 and 64 bits versions.

**Comment by aafemt** [comment]
First error is logical because custno is an integer field and string 'a' cannot be converted to integer.

  Second error is an obvious bug in the Delphi program that calls isc_dsql_free_statement(DSQL_close) after the first error prevented opening of the cursor. Contact the developer of the program.

**Comment by ockham1** [comment]
The above errors are produced using uniquely the Firebird ISQL tool, not a Delphi app.
Moreover, this error "Attempt to reclose a close cursor" doesn't occur with Firebird-3.0.11.33703_0 and Firebird-4.0.3.2975-0, 32 and 64 bits versions.

**Comment by aafemt** [comment]
If the error doesn't happen with latest Firebird releases then it is not an issue.

**Comment by mrotteveel** [comment]
Have you tried with Firebird 5.0 Release Candidate 1 (published yesterday)?

**Comment by ockham1** [comment]
I just installed the new release and the error has been fixed with Firebird 5.0 Release Candidate 1. Thanks.

**Comment by mrotteveel** [comment]
Good to hear. Thanks for confirming.
