### ISSUE TITLE
Blob corruption in FB4.0.3 (embedded)

### ISSUE THREAD

**Issue by TommiPrami** [FirebirdSQL/firebird#7772]
Short summary, 

- Take a backup with Fb259 embedded.
- Restore it using:
  - FB 4.0.2 embedded, all seems to be OK.
  - FB 4.0.3 embedded, blobs get corrupted.
  
Tested with FB 4.0.3 with 42 different test databases I could (easily) get my hands of, and all those suffered various degrees of corruption.  Could not reproduce this with super simple test case, if I remember correctly that I tested it on top of FB 4.0.3.

I'll send test case to Vlad Khorsun.

**Comment by TommiPrami** [comment]
Link to a Test case sent...

**Comment by hvlad** [comment]
Check next snapshot build, please

**Comment by pavel-zotov** [comment]
@@@ QA issue @@@

Currently (01-oct-2023) 5.0.0.1235 and 6.0.0.65 are also affected. Waiting for frontport.

**Comment by TommiPrami** [comment]
Was this a general issue in FB engine or just in GBak, or even more specific, restoring from fb25x backup (or similar, from old backup)?

Info determines actions needed for production.

**Comment by hvlad** [comment]
The bug was in the engine and related to the new batch feature and its handling of stream blobs of size between 64KB and 128KB.
Restore uses batches for remote database access and for some cases of embedded/services usage.
Patch for #7611 makes a more cases when batches is used for embedded/services usage, therefore v4.0.2 works correctly in your case and v4.0.3 - does not.

**Comment by mrotteveel** [comment]
I think that is serious enough to require a 4.0.4 or a 4.0.3 update 1 release to be honest. What do you think @dyemanov?

**Comment by TommiPrami** [comment]
OK,

DAC we use does not use the new Batch feature, so our app itself is safe.
Restoring is the problem though...

Have to ponder whether we can go back to FB 4.0.2...

So 4.0.4 is not coming soon then...?

-Tee-

**Comment by dyemanov** [comment]
> I think that is serious enough to require a 4.0.4 or a 4.0.3 update 1 release to be honest. What do you think @dyemanov?

We already have 12 bugfixes for the v4 branch, so 4.0.4 would be appropriate, I suppose.
