### ISSUE TITLE
[FeatureRequest] Detect modified record during SQL- Update or Delete Comand

### ISSUE THREAD

**Issue by hhfiddelke** [FirebirdSQL/firebird#7780]
I am searching for a functionality that allows me to detect if a record was modified, in an modify- or delete- trigger (or perhaps by platform) since it was read from database.

Scenario:
I have a application that reads many many records for displaying in list forms, but only a few will be modified. 
To prevent system from locking records and reducing traffic, i would like to use an optimistic approach that thinks that in over 99,9% of all cases, a SQL modify/delete will not update a record that was modified since original record was read.
To handle this, i need a trigger, that is able to detect that the Update- or Delete statement will update a record that was modified in the meantime.

My view came on RDB$RECORD_VERSION. If it would be possible to use RDB$RECORD_VERSION in an Update-/Delete- statement, i would be able to detect if i am updating or deleting an old version:
`Update Table
set RDB$RECORD_VERSION= RecordVersionOnRead,.....
where ????`
or
`Delete Table
where RDB$RECORD_VERSION= RecordVersionOnRead ......`

Then an OnUpdate or OnDelete!!- trigger would be able to compare Old.RDB$RECORD_VERSION to New.RDB$RECORD_VERSION and throw an error if the two values differ.

**Comment by aafemt** [comment]
Firebird already has RDB$RECORD_VERSION that contain transaction number which created this record version.

Just use in your application "`update table set ..... where .... and RDB$RECORD_VERSION = :RecordVersionOnRead`". If this query updated no record - handle it however you like. No trigger is needed.

Use Firebird support mail list for support questions instead of issue tracker.

**Comment by hhfiddelke** [comment]
Yes, you are fully right. That was the answer i was looking for and did not see.🙄
One last question from an unknowingly person: Does Update return a Count also if no data is modified?

**Comment by aafemt** [comment]
This pseudo-field somehow is missed in Language Reference so there is no wonder that you missed it. Perhaps it is a reason for a ticket in documentation issues tracker.

If you are asking about "returning" clause I doubt that it supports aggregate functions. Info API of course in any case returns number of updated records including zero.

**Comment by mrotteveel** [comment]
> This pseudo-field somehow is missed in Language Reference so there is no wonder that you missed it. Perhaps it is a reason for a ticket in documentation issues tracker.

None of the pseudo-columns are documented in the language reference. The language reference documents the query language, not every feature of Firebird. Though I'm on the fence if this is something that needs to be documented in the language reference, given there isn't really any other manual where this would fit I'll see if I can document them in the "Context variables" chapter.

**Comment by mrotteveel** [comment]
> Does Update return a Count also if no data is modified?

The update count counts the number of records that where touched by an update, even if the record already had the values that you're updating to. 

So:
- No records matching the where clause: update count 0
- Otherwise, the update count is non-zero and equal to the number of records matched by the where clause

**Comment by mrotteveel** [comment]
To be honest, I don't see what you're trying to achieve here, but as Dimitry says, this is more suitable to ask about on [firebird-support](https://groups.google.com/g/firebird-support).
