### ISSUE TITLE
Drop UDFs

### ISSUE THREAD

**Issue by mluzniak** [FirebirdSQL/firebird#7782]
I'm using firebird version 2.5 and I've been tasked with converting it to version 4.0 - which I've pretty much done.

My problem is with the UDFs that were used in version 2.5, and now I would like to use the native functions that are built into 4.0. My idea is to use modifications to the system tables to remove any dependencies on a particular UDF by commenting out the procedure body, view and trigger, removing (right mous button -> Drop UDF) the UDF function (it should no longer have dependencies) and uncommenting out the commented out mechanisms. Is this a good approach? What should such a process look like?

I am not a Firebird administrator.

**Comment by aafemt** [comment]
The best and simplest way is to modify script which you use to create a new database before you create the new database and pump data from old database into it. This is not a Firebird issue.

**Comment by mrotteveel** [comment]
Please ask support questions on [firebird-support](https://groups.google.com/g/firebird-support). The issue-tracker is intended for reporting bugs and feature requests.
