### ISSUE TITLE
> مرحبا

### ISSUE THREAD

**Issue by a848300** [FirebirdSQL/firebird#7785]
> مرحبا
> 
> قمنا مؤخرا بترقية قاعدة البيانات الخاصة بنا من Firebird 2.5 إلى Firebird 4.0.3 (تعمل على Windows Server 2k22 أو Windows 11). الآن يشكو بعض الناس من أن بدء تشغيل تطبيقنا يستغرق وقتا أطول من ذي قبل وهم على حق.
> 
> بادئ ذي بدء ، حول قاعدة البيانات (downloads.webaverp.com/tmp/2023.01.FB4.zip) 3k الجداول 11k الإجراءات 9k المشغلات تم إنشاؤه عن طريق النسخ الاحتياطي من 2.5 والاستعادة في 4.0.3. إعادة ترجمة جميع المشغلات والإجراءات.
> 
> سيستغرق الاتصال بقاعدة البيانات وتنفيذ إجراء (مباشرة بعد الاتصال) ما يصل إلى 10 ثوان. يتم التنفيذ الثاني في غضون أجزاء من الثانية بغض النظر عما إذا كنت قد ارتكبت أو تراجعت عن التنفيذ الأول للإجراء. نحن نستخدم IBExpert ك IDE وراجعت شاشة SQL الخاصة بهم: [07.09.2023 15:46:01] - [بدء المعاملة] بدأت المعاملة 51335 [07.09.2023 15:46:01] - [إعداد] حدد * من P_BMAND_CHECK [07.09.2023 15:46:08] - [تنفيذ] حدد * من P_BMAND_CHECK [07.09.2023 **15:46:****08**] - [جلب] BMAND_ID = 1
> 
> هناك تأخير لمدة 7 ثوان بين الإعداد والتنفيذ.
> 
> باستخدام نفس قاعدة البيانات في Firebird 2.5.9 (نفس الهيكل) يبدو كما يلي: [07.09.2023 15:50:30] - [بدء المعاملة] بدأت المعاملة 51344 [07.09.2023 15:50:30] - [إعداد] حدد * من P_BMAND_CHECK [07.09.2023 15:50:30] - [تنفيذ] حدد * من P_BMAND_CHECK [07.09.2023 **15:50:****30**] - [جلب] BMAND_ID = 1
> 
> لا يوجد تأخير بين الإعداد والتنفيذ.
> 
> مقارنة بنفس قاعدة البيانات تحت FB2.5.9 عند التنفيذ الأول بعد الاتصال: [07.09.2023 15:56:32] - [بدء المعاملة] بدأت المعاملة 76236 [07.09.2023 15:56:32] - [إعداد] حدد * من P_BMAND_CHECK [07.09.2023 15:56:32] - [تنفيذ] حدد * من P_BMAND_CHECK [07.09.2023 15:56:32] - [جلب] BMAND_ID = 1
> 
> لا يوجد تأخير بين الإعداد والتنفيذ.
> 
> أنا مرعوب من أن Firebird يقوم بتحميل شجرة التبعية عند بدء التشغيل أو التنفيذ الأول للإجراءات ولكن الأداء ازداد سوءا في ذلك.
> 
> راجع للشغل: يحتوي الإجراء P_BMAND_CHECK على تبعيات ل 940 إجراء و 250 محفزا.
> 
> شكرا لمساعدتك.
> 
> أطيب التحيات أندريه شوابي

_Originally posted by @a848300 in https://github.com/FirebirdSQL/firebird/issues/7743#issuecomment-1749360338_

**Comment by hvlad** [comment]
duplicate of #7743

**Comment by mrotteveel** [comment]
In the future, please post issues in English.
