### ISSUE TITLE
Firebird 4.0.3 BLOB data truncated on restore of fb3.0.11 backup

### ISSUE THREAD

**Issue by StefanSchmaltz** [FirebirdSQL/firebird#7793]
currently we tried to convert a fb3.0.11 database to fb4.0.3. (Win64)
We did this:
- shutdown all processes that access this database
- backup fb3.0.11 database with gbak -B
- uninstall fb3.0.11
- install fb4.0.3
- restore database with gbak -R
- Start process
- result: **Many broken blob data records**
- no error output at all!

Then we tried same operations with fb4.0.2 - no data loss!

Looks like this is this bug: https://github.com/FirebirdSQL/firebird/issues/7772

**Comment by mrotteveel** [comment]
I think this is a duplicate, do you agree @hvlad?

**Comment by hvlad** [comment]
Seems duplicate, agree. To make sure, @StefanSchmaltz could check with current snapshot of 4.0.4

**Comment by StefanSchmaltz** [comment]
Yes, it's working well with 4.0.4.

**Comment by hvlad** [comment]
Duplicate of #7772

**Comment by hvlad** [comment]
Thank you for confirmation.
