### ISSUE TITLE
Update official Windows compiler to VS 17.7.4

### ISSUE THREAD

**Issue by asfernandes** [FirebirdSQL/firebird#7796]

**Comment by hvlad** [comment]
Current version is 17.7.5, released 10.10.2023

**Comment by hvlad** [comment]
Also, it is probably better to use ["Evergreen bootstrappers" that "always install the latest release"](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-history)

**Comment by dyemanov** [comment]
Shouldn't this ticket be closed now?
