### ISSUE TITLE
Allow foreing/unique key to use existing index

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7798]
Hi *!

Allowing FK/UK to use existing (non-expression) index could save creating an extra unique key/index on the same field.
FK + unique means 1-1 relation between the tables. Currently if you apply this schema you end up a duplicate and unnecessary index.

**Comment by dyemanov** [comment]
#7258 ?

**Comment by EPluribusUnum** [comment]
@dyemanov , yep, duplicate. Sorry.
