### ISSUE TITLE
Question about SYSDBA replacement weird approach

### ISSUE THREAD

**Issue by YordanYanakiev** [FirebirdSQL/firebird#7802]
Hello.
I wonder if a database is opened as a text file with some text editor ( like Notepad++), and SYSDBA is replaced as binary text with an string with the same length ( this part is working ) - will this generally change the SYSDBA or it is hidden somewhere else as well ?

**Comment by mrotteveel** [comment]
Please ask questions on [firebird-support](https://groups.google.com/g/firebird-support). The issue tracker is intended for reporting bugs and suggesting new features.
