### ISSUE TITLE
CURRENT_TIMESTAMP returns a diferent time than CURRENT_TIME...

### ISSUE THREAD

**Issue by adrianlmm** [FirebirdSQL/firebird#7806]
I'm testing 5.0.0 RC1 x64 in Windows 11 and CURRENT_TIMESTAMP returns a diferent value than CURRENT_TIME.

set bind of time with time zone to legacy;
select CURRENT_TIME, CURRENT_TIMESTAMP, LOCALTIME from RDB$DATABASE;

show this:

CURRENT_TIME	CURRENT_TIMESTAMP	      LOCALTIME
09:06:48.000	       16.10.2023, 16:06:48.620	     09:06:48.000

As you can see CURRENT_TIMESTAMP gives the time part wrong.

**Comment by asfernandes** [comment]
What's your time zone (show full result of CURRENT_TIMESTAMP)?

**Comment by adrianlmm** [comment]
In this attached image you can see the problem.
![firebird_time_zone](https://github.com/FirebirdSQL/firebird/assets/17146064/968e64a7-cc56-4808-b1e4-0df69bfa2713)

**Comment by asfernandes** [comment]
Please look if there is any related problem in firebird.log.
And run the same commands in ISQL and send the result.

**Comment by aafemt** [comment]
Because author of the ticket used binding to legacy only for time but not timestamp and his tool is unable to handle TZ types at all displaying only GMT part of them.

**Comment by AlexPeshkoff** [comment]
Yes, certainly.
But why text 'GMT*' is missing in the end? What configuration was used to not display timezone name at all?

**Comment by mrotteveel** [comment]
> Yes, certainly. But why text 'GMT*' is missing in the end? What configuration was used to not display timezone name at all?

Because they used `set bind of time with time zone to legacy;`, which means `CURRENT_TIME` is converted to `TIME WITHOUT TIME ZONE` and `CURRENT_TIMESTAMP` is converted to `TIMESTAMP WITHOUT TIME ZONE`, and GMT* is ISQL-side rendering for `WITH TIME ZONE` types if ICU is missing.

**Comment by mrotteveel** [comment]
Also, the tool used is FlameRobin, not ISQL, so it will not render GMT*.

**Comment by mrotteveel** [comment]
@adrianlmm is it also reproducable in ISQL? Maybe this problem is specific to FlameRobin, and not Firebird itself.

**Comment by aafemt** [comment]
> which means `CURRENT_TIME` is converted to `TIME WITHOUT TIME ZONE` and `CURRENT_TIMESTAMP` is converted to `TIMESTAMP WITHOUT TIME ZONE`

Are you sure that mapping for TIME also includes TIMESTAMP?

**Comment by arvanus** [comment]
Looks like something related to Flamerobin
[image: image.png]
America/Sao_Paulo is -03:00. Looks like Flamerobin is subtracting the
timezone again or something like that.

**Comment by arvanus** [comment]
Looks like something related to Flamerobin
![image](https://github.com/FirebirdSQL/firebird/assets/8182958/d268311a-78fa-4d63-b2a3-affd61f738c1)
America/Sao_Paulo is -03:00. Looks like Flamerobin is subtracting the timezone again or something like that.

**Comment by mrotteveel** [comment]
> > which means `CURRENT_TIME` is converted to `TIME WITHOUT TIME ZONE` and `CURRENT_TIMESTAMP` is converted to `TIMESTAMP WITHOUT TIME ZONE`
> 
> Are you sure that mapping for TIME also includes TIMESTAMP?

You're right, and that explains the difference between the values.

**Comment by mrotteveel** [comment]
It looks rather like FlameRobin is displaying the UTC-time.

**Comment by arvanus** [comment]
Any Firebird dev know if I can get the related timezone offset directly from the `XSQLVAR` (and how to retrieve this?)

https://github.com/mariuz/flamerobin/blob/e81c26cc9f21484a8c3f53ee72444abc9edea989/src/ibpp/row.cpp#L1462-L1463
![image](https://github.com/FirebirdSQL/firebird/assets/8182958/5e000e34-6abf-41a1-803a-d29bd6dd4a40)

Today Flamerobin extracts from `sqldata` an `ISC_TIMESTAMP_TZ` with time/timestamp and the timezone as an ISC_SHORT.
I'm seeing here that Fr has declared an `ISC_TIMESTAMP_TZ_EX` but I tried to use and the `ext_offset` comes zeroed

**Comment by mrotteveel** [comment]
`ISC_TIMESTAMP_TZ_EX` only applies when you bind to `EXTENDED` with [`SET BIND`](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-management-setbind).

**Comment by mrotteveel** [comment]
For a normal `TIMESTAMP WITH TIME ZONE`, it encodes either an offset **or** the time zone id, with the extended variant, it will encode the offset or time zone id followed by the offset (in the case of an offset value, this means it encoded the offset twice).

**Comment by mrotteveel** [comment]
That said, I think this is a question which should be asked on [firebird-devel](https://groups.google.com/g/firebird-devel).

**Comment by asfernandes** [comment]
> `ISC_TIMESTAMP_TZ_EX` only applies when you bind to `EXTENDED` with [`SET BIND`](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-management-setbind).

Actually, types are used as the code accessing the Firebird library wants. This is the authority, not `SET BIND`.

If `ISC_TIMESTAMP_TZ_EX` is easier for an access component, so use it (assuming the library is written knowing its existence). Just change the type after describe.

**Comment by mrotteveel** [comment]
> Actually, types are used as the code accessing the Firebird library wants. This is the authority, not `SET BIND`.

But you won't have the "extended" information in it, so no offset.

**Comment by AlexPeshkoff** [comment]
On 10/18/23 10:52, Mark Rotteveel wrote:
>
>     Actually, types are used as the code accessing the Firebird
>     library wants. This is the authority, not |SET BIND|.
>
> But you won't have the "extended" information in it, so no offset.
>

Mark, _normally_ offset is calculated by client using ICU by TZ code. 
Extended is needed when people do not have ICU on client and have 
absolutely no desire/ability to install it there. The exact sign of such 
behavior (missing ICU) is TZ named 'GMT*'. I've already lost myseif in 
this thread - how does isql work on problematic system?

**Comment by mrotteveel** [comment]
> Mark, _normally_ offset is calculated by client using ICU by TZ code. Extended is needed when people do not have ICU on client and have absolutely no desire/ability to install it there. The exact sign of such behavior (missing ICU) is TZ named 'GMT*'. I've already lost myseif in this thread - how does isql work on problematic system?

The OP is not using ISQL, they are using FlameRobin.

**Comment by AlexPeshkoff** [comment]
@adrianlmm Can you try with isql - what timestamp text will you get?

**Comment by mrotteveel** [comment]
@AlexPeshkoff We've already established this is a display problem in FlameRobin (it is showing the UTC time for WITH TIME ZONE types), not a Firebird problem. There is no need for further analysis on our side.

**Comment by AlexPeshkoff** [comment]
On 10/18/23 11:53, Mark Rotteveel wrote:
>
> We've already established this is a display problem in FlameRobin (it 
> is showing the UTC time for WITH TIME ZONE types), not a Firebird 
> problem. There is no need for further analysis on our side.
>

Sorry - I've said that I'm a bit lost in this thread :-)

**Comment by mrotteveel** [comment]
> Of course it will. `SET BIND` is just about what describe API will do. Definitive type is what is specified after it and may be changed in code.

Not if you _only_ use the struct `ISC_TIMESTAMP_TZ_EX`, you will also need to request the type `SQL_TIMESTAMP_TZ_EX` in the SQLDA (to be clear, I haven't checked what FlameRobin is actually doing).

**Comment by adrianlmm** [comment]
> mrotteveel

here it is.
![isql_timezone](https://github.com/FirebirdSQL/firebird/assets/17146064/c2300bf7-e68a-4896-8cbc-9f57382ddb45)
