### ISSUE TITLE
Crash "Fatal lock manager error: Process disappeared in LockManager::acquire_shmem"

### ISSUE THREAD

**Issue by gerdus** [FirebirdSQL/firebird#7809]
Log message:
`Wed Oct 18 07:54:39 2023 Fatal lock manager error: Process disappeared in LockManager::acquire_shmem, errno: 22 --Invalid argument`

Core dump: https://infireal.com/github-issues/firebird-crash-2023-10-18/

version is V4.0.4.2997 snapshot binaries from firebird website
OS: Ubuntu 22.04.3 LTS

**Comment by AlexPeshkoff** [comment]
@gerdus Have you seen https://github.com/FirebirdSQL/firebird/issues/7762#issuecomment-1768836573 ?

**Comment by gerdus** [comment]
Sorry, did not realize there was not snapshot archive on the website to get a specific snapshot build.

Bin: [https://infireal.com/github-issues/firebird-crash-2023-10-18/Firebird-4.0.4.2997-0.amd64.tar.gz](https://infireal.com/github-issues/firebird-crash-2023-10-18/Firebird-4.0.4.2997-0.amd64.tar.gz)
Debuginfo:  [https://infireal.com/github-issues/firebird-crash-2023-10-18/Firebird-debuginfo-4.0.4.2997-0.amd64.tar.gz](https://infireal.com/github-issues/firebird-crash-2023-10-18/Firebird-debuginfo-4.0.4.2997-0.amd64.tar.gz)

**Comment by AlexPeshkoff** [comment]
I see what caused an error - but no ideas why it happened. If you get 
any more cores with same error - may be they can help.

**Comment by gerdus** [comment]
New crash this morning with same log message

```
Fri Oct 27 11:40:03 2023 Fatal lock manager error: Process disappeared in LockManager::acquire_shmem, errno: 0
Fri Oct 27 11:41:42 2023 /opt/firebird/bin/fbguard: /opt/firebird/bin/firebird terminated abnormally (-1)
Fri Oct 27 11:41:42 2023 /opt/firebird/bin/fbguard: guardian starting /opt/firebird/bin/firebird
```

Core Dump: [https://infireal.com/github-issues/firebird-crash-2023-10-27/](https://infireal.com/github-issues/firebird-crash-2023-10-27/)

**Comment by AlexPeshkoff** [comment]
Gerdus, please try special build https://drive.google.com/drive/folders/1sRlWtC2fYsPtL-Gzq0x6HpPj53ciuN6H?usp=sharing
That's exactly snapshot you are using currently + fix for this bug. Suppose it should help but certainly I need your feedback.

**Comment by gerdus** [comment]
Ok I have deployed your build. Will monitor and let you know result.
Thank you.

**Comment by gerdus** [comment]
It has been two weeks without a crash, so I think you can close this as resolved. Thank you very much.

**Comment by fperana** [comment]
@AlexPeshkoff in your opinion, could it be that this issue and issue #7762 would be related to my issues #7371 and #7530? I'm still running your patched 4.0.2 version (no time to install 4.0.3), but it still crashes now and then.
I'm now thinking of upgrading to 4.0.4, but this issue makes me wonder if it's better to try the latest fix you've posted here.

**Comment by AlexPeshkoff** [comment]
Very possible. When we deal with races-related bugs it's often a matter of lucky chance that caught core dump contains useful information. @gerdus succeeded to get useful dump with which reasons got clear and fix became possible. I'm sure that all issues are races-related - in other case it's much simpler to reproduce and fix them. But certainly nobody can guarantee that there no other races around.

**Comment by AlexPeshkoff** [comment]
I doubt a fix of single problem which is not regression in 404 is enough reason for 405 release.

**Comment by fperana** [comment]
Just another question, does this build contain fix for #7772?

**Comment by AlexPeshkoff** [comment]
No - it was split 2 days before fix for 7772. But I hope very soon you will have snapshot with both.

**Comment by fperana** [comment]
@AlexPeshkoff so I'll wait for that snapshot (how can I tell when it's ready? or will you prepare it for me? best would be a 4.0.4 release + fix).

@TommiPrami we're talking of a special build with a fix for the subject of this thread.

**Comment by AlexPeshkoff** [comment]
Snapshot should be ready tomorrow: I've merged fix into release branch. Just make sure it's fresh (current date) and also I recommend to check http://firebirdtest.com/ how did it pass regular QA. Pay attention - that's exactly same QA which is used for releases.
