### ISSUE TITLE
Improve SKIP LOCKED implementation

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#7810]
Make SKIP LOCKED works in all transaction isolation levels, including RC NRV
Avoid preliminary lock for UPDATE and DELETE statements 

More details at thread "SKIP LOCKED problems" in fb-devel
https://groups.google.com/g/firebird-devel/c/BIbAz_YJMFw

**Comment by hvlad** [comment]
The fix #7811 introduced bug in DELETE RETURNING handling - calculated fields now returned as NULL's.
Thus some additional work is required.
Also, documentation should be updated.
Re-opened to fix these issues.

**Comment by pavel-zotov** [comment]
QA note.
Test checks only UPDATE and DELETE behavior.
Ability to run 'SELECT ... WITH LOCK' is checked in gh_7350_test.py
