### ISSUE TITLE
execute statement on external connection always using superserver mode on classic mode

### ISSUE THREAD

**Issue by myilmaznetsim** [FirebirdSQL/firebird#7813]
test case,
configure server to classic mode

create 2 empty database c:\test.fdb and c:\test1.fdb
isql c:\test.fdb

set term ^ ;
EXECUTE BLOCK
RETURNS
(
  REMOTE_PID VARCHAR(10),
  LOCAL_PID VARCHAR(10)
)
AS
BEGIN
  EXECUTE STATEMENT 'SELECT MON$SERVER_PID FROM MON$ATTACHMENTS WHERE MON$ATTACHMENT_ID = CURRENT_CONNECTION'
            AS USER 'SYSDBA' PASSWORD 'masterkey'
            ON EXTERNAL DATA SOURCE 'C:\TEST1.FDB'
     INTO :REMOTE_PID;

  SELECT MON$SERVER_PID FROM MON$ATTACHMENTS WHERE MON$ATTACHMENT_ID = CURRENT_CONNECTION
    INTO :LOCAL_PID;

  SUSPEND;
END ^

/*
REMOTE_PID LOCAL_PID
========== ==========
24928      24928
*/
PIDs must diffirent but not
tested only windows WI-V4.0.3.2974

**Comment by aafemt** [comment]
What makes you think that PID must be different? Classic/super modes is about handling remote connections only. Internal connections always use the same engine instance.

**Comment by dyemanov** [comment]
It uses the embedded mode. If you want running as a Classic, please specify localhost in your connection string.
