### ISSUE TITLE
Extend rdb$get_context('SYSTEM', '***') with other info from MON$ATTACHMENT

### ISSUE THREAD

**Issue by arvanus** [FirebirdSQL/firebird#7818]
Hi, currently SYSTEM context already returns tons of useful data for audit, like
CLIENT_PROCESS, CLIENT_ADDRESS, CLIENT_HOST and CLIENT_PID. Is it possible to also add CLIENT_VERSION and REMOTE_OS_USER (like from mon$attachments)?

Note: I know I can add a USER_SESSION variable with this data at an connect DDL trigger, but this way the user could change it latter.
Also if possible and done, could this change also be available at Fb 4?
Thanks!

**Comment by mrotteveel** [comment]
Although I'm in favor of this, I wonder why you can't just query it from `MON$ATTACHMENT`. Also, for your information, `CLIENT_PROCESS`, `CLIENT_PID`, `CLIENT_VERSION` and `REMOTE_OS_USER` can all be controlled by the user if they really want to. For example, when using Jaybird, the user can set the process and PID themselves, and the `CLIENT_VERSION` and `REMOTE_OS_USER` could be changed by creating a customised version of the driver.

**Comment by arvanus** [comment]
> I wonder why you can't just query it from `MON$ATTACHMENTS`

Basically performance related, as I get this info for each inset/update/delete operation, always reading from MON$ stores a large snapshot that I simply wont use, and every CPU cycle released is a win.

Obviously I can store this info on connect DDL trigger, but as I already have almost every SYSTEM var that I need, I think it could make the process cleaner to get everything from the same place.


Thanks!

**Comment by arvanus** [comment]
I would love to try to implement a path for this issue, it would be my first contribution in the code :) 
If you agree I'll take a look at the code, looks like I need to change at src/jrd/SysFunction.cpp uniquely (and somewhere in the docs)
Also if it's OK I will keep the names as `CLIENT_VERSION` and `REMOTE_OS_USER`

**Comment by hvlad** [comment]
Added two new context variables: `CLIENT_OS_USER` and `CLIENT_VERSION`.
Note, historically context variables uses prefix `CLIENT_` while `MON$ATTACHMENTS` uses prefix `MON$REMOTE_` for the same data items.

**Comment by hvlad** [comment]
> I would love to try to implement a path for this issue, it would be my first contribution in the code :) If you agree I'll take a look at the code, looks like I need to change at src/jrd/SysFunction.cpp uniquely (and somewhere in the docs) 

We going to freeze 4.0.4 branch in next few days, therefore I decided to act quickly :)
If you want to create some another patch - you are welcome!

> Also if it's OK I will keep the names as `CLIENT_VERSION` and `REMOTE_OS_USER`

Explained above.

**Comment by arvanus** [comment]
> We going to freeze 4.0.4 branch in next few days, therefore I decided to act quickly :)
> If you want to create some another patch - you are welcome!

Thank you!

**Comment by arvanus** [comment]
For feedback, tested and is working!
Thanks
