### ISSUE TITLE
Difficulty returning the product version with the legacy connection

### ISSUE THREAD

**Issue by MarceloZaniboni** [FirebirdSQL/firebird#7819]
I am having difficulties with the Firebird 5.0 Release Candidate 1 version. The same did not happen in the Firebird 5.0 Beta 1 version, regarding version changes in legacy applications developed in Delphi Tokyo using the DBExpress (TSQLConnection) component.
Test with the latest snapshot version available, the problem still persists.
Next, send a test application for analysis if possible.
And two images, one with the problem in the latest version of Release Candidate 1 available and another with the result of beta version 1.
Thank you very much in advance.
Thanks,
Marcelo Zaniboni

![FB5 0 0 1258-0-RC1](https://github.com/FirebirdSQL/firebird/assets/149497214/928cd3d6-e74d-465c-9c75-dfc4e3ffa46f)

![FB5 0 0 973-BETA1](https://github.com/FirebirdSQL/firebird/assets/149497214/bbc4662f-1800-41fe-86b8-02c3559f4b04)

[TestLegancyCnxFB50.zip](https://github.com/FirebirdSQL/firebird/files/13216772/TestLegancyCnxFB50.zip)

**Comment by hvlad** [comment]
The DBX driver call `isc_database_info()` and asks for `isc_info_isc_version` info item. 
It provides output buffer of 40 bytes length.
The info requested is 49 bytes length and can't fit the buffer passed by client.
Thus Firebird answers with `isc_info_truncated`.
Then app throws AV. 

The Firebird answer is `WI-5.0.0.1227 Firebird 5.0 Release Candidate 1`
Before RC1 it was `WI-5.0.0.973 Firebird 5.0 Beta 1` and fits into 40-byte buffer.
After release it will be shorter again.

The guess is that driver can't correctly handle `isc_info_truncated` or crashes when tries to extract some version number from this info-string and can't find some known pattern in it.

We can make version string shorter or truncate it according to the client buffer size but I not sure we should do it.

**Comment by dyemanov** [comment]
We never did that in prior versions and nobody complained so far, while we supposedly have some DBX users. Weird ;-)

**Comment by hvlad** [comment]
From another POV - DBX users are unable to test RC, which also not good.

**Comment by AlexPeshkoff** [comment]
The simplest is change 'Release Candidate' => 'RC' .

**Comment by AlexPeshkoff** [comment]
In RC2

**Comment by aafemt** [comment]
> From another POV - DBX users are unable to test RC, which also not good.

They are able to test DBX and found an obvious bug in it. Now the ball is on Embarcadero side.

**Comment by MarceloZaniboni** [comment]
> > From another POV - DBX users are unable to test RC, which also not good.
> 
> They are able to test DBX and found an obvious bug in it. Now the ball is on Embarcadero side (or whoever is the author of the driver).

The problem is that DBXExpress is a discontinued drive. That's why I said it's a legacy application.

**Comment by aafemt** [comment]
It means that you must fix the application, that's all. Not a Firebird issue.

**Comment by MarceloZaniboni** [comment]
> It means that you must fix the application, that's all. Not a Firebird issue.

As it is a legacy application, it is not possible to change everything at once, this is already being modified gradually by the team. But as there is a lagado configuration in Firebird, I understand that it could work, as it worked in the beta version. But that's just my point of view.

**Comment by AlexPeshkoff** [comment]
Marcelo, your application is unable to handle version information string that is a bit longer than one in beta version - yep, strlen("release candidate") > strlen("beta"). :-) Pay attention that length of version string in _LEGACY_ API is limited somewhere around 255 bytes (a bit smaller - but one returned to your app is definitely MUCH shorter). I.e. your application violates _legacy_ rules. That's why it does not work.

**Comment by hvlad** [comment]
@AlexPeshkoff, it is not an applicaiton bug, it is DBX driver problem. 
AFAIU, DBX is closed source and can't be fixed easily. 

The first question is should we change something on our side or recommend @MarceloZaniboni to wait for final release of Firebird 5 ?

**Comment by AlexPeshkoff** [comment]
On 11/1/23 16:24, Vlad Khorsun wrote:
>
> @AlexPeshkoff <https://github.com/AlexPeshkoff>, it is not an 
> applicaiton bug, it is DBX driver problem.
> AFAIU, DBX is closed source and can't be fixed easily.
>

I understand it - but as long as app was built using DBX it becomes app 
problem.

> The first question is should we change something on our side or 
> recommend @MarceloZaniboni <https://github.com/MarceloZaniboni> to 
> wait for final release of Firebird 5 ?
>

As I've already replied - the simplest solution is to call 'release 
candidate 2' RC2. Overflow will be avoided - and this should not harm 
others.

**Comment by aafemt** [comment]
> it is DBX driver problem. AFAIU, DBX is closed source and can't be fixed easily.

  Perhaps, they should try DBX driver by Devart: https://www.devart.com/dbx/interbase/

**Comment by hvlad** [comment]
> As I've already replied - the simplest solution is to call 'release candidate 2' RC2

Ok, if there will be no objections, I'll commit it tomorrow.

**Comment by hvlad** [comment]
Check next snapshot build, please

**Comment by MarceloZaniboni** [comment]
> Check next snapshot build, please

Thank you very much, resolved!
