### ISSUE TITLE
5.0.0.0-RC1 Native Error Exception 335545170  Macos SONOMA 14.1

### ISSUE THREAD

**Issue by greyns** [FirebirdSQL/firebird#7822]
Error opening international conversion descriptor from  to UTF-8
Invalid argument

Only with Macos 14.1 Sonoma, works fine with previous release
Don't know if it is coming from Firedac/Delphi or from Firebird

**Comment by AlexPeshkoff** [comment]
What version of FB are you using?

**Comment by greyns** [comment]
Answer from Embarcadero : 

Re: Error FireDac + MacOS 14.1 Sonoma + Firebird 5 RC1

Sync status from internal system, internal issue closed on Nov 10, 2023 by Dmitry Arefiev with comment:
The issue must be fixed on Firebird side.

**Comment by dyemanov** [comment]
@AlexPeshkoff The docs says that "" (empty string) can be passed (instead of "char") to `iconv_open` to represent the current system locale. But we pass NULL instead (const char* const `IConv::SYSTEM = NULL`). Could it be the reason?

**Comment by AlexPeshkoff** [comment]
If empty string can be used as system encoding charmapName() becomes pretty useless. But...
@dyemanov Linux'es man iconv_open says nothing about use of empty string for system encoding. Can you proof-link that?
PPS. I think that should be some very serious link - in man I can read that 'The values permitted for fromcode and tocode and the supported combinations are system-dependent'. I.e. I'm afraid that some libc can reject to support empty string here.

**Comment by aafemt** [comment]
http://git.savannah.gnu.org/cgit/libiconv.git/tree/lib/iconv_open1.h#n89

**Comment by AlexPeshkoff** [comment]
The feature is documented for oracle linux & mac os.
https://docs.oracle.com/cd/E86824_01/html/E54766/iconv-open-3c.html
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/iconv_open.3.html

If changing 
const char* const IConv::SYSTEM = NULL;
to
const char* const IConv::SYSTEM = "";
helps - I see no problems with such a fix.

But first of all I suggest to@greyns to try from command line:
echo QQ|iconv -f UTF8 -t cp1251
echo QQ|iconv -f UTF8 -t UTF8
and see what happens.

**Comment by greyns** [comment]
I've tried and it seems to do...nothing :
echo QQ|iconv -f UTF8 -t cp1251
QQ
echo QQ|iconv -f UTF8 -t UTF8
QQ

I can test what you want. I have a Macbook with MacOS13.6.1 and a Mac Mini
with MacOS 14.1.1
My softwares are installed on both the same way, with the same releases of
Firebird.
On MacOS 13.6.1 : no problem
On MacOS 14.1.1 : Exception message = [FireDAC][Phys][FB]Error opening
international conversion descriptor from  to UTF-8 Invalid argument

**Comment by AlexPeshkoff** [comment]
I did not expect that commands to change input text - just wanted to make sure they do not fail.

Please also try:
echo QQ|iconv -f UTF8 -t UTF-8 
(I see exactly this in your error message).

Next - did you try to attach to same datasource as one used in Firedac/Delphi using our isql?

**Comment by greyns** [comment]
echo QQ|iconv -f UTF8 -t UTF-8
QQ

I'm not used with ISQ (nor command line, coming from Windows ! Sorry).
What do you want me to try ?

**Comment by AlexPeshkoff** [comment]
isql -user NAME -pas PASSWORD HOST:DBPATH
subst words in CAPITAL with your actual values

**Comment by greyns** [comment]
It works, no error...

Le jeu. 23 nov. 2023, 11:31, Alexander Peshkov ***@***.***> a
écrit :

**Comment by aafemt** [comment]
Try to call setlocale() at the start of your application.

**Comment by greyns** [comment]
I'm going to try...
Actually I have that on both Mac :
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL=

**Comment by aafemt** [comment]
You must be aware that on *NIX-based systems these locale settings are not applied to processes automatically but requires an explicit call of setlocale().

**Comment by greyns** [comment]
I'm trying to execute from my app :
  _system(PAnsiChar('setlocale(LC_ALL, "fr_FR.UTF-8")')
but it is not working because LC_ALL is not recognized by the system.

So I tried :
{$IFDEF MACOS}
  _system(PAnsiChar('export LC_ALL="fr_FR.UTF-8"'));
 {$ENDIF MACOS}
It works but I still can't connect to database.

**Comment by greyns** [comment]
I saw that, this valid from C++, not from Delphi/Pascal

**Comment by aafemt** [comment]
Delphi can call C functions without problems. Perhaps setlocale() is declared in Posix.Locale unit?..

**Comment by greyns** [comment]
Congratulations guys ! Now it works...

I have added in uses clause :
  {$IFDEF MACOS}
  , Posix.Stdlib, Posix.Locale
  {$ENDIF MACOS}

and in the OnCreate of main form :
  {$IFDEF MACOS}
  setlocale(LC_ALL, PAnsiChar('fr_FR.UTF-8'));
  {$ENDIF MACOS}

Your support is more efficient than Embarcadero's one... Don't know if it
is on Apple or Embarcadero's side that the problem appears but it is solved
with your help.
Thanks.
