### ISSUE TITLE
Difficulty in returning users

### ISSUE THREAD

**Issue by MarceloZaniboni** [FirebirdSQL/firebird#7834]
I'm having difficulties with Firebird version 5.0.0.1261-0-RC2. The same did not happen in the Firebird 5.0.0.973-BETA1 version, regarding the version change in legacy applications developed in Delphi Tokyo that are gradually being migrated to FireDac components.

firebird.conf configuration:

AuthServer = Legacy_Auth, Srp, Win_Sspi

AuthClient = Legacy_Auth, Srp, Win_Sspi

UserManager = Legacy_UserManager

DataTypeCompatibility = 2.5

WireCrypt = Disabled

TFDIBSecurity component, method “FDIBSecurity.DisplayUsers;”
Next, send a test application for analysis if possible.
And two images, one with the problem in the latest version of the Release Candidate available and the other with the result of the beta 1 version.
Thank you very much in advance.

![FB5 0 0 1261-0-RC2](https://github.com/FirebirdSQL/firebird/assets/149497214/f5029071-0d96-461c-a6d0-c9a1b93ae4c5)

![FB5 0 0 973-BETA1](https://github.com/FirebirdSQL/firebird/assets/149497214/3007bf27-202d-437c-998b-ac8d1e72a681)

[TestFDIBSecurityDisplayUsers.zip](https://github.com/FirebirdSQL/firebird/files/13299562/TestFDIBSecurityDisplayUsers.zip)

**Comment by aafemt** [comment]
During upgrade you replaced existing security database with uninitialized one. Not a Firebird issue. Read the documentation mentioned in error text.

**Comment by MarceloZaniboni** [comment]
> During upgrade you replaced existing security database with uninitialized one. Not a Firebird issue. Read the documentation mentioned in error text.

I understand, yes, it is being replaced, for the reason that the default database users are configured. I will modify, to create after installation and test again.

**Comment by MarceloZaniboni** [comment]
That was it resolved. Thanks.
