### ISSUE TITLE
ISQL show table extract collation wrongly

### ISSUE THREAD

**Issue by livius2** [FirebirdSQL/firebird#7837]
During working with issue in flamerobin 
https://github.com/mariuz/flamerobin/issues/348

we found that ISQL also extract metadata of column collations wrongly.

```
SET SQL DIALECT 3;
CREATE DATABASE 'localhost:d:\WIN1250.FDB' PAGE_SIZE 16384 DEFAULT CHARACTER SET WIN1250; 
```

now alter default collation
```
ALTER CHARACTER SET WIN1250 SET DEFAULT COLLATION PXW_PLK;
```

```
CREATE TABLE TEST_CCC
(
A VARCHAR(100) COLLATE PXW_PLK,
B VARCHAR(100) COLLATE WIN1250,
C VARCHAR(100)
);
```

no collation info only character set...

```
SQL> show table TEST_CCC;
A                               VARCHAR(100) CHARACTER SET WIN1250 Nullable
B                               VARCHAR(100) Nullable
C                               VARCHAR(100) CHARACTER SET WIN1250 Nullable
```

but run sql:

```
SELECT
    RF.RDB$RELATION_NAME
    , RF.RDB$FIELD_NAME
    , F.RDB$COLLATION_ID
    , C.RDB$COLLATION_NAME
FROM
    RDB$RELATION_FIELDS RF
    INNER JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE
    INNER JOIN RDB$COLLATIONS C ON F.RDB$COLLATION_ID=C.RDB$COLLATION_ID AND F.RDB$CHARACTER_SET_ID=C.RDB$CHARACTER_SET_ID
WHERE
    RF.RDB$RELATION_NAME IN('TEST_CCC')
```

![image](https://github.com/FirebirdSQL/firebird/assets/14888294/d243de9e-728b-4fa1-bd71-e84b6b3737e4)

**Comment by aafemt** [comment]
Already fixed in master branch.

**Comment by livius2** [comment]
I have used latest snapshot Firebird-5.0.0.1264-0-RC2-windows-x64-withDebugSymbols.zip

**Comment by aafemt** [comment]
The master branch is 6.0.

**Comment by livius2** [comment]
Ah missed that 6 was turned on, long was 5 ;-)
But i suppose it should be backported to 4 and 5 too.

**Comment by aafemt** [comment]
This bug was born in 2.5 and lived unnoticed for so long that now it deserves some reservation.

**Comment by dyemanov** [comment]
I don't think it's important enough to be backported.
