### ISSUE TITLE
Add option to gbak  -noDdlTriggers like there is currently -nodbtriggers

### ISSUE THREAD

**Issue by livius2** [FirebirdSQL/firebird#7838]
I see that if someone do error in DDL trigger it can make metadata unchangeable.
Same as an error in DB triggers.

```
CREATE exception EBAD_DDL_TRIGGER 'BAD_DDL_TRIGGER';

SET TERM ^ ;
CREATE TRIGGER BAD_DDL_TRIGGER BEFORE ANY DDL STATEMENT
AS
BEGIN
  EXCEPTION EBAD_DDL_TRIGGER;
END^
SET TERM ; ^
```

now you cannot change any metadata and deactivation of this trigger is also not possible

```
ALTER TRIGGER BAD_DDL_TRIGGER INACTIVE;
``` 

Will be good to have option `gbak  -noDdlTriggers` like we have currently `-nodbtriggers`

**Comment by hvlad** [comment]
Hmm... do you mean isql ? Or gbak (why?) ? Or both ? ;)

**Comment by livius2** [comment]
`nodbtriggers` is currently in both i suppose this one should follow :)

**Comment by aafemt** [comment]
Aren't DDL triggers database triggers? -nodbtriggers should affect them as well IMHO.

**Comment by arvanus** [comment]
So... as we are talking about nodbtriggers/noddltriggers, what about the possibility to add noddltriggers too? Yes, this is controversial but sometimes I need to do some bulk changes and I need to shutdown the base, disable all triggers, run some critical updates and reactive the triggers and set db online. Having the possibility to disable the triggers only for one connection is very useful(and catastrophic if the user doesn't know what is doing)

**Comment by hvlad** [comment]
> Aren't DDL triggers database triggers? -nodbtriggers should affect them as well IMHO.

Sure. DDL triggers are Database triggers and  -nodbtriggers disables its as well.

**Comment by asfernandes** [comment]
It's documented in [README](https://github.com/FirebirdSQL/firebird/blob/master/doc/sql.extensions/README.ddl_triggers.txt#L100)

```
Utilities support:
	DDL triggers is a type of database triggers, so the parameters -nodbtriggers (GBAK and ISQL)
	and -T (NBACKUP) also works for them.
	These parameters could only be used by database owner and SYSDBA.
```

@livius2 do you have a problem to use it?
