### ISSUE TITLE
DEFAULT value handling bug

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#7856]
Hi *!

CREATE TABLE X (
    ID  INTEGER not null
);
COMMIT;
INSERT INTO x(id) VALUES (1);
COMMIT;
ALTER TABLE X ADD D INTEGER DEFAULT -1 NOT NULL
COMMIT;
SELECT * FROM x -- 1, -1 - OK
COMMIT;
ALTER TABLE X ALTER COLUMN D SET DEFAULT 0
COMMIT;
SELECT * FROM x -- 1, -1 This is unexpected. It should be 1, 0

3.0.11, 4.0.4 and 5.0.0RC2

**Comment by aafemt** [comment]
Can you quote from standard or other authoritative source why it should be 1,0? Changing default source cannot change already stored values.

**Comment by EPluribusUnum** [comment]
@aafemt  the insert was before addign D column. -1 was never stored.

**Comment by EPluribusUnum** [comment]
Adding a column with a default value does not updates the records in the table.

**Comment by asfernandes** [comment]
That was a bug in the past and it was fixed.
The current behavior is correct.
When DEFAULT of NOT NULL column is set, it's likely existing record is updated.

**Comment by EPluribusUnum** [comment]
@asfernandes , then the missing/wrong update is the bug. No UPDATE triggers fired and no check errors when you commit the ADD with DEFAULT command.

**Comment by asfernandes** [comment]
It should not trigger row level triggers. It's done at metadata level.
It was discussed and agreed, others RDBMS had similar behavior.

**Comment by EPluribusUnum** [comment]
@asfernandes , OK, thank you.

**Comment by dyemanov** [comment]
The fact that adding a column does not update the already stored data is a feature (unique, I guess) of Firebird. But this is just an implementation detail which is hidden under the hood. The data should look like the new column was actually populated with the default value.

**Comment by asfernandes** [comment]
AFAIK Oracle does the same thing but not documented how.
