### ISSUE TITLE
Dateadd to timestamp generated by dateadd and rand in subselect

### ISSUE THREAD

**Issue by atiris** [FirebirdSQL/firebird#7866]
Can someone check this on latest version? _(I can't because of restrictions at work where we have firebird installed.)_

```sql
select a.tsactual, dateadd (minute, 10, a.tsactual) tsactualplus10
     , a.tsmodified, dateadd (minute, 10, a.tsmodified) tsmodifiedplus10
     , a.tsrand, dateadd (minute, 10, a.tsrand) tsrandplus10
  from (select current_timestamp tsactual
             , dateadd (minute, 60, current_timestamp) tsmodified
             , dateadd (minute, 60 * RAND(), current_timestamp) tsrand
          from rdb$database) a;
```

Sample result in my case is `2023-11-21 12:33:27.045` for `tsrand` and `2023-11-21 13:13:27.045` for `tsrandplus10`.

Everything works except `tsrandplus10`. It looks like when `tsrandplus10` is calculated, `RAND()` is called again and value `tsrand` from subselect is not used.

_Version: Debian 5.10.197-1 (2023-09-29) x86_64 Firebird TCP/IP server version LI-V3.0.7.33374 Firebird 3.0_

**Comment by mrotteveel** [comment]
The issue tracker is not intended for support questions. If you intend to report a bug, please describe clearly what you think the bug is, otherwise, ask on https://groups.google.com/g/firebird-support.

**Comment by atiris** [comment]
Ok, and I thought the error was described very clearly from the title and also with the help of an example...  
Well, okay, what if i reformat my report like this:

**Bug:** Dateadd applied to timestamp created by random dateadd in subselect is not correct.  
**Replication:**
```sql
select datediff (minute from tsrand to tsrandplus10) diffminutes
  from (select a.tsrand, dateadd (minute, 10, a.tsrand) tsrandplus10
          from (select dateadd (minute, 24 * 60 * RAND(), current_timestamp) tsrand
                  from rdb$database) a
       ) b;
```
**Expectation:** Diffminutes should be always 10.
**Observation:** It returns random values mostly from range -1000 - +1000.
**Database version:** Firebird TCP/IP server version LI-V3.0.7.33374 Firebird 3.0

_The only thing I wanted to add (if you're calling it support) is if someone could test it on the latest version as well, since I can't install latest version at work. However, this does not change the fact that select does not behave as I would expect._

**Comment by aafemt** [comment]
Expressions from derived tables are expected to be re-evaluated every time they used. IMHO, it is not a bug.

**Comment by atiris** [comment]
Ok, thank you.

**Comment by mrotteveel** [comment]
> Expressions from derived tables are expected to be re-evaluated every time they used. IMHO, it is not a bug.

I do think this behaviour is a bug: it should be reevaluated for each row, but when the column from the same row is referenced multiple times, IMHO it should produce a stable value.

**Comment by atiris** [comment]
Thanks for the explanation. This was totally counterintuitive to me too, but if that's how it's intended, then ok. While there is such a case where the rand value can be fixed. Here are the examples I tried:

**Values x and y are different / random**

```sql
select randval x, randval y
  from (select rand() randval from rdb$database) a
```

```sql
with a as (select rand() randval from rdb$database)
select randval x, randval y from a
```

**Values x and y are identical** (as expected according to comment from @aafemt)

```sql
select randval x, randval y
  from (select (select rand() randval from rdb$database) randval from rdb$database) a
```

From my point of view, the difference between the first and the last option was only at the level of "optimization", but thank you very much for the explanation, I will be more careful with the placement of such functions.

**Comment by atiris** [comment]
Also, to make this topic complete for anyone who needs to solve random numbers like me.  
In case of select rand number for multiple rows like this:

```sql
select a.id
     , (select RAND() from rdb$database) val
  from (select 1 id from rdb$database union all select 2 id from rdb$database) a
```

**All lines will have the same "random" number.**  
At the moment, I still don't know how to generate a random number for individual rows, while it will remain fixed during the next selection into multiple columns. Now I can get only four identical numbers, or four different numbers, but my goal is to set a "fixed" random number per line.

```sql
select b.id
     , b.val x
     , b.val y
  from (
select a.id
     , (select RAND() from rdb$database) val -- four identical numbers in two lines
     -- , RAND() val -- four random numbers even in the same line
  from (select 1 id from rdb$database union all select 2 id from rdb$database) a
       ) b
```

**Comment by atiris** [comment]
Ok, I got it,  
this will generate random numbers for individual rows, while the rest are fixed even when selecting into multiple columns.

```sql
select c.id
     , c.val x
     , c.val y
  from (
select b.id
     , (select b.val from rdb$database) val
  from (
select a.id
     , rand() val
  from (select 1 id from rdb$database union all select 2 id from rdb$database) a
       ) b
       ) c
```
