### ISSUE TITLE
Error "wrong page type" during garbage collection on v4.0.4

### ISSUE THREAD

**Issue by vcrits** [FirebirdSQL/firebird#7867]
After upgrading firebird from v4.0.3 to v4.0.4 a strange error message appears on the replica site, even though the database is not corrupt. The error message always comes after importing the log journal files.

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-88-generic x86_64) Firebird-4.0.4.3022-0.amd64 (asynchronous mode)

dbserver	Tue Nov 21 12:57:34 2023
	Database: /database/xxx_replica.fdb
	database file appears corrupt (/database/xxx_replica.fdb)
	wrong page type
	page 0 is of wrong type (expected data, found database header)

dbserver	Tue Nov 21 13:00:30 2023
	Database: /database/xxx_replica.fdb
	Validation started

dbserver	Tue Nov 21 13:03:25 2023
	Database: /database/xxx_replica.fdb
	Validation finished: 0 errors, 0 warnings, 0 fixed

**Comment by hvlad** [comment]
Reproducible test case could help to fix the issue

**Comment by dyemanov** [comment]
Please try the today's snapshot (build 3025):
https://web.firebirdsql.org/downloads/snapshot_builds/linux/fb4.0/

and report back whether the issue still persists.

**Comment by vcrits** [comment]
Thank you all,
v4.0.5.3025 runs without errors, the ticket can be closed.

**Comment by vcrits** [comment]
completed

**Comment by dyemanov** [comment]
Just in case someone else runs into this issue, it does not seem being related to replica only, it may theoretically appear on the primary (or without replication at all) too.
