### ISSUE TITLE
Unexpected results when using natural right join

### ISSUE THREAD

**Issue by suyZhong** [FirebirdSQL/firebird#7879]
Considering the test case below. 

```sql
CREATE TABLE t0(c0 INT, c1 INT);
CREATE TABLE t1(c0 INT);

INSERT INTO t0(c0, c1) VALUES (1, 2);
INSERT INTO t1( c0) VALUES (3);

SELECT * FROM t0 NATURAL RIGHT JOIN t1; -- 3 <null>
SELECT (c0 IN (c0, c1)) FROM t0 NATURAL RIGHT JOIN t1; -- <true>
SELECT * FROM t0 NATURAL RIGHT JOIN t1 WHERE ((c0 IN (c0, c1))); 
-- Expected: 3 <null>
-- Actual: empty
```

The third `SELECT` returns an empty result, which is surprising: If the result of second query is `true`, the value of the `IN` expression should be true, and thus the third query should return the row of the `JOIN `, that is `3 <null>`, same as the first query.

I found this in version 6.0.0.154 where I built from source code https://github.com/FirebirdSQL/firebird/commit/ab3723448b3fba1f5fb618616e84c4fb231b63b4

**Comment by dyemanov** [comment]
`WHERE` condition is applied after a join. `(c0 IN (c0, c1))` means `(c0 = c0 OR c0 = c1)` and `NULL = <something>` can never be true.

**Comment by dyemanov** [comment]
It appears that the second query is wrongly returns TRUE then.

**Comment by dyemanov** [comment]
@mrotteveel It's **RIGHT** join, so the false join condition does not eliminate the rows from the output.

**Comment by dyemanov** [comment]
Firebird v4 returns {3, null} for the third query, while Firebird v5/v6 return no rows.

**Comment by dyemanov** [comment]
IIRC, every unqualified (without an alias) field reference inside a select list of `A NATURAL JOIN B` is replaced with COALESCE(A, B) under the hood. So the expression actually becomes `COALESCE(T0.C0, T1.C0) IN (COALESCE(T0.C0, T1.C0), T1.C1)` inside the select list and thus evaluates to `TRUE`. If fields are qualified properly, the result is different:

`SELECT (t1.c0 IN (t0.c0, t0.c1)) FROM t0 NATURAL RIGHT JOIN t1`
-- <null>

(in all FB versions)

and this:

`SELECT * FROM t0 NATURAL RIGHT JOIN t1 WHERE ((t1.c0 IN (t0.c0, t0.c1)));`

returns no rows even in v4.

**Comment by mrotteveel** [comment]
> It appears that the second query wrongly returns TRUE then.

See my previous comment, that is the correct result: `c0 in (c0, c1)` is `c0 = c0 OR c0 = c1`, is TRUE OR UNKNOWN is TRUE.

**Comment by mrotteveel** [comment]
Interestingly enough, the equivalent using `= ANY` does produce the right result:

```sql
SELECT * FROM t0 NATURAL RIGHT JOIN t1 WHERE c0 = any(select c0 from rdb$database union all select c1 from rdb$database);
```

**Comment by dyemanov** [comment]
> > It appears that the second query wrongly returns TRUE then.
> 
> See my previous comment, that is the correct result: `c0 in (c0, c1)` is `c0 = c0 OR c0 = c1`, is `3 = 3 OR 3 = NULL`, is TRUE OR UNKNOWN, is TRUE.

Yes, if `c0` is wrapped with `COALESCE`. I implied `c0` is actually `t0.c0` when was writing it's incorrect, as `NULL = NULL => UNKNOWN`.

**Comment by mrotteveel** [comment]
> > > It appears that the second query wrongly returns TRUE then.
> > 
> > 
> > See my previous comment, that is the correct result: `c0 in (c0, c1)` is `c0 = c0 OR c0 = c1`, is `3 = 3 OR 3 = NULL`, is TRUE OR UNKNOWN, is TRUE.
> 
> Yes, if `c0` is wrapped with `COALESCE`. I implied `c0` is actually `t0.c0` when was writing it's incorrect, as `NULL = NULL => UNKNOWN`.

Sure, but IIRC there should be no `t0.c0` or `t1.c0` after a natural join, there should only be a single `c0` of the join result.

**Comment by dyemanov** [comment]
Explained plan shows that `RIGHT JOIN` was changed to INNER JOIN in v5/v6, due to `WHERE` condition not caring about NULLs. This looks wrong. Maybe the `COALESCE` replacement happens after this check. I will look closer.
