### ISSUE TITLE
Unstable error messages in services due to races related with service status vector

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7885]
Ticked was created by Alex request. Failed restore (using services API) can miss final message "Exiting before completion due to errors".

We have QA test for CORE-5771. It verifies that attempt to restore DB via services when target DB exists does not cause FB crash.
Outcome if this test became unstable when ServerMode = SS since 6.0.0.100: message "-Exiting before completion due to errors" often is missed from expected output.
Illustration can be seen in attached screen.
![unstable-QA-for-core-5771-when-FB-mode-is-SS-since-6_0_0_100](https://github.com/FirebirdSQL/firebird/assets/17821573/d26a9ff0-edb8-433b-98a0-450c7d0d8442)

**Comment by AlexPeshkoff** [comment]
Reopened in order to backport after running QA on v.6

**Comment by AlexPeshkoff** [comment]
Not backported to FB3 - was never noticed on that codebase (though theoretically possible).

**Comment by Noremos** [comment]
I encountered this problem on FB 3.
It also seems like the problem is not fully fixed in FB 5 and FB 6. Usually, only one error message appears (`cannot open backup file` in this case), but with trace enabled, a second error sometimes appears (-`Exiting before completion due to errors` in this case). I tried adding an extra check to the both `Service::setServiceStatus` functions to ensure that only one error message is written, and that seems to have worked:
```cpp
	if ((svc_flags & SVC_evnt_fired) == 0)
	{
		// The service has not started, but we are receiving an error
		svc_flags |= SVC_failed_start;
	}
	else if ((svc_flags & SVC_failed_start) != 0)
	{
		// Service has started with an error, but we are trying to write one more error
		return;
	}
```

**Comment by AlexPeshkoff** [comment]
Can I see it in diff format?

**Comment by AlexPeshkoff** [comment]
On 2/5/25 18:09, Artyom Abakumov wrote:
>
>     Can I see it in diff format?
>
> I'm not sure if it's the best solution, but here it is.
>

For me - MUCH better. Everything got clear in suggested fix. It's OK in 
general - just let's avoid copyNpaste, better add new function to class 
Service and call it together with checkForShutdown:

diff --git a/src/jrd/svc.cpp b/src/jrd/svc.cpp
index 7d0dfdbeb3..ba0d277ff4 100644
--- a/src/jrd/svc.cpp
+++ b/src/jrd/svc.cpp
@@ -516,7 +516,7 @@ void Service::putBytes(const UCHAR* bytes, FB_SIZE_T 
len)

  void Service::setServiceStatus(const ISC_STATUS* status_vector)
  {
-       if (checkForShutdown())
+       if (checkForShutdown() || yourNewFunc())
         {
                 return;
         }


Also please add new issue & prepare PR.

**Comment by Noremos** [comment]
> Also please add new issue & prepare PR.

Done
https://github.com/FirebirdSQL/firebird/issues/8430
https://github.com/FirebirdSQL/firebird/pull/8431

**Comment by dyemanov** [comment]
Given that v3 is reported as also affected, is it worth backporting there too?
