### ISSUE TITLE
Hang in case of error when sweep thread is attaching to database.

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#7917]
Sweep thread very rarely has any errors on startup. But in a case when encrypted database to be swept the thread fails on attach except a case when shared between attachments key is provided by key holder plugin. This makes all attachments hang on detach (i.e. sweep thread exits not releasing appropriate lock).

**Comment by pavel-zotov** [comment]
@@@ QA issue @@@

Checked on Windows only (appropriate mark was added temporary).
Snapshots: 6.0.0.175, 5.0.0.1305, 4.0.5.3049.
Currently only SuperServer works fine.
Classic has the same problem as before fix. Sent report to Alex, 28.12.2023 13:10.

**Comment by AlexPeshkoff** [comment]
Reopened due to regressions, found by QA

**Comment by AlexPeshkoff** [comment]
Fix backported in https://github.com/FirebirdSQL/firebird/issues/7985

**Comment by pavel-zotov** [comment]
QA issue. Checked on 4.0.5.3053, 5.0.1.1327, 6.0.0.230 (intermediate snapshots; all in CS/SS). All fine.
