### ISSUE TITLE
FB5 uses PK for ordered plan even if less count of fields matching index exists.

### ISSUE THREAD

**Issue by livius2** [FirebirdSQL/firebird#7921]
FB5 uses PK for ordered plan even if less count of fields matching index exists.

use all scripts and data generator from
https://github.com/FirebirdSQL/firebird/issues/7904

and add additional scripts after:

```SQL
CREATE TABLE DYREKCJA
(
DYR_ID SMALLINT NOT NULL PRIMARY KEY
);
commit;

INSERT INTO DYREKCJA
SELECT DISTINCT DYR_ID FROM ROZLICZENIE;

ALTER TABLE ROZLICZENIE ADD CONSTRAINT FK_ROZLICZENIE__DYREKCJA  FOREIGN KEY (DYR_ID) REFERENCES DYREKCJA (DYR_ID);
```

and then run this query:

```SQL
SELECT
	RL.DYR_ID AS "Dyrekcja"
	, COUNT(*) AS "RL"
FROM
	ROZLICZENIE RL
WHERE
	RL.OKRES_NUMER = '15'
	AND RL.DOK_ROZLICZENIOWY_ID IN ('1')
GROUP BY
	RL.DYR_ID
/* PLAN (RL ORDER FK_ROZLICZENIE__DYREKCJA INDEX (ROZLICZENIE_FK4)) */
```

FB5 plan:
PLAN (RL ORDER PK_ROZLICZENIE INDEX (ROZLICZENIE_FK4))

but should be:
PLAN (RL ORDER **FK_ROZLICZENIE__DYREKCJA** INDEX (ROZLICZENIE_FK4))

Forgot to add that result is slower in our cases by >40% as index with 5 or more columns is used instead of 1 column index.

**Comment by dyemanov** [comment]
Wider (compound) index surely has a higher scan cost but the final retrieval cost (including data fetches) in both cases is estimated as very close (less than 2% of difference), thus kinda random index choice happens. I've committed a fix that prefers the actually cheaper index in this case.

**Comment by dyemanov** [comment]
BTW, this code wasn't touched for many years, so I'm wondering whether it's really a v5 regression or an old issue.

**Comment by livius2** [comment]
I have not tested this against FB4, so maybe ealier regression, but if this was random choice it is interesting that in FB3 it choose always cheaper index. Interesting also as you wrote that this should be less then 2%. In our cases it is >40% slowdown. In extream case it is even 107% when FB5 choose index with 6 fields and should use 1 field index. Thank you for fast fix, i will test on next snapshot.

**Comment by dyemanov** [comment]
It's fixed in v6 only so far.

**Comment by dyemanov** [comment]
And I've found the difference why v3 always chooses the cheaper index ;-) I just need to recall why this was changed in v4...

**Comment by livius2** [comment]
> It's fixed in v6 only so far.

I will really appreciate if it will be on FB5 too, as we are in hight testing phase to jump with the project to FB5 when released.

**Comment by dyemanov** [comment]
Out of curiosity, how many leaf pages these indices have? I mean `PK_ROZLICZENIE` vs `FK_ROZLICZENIE__DYREKCJA`, for example. You may find this info in the `gstat` output.

**Comment by livius2** [comment]
On real test database:

```
    Index FK_ROZLICZENIE__DYREKCJA (10) 
	Root page: 2143246, depth: 3, leaf buckets: 1950, nodes: 6315633 
	Average node length: 5.01, total dup: 6315621, max dup: 905933 
	Average key length: 2.00, compression ratio: 1.00 
	Average prefix length: 2.01, average data length: 0.00 
	Clustering factor: 209667, ratio: 0.03 
	Fill distribution: 
	     0 - 19% = 1 
	    20 - 39% = 0 
	    40 - 59% = 0 
	    60 - 79% = 0 
	    80 - 99% = 1949 
```

```
    Index PK_ROZLICZENIE (3) 
	Root page: 2006362, depth: 3, leaf buckets: 4253, nodes: 6315633 
	Average node length: 10.88, total dup: 0, max dup: 0 
	Average key length: 7.88, compression ratio: 3.55 
	Average prefix length: 23.00, average data length: 4.95 
	Clustering factor: 515124, ratio: 0.08 
	Fill distribution: 
	     0 - 19% = 1 
	    20 - 39% = 0 
	    40 - 59% = 0 
	    60 - 79% = 0 
	    80 - 99% = 4252 
```
