### ISSUE TITLE
FB5 slow query (different plan vs FB4)

### ISSUE THREAD

**Issue by NickNevzorov** [FirebirdSQL/firebird#7923]
I have a working database Firebird 2.5. Now I convert to 4.0 (ODS 13.0) and testing.

Working simple query:

```
select max(id) as id
from ptl_scan
where ptl_scan.create_date > DateAdd(second, -60 * 60, current_timestamp)
group by users_id
```

In FB2.5 and FB4 plan and execution 30ms:

> PLAN (PTL_SCAN ORDER PTL_SCAN_USERS_ID INDEX (PTL_SCAN_CREATE_DATE))

In FB5 plan and execution 1500ms (database same with FB4):

> PLAN (PTL_SCAN ORDER PTL_SCAN_USERS_ID)

Database for debug:

[TEST.zip](https://github.com/FirebirdSQL/firebird/files/13695605/TEST.zip)

**Comment by hvlad** [comment]
I see the same PLAN using fb4 and fb5:

`PLAN (PTL_SCAN ORDER PTL_SCAN_USERS_ID INDEX (PTL_SCAN_CREATE_DATE))`

Did you tried latest snapshot build of fb5 ?

**Comment by NickNevzorov** [comment]
@hvlad No, I have download 5.0.0.973 build ((

Thanks! Latest snapshot build working fine!
