### ISSUE TITLE
Some default values is set incorrectly for SC\CS architectures

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#7927]
Default values for `TempCacheLimit`, `DefaultDbCachePages` and `GCPolicy` settings is set as if `ServerMode = Super`, 
even if `ServerMode` is set to 'Classic' or 'SuperClassic'.

The issue is with default values only, if mentioned settings is set explicitly - correct values is used.

**Comment by hvlad** [comment]
Will be ported into v5 later

**Comment by pavel-zotov** [comment]
QA issue: test currently is skipped for FB 5.x. Waiting for port.
