### ISSUE TITLE
 Make TempCacheLimit setting to be per-database, (not per-attachment) for SuperClassic.

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#7928]
Improvement #5984 have side-effect that breaks backward compatibility for SuperClassic architecture.

Current implementation makes `TempCacheLimit` as per-attachment limit, while it was per-process before.

When users migrates from previous versions to the FB4 (or later) and left `TempCacheLimit` setting tuned for the known SuperClassic memory usage, it is not expected that actual memory consumption could be a lot larger than before.

This ticket offers to make `TempCacheLimit` as common limit for all attachments to the same database in the given SuperClassic process.
It will not affect Classic and SuperServer architectures.

**Comment by livius2** [comment]
It will be good if it will be configurable settings `per-attachement`/`per-database`/`per-process`.
An even for `SuperServer` not only for `SuperClassic` then.

**Comment by hvlad** [comment]
> It will be good if it will be configurable settings `per-attachement`/`per-database`/`per-process`. An even for `SuperServer` not only for `SuperClassic` then.

This issue is about broken backward compatibility with bad side effect.

**Comment by livius2** [comment]
> > It will be good if it will be configurable settings `per-attachement`/`per-database`/`per-process`. An even for `SuperServer` not only for `SuperClassic` then.
> 
> This issue is about broken backward compatibility with bad side effect.

Yes i kniow, but maybe based on this create new usefull feature. 
As now it is hard to decide what value to setup when it is e.g. per connection...

**Comment by hvlad** [comment]
Will be ported into v5 later
