### ISSUE TITLE
building FB 3/4 --with-builtin-[tommath|tomcrypt] fails

### ISSUE THREAD

**Issue by hisnameishb** [FirebirdSQL/firebird#7938]
Tried to compile 4.0.4.3010-0 or 3.0.11.33703-0 always fails with this builtin tommath/tomcrypt
Its always the same: it fails when it comes to the tommath folder:
Leaving directory '/foo/Firebird-3.0.11.33703-0/extern/cloop'
make -C /foo/Firebird-3.0.11.33703-0/extern/libtommath -f makefile.shared LIBTOOL=libtool
make[4]: Entering directory '/foo/Firebird-3.0.11.33703-0/extern/libtommath'
libtool --mode=link --tag=CC gcc  *.lo -o libtommath.la -rpath /usr/lib -version-info 0:41
/bin/sh: 1: libtool: not found

I cd'ed to the tommath folder and run make in it, it compiled without problems.

Again I run make for FB and get the same error above. It seems make does not find the files inside the builtin tommath folder.

My OS: Ubuntu 22.10, amd64

**Comment by aafemt** [comment]
No, it fails to find libtool. Did you install it?

**Comment by AlexPeshkoff** [comment]
When you type just 'make' libtool is not needed and build completes ok. But for FB we need shared tommath library therefore run 'make -f makefile.shared' and ut requires libtool.

**Comment by hisnameishb** [comment]
Installed libtool, it was not installed. I thought the libtool-script in the root of the sourcedir is used:
```
Firebird-3.0.11.33703-0$ ls -1
...
libtool   <----
m4
...
```

Now trying to build FB 3.x with installed libtool:
```
$ make
make[4]: Entering directory '/foo/Firebird-3.0.11.33703-0/extern/libtommath'
libtool --mode=link --tag=CC gcc  *.lo -o libtommath.la -rpath /usr/lib -version-info 0:41
libtool:   error: '*.lo' is not a valid libtool object

Trying to
cd ./extern/libtommath
$ make 
-> compiled libtommath.a without problems

Now tried this:
$ make -f makefile.shared
make -f makefile.shared 
libtool --mode=link --tag=CC gcc  *.lo -o libtommath.la -rpath /usr/lib -version-info 0:41
libtool:   error: '*.lo' is not a valid libtool object
make: *** [makefile.shared:90: libtommath.la] Error 1
```
