### ISSUE TITLE
How can I compile FB 3/4 the embedded Version for Linux?

### ISSUE THREAD

**Issue by hisnameishb** [FirebirdSQL/firebird#7939]
Hi,
there is no configure option for building FB as libfbembed.so. The old prebuild package for FB 1 had this lib precompiled,
the newer precompiled packages come all without the embeded Version, why?

How can I compile the FB as embedded version for Linux?

**Comment by aafemt** [comment]
Because of a new architecture. Read Release Notes for Firebird 3: embedded attachment is a mode of work that don't need special build and is chosen by connection string.
