### ISSUE TITLE
ARM64 version for macOS is missing

### ISSUE THREAD

**Issue by satial-interfaces** [FirebirdSQL/firebird#7957]
The ARM64 version for macOS is missing on the Firebird 5.0 release page. Only x86-64 is available, which means Rosetta 2 (emulation) must be enabled to be able to get it running on a 'modern' Mac.

**Comment by asfernandes** [comment]
Can you test this, please? https://github.com/asfernandes/firebird/releases/download/v5.0.0-macos-arm64/Firebird-5.0.0.1306-0-macos-arm64.pkg

Note that MacOS ARM64 is almost untested.

I had been able to build it uysing https://www.flyci.net/ and I suppose we can add it to automated tools, however, due to free limits, we can setup it only to build official releases and not for general CI.

**Comment by mrotteveel** [comment]
GitHub supports building against the M1 using `macos-latest-xlarge`/`macos-13-xlarge` (in beta). See also https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/ I'm not sure what the impact will be on our free plan, but I'd say it should be simpler than relying on a third-party.

**Comment by asfernandes** [comment]
> GitHub supports building against the M1 using `macos-latest-xlarge`/`macos-13-xlarge` (in beta)

This is not for free.

**Comment by mrotteveel** [comment]
On 13/01/2024 15:36, Adriano dos Santos Fernandes wrote:
>     GitHub supports building against the M1 using
>     |macos-latest-xlarge|/|macos-13-xlarge| (in beta)
> 
> This is not for free.

You're right. I had missed the "Included minutes cannot be used for 
larger runners." on 
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

Mark
-- 
Mark Rotteveel

**Comment by satial-interfaces** [comment]
Just installed and ran it with my medium-sized app, and all looks very well!

**Comment by kgantchev** [comment]
Hi, I'm the CEO and co-founder of FlyCI.  You can also try the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners.

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Exclusive M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```
 
They're up to 2x faster and up to 2x cheaper than GitHub's. We'll be very happy to have you on board.

**Comment by kgantchev** [comment]
Hi, I'm the CEO and co-founder of FlyCI. I want to thank @asfernandes for using FlyCI.

We certainly welcome you to try [FlyCI](https://www.flyci.net/)'s M1 and M2 runners which are on average about 2x faster and 2x cheaper than GitHub's runners. We also offer a free tier of 500 mins/month on the M1 runner so you don't have to use up your GitHub actions free tier minutes.

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Exclusive M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```
 
We'll be very happy to have you on board.

**Comment by asfernandes** [comment]
I added the package to 5.0.0 release and setup the CI for releases ans snapshots for now.
