### ISSUE TITLE
Unable to alter view with columns based on UTF8 collation: "SQLSTATE = HY000 / Unrecognized C++ exception"

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#7958]
[FBT_OUTCOMES_FB60_WINDOWS.meta-only.fbk.zip](https://github.com/FirebirdSQL/firebird/files/13930774/FBT_OUTCOMES_FB60_WINDOWS.meta-only.fbk.zip)
Please download .zip, unpack .fbk from it.
Run any snapshot FB 6.x with date >= 09-jan-2024 (i.e. 6.0.0.198 and later). Use default firebird.conf.
Restore database from .fbk

Then try script:
```
set echo on;
commit;
create or alter view v_tmp_total_results as select 1 x from rdb$database;
commit;

quit;
```

It will fail with:
```
Statement failed, SQLSTATE = HY000
Unrecognized C++ exception
```

/*
0xFF.
And, if DB connection is embedded, then following message appears after first:
```
Statement failed, SQLSTATE = 08003
invalid transaction handle (expecting explicit transaction start)
```
*/

View 'v_tmp_total_results' has 62 columns, of which 60 are declared as varchar(nn) charset utf8 and depend on collation:
```
CREATE COLLATION NS_COLL FOR UTF8 FROM EXTERNAL ('UNICODE') PAD SPACE 'COLL-VERSION=153.88;ICU-VERSION=63.1;numeric-sort=1';
```

This error blocks creation of reports after daily QA runs. Please fix it.

**Comment by pavel-zotov** [comment]
PS.
May this is the reason of problem:
https://github.com/FirebirdSQL/firebird/commit/d29e9cecb8bf464936e903908ce538f5da2b8854
?

**Comment by asfernandes** [comment]
Fixed. Not putting fixed label as it's master-only regression.
