### ISSUE TITLE
UseFileSystemCache defaults to false

### ISSUE THREAD

**Issue by reevespaul** [FirebirdSQL/firebird#7961]
Contrary to expectations the test for `UseFileSystemCache` in pag.cpp defaults to false unless explicitly set.

I've tested this in v4.0.5 and the code appears to be unchanged in master, so I guess this applies to v5 too.

Luckily the code then does the test to see if the db page buffer is less than the FileSystemCacheThreshold. In most cases this will return true so most users will not be affected.

**Comment by hvlad** [comment]
Sorry, could you be more specific - why do you think default is false, how to you test and what code you referes to ?


fb40\temp\x64\Release\firebird>isql -z
ISQL Version: WI-V4.0.5.3045 Firebird 4.0
Use CONNECT or CREATE DATABASE to specify a database
SQL> connect s:\temp\a.40.fdb;
Server version:
WI-V4.0.5.3045 Firebird 4.0
Database: s:\temp\a.40.fdb, User: SYSDBA
SQL>
SQL>
SQL> set list;
SQL> select * from rdb$config where rdb$config_name = 'UseFileSystemCache';

RDB$CONFIG_ID                   69
RDB$CONFIG_NAME                 UseFileSystemCache
RDB$CONFIG_VALUE                true
RDB$CONFIG_DEFAULT              true
RDB$CONFIG_IS_SET               <false>
RDB$CONFIG_SOURCE               <null>

**Comment by reevespaul** [comment]
I stepped through the code in pag.cpp and 
```
useFSCache = dbb->dbb_config->getUseFileSystemCache(&present);
``` 
returns false unless the value has been explicitly set in firebird.conf

**Comment by hvlad** [comment]
I also stepped thru the code, many times, believe me ;)
Could you run simple test above ?

You may check [this line](https://github.com/FirebirdSQL/firebird/blob/v4.0-release/src/common/config/config.h#L308), for example - the last (4th) value (`true`) is default value.

**Comment by hvlad** [comment]
So, when `UseFileSystemCache` is not set, the file system cache usage is defined by comparison of number of page buffers set and `FileSystemCacheThreshold` - as [documented](https://firebirdsql.org/file/documentation/release_notes/html/en/4_0/rlsnotes40.html#rnfb40-config-usefscache), where is the problem ?

**Comment by hvlad** [comment]
> RDB$CONFIG is convinced that the file system cache is being used:

No, it shows configuration values that was set (or not) and its default values. 
No more, no less.

**Comment by hvlad** [comment]
> The convention in firebird.conf is that all settings _are_ already set to the defaults and that there is no need to uncomment them unless the purpose is to change the default.

And I don't see it as broken.

> I suppose the explanation for `UseFileSystemCache` should also say something such as:
"Explicitly uncomment this setting if you want to experiment with large DB Cache pages while simultaneously using the file system cache."

Note the CAUTION section in `FileSystemCacheThreshold` description also. I consider it as more than enough. 
If you have another opinion, feel free to change comments in firebird.conf, no problem.

And, agree, it is very far from initial:
> Contrary to expectations the test for UseFileSystemCache in pag.cpp defaults to false unless explicitly set.

**Comment by hvlad** [comment]
I think there is nothing to add here and issue should be closed as not planned
