### ISSUE TITLE
Implement ability to check FOREIGN KEY constraint not using index on referencing table

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#7965]
When data in referenced (parent) table is mostly stable and changed rarely it makes sense to not build index on referencing (detail) table to check FK. In rare case when parent table is modified, read lock on detail table is enough to check FK constraint.
This allows to significantly lower number of indices on detail table(s) thus saving both disk and CPU resources.

**Comment by mrotteveel** [comment]
You've mixed up the terms referencing and referenced. The child table references the parent, not the other way around.

**Comment by dyemanov** [comment]
#3138 ?

**Comment by hvlad** [comment]
Yes, looks like #3138.

**Comment by dyemanov** [comment]
Closed in favour of #3138 (which is older and already has some votes assigned).
