### ISSUE TITLE
Line comment causes multiline input in ISQL

### ISSUE THREAD

**Issue by Noremos** [FirebirdSQL/firebird#7968]
Firebird 6 (the master branch, 8399037ffd4fcd437e0d9c0213b68c7567b7b10e) behaves as followed:
```
./isql -u SYSDBA employee
Database: employee, User: SYSDBA
SQL> --
CON> ;
SQL>
```

But all early versions (e.g. Firebird 5) do not consider a comment as the beginning of a multiline statement

```
./isql -u SYSDBA employee
Database: employee, User: SYSDBA
SQL> --
SQL>
```

Is this a new behavior or a bug?

**Comment by asfernandes** [comment]
This was already discussed in fb-devel, it's new behavior implemented with `SET AUTOTERM`.
