### ISSUE TITLE
Option for GEN_UUID to generate v7 UUID

### ISSUE THREAD

**Issue by r1gm** [FirebirdSQL/firebird#7980]
UUID v7 more index-able than UUID v4(Current used in FirebirdSQL, CMIIW), please bring support for UUID v7 in FirebirdSql.

**Comment by mrotteveel** [comment]
As far as I'm aware, the relevant RFC hasn't been published yet, so as of now, there is no official v7 UUID, and implementation at this time would be premature.

**Comment by sergeyprokhorenko** [comment]
However, no changes will be made to the text of the RFC. Therefore, no one waits for official approval:
[Rust](https://crates.io/crates/uuidv7)
[PostgreSQL](https://commitfest.postgresql.org/46/4388/)
[JavaScript](https://www.npmjs.com/package/uuidv7)
[Google](https://github.com/google/uuid/pull/139)
etc.

**Comment by michaelpq** [comment]
> [PostgreSQL](https://commitfest.postgresql.org/46/4388/)

FWIW, I doubt that any PostgreSQL committer will be OK to push a patch to add support for UUIDv7 without an approved RFC. There is too much risk in finishing with a non-compliant behavior.

**Comment by piervalli** [comment]
Hi All
In Postgresql  after many revisitions uuid7 is approved for next version.

https://commitfest.postgresql.org/47/4388/

**Comment by basid-irk** [comment]
RFC 9562 Universally Unique IDentifiers (UUIDs)
> RFC: [9562](https://rfc-editor.org/rfc/rfc9562)
> Obsoletes: [4122](https://rfc-editor.org/rfc/rfc4122) 
> Category: Standards Track
> Published: May 2024 
> ISSN: 2070-1721

**Comment by reevespaul** [comment]
I know gen_uuid() generates UUID v4 but surely the new syntax should also support gen_uuid(4).

And is there any plan to backport this feature to v4 and v5?

**Comment by mrotteveel** [comment]
@reevespaul The syntax accepts `GEN_UUID()`, which uses `4` and `GEN_UUID(4)` and `GEN_UUID(7)`.
