### ISSUE TITLE
iif returns space instead of empty string iif('A'='B','_','') FB4.0.4,3.0.7 Win, Linux and UTF8 , WIN1251 Databases

### ISSUE THREAD

**Issue by andrewkip** [FirebirdSQL/firebird#7981]
Hi

Steps for reproduce
```
select '['||iif('A'<>'B','','_')||']'from RDB$DATABASE
select '['||iif('A'='B','_','')||']'from RDB$DATABASE
```

in both cases iif returns wrong result - returns space insttead of empty string

tested on 
FB 4,0.4, 3.0.7  Win Linux and UTF8, WIN1251 Databases
but 
select '['||iif('A'='B','_',trim(''))||']'from RDB$DATABASE works fine :)

brgds

**Comment by mrotteveel** [comment]
This is not a bug. You're using string literals as arguments to `IIF`, and string literals are of type `CHAR`. The longest return value is `'_'`, which is `CHAR(1)`, this means the return type of the `IIF` is `CHAR(1)` as well. That means that `''` is padded with a space to be a `CHAR(1)`.

You need to use `TRIM` around the entire expression (or both the second and third argument) to get the result you expect.
