### ISSUE TITLE
Unexpected results when using `CASE WHEN` with `RIGHT JOIN`

### ISSUE THREAD

**Issue by suyZhong** [FirebirdSQL/firebird#7993]
Considering the test case below. 

```sql
CREATE TABLE t0(c0 BOOLEAN);
CREATE TABLE t1(c1 BOOLEAN);
INSERT INTO t0 (c0) VALUES (true);
INSERT INTO t1 (c1) VALUES (false);

SELECT * FROM t1 RIGHT  JOIN t0 ON t0.c0; -- false true
SELECT * FROM t1 RIGHT  JOIN t0 ON t0.c0 WHERE (CASE t1.c1 WHEN t1.c1 THEN NULL ELSE true END ); -- null true (Unexpected)

SELECT (CASE t1.c1 WHEN t1.c1 THEN NULL ELSE true END ) FROM t1 RIGHT  JOIN t0 ON t0.c0; -- null
```

The second `SELECT` returns an unexpected result: if the result of the `CASE` expression is `NULL`, the value of the `WHERE` clause in the second should be `NULL`, and thus the second query should return empty result. Additionally, the output of the second query, containing a `WHERE` condition, must not include rows that differ from those returned by the first query.

I found this in version LI-T6.0.0.247 where I built from source code da67351ad9a17fb74869bc0554311fa3

Besides, I have one question considering an error: `Too many concurrent executions of the same request [SQLState:54001, ISC error code:335544663]`. Does this mean that we couldn't send many same queries (e.g. `SELECT * FROM t0`) to the server at the same time?

**Comment by asfernandes** [comment]
> Besides, I have one question considering an error: `Too many concurrent executions of the same request [SQLState:54001, ISC error code:335544663]`. Does this mean that we couldn't send many same queries (e.g. `SELECT * FROM t0`) to the server at the same time?

Please check if the error disapear if you put `MaxStatementCacheSize = 0` in `firebird.conf`.

**Comment by livius2** [comment]
> > Besides, I have one question considering an error: `Too many concurrent executions of the same request [SQLState:54001, ISC error code:335544663]`. Does this mean that we couldn't send many same queries (e.g. `SELECT * FROM t0`) to the server at the same time?
> 
> Please check if the error disapear if you put `MaxStatementCacheSize = 0` in `firebird.conf`.

Is this some known issue?

**Comment by asfernandes** [comment]
> > Please check if the error disapear if you put `MaxStatementCacheSize = 0` in `firebird.conf`.
> 
> Is this some known issue?

There is https://github.com/FirebirdSQL/firebird/issues/7960

Previously this happened only with stored routines, but now may happen with DSQL statements when the statement cache is turned on (default).

But I think the fix should not be directed to statement cache code, so it's the same existing problem that becomes more general.

**Comment by livius2** [comment]
@asfernandes thanks
