### ISSUE TITLE
Int128 datatype not supported in FB_MESSAGE macro 

### ISSUE THREAD

**Issue by AlexPeshkoff** [FirebirdSQL/firebird#8006]
Bug was reported to me by user privately.

An attempt to use int128 field in UDR fails when trying to describe it in the message.

**Comment by aafemt** [comment]
It looks rather as "an attempt to use Int128 in a static buffer" than "in UDR"...

**Comment by AlexPeshkoff** [comment]
in a static message buffer ?

**Comment by aafemt** [comment]
...or however is called this ugly bunch of macros and templates in Message.h. In your commit I see no changes anywhere else. Did I miss something?

**Comment by AlexPeshkoff** [comment]
No more changes except small one in related example. 
BTW, you may call that macros ugly but they help make required changes in single place, and people use it.

**Comment by aafemt** [comment]
Still it is not related to UDR in any manner and can be used anywhere in API code.

**Comment by AlexPeshkoff** [comment]
> Still it is not related to UDR in any manner and can be used anywhere in API code.

Yes, therefore I've renamed this ticket
