### ISSUE TITLE
Unexpected results when using newline in string

### ISSUE THREAD

**Issue by suyZhong** [FirebirdSQL/firebird#8014]
Consider the test case below. It is unexpected that, if the second query returns `true`, the third query returns an empty result, because the value of the `WHERE` predicate should be `true` as well.

```sql
CREATE TABLE t0(c0 VARCHAR(500), PRIMARY KEY(c0)); -- PK is needed
INSERT INTO t0 (c0) VALUES ('a
');

SELECT * FROM t0; -- 'a\n'
SELECT (t0.c0 < 'a') FROM t0; -- true (unexpected)
SELECT * FROM t0 WHERE (t0.c0 < 'a'); 
-- Expected (if true for second query is expected): 'a\n'
-- Actual: Empty Table
```

Not sure if the issue https://github.com/FirebirdSQL/firebird/issues/7997 has been solved, looks like I could still reproduce the issue. But I guess it's not the same issue.

I found this in version LI-T6.0.0.268 where I built from source code de4c4d075d4fac708be865624840377fdeb937bf

**Comment by asfernandes** [comment]
Accordingly to standard this should be correct.

Regarding the inconsistency, AFAIR https://github.com/FirebirdSQL/firebird/pull/6871 should fix it (https://github.com/FirebirdSQL/firebird/issues/6839) but the solution was not reviewed and I never merged it.

**Comment by asfernandes** [comment]
Accordingly to the standard, strings (even VARCHAR) should be padded for the greater length when comparing.
When spaces are added, it changes logic in relation to common string comparation without padding.

**Comment by AlexPeshkoff** [comment]
Duplicate.
