### ISSUE TITLE
AV when both function and dependent table are dropped in the same transaction

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#8020]
1. create metadata and disconnect
```
set autoddl off;
set term ^;

create function f(x int)
  returns int
as
begin
  return x;
end
^
create table t_fn (x int, fx computed by (f(x)))
^
commit
^
set term ;^
exit;
```

2. connect and drop objects

```
set autoddl off;
drop function f;
drop table t_fn;
commit;
```

**Comment by pavel-zotov** [comment]
[Script](https://github.com/FirebirdSQL/firebird/issues/8020#issue-2157203395) shows on 6.0.0.269:
```
SQLSTATE = 39000 / unsuccessful metadata update / -DROP TABLE T_FN failed / -invalid request BLR at offset 1 / -function F is not defined
```
Is it expected ?

**Comment by pavel-zotov** [comment]
QA issue: test need to be adjusted after #8021 will be fixed (DROP statements must be in DSQL form rather than be 'enclosed' in EB and begin/end with suppressing exceptions). See notes.
