### ISSUE TITLE
Error.... 

### ISSUE THREAD

**Issue by Jhironsel** [FirebirdSQL/firebird#8045]
SET TERM ^ ;
CREATE PROCEDURE ADMIN_CONSULTA_PERMISOS2
RETURNS (
    PROFILE_ANY D_BOOLEAN_F
)
SQL SECURITY DEFINER
AS
BEGIN
    PROFILE_ANY =(select rdb$system_privilege(PROFILE_ANY_ATTACHMENT) from RDB$DATABASE);
    SUSPEND;
END
^
SET TERM ; ^
GRANT EXECUTE
 ON PROCEDURE ADMIN_CONSULTA_PERMISOS TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA;

![image](https://github.com/FirebirdSQL/firebird/assets/28508219/85bcbaca-5d97-42b2-a01a-a44c3f75854a)

![image](https://github.com/FirebirdSQL/firebird/assets/28508219/4f4e6690-0a73-4d2b-8d27-8a907ed627fa)

Total execution time: 0.024s
Committing transaction...
Transaction committed (elapsed time: 0.000s).
Starting transaction...
Preparing statement: 
CREATE PROCEDURE ADMIN_CONSULTA_PERMISOS2
RETURNS (
    PROFILE_ANY D_BOOLEAN_F
)
SQL SECURITY DEFINER
AS
BEGIN
    PROFILE_ANY =(select rdb$system_privilege(PROFILE_ANY_ATTACHMENT) from RDB$DATABASE);
    SUSPEND;
END

Error: *** IBPP::SQLException ***
Context: Statement::Prepare( 
CREATE PROCEDURE ADMIN_CONSULTA_PERMISOS2
RETURNS (
    PROFILE_ANY D_BOOLEAN_F
)
SQL SECURITY DEFINER
AS
BEGIN
    PROFILE_ANY =(select rdb$system_privilege(PROFILE_ANY_ATTACHMENT) from RDB$DATABASE);
    SUSPEND;
END
 )
Message: isc_dsql_prepare failed

Engine Code    : 335545111
Engine Message :
unknown ISC error 335545111

**Comment by hvlad** [comment]
1. 335545111 is `isc_wrong_prvlg` and its text is 'System privilege @1 does not exist'
2. Use correct fbclient.dll to see correct error messages, used one looks too old.
3. SQL Profiler is a FB5 feature, while you run FB4

**Comment by Jhironsel** [comment]
Thanks....
