### ISSUE TITLE
Create if not exists

### ISSUE THREAD

**Issue by ertankucukoglu** [FirebirdSQL/firebird#8062]
Hello,

Latest snapshot builds includes "drop if exists" support (at least for tables).
Both "drop if exists" and "create if not exists" has been discussed in several other places including https://github.com/FirebirdSQL/firebird/issues/4203
Since half of the job seems to be implemented, I would very much like to have the other half for v6.0.

Thank you for your consideration.

Regards,
Ertan

**Comment by pavel-zotov** [comment]
QA issue: have several questions, sent example to Adriano 15.04.2024 15:07. Waiting for reply.
