### ISSUE TITLE
FB 5.0.1: error at the end of the backup process

### ISSUE THREAD

**Issue by gsbelarus** [FirebirdSQL/firebird#8068]
Server mode: Classic or Super (tested for both)
Max parallel workers: 64
Parallel workers: 16

At the end of database backup gets the following message:

```
12:42:46,47 C:\Program Files\FB5>gbak -b "G:\XXXXXX.FDB" "G:\XXXXXXX.bk" -pas XXXXXXX -user sysdba -se localhost/3056:service_mgr
gbak: ERROR:Error reading data from the connection.
gbak:Exiting before completion due to errors
```

There is a record in the firebird.log:

```
XXXXXXXX	Wed Apr  3 12:57:23 2024
	INET/inet_error: read errno = 10054, server host = localhost, address = ::1/3056
```

Visually, the resulting bk file looks fine, though I didn't check how the database will be restored from it.

**Comment by hvlad** [comment]
Title shows "restore", command line shows "-b", i.e. backup. What is correct ? ;)
How it can be reproduced ? Or you have a crash dump ?

**Comment by gsbelarus** [comment]
Sorry, fixed the title. This is an issue with back up now. I'm still in my thoughts about that restoring error, that was fixed recently.

**Comment by hvlad** [comment]
I need more info to investigate the issue. 
Tried to reproduce with db that I've used to reproduce #7942 - no luck.

**Comment by hvlad** [comment]
Any new info, test case probably ?

**Comment by gsbelarus** [comment]
I will wait until this commit goes into the FB 5 build and then recheck.

https://github.com/FirebirdSQL/firebird/commit/e96fc77d504740d2d8e7b69d9594c2700877c9a3

**Comment by hvlad** [comment]
Hmm... that was about restore. Anyway, it was fixed in v5 first, two days ago.

**Comment by hvlad** [comment]
Look like 5.0.1 will not include fix for this "Elusive Joe". Should I close the issue as not reproducible ?

**Comment by gsbelarus** [comment]
it is reproducible 100%. I'm just weighting procs and cons of sending sensitive data.

**Comment by hvlad** [comment]
It is up to you, but I can't fix something that is not reproducible and with no info.

**Comment by gsbelarus** [comment]
@hvlad выслал письмом как получить бд, чтобы проверить

**Comment by gsbelarus** [comment]
@hvlad sent instructions how to get the db by email

**Comment by hvlad** [comment]
Received your email, thanks

**Comment by hvlad** [comment]
Still can't reproduce it

**Comment by gsbelarus** [comment]
I'm closing it. Let's assume it is somehow related to the particular configuration of Windows 2019 Server and three Firebird servers (2.5, 3.0, 5.0) running on different ports.
