### ISSUE TITLE
ReleaseSemaphore errors in firebird.log

### ISSUE THREAD

**Issue by lwennekers** [FirebirdSQL/firebird#8073]
Hello,

I'm using Firebird 4.0.2 and created a backup process which I can start manually and is executed automatically. The logging below shows the errors on the ReleaseSemaphore at 10:02 (the automatic process) and at 08:39 (the manual process).
I used the .net FirebirdClient. First I create a backup. After that I restore the backup to a new database. That new database is manipulated, by making certain fields empty. The manipulated database is then back upped again. It's a sequential process so all steps wait for the previous step. For the moment I got 4 tests systems running and they all show the same errors. I hope that you can tell me what I'm missing so the error wouldn't occur anymore.

Kind regards,
Leonard Wennekers

AW-WIN10X	Wed Apr  3 08:39:28 2024
	Operating system call ReleaseSemaphore failed. Error code 6
AW-WIN10X	Wed Apr  3 08:39:31 2024
	Operating system call ReleaseSemaphore failed. Error code 6
AW-WIN10X	Wed Apr  3 10:02:59 2024
	Operating system call ReleaseSemaphore failed. Error code 6
AW-WIN10X	Thu Apr  4 11:42:45 2024
	INET/inet_error: read errno = 10054, client host = AW-Win10x, address = 127.0.0.1/51940, user = AW-WIN10X$
AW-WIN10X	Thu Apr  4 15:45:08 2024
	INET/inet_error: read errno = 10054, client host = AW-Win10x, address = 127.0.0.1/63069, user = xxxxxxxxxxxx
AW-WIN10X	Fri Apr  5 10:02:17 2024
	Operating system call ReleaseSemaphore failed. Error code 6
AW-WIN10X	Sun Apr  7 10:02:17 2024
	Operating system call ReleaseSemaphore failed. Error code 6

**Comment by hvlad** [comment]
First, upgrade to 4.0.4. If it happens again, try latest snapshot build or provide reprodusible test case, please.

**Comment by lwennekers** [comment]
Thanks for your response. I upgraded our test systems and will monitor it for the time being. When the problem remains I also will try to provide you a testcase,

**Comment by hvlad** [comment]
Any news ?

**Comment by lwennekers** [comment]
As a mather of fact yes there is news. It seems that you provided the solution with an upgrade to 4.0.4. The was no ReleaseSemaphore error anymore in the firebird.log. Thanks, I think the issue can be closed,

**Comment by hvlad** [comment]
Good to know, thanks!
