### ISSUE TITLE
The isc_array_lookup_bounds function returns invalid values for low and high array bounds

### ISSUE THREAD

**Issue by ViktorVDev** [FirebirdSQL/firebird#8100]
[OFS_FB4.txt](https://github.com/FirebirdSQL/firebird/files/15203897/OFS_FB4.txt)
[OFS_FB5.txt](https://github.com/FirebirdSQL/firebird/files/15203898/OFS_FB5.txt)
In FB5 and newer (tested for the latest snapshots of FB5 and FB6), there is an incorrect behavior upon calling the isc_array_lookup_bounds() function: the array bounds ALWAYS equal zero.

To reproduce, an EMPLOYEE.FDB from Firebird demo may be used.
The query used is: SELECT * FROM JOB.

Upon the further investigation it turned out that upon making a call for select fd.rdb$lower_bound, fd.rdb$upper_bound from rdb$field_dimensions fd where fd.rdb$field_name = ? order by fd.rdb$dimension

As the parameter's value, the value from the rdb$field_name field of the rdb$relation_fields table is sent, instead of sending the value of the rdb$field_source field of the aforementioned table. 
 
Please see the attached results from the sniffer for FB4 (everything works properly) and FB5.

**Comment by asfernandes** [comment]
@ViktorVDev could you please test fix in next snapshot of FB 5?

**Comment by TommiPrami** [comment]
On our tests this also affects 4.0.4, but not 4.03.

Do Double Check is this needed to be backported also 4.05.

**Comment by asfernandes** [comment]
> On our tests this also affects 4.0.4, but not 4.03.
> 
> Do Double Check is this needed to be backported also 4.05.

The function wasn't changed in v4 branch, so I don't see how the same bug could be there.
