### ISSUE TITLE
Replication does not preserve character encoding Firebird 5

### ISSUE THREAD

**Issue by Michel-Itapira** [FirebirdSQL/firebird#8107]
Scenario: 
2 virtualized Debian servers, identical copies, include Firebird conf and database , database is same both have field ISO8859_1.
When you configure one database for replica and another for master, 
if the field is encoded to ISO8859_1 , the data is replicated in UNICODE, 
Example:
Data in master
"Dispositivo não foi encontrado com essa chave"
Data replicate in replicate
"Dispositivo nÃ£o foi encontrado com essa chave"
Change HEX  0xE3 to 0xC3 0x A3

**Comment by dyemanov** [comment]
Is this field blob or varchar?

**Comment by Michel-Itapira** [comment]
varchar

**Comment by dyemanov** [comment]
It's replicated exactly as stored. Maybe you connect to the replica using different (unicode) connection charset and thus see different data?

**Comment by Michel-Itapira** [comment]
Blob Text

**Comment by Michel-Itapira** [comment]
It's replicated exactly as stored. Maybe you connect to the replica using different (unicode) connection charset and thus see different data?
Same connection change ip only

**Comment by dyemanov** [comment]
If it's a blob, then it looks like #7969. Try the fresh snapshot build.
