### ISSUE TITLE
Cast dies with numeric value is out of range error (5.0.1 snapshot)

### ISSUE THREAD

**Issue by omachtandras** [FirebirdSQL/firebird#8120]
Hi,

5.0.1.1398 snapshot

select cast('27' as numeric(4,2))
from rdb$database

causes
arithmetic exception, numeric overflow, or string truncation.
numeric value is out of range.
error.

It works fine with 5.0.0.1306 and 4.0.*, 3.0.*

**Comment by asfernandes** [comment]
Looks like it appeared in v4 in commit c909897a878917a71852a8a11aa90aad2d091f71
For me, results are different:
```
SQL> select cast('27' as numeric(4,2)) from rdb$database;

   CAST 
======= 
   0.27 
```

**Comment by omachtandras** [comment]
Confirmed, 5.0.1.1408 and 4.0.5.3103 are working fine.
@hvlad, @asfernandes thanks for the fix.

**Comment by pavel-zotov** [comment]
QA note: could not reproduce on 5.0.1.1398-f339eb4
![image](https://github.com/FirebirdSQL/firebird/assets/17821573/2d76e1b0-fcff-450f-9f28-fe7c4fd8f854)

**Comment by pavel-zotov** [comment]
PS. Although *can* be reproduced on 4.0.5.3077 (14-mar-2024) :-)

**Comment by hvlad** [comment]
> QA note: could not reproduce on 5.0.1.1398-f339eb4 ![image](https://private-user-images.githubusercontent.com/17821573/334051514-2d76e1b0-fcff-450f-9f28-fe7c4fd8f854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDM0MDQsIm5iZiI6MTcxNjgwMzEwNCwicGF0aCI6Ii8xNzgyMTU3My8zMzQwNTE1MTQtMmQ3NmUxYjAtZmNmZi00NTBmLTlmMjgtZmU3YzRmZDhmODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA5NDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZjEzZTRlNzZlNmM3YTVlMzNjM2M3ODBjM2JiYmJjMDBiMWM4ZmVlZjJiNjljNzgzZjdmMGFhN2FhNWVjNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z2kqvZsDOnQos9K6iUAVWJzJu5lqCAnVROHWYxAXBJ4)

Do you consider 0.27 as correct result here ?

**Comment by pavel-zotov** [comment]
i did not pay attention on arithmetic correctness of result :-)
just see that no error raised on snapshot 5.0.1.1398
