### ISSUE TITLE
Firebird 5.0 Embedded app crash on query

### ISSUE THREAD

**Issue by piervalli** [FirebirdSQL/firebird#8131]
Some time when I use Firebird embedded in the app crash and if I check 
firebird.log there is following message

How can I add more information for understand it?
DESKTOP-PIER	Sat May 11 21:47:38 2024
	 Access violation.
		The code attempted to access a virtual
		address without privilege to do so.
	This exception will cause the Firebird server
	to terminate abnormally.

The query is not complex
SELECT FIRST 5000 SKIP 0 product.* from product  WHERE  "id" IN ('018f2ef8-8214-740b-8503-060903000e06','018f4532-07d0-7c0e-8501-050a01010109','018f4532-2310-7b01-880f-000f07040607','018f4531-90d5-7f0d-850b-050c050d020d','018f4532-436a-7c01-8503-0107020c0300')  ORDER BY product."id"  

Products are 500 records.

The crash is random i don't have a reproduction script,but I catch a dump. I haved installed Firebird with debug symbols.

`
  ntdll.dll!LdrpCallInitRoutine+0x6f
  ntdll.dll!LdrShutdownProcess+0x213
  ntdll.dll!RtlExitUserProcess+0xad
  KERNEL32.DLL!ExitProcessImplementation+0xa
  ucrtbase.dll!exit_or_terminate_process+0x44
  ucrtbase.dll!common_exit+0x6f
  Engine13.DLL!ISC_exception_post+0x25f  [C:\firebird-build\src\common\isc_sync.cpp @ 1115]
  Engine13.DLL!`looper_seh'::`1'::filt$0+0x19  [C:\firebird-build\src\jrd\exe.cpp @ 1590]
  VCRUNTIME140.dll!__C_specific_handler+0xa0  [D:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp @ 376]
  Engine13.DLL!__GSHandlerCheck_SEH+0x6a  [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\gs\amd64\gshandlerseh.cpp @ 103]
  ntdll.dll!RtlpExecuteHandlerForException+0xf
  ntdll.dll!RtlDispatchException+0x40f
  ntdll.dll!KiUserExceptionDispatch+0x2e
  Engine13.DLL!MOV_get_string+0x1f  [C:\firebird-build\src\jrd\mov.cpp @ 241]
  Engine13.DLL!compress+0x5bc  [C:\firebird-build\src\jrd\btr.cpp @ 2812]
  Engine13.DLL!BTR_make_key+0x16e  [C:\firebird-build\src\jrd\btr.cpp @ 1853]
  Engine13.DLL!Jrd::IndexScanListIterator::makeKeys+0x94  [C:\firebird-build\src\jrd\btr.cpp @ 748]
  Engine13.DLL!Jrd::IndexTableScan::internalGetRecord+0x5ba  [C:\firebird-build\src\jrd\recsrc\IndexTableScan.cpp @ 264]
  Engine13.DLL!Jrd::RecordSource::getRecord+0x41  [C:\firebird-build\src\jrd\recsrc\RecordSource.cpp @ 79]
  Engine13.DLL!Jrd::FilteredStream::evaluateBoolean+0x75  [C:\firebird-build\src\jrd\recsrc\FilteredStream.cpp @ 381]
  Engine13.DLL!Jrd::FilteredStream::internalGetRecord+0x75  [C:\firebird-build\src\jrd\recsrc\FilteredStream.cpp @ 108]
  Engine13.DLL!Jrd::RecordSource::getRecord+0x41  [C:\firebird-build\src\jrd\recsrc\RecordSource.cpp @ 79]
  Engine13.DLL!Jrd::RecordSource::getRecord+0x41  [C:\firebird-build\src\jrd\recsrc\RecordSource.cpp @ 79]
  Engine13.DLL!Jrd::RecordSource::getRecord+0x41  [C:\firebird-build\src\jrd\recsrc\RecordSource.cpp @ 79]
  Engine13.DLL!Jrd::Cursor::fetchNext+0xbf  [C:\firebird-build\src\jrd\recsrc\Cursor.cpp @ 255]
  Engine13.DLL!Jrd::ForNode::execute+0xdc  [C:\firebird-build\src\dsql\StmtNodes.cpp @ 5231]
  Engine13.DLL!EXE_looper+0x3f2  [C:\firebird-build\src\jrd\exe.cpp @ 1455]
  Engine13.DLL!looper_seh+0x34  [C:\firebird-build\src\jrd\exe.cpp @ 1587]
  Engine13.DLL!execute_looper+0xe5  [C:\firebird-build\src\jrd\exe.cpp @ 1050]
  Engine13.DLL!EXE_receive+0x12c  [C:\firebird-build\src\jrd\exe.cpp @ 631]
  Engine13.DLL!JRD_receive+0x24  [C:\firebird-build\src\jrd\jrd.cpp @ 9348]
  Engine13.DLL!Jrd::DsqlDmlRequest::fetch+0x416  [C:\firebird-build\src\dsql\DsqlRequests.cpp @ 412]
  Engine13.DLL!Jrd::DsqlCursor::fetchNext+0x17  [C:\firebird-build\src\dsql\DsqlCursor.cpp @ 110]
  Engine13.DLL!Jrd::JResultSet::fetchNext+0x14a  [C:\firebird-build\src\jrd\jrd.cpp @ 5292]
  Engine13.DLL!Firebird::IResultSetBaseImpl<Jrd::JResultSet,Firebird::CheckStatusWrapper,Firebird::IReferenceCountedImpl<Jrd::JResultSet,Firebird::CheckStatusWrapper,Firebird::Inherit<Firebird::IVersionedImpl<Jrd::JResultSet,Firebird::CheckStatusWrapper,Firebird::Inherit<Firebird::IResultSet> > > > >::cloopfetchNextDispatcher+0x35  [C:\firebird-build\src\include\firebird\IdlFbInterfaces.h @ 10229]
  fbclient.dll!Why::YResultSet::fetchNext+0x68  [C:\firebird-build\src\yvalve\why.cpp @ 4819]
  fbclient.dll!Why::IscStatement::fetch+0x6b  [C:\firebird-build\src\yvalve\why.cpp @ 4705]
  fbclient.dll!isc_dsql_fetch+0x20b  [C:\firebird-build\src\yvalve\why.cpp @ 2553]
  qsqlibase.dll!QIBaseResult::gotoNext+0x3d0
  Qt5Sql.dll!QSqlCachedResult::cacheNext+0x5b
  Qt5Sql.dll!QSqlQuery::next+0x56
  WebServer.dll!Dao::getMap<Product>+0x8f2  [C:/Qt/5.15.13/mingw81_64/include/QtCore/qthreadstorage.h @ 135]
`

Last row is my class it calls QSqlQuery::next to fetch new new record,QIBaseResult is the driver where there is wrapper with fbclient.

Have you   some a suggestional for addition debug?
Thanks
Pier

**Comment by hvlad** [comment]
Could you try with latest snapshot of 5.0.1 ?

**Comment by piervalli** [comment]
yes,
have you link to dowload it?
Thanks

**Comment by piervalli** [comment]
Hi,
thanks, today it is ok.

**Comment by hvlad** [comment]
Considered it was fixed already
