### ISSUE TITLE
[FB5] SUM() breaks query for BIGINT columns and arithmetic operations

### ISSUE THREAD

**Issue by janzikmund** [FirebirdSQL/firebird#8137]
Firebird version: 5.0.0 in [Docker container](https://hub.docker.com/r/jacobalberty/firebird)

When connecting from Python, PDO or php_interbase, an error is thrown when:

### 1. SUM() column contains arithmetic operation, eg.
`SELECT SUM(1+1) FROM RDB$DATABASE`

**Expected result**: 2

**Result**: Error (from Python script): 
`fdb.fbcore.DatabaseError: ('Cursor.fetchone:\n- SQLCODE: -804\n- Incorrect values within SQLDA structure\n- empty pointer to data\n- at SQLVAR index 0', -804, 335544713)`

### 2. SUM() is run on BIGINT column type
Example using demo employee database:

```
ALTER TABLE EMPLOYEE ADD TEST BIGINT;
UPDATE EMPLOYEE SET TEST=1;
SELECT SUM(TEST) FROM EMPLOYEE;
```

**Expected result**: (int) number of rows in table

**Result**: Error
`fdb.fbcore.DatabaseError: ('Cursor.fetchone:\n- SQLCODE: -804\n- Incorrect values within SQLDA structure\n- empty pointer to data\n- at SQLVAR index 0', -804, 335544713)`

For a reference, below is the Python3 script I am testing with:

```
import fdb
con = fdb.connect(dsn='localhost:/usr/local/firebird/examples/empbuild/employee.fdb', user='SYSDBA', password='masterkey')
cur = con.cursor()

cur.execute("SELECT SUM(1+1) FROM RDB$DATABASE")
print(cur.fetchall())

cur.execute("SELECT SUM(TEST) from EMPLOYEE")
print(cur.fetchall())
```

**Comment by hmoffatt** [comment]
Firebird 4 and later return BIGINT for SUM() etc which seems to be missing from fdb. You can tell Firebird to use BIGINT instead:

```
cur.execute('set bind of int128 to bigint')
```

**Comment by janzikmund** [comment]
Thanks so much, I can confirm both ways above fix the problem. 

@hmoffatt - you probably meant "..return INT128", correct? Then it makes complete sense.

But do you assume this might be fixed with future versions of fdb/php-firebird? I understand they both depend on libfbclient.so , but even latest stable version gave the error. 

What I am after is- will we be able to use SUM() reliably with default settings, or is it assumed we will need this returned type override or be locked in DataTypeCompatibility mode?

**Comment by aafemt** [comment]
According to [change log](https://firebird-driver.readthedocs.io/en/latest/changelog.html#version-0-7-0) the driver supports int128 staring from version 0.7.0.

**Comment by dyemanov** [comment]
`fdb` is deprecated, `firebird-driver` should be used instead.

**Comment by hmoffatt** [comment]
> What I am after is- will we be able to use SUM() reliably with default settings, or is it assumed we will need this returned type override or be locked in DataTypeCompatibility mode?

php-firebird has an open issue https://github.com/FirebirdSQL/php-firebird/issues/58 ; development seems to be stalled though, timezone support is also missing https://github.com/FirebirdSQL/php-firebird/issues/26 .

I also use Qt which is also missing INT128 support across all platforms, so I just add the 'set bind' to my connect string. I don't see how to do that in Python with fdb though.

**Comment by janzikmund** [comment]
@aafemt , @dyemanov : Nice, that takes care of it for Python, then 👍

As for PHP, it also has this ticket, so hopefully it will get there as well:
https://github.com/FirebirdSQL/php-firebird/issues/26 

Thanks so much for all help

**Comment by janzikmund** [comment]
Closing.

**Comment by AlexPeshkoff** [comment]
On 5/28/24 13:58, Hamish Moffatt wrote:
> Can I still talk to 2.5 servers, as long as I use a recent fbclient 
> library

Yes.
