### ISSUE TITLE
Firebird 5.0 - Implicit cast from integer to string error

### ISSUE THREAD

**Issue by fous65** [FirebirdSQL/firebird#8144]
In Firebird 5.0 are unexpected results from following statement (in Firebird 4/3/2.5 - OK):

CREATE TABLE tab1 (ID integer,  abc integer);
commit;
insert into tab1 (id, abc) values (1, 1);
insert into tab1 (id, abc) values (2, 1);
insert into tab1 (id, abc) values (3, 2);
insert into tab1 (id, abc) values (4, 1);
insert into tab1 (id, abc) values (5, 3);
insert into tab1 (id, abc) values (6, 3);
insert into tab1 (id, abc) values (7, 4);
commit;

**"select * from tab1 where abc in ('1', '2', '3', '4')" -  OK**
          ID          ABC 
============ ============ 
           1            1 
           2            1 
           3            2 
           4            1 
           5            3 
           6            3 
           7            4 

**adding '11': "select * from tab1 where abc in ('1', '2', '3', '4', '11')" - abc=2 is missing**
          ID          ABC 
============ ============ 
           1            1 
           2            1 
           4            1 
           5            3 
           6            3 
           7            4 

**changing '4' -> '04': "select * from tab1 where abc in ('1', '2', '3', '04')" -  abc=1 missing**
          ID          ABC 
============ ============ 
           3            2 
           5            3 
           6            3 

Firebird/Windows/AMD/Intel/x64 (access method), version "WI-V5.0.0.1306 Firebird 5.0"

**Comment by pavel-zotov** [comment]
Second and third queries return 7 records (as 1st one) on intermediate snapshots  5.0.1.1411 #81ea7c8, 6.0.0.366 Firebird 6.0 #ab2c956

**Comment by asfernandes** [comment]
Should this issue be closed as duplicate?

**Comment by fous65** [comment]
For me, yes
