### ISSUE TITLE
Deadlock happens when run 'List Trace Sessions' service and there are many active trace sessions

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#8151]
The bug was found when few instances of QA tests was running concurrently.

The stack trace is [attached](https://github.com/user-attachments/files/15594866/gdb-firebird-3179885.txt), look at threads 7 and 2

The problem happens when textual representation for list of trace sessions takes more than 1KB (internal size of service output buffer) and service working thread runs faster than service start thread fire EVENT_SERVICE_START.

**Comment by Noremos** [comment]
Hello. I've noticed the [findSession](https://github.com/FirebirdSQL/firebird/blob/master/src/jrd/trace/TraceConfigStorage.cpp#L673) method does not check check if the slot is alive (used > 0) or not. Is it by design?

**Comment by hvlad** [comment]
> Hello. I've noticed the [findSession](https://github.com/FirebirdSQL/firebird/blob/master/src/jrd/trace/TraceConfigStorage.cpp#L673) method does not check check if the slot is alive (used > 0) or not. Is it by design?

Yes, by design. This is low-level routine that implements binary search, no more.
The caller intentions is not known here.
