### ISSUE TITLE
firebird 5.0.0.1306 global temporary table on commit delete rows

### ISSUE THREAD

**Issue by chedek** [FirebirdSQL/firebird#8154]
Global temporary table on commit delete rows does't work. 
All rows preserved till reconnection. I'm using linux distributive amd64.

**Comment by pavel-zotov** [comment]
Can not reproduce on Windows.
```
set bail on;
shell if exist e:\temp\tmp4test.fdb del /q /f e:\temp\tmp4test.fdb;
create database 'localhost:e:\temp\tmp4test.fdb';
show version;

create global temporary table gtt_test (id int primary key, x int) on commit delete rows;
commit;
insert into gtt_test select row_number()over(), rand() * 100 from rdb$types rows 10;
commit;

set count on;
set echo on;
select * from gtt_test;
```
Output:
```
ISQL Version: WI-V5.0.0.1306 Firebird 5.0
Server version:
Firebird/Windows/AMD/Intel/x64 (access method), version "WI-V5.0.0.1306 Firebird 5.0"
Firebird/Windows/AMD/Intel/x64 (remote server), version "WI-V5.0.0.1306 Firebird 5.0/tcp (PZ)/P18:C"
Firebird/Windows/AMD/Intel/x64 (remote interface), version "WI-V5.0.0.1306 Firebird 5.0/tcp (PZ)/P18:C"
on disk structure version 13.1
select * from gtt_test;
Records affected: 0
```
(used default firebird.conf; checked both Super & Classic; checked remote and local protocols)

**Comment by hvlad** [comment]
> Global temporary table on commit delete rows does't work. All rows preserved till reconnection. I'm using linux distributive amd64.

Reproducible test case, please

**Comment by chedek** [comment]
This example cannot show the problem. It's not very simple to reproduce problem. This part of log monitor:
"SelectQuery: [Execute] select result,ncodnakl,ncoddemand,error from ProcessNaklUtv(576478,1,0,2,1)"
: [Commit retaining (Soft commit)](4922306)"

After commit with retaining transaction I see the records the tran_id=4922306 in table: 

CREATE GLOBAL TEMPORARY TABLE TMP$CHECKFILTER (
    TIPNAME    D_NAME32 NOT NULL /* D_NAME32 = VARCHAR(32) */,
    COD        D_COD NOT NULL /* D_COD = INTEGER DEFAULT 0 NOT NULL */,
    GROUPS     D_NAME80 NOT NULL /* D_NAME80 = VARCHAR(80) */,
    RESULT     D_COD_S /* D_COD_S = SMALLINT DEFAULT 0 NOT NULL */,
    CODUSER    D_COD /* D_COD = INTEGER DEFAULT 0 NOT NULL */,
    ISDEFAULT  D_COD_S /* D_COD_S = SMALLINT DEFAULT 0 NOT NULL */,
    TRAN_ID    D_COD /* D_COD = INTEGER DEFAULT 0 NOT NULL */
) ON COMMIT DELETE ROWS

**Comment by hvlad** [comment]
Why do you think that COMMIT RETAINING should clear the GTT data ?

See: here https://github.com/FirebirdSQL/firebird/issues/6293 it was decided that COMMIT RETAINING should preserve rows and backward compatible setting was introduced (ClearGTTAtRetaining), 

then here https://github.com/FirebirdSQL/firebird/issues/7897 that setting was removed as obsolete.
