### ISSUE TITLE
Add support gen_uuid() as possible DEFAULT value for new fields

### ISSUE THREAD

**Issue by SkliarOleksandr** [FirebirdSQL/firebird#8155]
Now you can't use internal/system functions as a default value:

alter table MY_TABLE add REC_UID GUID default **gen_uuid()** not null

As I know, one possible reason is a BACKUP utility problem

but what is the difference between this? 

alter table MY_TABLE add REC_DATE timestamp default **current_timestamp** not null ? 

It would be really great to have the ability to use gen_uuid() as a default value, of course there is a workaround 
when we create a nullable field, then update it, then set not-null, but for code-first ORMs it's very inconvenient.

**Comment by SkliarOleksandr** [comment]
I understand your position, and it makes sense. But again, we are talking about how convenient is FB for a particular task. 
In our project, we use code-first ORM that doesn't use triggers at all, and yes, we can add a custom script - but this is a crutch.
Using gen_uuid() as a default value looks logical and obviously will be helpful although it's not a part of SQL standard (for today!)

**Comment by aafemt** [comment]
UUID identifiers are often generated on the client side. This is one of their advantages over generators.

**Comment by asfernandes** [comment]
If you try this alter table with current_timestamp, you will see that existing records will have the same timestamp. I can't imagine you want the same with uuids.

**Comment by SkliarOleksandr** [comment]
...at least that makes some sense since the update is performing quickly (as usual) and I honestly didn't know about this)). 
Of course, there is no sense to take one UUID for many records.

**Comment by asfernandes** [comment]
> ...at least that makes some sense since the update is performing quickly (as usual) and I honestly didn't know about this)). Of course, there is no sense to take one UUID for many records.

Yes, it's quick because it's stored once in metadata associated with the format version. And it fixed an old bug where a `default current_timestamp` were evaluated each time the record was selected, acting like a computed value.
