### ISSUE TITLE
in operator bug in fb5

### ISSUE THREAD

**Issue by ibexpertHK** [FirebirdSQL/firebird#8157]
i tested this sql statement on fb50 connection using ibexpert and simply executing it after 
entering the params, it crashes the firebird server instance on fb5 

select * from rdb$relations where rdb$db_key in (:p1,:P2)

using the in operator with only one parameter does not crash it on fb5. 
select * from rdb$relations where rdb$db_key in (:p1)

we tested the same statements in fb40 and also in fb15 and it works there as 
as expected without crashing anything (customer who first reported that problem 
needs to convert c#  application from fb15 to newer fb version, now we decided 
not to use fb50 until this bug is fixed, but since fb40 is not crashing, that is the 
target for now. so in any client platform the statement is able to crash the server 
instance, which should not be.

**Comment by dyemanov** [comment]
It should be already fixed by commit c432bd0, please test the snapshot build.

**Comment by dyemanov** [comment]
Likely duplicate for #8136.
