### ISSUE TITLE
FB5 return INT128

### ISSUE THREAD

**Issue by usystem** [FirebirdSQL/firebird#8158]
FB5 Query SELECT SUM(NUMERIC(15,2)) return INT128 - is this how it should be? If so, why are we so happy?
My function sums up the values ​​in a grid column by the name of the field in the column, and here it is!
You can, of course, do a cast, but you still need to find out that this is NUMERIC(15,2) that is, climb onto the server.

**Comment by aafemt** [comment]
For me this SUM returns type NUMERIC(38, 2) and that's what is expected.

**Comment by mrotteveel** [comment]
As Dmitry says, it returns a `NUMERIC(38,2)`, not just the `INT128` base type, and this is not new in Firebird 5.0, and has been the case since Firebird 4.0.
