### ISSUE TITLE
FB 5 left join on stored procedure produces GDSCODE: 335544348 error. Employee.fdb test case included. FB 2.5, 3 and 4 OK.

### ISSUE THREAD

**Issue by cfnz** [FirebirdSQL/firebird#8159]
Firebird 5 reports an error (see below) whereas Firebird 4, 3 and 2.5 all return results for the same query. 

I have tested with the released FB 5 and latest snapshot build available at time of writing (5.0.1.1416).

Setting `OuterJoinConversion = false` resolves the issue (so not sure if I need to report this issue, but as result is different to prior versions, I have)

The error in Firebird 5 is: 
```
The cursor identified in the UPDATE or DELETE statement is not positioned on a row.
no current record for fetch operation.
-----------------------------------------------------------------------------------
SQLCODE: -508
SQLSTATE: 22000
GDSCODE: 335544348
```
The test case uses the shipped employee.fdb db. Change the GET_EMP_PROJ stored proc to also return the given emp_no, like so:

```
create or alter procedure Get_Emp_Proj (Emp_No smallint)
returns (
  Proj_Id char(5),
  Emp_No_Out smallint)
as
BEGIN
    FOR SELECT emp_no, proj_id
        FROM employee_project
        WHERE emp_no = :emp_no
        INTO :emp_no_out, :proj_id
    DO
        SUSPEND;
END;
```
Then try the following query:
```
select *
from
  Employee E
  left join Get_Emp_Proj(E.Emp_No) P on E.Emp_No = P.Emp_No_Out
  where p.Proj_Id = 'VBASE'

```
As mentioned, the query works on Firbird 2.5 (Win and Linux), 3 (only tried Linux), 4 (only tried Linux) but not on 5 or 5 snapshot build (again, only tried Linux).

Original query was in [support group](https://groups.google.com/g/firebird-support/c/aPwJznHVF94). That group also referenced https://github.com/FirebirdSQL/firebird/issues/8115 which is different to this issue as they were not getting an error.

**Comment by dyemanov** [comment]
Duplicates #7937.

**Comment by dyemanov** [comment]
No. But the fix was already backported, so you may try the snapshot build and revert `OuterJoinConversion` back.

**Comment by mrotteveel** [comment]
> With the fix of `OuterJoinConversion = false` that I have used... is there any disadvantages to this?

Effectively that is a temporary backwards compatibility option so the optimizer uses the old way of doing things. I would expect that option to go away in a future version, so IMHO you shouldn't depend on it long term.

**Comment by cfnz** [comment]
Just confirming that the snapshot build fixes the employee test case as well as the original queries that had issues. Thanks.
