### ISSUE TITLE
Allow creation of custom aggregate function

### ISSUE THREAD

**Issue by livius2** [FirebirdSQL/firebird#8173]
Allow creation of custom aggregate function

I see two types of aggregate.

1. Totally universal without declaration `CUSTOM_AGG` and reserved word `CURRENT_CUSTOM_AGG`:
```  
  SELECT 
  CUSTOM_AGG(
          CASE 
		  WHEN X.FLD_1 IS NULL THEN CURRENT_CUSTOM_AGG 
		  WHEN X.FLD_2>17 THEN COALESCE(CURRENT_CUSTOM_AGG, 0) / X.FLD_2 
		  ELSE COALESCE(CURRENT_CUSTOM_AGG, 0) + X.FLD_1 
		  END) 
  FROM 
  TABLE_X X
  GROUP BY X.SOME_FIELD
```
 
2. declarative agg functions

```
/* CURRENT_CUSTOM_AGG is passed by Firebird and available inside body */
CREATE AGGREGATE FUNCTION BIN_OR_AGG (/* CURRENT_CUSTOM_AGG INTEGER, */ VALUE INTEGER)
  	RETURNS INTEGER
  	AS
  	BEGIN
  	  RETURN BIN_OR(COALESCE(CURRENT_CUSTOM_AGG, ), COALESCE(VALUE, 0));
  	END
```

```	
SELECT 
X.SOME_FIELD, BIN_OR_AGG(X.FLD_1) AS MASK
FROM 
TABLE_X X 
GROUP BY X.SOME_FIELD
```

**Comment by mrotteveel** [comment]
I recall there was a discussion a while back about a feature like this, though I'm not sure if there was already a ticket.

**Comment by dyemanov** [comment]
#1745 ?

**Comment by mrotteveel** [comment]
As an aside, I don't see how you could use either of your proposals to implement an aggregate function like AVG, or the statistical or linear regression aggregate functions. I think that would be the true test if it can be used for implementing a wide variety of aggregate functions.

**Comment by livius2** [comment]
> I don't see how you could use either of your proposals to implement an aggregate function like AVG, or the statistical or linear regression aggregate functions. I think that would be a good test if it can be used for implementing a wide variety of aggregate functions.

Simply add more build in params/variables like: 
`IS_LAST` - last from frame point of view 
`CURRENT_COUNT`

This is only proposition, you can extend it.
