### ISSUE TITLE
Sometimes a trace session is terminated spontaneously

### ISSUE THREAD

**Issue by Noremos** [FirebirdSQL/firebird#8180]
Sometimes a system session can just disappear. The easiest way to reproduce the problem is to run 2 tests via firebird-qa:
python3 -m pytest --server local --disable-db-cache tests/bugs/core_2940_test.py tests/bugs/core_2981_test.py
The second test will fail with the following result:
Trace session ID 3 not found

**Comment by hvlad** [comment]
> Sometimes a system session can just disappear. The easiest way to reproduce the problem is to run 2 tests via firebird-qa: python3 -m pytest --server local --disable-db-cache tests/bugs/core_2940_test.py tests/bugs/core_2981_test.py The second test will fail with the following result: Trace session ID 3 not found

Can't reproduce with this test:

```
tests\bugs\core_2940_test.py .                                                                                                                   [1/2]
tests\bugs\core_2981_test.py .                                                                                                                   [2/2]

================================================================= 2 passed in 5.00s ==================================================================

```

**Comment by Noremos** [comment]
> Should add that this is possible for CS only and after some worker process died.

Sorry, I completely forgot to put the configs.
Firebird.conf:
```
TracePlugin = fbtrace
AuditTraceConfigFile = fbtrace.conf
ServerMode = Classic
ExternalFileAccess = Full
```

fbtrace.conf:
```
database
{
	enabled = true
}
```

firebird 5 (33085744b88f87325d1ea167b48c98bd1a95eae6)

**Comment by hvlad** [comment]
With such config I can confirm the error by QA tests you show.
But... it shows problem in QA tests, not directly related with Firebird and this issue.
Just apply this patch: FirebirdSQL/firebird-qa/pull/25 and see.

**Comment by Noremos** [comment]
> But... it shows problem in QA tests, not directly related with Firebird and this issue.
I ran tests with the cnt_used != 0 asserts and they failed. So I'm assumed some kind of Firebird related issue still exists. After my PR, the approvals passed

**Comment by hvlad** [comment]
Don't get me wrong - I confirmed the issue, it is definitely exists and fixed - else I would not have approved your PR.
The question is how to create QA test for it.
