### ISSUE TITLE
isql error code

### ISSUE THREAD

**Issue by piervalli** [FirebirdSQL/firebird#8190]
Dear,

I have created this script 
```batchfile
SET bin="C:\Program Files\Firebird\Firebird_5_0"
SET script=./indexSql.txt
SET username=SYSDBA
SET password=firebirdsql
SET PATDB=c:\temp\database.fdb
%bin%\isql -i %script% -u %username% -p %password% %PATDB%
if %ERRORLEVEL% NEQ 0 echo Error
``` 
If the database does not exists isql return always 0, It should be return an error code.

What do you think?

Thanks
Pier

**Comment by hvlad** [comment]
Did you tried -bail switch 
https://www.firebirdsql.org/file/documentation/html/en/firebirddocs/isql/firebird-isql.html#isql-switches

or command
https://www.firebirdsql.org/file/documentation/html/en/firebirddocs/isql/firebird-isql.html#isql-set-bail

?

**Comment by piervalli** [comment]
Sorry,
it is works with -b 

Thanks

**Comment by piervalli** [comment]
Resolved
