### ISSUE TITLE
Function MAKE_DBKEY may produce random errors if used with relation name

### ISSUE THREAD

**Issue by aafemt** [FirebirdSQL/firebird#8203]
Because function `LiteralNode::getText() `returns string which is not zero-terminated. Particularly QA test gh_8168_test.py sometimes unexpectedly produces "Malformed string" error.

**Comment by hvlad** [comment]
Few notes: 
- it happens in DEBUG build with table names of any length and in RELEASE build with table names greater than 15 bytes. 
As QA test [gh_8168_test](https://github.com/FirebirdSQL/firebird-qa/blob/master/tests/bugs/gh_8168_test.py) uses short table names, it could fail with DEBUG build only
- gbak is not affected as it uses table ID's, not names.
