### ISSUE TITLE
Incompatibility with LPAD Collation PT_BR Between Firebird 2.5 and 5.0.1

### ISSUE THREAD

**Issue by gilbertoximenes** [FirebirdSQL/firebird#8206]
The following command runs without issues on Firebird 2.5 but returns an error on Firebird 5.0.1.
Command:
```
CREATE DATABASE 'localhost/3050:c:\temp\example.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192 DEFAULT CHARACTER SET ISO8859_1;

SELECT * FROM RDB$DATABASE WHERE LPAD(1, 3, '0') collate pt_br like '001';
```

Error Message:
Dynamic SQL Error
-SQL error code = -204
-COLLATION PT_BR for CHARACTER SET NONE is not defined

Description:
When executing the above SQL command on Firebird 5.0.1, an error is returned indicating that the collation PT_BR for character set NONE is not defined. This command runs correctly on Firebird 2.5 without any errors.

**Comment by asfernandes** [comment]
Database's default character set is used only for DDL objects creation.

You need to use a connection charset too, and string literals is based on it.

2.5 is very old version that has some different understanding and inconsistencies about this.

**Comment by gilbertoximenes** [comment]
Thank you for your prompt response.  
Even disregarding version 2.5, I believe the behavior of Firebird 5 is not consistent.  
Connecting to the example database created above using CHARACTER SET ISO8859_1:

This command throws an error because LPAD returns a string with charset NONE:  
```sql
SELECT * FROM RDB$DATABASE WHERE LPAD(1, 3, '0') COLLATE pt_br LIKE '001';
```

This command executes normally because LPAD returns a string with charset ISO8859_1:  
```sql
SELECT * FROM RDB$DATABASE WHERE LPAD('1', 3, '0') COLLATE pt_br LIKE '001';
```

**Comment by asfernandes** [comment]
1 is not a string and in this case it's being converted to NONE charset.

**Comment by dyemanov** [comment]
@asfernandes  Don't you think that a NONE string padded with a ISO8859_1 string should produce ISO8859_1 result rather than NONE?

**Comment by gilbertoximenes** [comment]
I have the impression that at least the documentation could describe how the implicit conversion mechanism works and how the charset is defined in such cases. I have added other examples using the same database from the first message, and it is possible to observe that LPAD and TRIM generate different charsets (NONE  and ASCII). The same occurs with other functions.
```
SELECT * FROM RDB$DATABASE WHERE LPAD(1, 1) collate pt_br like '1';
-- COLLATION PT_BR for CHARACTER SET NONE is not defined

SELECT * FROM RDB$DATABASE WHERE TRIM(1) collate pt_br like '1';
-- COLLATION PT_BR for CHARACTER SET ASCII is not defined.

SELECT * FROM RDB$DATABASE WHERE 1||'' collate pt_br like '1';
-- RUNS FINE

SELECT * FROM RDB$DATABASE WHERE CAST(1 as VARCHAR(1)) collate pt_br like '1';
-- RUNS FINE
```

**Comment by aafemt** [comment]
Your "CREATE DATABASE" command is wrong. You must add "SET NAMES ISO8859_1" to it.

**Comment by aafemt** [comment]
Try to do it as a separate command before "CREATE DATABASE".

**Comment by gilbertoximenes** [comment]
> Try to do it as a separate command before "CREATE DATABASE".

Thank you for your response, but the same error persists.
