### ISSUE TITLE
CAST() ignores collation of target data type

### ISSUE THREAD

**Issue by aafemt** [FirebirdSQL/firebird#8249]
@aafemt this change introduced a problem making this query work:
```
select cast('x' as varchar(10) character set utf8 collate wrong) from rdb$database;
```

_Originally posted by @asfernandes in https://github.com/FirebirdSQL/firebird/issues/7748#issuecomment-2342463807_

**Comment by asfernandes** [comment]
This is a regression introduced in #7748
