### ISSUE TITLE
Error code -101 error in allocation buffer

### ISSUE THREAD

**Issue by jasimalajmi** [FirebirdSQL/firebird#8276]
![IMG_3133](https://github.com/user-attachments/assets/fee58fef-06df-4117-a89b-402b2f944c7a)

The firebird 2.5

**Comment by mrotteveel** [comment]
That doesn't seem to be a Firebird error. Secondly, the issues is for reporting bugs, and even if this is a problem with Firebird itself, so far this looks more like a support request, which should be posted on https://groups.google.com/g/firebird-support (or under GitHub Discussions).

But even if this is a support request, you'll need to provide more information than just a screenshot and a Firebird version.
