### ISSUE TITLE
charset problem on connect

### ISSUE THREAD

**Issue by direktor05** [FirebirdSQL/firebird#8306]
I get the following error when starting application using Firebird:

DM.FDB Connection Error .bad parameters on attach or create database.
CHARACTER SET WIN1250 is not defined

How to fix this?

**Comment by mrotteveel** [comment]
Usually this means that the intl directory and/or the files it contains are missing.

**Comment by mrotteveel** [comment]
Also asked on:

- https://github.com/FirebirdSQL/firebird/discussions/8305
- https://groups.google.com/g/firebird-support/c/5dLEkMsEXNQ
