### ISSUE TITLE
AUTOTERM: excessive error reporting

### ISSUE THREAD

**Issue by dyemanov** [FirebirdSQL/firebird#8332]
Consider this (erroneous) script:

```sql
execute block
as 
     declare cnt int = 1000;
     declare sum bigint = 0;
begin
     while (cnt > 0) do
     begin
       sum = sum + cnt;
       cnt = cnt - 1;
     end
end
```

When executed using `SET TERM` the reported error is:

```
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 4, column 11
-sum
```

However, when executed using `SET AUTOTERM` the console output is:

```
SQL> execute block
CON> as
CON>   declare cnt int = 1000;
CON>   declare sum bigint = 0;
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 4, column 11
-sum
SQL> begin
CON>   while (cnt > 0) do
CON>   begin
CON>     sum = sum + cnt;
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 1, column 1
-begin
SQL>     cnt = cnt - 1;
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 1, column 1
-cnt
SQL>   end
CON> end;
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 1, column 1
-end
```

It looks like ISQL switches into continuation mode after error, but it's documented that it should happen for the `isc_command_end_err2` error while here we have `isc_dsql_token_unk_err` raised.

**Comment by asfernandes** [comment]
I don't think there is anything wrong or that could be fixed.

AUTOTERM is a feature for interactive use. Yes, a pasted text is still interactive and I'd love to see something better, but as soon you enter:

```
execute block
as 
     declare cnt int = 1000;
     declare sum bigint = 0;
```

there is parse error in the script. Look at `SQL>`. It's not in continuation mode, it just thinks what comes next is a new command. And if you were manually entering line by line, that would be clear.

Another example:

```
execute block
as 
    declare cnt int = 1000;
    declare sum bigint = 0;
execute block returns (n integer)
as 
begin
    n = 1;
    suspend;
end;
```

It's just two commands stuck together, one with error and a correct one.

**Comment by dyemanov** [comment]
Well, maybe I expect too much from `AUTOTERM`. It looked so handy for script writers (permanently remembering about `SET TERM` is a PITA) so I tend to treat it as a common usage feature with only performance being probably an issue. Now I see this assumption was wrong.

**Comment by dyemanov** [comment]
Closing the issue, sorry for the noise. I suppose we'll have to stick with our own implementation for the time being, as I don't see `SET AUTOTERM` being a proper replacement.
