### ISSUE TITLE
Firebird 5.0.0 User trusted authentication on Windows checking user specific group 

### ISSUE THREAD

**Issue by Mus-dev99** [FirebirdSQL/firebird#8335]
Hey everyone,

i want to set up User trusted authentication on our Windows hosted Firebird server. For this purpose i have followed this guide:
https://ib-aid.com/download/docs/fb5migrationguide.html#_setting_up_trusted_authentication

On the second step it verifies any user trying to connect to the database, which isnt what i want.
I want to check if the user belongs to a specific Windows group before letting him in.

Now this works for my user specifically:
create global mapping dev
using plugin win_sspi
from user "domain\MyName"
to User Sysdba;

2 Problems here:

1. the same query doesnt work with:
create global mapping dev
using plugin win_sspi
from user "domain\MyName"
**to Role my_own_role;**

So its not possible to assign that user to my own created role.

2. a mapping that automatically assigns users from my specified group within our domain to a specific role.
So we might have a active directory group called Devs and we want to let every member of Devs inside.
I've tried a lot but i imagine something like a wildcard or specifying the group working:

Wildcard:
CREATE Global MAPPING dev
USING PLUGIN WIN_SSPI
FROM User **"DN\%"**
TO ROLE my_own_role;

or 

Group:
create global mapping trusted_auth
using plugin win_sspi
from Group "dn\Developer_group"
to ROLE my_own_role;

Does somebody know why my mappings arent working?
Is it even possible to create mapping that automatically assigns every user withing an active directory group to a role?

**Comment by vk-git-hub** [comment]
Hey, Mus-dev99.
2 Problems here:

the same query doesnt work with:
create global mapping dev
using plugin win_sspi
from user "domain\MyName"
to Role my_own_role;

You need to create role (e.g., role1), to create user (e.g. user1), assign this role with this user and create global mapping MAP_TRUST_AUTH_SQLUSERS_2
using plugin win_sspi
from user "domain\MyName"
to user user1;

**Comment by Mus-dev99** [comment]
Hello thanks for answering me,
i have solved the problem with this [guide ](https://ib-aid.com/download/docs/fb5migrationguide.html#_setting_up_trusted_authentication).
Step 2 was crucial to solve it. Unfortunately now im having problems with multiple mappings.
I have created following mappings:

Mapping 1:
CREATE MAPPING TRUSTED_AUTH
USING PLUGIN WIN_SSPI
FROM ANY USER
TO USER;

Mapping 2:
Create Mapping group1
using Plugin Win_Sspi
from Group "dn\User_group"
To Role Role_User;

Mapping 3:
Create Mapping group2
using Plugin Win_Sspi
from Group "dn\Admin_group"
To Role Role_Admin;

Now if my user tries to connect to the Database and is exclusively inside of User_group or Admin_group, it works and assigns him to the according role. But if the User is in both groups, then im getting a multiple mapping error.
I have though about different ways of solving it. You can see my new issue here: https://github.com/FirebirdSQL/firebird/issues/8352
But crucially i have thought about solving it by connecting with a priority role in mind. Im quoting the documentation: "For roles, the role defined by a mapping rule is only applied when the user does not explicitly specify a role on connect.".

Maybe youd have a better solution, as mapping every single user would be very laborious.
