### ISSUE TITLE
Missed records in replicated database

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#8350]
Issue was reported by user privately. 

After investigation it was found that master database contains records with zero blob_id and null flag not set. 

It is not clear how to create such records. 
Though, gbak and few other places in code handle such condition, therefore it looks like known state.

Current issue is that such records is not replicated, i.e. it is not written into replication log by master and thus its missed in replica.

**Comment by pavel-zotov** [comment]
::: QA note :::
Deferred until firebird-driver will be able to provide blob ID for just handled (inserted or updated) blob.
