### ISSUE TITLE
Report unique usernames for isc_info_user_names

### ISSUE THREAD

**Issue by mrotteveel** [FirebirdSQL/firebird#8353]
For administrators, `isc_info_user_names` reports the usernames of each connection. If multiple connections have the same username, then that name is repeated. Instead, it should report the _unique_ usernames; this will reduce the amount of information transferred, reducing the chance of truncation. 

Making this change should not break the API, as it makes no promises beyond reporting the usernames, though it might be good to ensure the username of the current connection remains the first as it is currently.

Specifically, to quote from the InterBase 6.0 API Guide:

> Names of all the users currently attached to the database; for _each_ such user, the result buffer contains an `isc_info_user_names` byte followed by a 1-byte length specifying the number of bytes in the user name, followed by the user name

**Comment by livius2** [comment]
If it currently reports the same username multiple times, I suppose it is the wrong way to create backward incompatibilities in `isc_info_user_names` provide new `isc_info_user_unique_names`

**Comment by mrotteveel** [comment]
> If it currently reports the same username multiple times, I suppose it is the wrong way to create backward incompatibilities in `isc_info_user_names` provide new `isc_info_user_unique_names`

No, it complies with the documented behaviour, which says it reports the names of the users; it doesn't say anything about uniqueness or not (in fact, I would argue that, based on the documentation, repeating usernames was a bug, as it explicitly says it returns the name for each user that is connected, not for each connection; that is if a user has multiple connections, that is still one user).

Also, for non-admin users it only reports the user of the current connection, and the same goes for ClassicServer connections (as it reports about connections to the same database in the current user process, and in ClassicServer, there is only one connection per process, the current connection). So, there basically is no reliable way to use it, so I can't see how anything would break from changing this.
