### ISSUE TITLE
Error result - "Data type unknown" MON$DATABASE.MON$CREATION_DATE Firebird 5.0.2 vs successful Firebird 3.0.12

### ISSUE THREAD

**Issue by VTolmasov** [FirebirdSQL/firebird#8367]
Version of Firebird 5.0.2 in Windows. Execute the request. Previously this query was successfully executed on Version of Firebird 3.0.12
```
SELECT *
FROM MON$DATABASE
```
Result:
can't format message 13:796 message file C:\WINDOWS\SYSTEM32\firebird.msg not found.
Data type unknown.
SQLCODE: -204
SQLSTATE: HY004
GDSCODE: 335544573

Execute the request without **MON$CREATION_DATE**

```
SELECT MON$OLDEST_TRANSACTION OLDESTTRANSACTION, MON$OLDEST_ACTIVE OLDESTACTIVE, MON$OLDEST_SNAPSHOT OLDESTSNAPSHOT, MON$NEXT_TRANSACTION NEXTTRANSACTION,
--MON$CREATION_DATE CREATIONDATE,
MON$PAGE_SIZE PAGESIZE, MON$PAGES PAGES, MON$ODS_MAJOR ODSMAJOR,
MON$ODS_MINOR ODSMINOR, MON$PAGE_BUFFERS PAGEBUFFERS, MON$SWEEP_INTERVAL SWEEPINTERVAL, MON$FORCED_WRITES FORCEDWRITES,
MON$RESERVE_SPACE RESERVESPACE, MON$NEXT_TRANSACTION - MON$OLDEST_ACTIVE NEXTOAT, MON$OLDEST_ACTIVE - MON$OLDEST_TRANSACTION OATOIT,
MON$SQL_DIALECT SQLDIALECT, MON$STAT_ID STATID
FROM MON$DATABASE
```
Successfully completed
In the structure of table **MON$DATABASE** there is a column **MON$CREATION_DATE**
![image](https://github.com/user-attachments/assets/79d366b0-fb1b-4978-895c-9d88435b28e7)

**Comment by aafemt** [comment]
As designed: outdated Firebird client cannot recognize type `TIMESTAMP WITH TIME ZONE`. Update client library to match server version.

**Comment by mrotteveel** [comment]
Or alternatively, configure `DataTypeCompatibility`, use `SET BIND` statement, or `isc_dpb_set_bind` connection property. See also the Firebird 4.0 release notes regarding these options.

As an aside, Firebird 5.0.2 is not a released version. The latest Firebird 5.0 is Firebird 5.0.1.

**Comment by VTolmasov** [comment]
> Как и задумано: устаревший клиент Firebird не может распознать тип `TIMESTAMP WITH TIME ZONE`. Обновите клиентскую библиотеку для соответствия версии сервера.

@aafemt Thank you!
Updating FirebirdSql.Data.FirebirdClient to 10.3.2.0 and updating ibexpert fixed the problem.
