### ISSUE TITLE
Strings concatenation operator may be omitted in some "compound" statements (like 'INSERT INTO ... SELECT ... FROM ...') // 5.x+

### ISSUE THREAD

**Issue by pavel-zotov** [FirebirdSQL/firebird#8370]
Please consider following script:
```
set bail on;
set list on;
shell del r:\temp\tmp4test.fdb 2>nul;
create database 'localhost:r:\temp\tmp4test.fdb' user 'sysdba' password 'masterkey';
show version;
commit;
 
recreate table test(id int);
commit;
 
set term ^;
execute block as
begin
    execute statement
        'insert into test(id) '
        'select 1 '
        'from rdb$database'
    ;
end
^
```
NOTE: there is no concatenation between lines ```insert into ...``` and ```select 1``` (and also next pair:  ```select 1 ``` and ```from rdb$database```).

FB 4.x will issue error for such script:
```
ISQL Version: WI-V4.0.6.3173 Firebird 4.0
...
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 5, column 9
-'select 1 '
 ```

FB 5.x and 6.x silently *accept* it, no error is issued.
 
Is it expected ?
(i'm not sure whether this is bug or no, thus i did not set any label for this ticket)

**Comment by mrotteveel** [comment]
This is a new feature in Firebird 5.0. See [Changes to literals](https://www.firebirdsql.org/file/documentation/release_notes/html/en/5_0/rlsnotes50.html#rnfb50-dml-literals), and tickets #5588 and #5589.
